#+setupfile: ../../styles/readtheorg.setup
#+title: Random

* What's Not so Good with IBIS

[[https://www.fujirumors.com/now-panasonic-explains-whats-not-good-ibis-looking-forward-fujifilm-x-h1-ibis-anyway/][Source]]

#+attr_html: :class no-border
| OIS  | Optical Image Stabiization  |
|------+-----------------------------|
| IBIS | In Body Image Stabilization |

Types of stabilizers:

#+caption: Tripod
file:../images/photography/04.jpg

#+caption: Gimbal
file:../images/photography/01.jpg

#+caption: Rig
file:../images/photography/02.jpg

#+caption: Dolly
file:../images/photography/03.jpg

The Panasonic GH5s is a high-sensitivity camera, and such a camera is used more with a tripod rather than handheld. When used handheld under low light conditions, a gimbal will be used by many customers. So we think there is no problem if no body IS is provided.

... heat dissipation. IBIS increases noise because of the heat, for example, when we shoot astrophotography out on a cold night, that ISO performance improves, due to the cold temperatures.

Sensor-shift IS systems operate by "floating" the sensor using a series of electromagnets. Even when they're "off" they're not locked in place, they're simply set so that the electromagnets aren't attempting to correct for movement. This has the side-effect that, which mounted on a professional stabilization rig, there's a risk of the sensor being shaken around.

Why OIS is better than IBIS:

1. With OIS, each lens is optimally tuned to achieve reliable correction.
2. OIS allows faster and more accurate AF & exposure metering, because the image comes already stabilized to the camera sensor.
3. OIS is more effective with long telephoto lenses.
4. Depending on the lens used, IBIS can introduce more or less vignetting.
5. Heat generated by IBIS introduces more grain to the images.

IBIS pros:

1. Very useful for slower non-stabilized lenses.
2. IBIS is paid just once, OIS is paid for each lens.
3. Allows to use features like sensor shift to create high-resolution images (only if the subject is perfectly static).
4. Can be used in combination with OIS.

If you really want the ultimate and very best image quality possible, then any form of in camera or lens stabilisation has to be avoided whenever possible.
