#+SETUPFILE: ../../styles/readtheorg.setup
#+TITLE: System Design for Tech Interviews

[[https://www.hiredintech.com/courses/system-design][System Design for Tech Interviews]]

* Introduction

The idea of these questions is to have a discussion about the problem at hand. There is no one right answer. What’s important for the interviewer is the process, which you use to tackle the problem. The important thing is to be able to justify your ideas.

System design questions require a combination of the right strategy and knowledge. By strategy we mean a way to approach the problem at an interview. There are two major challenges most candidates face when it comes to system design questions. Candidates either:

- Approach questions in a chaotic way and get ratholed, or
- Lack solid understanding of how to properly design architectures that scale.

* The System Design Process
** Step 1: Constraints and Use Cases

Just like algorithm design, system design questions will also most likely be weakly defined. The very first thing you should do is to clarify the system's constraints and to identify what use cases the system needs to satisfy. Never assume things that were not explicitly stated.
