#+SETUPFILE: ../../styles/readtheorg.setup
#+TITLE: History

* 飞翔的尸体与一次欧洲人口灭绝

[[https://zhuanlan.zhihu.com/p/21933764][Source]]

中世纪的公元 1345 年，黑海的北岸有座古城，名叫卡法。当时这座古城是克里米亚地区享誉盛名的贸易中心，后来因为城中商人之间的一次冲突，激怒了金帐汗国的一位蒙古王子，王子一怒之下率领蒙古军队围攻卡法，卡法守军坚守城池，决死抵抗，曾经横扫欧亚大陆的蒙古铁骑在卡法城墙之下竟然一筹莫展，双方就此开始了漫长的拉锯。

转眼就到了两年以后的 1347 年，有一天卡法守军突然发现蒙古军队的攻势停止了，似乎在蒙古军队里出了不小的麻烦。正如卡法守军所猜测的那样，围城的蒙古军队不知道从什么时候开始有很多士兵感染了一种怪病，人患了这种病以后，首先会持续高烧，流鼻血，紧接着在耳后、腋下、大腿内侧等处会出现奇怪的肿块，并且伴随着严重的皮下出血，而且那皮下出血实在是太过夸张，以至于出血部位的皮肤肿胀成紫黑色。这种病不仅传染性强，而且死亡率近乎 100%，发病的士兵几乎没有活过三天的。

眼看自己的围城大军就要土崩瓦解，那个蒙古王子恼怒之下心生一计，他命人把病死的蒙古士兵的尸体放到投石机上，然后把死尸像巨石一样空投进卡法城里，由此掀起了人类历史上第一次细菌战。卡法城里的守军目瞪口呆地看着一具具黑色的尸体呼啸着从自己的头顶上飞翔而过，然后在城里的街道上摔得汁水四溅。紧接着，那种恐怖的疾病就像幽灵一样爬到了守军士兵的身上，痛苦的呻吟开始在全城响起。在这无以名状的恐惧之下，坚持了两年卡法守军终于崩溃了，被吓疯了的守军不顾一切地夺船而逃，给蒙古人留下了一座被恐怖瘟疫毁灭的死城。那些逃跑的守城士兵所乘坐的小船，渐渐地驶向了欧洲，这也使得在接下来的几年里，被这种恐怖瘟疫所毁灭的，将不仅仅是卡法而已。

说到中世纪的欧洲，大家可能会想到高大雄伟的城堡，英勇无畏的骑士，风度翩翩的贵族。但是中世纪的欧洲，只能用「一塌糊涂」这四个字来形容。中世纪的欧洲完全没有公共卫生和个人卫生的概念，没有下水道（古罗马的下水道也已荒废），也没有普及公共厕所，人们有时直接在家里的地板上豪爽地拉屎，方便完了再用铲子把屎搓到墙角去，讲究一点的人家在便桶上方便，便桶被装满之后怎么办呢？直接从二楼窗户泼到大街上，这样一来行人在大街上被屎尿泼的满头满脸的情况屡见不鲜。有的国家甚至曾经还有规定，任何人从窗户倾倒粪便以前，要大声警告过往行人三次，以免造成不必要的冲突。而且这些排泄物被泼到街上以后通常不会被清理干净，反而会被行人和牲畜踩成新的路面，一下雨这些用屎踩成的路面在雨水的浸泡之下会变得泥泞不堪，甚至能淹死小狗。法国巴黎曾经把城里收集起来的粪便堆到城墙外边去，但是这些大粪不清理只会越堆越多，最后墙外的屎几乎要漫过城墙去了，为了防止敌人踩着屎翻过城墙，法国人经过讨论最后决定：加高城墙。

个人卫生更是无从谈起，中世纪的欧洲人有一种奇怪的观点，认为人在洗澡的时候毛孔会张开，空气里的有毒物质会趁机进入人的身体让人生病，而且中世纪的欧洲在基督教的严格主宰之下，无论贫民还是贵族都要严格遵循基督教的戒律。当时欧洲人认为自己只受洗于耶稣本人就行了，除此之外不用再做任何洗浴，所以在中世纪的欧洲人看来，洗澡的人既不卫生又不虔诚，因此对洗澡深恶痛绝。即使在中世纪之后很长一段时间里，欧洲人的个人卫生情况也是一塌糊涂。法国国王亨利四世憎恶洗澡，他周围的人说他整个人闻起来就像一块腐肉，他的第二任妻子在初次见到他的时候竟然被他身上恶臭的体味熏得晕倒在地。亨利四世生活在 16 世纪，而当时欧洲人的卫生状况相对于之前的中世纪来说已经有了很大的改善。中世纪时有的欧洲宗教人士因为过于虔诚，几十年来拒绝洗澡，以至于身上的伤口长了蛆。恶劣的卫生条件，为各种微生物的繁殖提供了绝佳的温床，在欧洲各地的一片恶臭之中，一场恐怖的人口灭绝已悄然拉开了帷幕。

从 1347 年开始，拜占庭、热那亚、威尼斯等地相继爆发疫情，人在得病以后流鼻血，高烧不断，浑身无力，腋下两腿之间出现肿块，嘴里冒出一阵阵腥臭，四肢关节就好像被火烧一样疼，最后就是严重的皮下出血，身体的一些部分变成紫黑色。几乎没有人可以活过三天，有的人甚至早上发病，中午就死了。死去的患者往往因为皮下出血，尸体变成紫黑色，所以后世的欧洲人在回忆这场浩劫时，给这种病起名为「黑死病」。

file:../images/history/01.gif

在黑死病出现后，热那亚政府紧急调动武装力量全面封锁领海，任何试图强行靠岸的外来船只一律开炮轰沉。威尼斯共和国也下令，所有外来船只必须在岸边隔离四十天以观察疫情。在意大利语中 quaranta 意为四十，这个词也因此演变成了英语中的 quarantine，意为隔离。在热那亚也被疫情渗透后，意大利各地紧急封锁国境，禁止热那亚公民入境，可是这一切在这场恐怖的瘟疫面前没有任何意义。有个热那亚商人去意大利北部的一座名叫皮亚琴察的城市串亲戚，但是因为封锁禁令，那个城市拒绝他入城，当天正好下着大雨，那个商人就一直站在城门外冒着大雨苦苦哀求，天黑以后，那个商人的亲戚终于忍不住了，偷偷地打开了城门，带他回家过夜。几天以后，皮亚琴察城里已经没有活人了。

没有人知道这病是如何传播的，更没有人知道要如何医治这种病。乞丐病死在大街上，贵族病死在城堡里，整个欧洲陷入了巨大的恐惧之中。最开始欧洲一些医生自以为知道这种瘟疫的传播途径，他们表示，人会得这种病是因为空气里充斥着腐败的物质，人吸入这种臭气以后就会病倒，所以中世纪时很多欧洲医生制作了这种乌鸦一样的面具，他们在鸟嘴的位置塞进各种香料，戴在脸上防止吸入腐败的臭气。但是正如大家所知道的那样，欧洲的医生在这种瘟疫面前就像普通人一样毫无还手之力。

于是又有一些人站出来表示，人之所以会得这种病，是因为上帝发怒了，人类的罪孽激怒了上帝，所以上帝降下瘟疫以示惩罚。要想避免感染，人们就应该向神父忏悔自己的罪行，虔诚地祈祷请求上帝的原谅。但是这依然没用，人们仍在死去，于是人们又觉得一定是自己忏悔的诚意不够，不少人一边骂着脏话侮辱自己一边抡起鞭子把自己抽得鲜血淋漓，以示自己真心实意地向上帝谢罪。耶稣受难时 33 岁半，所以这个自虐的活动要持续 33 天半，有不少人在活动中把自己活活打死。但是人们依然在不停地死去，神父也并没有比普通人更能抵御疾病。

这让人们失望透顶，人一失望就会愤怒，于是纷纷表示，这一切都是犹太人搞的鬼，犹太人害死了耶稣，必须要清算犹太人以平息主的愤怒。基督徒把一群群犹太人推入火堆活活烧死，如果有犹太人逃出来，围在四周的基督徒就一哄而上用大棍子把浑身着火的犹太人打得脑浆迸裂，或者乱刀捅死，当然这一样是没用的。人们彻底绝望了，最后甚至有人认为这种疾病是靠视线传染的，所以好多病人在生病以后，他的亲人会把他的房间用木板封死，任其活活渴死在屋里。父母抛弃孩子，丈夫抛弃妻子，人们纷纷表示世界末日已经近在眼前了。

如果有一天你得了传染病，你的病很是别人传染给你的，但是把病传染给你的那个人，他的病是怎么来的呢？如果我们一直向前追溯，这个世界上第一个得这种传染病的人，他的病是怎么来的呢？

包括黑死病、流感、天花、艾滋病在内，有很多传染病最开始是从动物身上来的。智人从一万多年前开始驯养野生动物之后就开始了人畜混居生活，和动物的近距离接触使得各种恐怖的瘟疫开始屠戮人间。6 世纪拜占庭帝国内就曾经爆发过一次严重瘟疫，被称为查士丁尼大瘟疫，当时人们上街时脖子上都得挂个牌子写上自己的姓名，因为在大街上走着走着可能突然就死了，脖子上有名牌收尸的时候比较方便。15 世纪，欧洲人登陆新大陆以后，各种致命的传染病轮番扫荡美洲，美洲的印第安人口被灭绝了 95%，传染病就这样永远地改变了美洲的民族人口比例。1918 年，西班牙大流感，全球感染 5 亿人，死亡 1 亿人，要知道当时全世界一共才 17 亿人。

中世纪黑死病之所以会在人群中迅速传播，其最直接的原因是欧洲人身上的跳蚤。在一些啮齿动物，比如家鼠的身体里存在着一种病菌，名叫鼠疫杆菌。在跳蚤吸食了老鼠的血以后，这种鼠疫杆菌会在跳蚤的前胃棘增生，造成前胃阻塞，这一效应被称为blocking，中文译作「菌栓」。有菌栓的跳蚤由于前胃被堵住了，吸食的血液很难进入胃里被消化，这让跳蚤始终处于饥饿之中，于是就更加疯狂地吸血。吸入的血液在和体内的鼠疫杆菌混合后，再由跳蚤呕吐回血管里，造成宿主感染。对于随地大小便还一辈子不洗澡的欧洲人来说，每个人都是一座会移动的跳蚤巢穴。就这样，这场恐怖的瘟疫横扫整个欧洲，轻而易举地就埋葬了 2000 多万人，相当于中世纪欧洲人口的 40%。欧洲人口几乎被腰斩，用了 150 年才恢复。最后因为欧洲人死得太多了，很多地方都被黑死病变成了无人区，黑死病才在数年之后渐渐平息。
* 每 10 秒杀一人，杀满 100 天

[[https://zhuanlan.zhihu.com/p/21979536][Source]]

十九世纪时，人们曾经做过一个实验，找来一只黑猩猩，在它面前摆上很多动物的照片，然后让这只黑猩猩给这些动物分类。有意思的是，这只黑猩猩把所有的动物分成两类：人类和非人类，但是当人们给它一张黑猩猩的照片时，它却把黑猩猩也划分到了人类里。这说明在黑猩猩看来，它们和人类是同类。其实从某种意义上来说，这只黑猩猩的划分非常有道理，人类和黑猩猩在基因上有 98% 是相同的，不少学者认为，黑猩猩和智人之间其实并没有什么本质差别。

在黑猩猩与智人的众多相似点中，有一个相似点非常残酷，那就是黑猩猩和智人是这个世界上仅有的两种会自发组织起来对别的同类族群施行种族灭绝的哺乳动物。对于黑猩猩来说，马尔萨斯陷阱一样是存在的，黑猩猩群体的数量会以几何速度递增，但是食物的总量却不会增加，对于不会种地的黑猩猩来说，它们获取更多食物的办法就是发动战争，消灭其他族群，然后将对方的地盘据为己有。

黑猩猩族群通常会有几只强壮的成年雄性在领地附近巡逻，如果它们看见有其他族群的黑猩猩落单的话，就会鬼鬼祟祟地靠过去，然后发动突然袭击，毫不犹豫地杀死目标。他们就用这种办法不断地杀掉别的族群里的雄性和幼崽，当它们认为优势已经足够大的时候，就会发动全面战争，将对方族群里的成年雄性和幼崽全部杀死，然后再用暴力占有对方族群里的母猩猩。

纵观整个人类历史，智人像黑猩猩那样的战争和屠杀行为是普遍存在的，而且这种行为非常古老。一些学者认为，黑猩猩和人类之所以嗜杀成性，其中一个很重要的原因就是黑猩猩和人类在遥远的过去有着共同的祖先。大概在距今 600 万年前，一只古猿生下了两个幼崽，一个成为了人类的祖先，另外一个成为了黑猩猩的祖先，因此人类和黑猩猩这两个物种同时从古猿那里继承了杀戮基因。对于黑猩猩来说，不同的族群生活在不同的区域，彼此之间有着清晰的界限，而人类在进入全球化之后，群体之间的界限变得非常模糊，这就使得问题变得复杂起来。

在人的大脑中有一个部位叫做下丘脑，这个部位会分泌一种被称为「催产素」的神经荷尔蒙，这种荷尔蒙会给人体带来各种各样的影响，其中有一个影响就是强化自身所在的团体认同。举个例子，大街上一个中国人和一个外国人正在打架，催产素水平高的中国人看到这种情况会倾向于帮助自己的同胞，如果正在打架的两个人都是中国人，但是一个是河南人一个是山东人，那催产素水平高的山东人会帮助自己的山东老乡，如果他发现两个打架的都是山东人，那催产素水平高的济南人则会团结起来对付青岛人。就这样，人们总是会倾向于分出个内外然后选边站，催产素的作用之一就是强化这种情绪。这种情绪往往是很多群体暴力行为的底层逻辑，大到国与国之间的战争和对峙，小到国安球迷和天津球迷之间的吵架斗殴，都是由这种情绪支配的。可是这些所谓的内外有的时候是客观存在的，有的时候则是不怀好意的人刻意编造出来的。

非洲中部有个小国卢旺达， _比利时殖民者在统治这个国家时，实行了一个非常荒谬的民族划分政策，他们通过观察当地人鼻子的宽度、身高、皮肤的颜色，把全国人大体上划分为两个民族，身高较高肤色较浅的被称为图西族，占总人口的 14%，肤色较深身高较矮的被称为胡图族，占总人口的 85%。除此之外比利时人还按照财产划分民族，规定有十头牛以上的人属于图西族，十头牛以下的算胡图族。_ 在今天看来，这种民族划分完全没有任何科学依据。 _当时比利时人为了将卢旺达人分而治之，他们要求所有卢旺达国民都要携带身份证，在身份证上清晰地标注其民族身份，然后再在行政、教育、经济、司法等方面故意偏袒作为少数民族的图西族，以挑拨两个民族之间的关系。_ 一开始卢旺达人对这种民族划分根本不以为然，因为他们之前从来就没有这种民族意识，但是当卢旺达人发现比利时殖民者一本正经地推行这个政策的时候，他们也不得不认真起来。

这种以践踏公平公正为代价而偏袒少数民族的政策并不能真正地造福少数民族，因为这种不公平会让卢旺达的主体民族对少数民族心生怨恨。在当时的卢旺达，这种因为不公正的民族政策而导致的愤怒和委屈，主体民族的怨恨也因此在社会生活中迅猛地传播和积累。再也没有什么能比不公平的民族政策更能撕裂一个国家了。另外， _比利时人在统治卢旺达时，认为图西族人的肤色较浅，比较接近白人，所以相对高贵一些，于是他们就利用只占总人口 14% 的图西人统治占总人口 85% 的胡图人，_ 比利时人的各种偏袒手段让卢旺达的少数民族图西人变得傲慢自负，而对卢旺达主体民族的侮辱和压迫却让胡图人越加地愤怒和不满，主体民族的怒火就像炽热的岩浆一样在全国蔓延。 _后来比利时人在离开这个国家时却出卖了图西人，他们故意把政权交到了胡图族的手里，这使得之前备受欺压的胡图人终于有了反攻清算的机会。_ 卢旺达本来就是一个在马尔萨斯陷阱里苦苦轮回的国度，殖民者荒谬的民族政策更加深了两族之间的仇恨和隔阂。

其实早在事件爆发以前，胡图族就已经在准备开展大规模的种族屠杀了，他们用各种手段搜集武器装备，然后秘密分发下去。他们还提前从中国订购了好多大砍刀，工厂看了订单以后，问为什么突然需要这么多大砍刀，胡图族人说他们今年香蕉的收成特别好，要买砍刀回去砍香蕉去。在民间，小道消息已经在市井街巷传得沸沸扬扬，有的图西人从自己的胡图族朋友那里听说，胡图族已经在秘密训练武装民兵。现在已经万事俱备，部署在全国的武装民兵都在等一个信号，那个信号是一句话：Cut down the tall trees（tall trees 在这暗示身高较高的图西人），只要这个信号一发出，全国的胡图族民兵就会倾巢而出，用砍刀和子弹清洗所有图西族人。

1994 年 4 月 6 日晚上 8:20，卢旺达的胡图族总统在去签署和平协议的路上时，其飞机在首都基加利机场附近被一颗来路不明的飞弹击中，包括总统在内的所有机上乘员当场遇难。到底是谁发射了那颗飞弹，仍然是个历史之谜，图西族和胡图族都在第一时间指责对方杀死了总统。无论如何，这场事故犹如弹药库里的一颗火星，顷刻间就引爆了卢旺达国内沉积已久的民族仇恨。

飞机失事的那天晚上，正好赶上非洲杯半决赛直播，很多卢旺达人都坐在收音机前听转播，突然之间，卢旺达全国的收音机里都传来了这样的声音，一个沙哑的男声咬牙切齿地说：卢旺达人民们，我们伟大的总统被蟑螂一样低贱的图西族人谋杀了，他们诱骗总统去签署虚假的和平协议，却在路上用飞弹伏击了他，优秀的胡图族同胞们啊，清算的时刻到了! We must cut the tall trees！Cut the tall trees now！

这句恶狠狠的诅咒通过无线电波传遍了卢旺达的大街小巷，片刻沉寂之后，卢旺达首都基加利以及附近郊区，自动步枪的开火声成片响起，爆炸、哭喊、求饶、咒骂，玻璃被砸碎的声音，砍刀砍进骨头里的声音，此起彼伏，收音机里不断地大喊着图西人的家庭住址和姓名，敦促胡图族将他们赶尽杀绝。

据一个联合国维和部队的军官回忆，在屠杀开始之后，卢旺达的公路上被疯狂的胡图人设下了很多路障，胡图族的民兵会严格检查每一辆过往车辆，如果发现图西人直接揪下来用砍刀斩首。而且胡图族民兵的脖子上还挂一个哨子，只要发现有图西族人试图逃跑，那人一吹哨子，附近的胡图族民兵就会拎着砍刀包抄上来，把图西人围在中间乱刀砍死。那个联合国军官说，他们的眼神已经不像是人类的眼神了，看起来就像被邪灵附体一样。有人回忆到，早在大屠杀全面爆发以前，就有几个胡图族士兵当着联合国维和部队士兵的面，用大砍刀把一个图西族妇女凌迟，那几个维和士兵被吓得连一句劝阻的话都说不出来，后来有人质问他们为什么不阻止暴行，他们辩解说，这是卢旺达人在杀卢旺达人，不归他们管。

上世纪 90 年代，卢旺达有相当多的胡图人是文盲，在广播电台的煽动下，他们真心地认为图西人是劣等生物，是蟑螂，所以有的胡图人甚至怀着非常轻松愉悦的心情屠杀图西人，就像修建草坪一样。胡图族民兵闯进图西人聚居区，然后一个房间接着一个房间杀人，一个街区接着一个街区清洗。广播电台里广播了图西人的住址之后还特意嘱咐一句，说有的图西人家里有孕妇，别忘了把孕妇肚子里的图西孽种也干掉。联合国维和部队军官曾经向美国方面申请炸掉那个煽动仇恨的广播电台，可是美国方面说这属于侵害别国主权。军官说那对那电台进行短波干扰总可以吧？让那个广播台闭嘴！否则会有更多的图西人被杀。美国方面说：你知道短波干扰的成本有多高吗？一个小时 8500 美元！就这样，在广播的煽动下，屠杀在全国迅速蔓延。

联合国军官还回忆说，他在自己办公室的时候，电话突然响了，电话那边是他的图西族朋友在喊：救命啊！救命！胡图族来杀人了！他们闯进来了！救命！然后先是传来一阵咒骂，然后紧接着就是砍刀砍肉，分筋错骨的声音，然后电话就被挂了。那个军官惊魂未定地挂了电话，刚一放下话筒，电话在一瞬间又响起来了，刚才那一幕再次重现。那个军官一天之内不知道接了多少个这样的电话，最后精神上受到了永久性的刺激。胡图族每天往他们国家的阿卡盖拉河里扔无数具图西人的尸体，这些尸体最后被河水送到了下游的乌干达，大量的尸体泡烂在河里，使得乌干达爆发了大瘟疫。最后卢旺达杀人能杀到什么程度，1994 年 7 月时，在卢旺达首都基加利附近，朝任何一个方向望去，尸体都能从脚下一直铺到地平线的尽头，整个国家都被笼罩在尸体腐烂的恶臭中，变成了一间巨大的露天太平间。

一些西方国家在卢旺达大屠杀中扮演了非常不光彩的角色。当时的一些西方媒体和领导人讲话中一直在用一个非常暧昧的词 massacre，这个词在英语中泛指大屠杀，而西方之所以一直坚持用这个词是为了避免使用 genocide，这个词在英语中特指「种族灭绝」。在二战时，德国纳粹曾经对犹太人进行过恐怖至极的屠杀。二战结束之后，人类社会觉得二战时发生的一些反人类暴行实在太邪恶了，无论如何也要阻止这种暴行再次发生。于是在 1948 年，联合国制定了第一个关于人权问题的国际公约：《防止及惩治灭绝种族罪公约》。这个公约的精神指出，世界上任何团体或组织如果做出种族灭绝的行为，将被视为整个人类文明的敌人，一些国家特别是美国将有义务立即采取强力行动阻止种族灭绝行为。可是 90 年代初，美军刚在非洲索马里吃了大亏，当时美军士兵的尸体被索马里武装分子扒光了游街，美国上下一片震恐，迫不及待地想从非洲脱身。所以为了欺骗世界舆论，更为了逃避责任，在胡图族对图西族进行种族灭绝的时候，美国从媒体到领导人竟然全部一口咬死说这不是种族灭绝，放任无数的图西人被有计价地灭绝。

卢旺达大屠杀持续了 100 天，全国死亡 100 万人，平均每天杀 1 万人，每小时杀 400 人，每 10 秒杀一个人。

20 多年过去，今天的卢旺达已经逐渐从当年大屠杀的阴影之中走了出来，实现了民族和解，今天卢旺达人的身份证上已经不再标注民族身份了，今天在那个国家里，只有一个民族，那就是卢旺达民族。
* 地狱看起来就像光绪初年的山西一样

[[https://zhuanlan.zhihu.com/p/21890770][Source]]

大约在 200 多年前，位于东太平洋赤道地区的渔民发现了一种奇怪的现象，那就是每隔几年，东太平洋地区海域的水温会明显升高，沿海地区的鱼群神秘消失，海鸟也会随之大量死亡，于此同时，世界其他地区的气候变得诡异起来，飓风、海啸、暴雨、洪涝、高温、干旱、极寒、暴雪等极端现象频现，由于这种奇怪现象往往会在圣诞节之际发展到最高峰，所以当地渔民就称这种现象为 El Nino，意为「上帝之子」，中文音译为「厄尔尼诺」现象。

且让我们把镜头转向清光绪元年，也就是公元 1875 年，清帝国在经历了一系列重大打击之后正努力恢复着元气，彼时的清帝国距离甲午惨败还有 20 年的时间，朝廷和洋人之间取得了暂时的和平，太平天国和捻军也已被镇压，恍惚之中，清帝国似乎真的有了一丝回光返照的迹象，奈何天要灭大清。1875 年，「上帝之子」再次降临东太平洋，在接下来的几年之内，全球将迎来历史中少见的强厄尔尼诺现象。这给人的感觉就好像西方的上帝要亲手埋葬这个东方的帝国。

光绪初年的清帝国并没有完全从两次鸦片战争的余波之中走出来，尽管清政府一再下令禁烟，但是全国范围内有很多农民出于贪婪依然顶风犯案，大规模地种植罂粟花以制备鸦片。贩毒的利润永远比种地高，所以罂粟占用了大片的耕地，这使得本来就紧张的粮食贮备更加紧张。就在这时，厄尔尼诺现象带来的干旱开始在华北地区尤其是山西省显现，一些地方文献开始出现粮食歉收的记载。1876 年，旱情没有得到任何缓解，山西的一些县城由于粮食歉收已经有人开始吃树皮、草根，但是这对于这场灾荒来说仅仅算个热身而已。

1877 年，恐怖开始了，山西各地迎来了全面旱荒，粮食大面积绝收。中国的老百姓对于灾荒是非常敏感的，一些有逃荒经验的民众知道如果留下来只怕是九死一生。大灾临头之际，老百姓的第一反应就是逃跑。当地知府得知老百姓要逃荒，立即赶赴现场，苦苦哀求百姓不要离开家乡，并且承诺一定会赈济百姓，老百姓见状，哗啦一下跪倒一片，说「多费府大老爷好心，念我们饥寒，就是每家与我们三两斗麦子，能吃几日？」老百姓知道，现在趁还有体力，能跑赶紧跑，要是跑到了有收成的地界说不定还能捡条命，要是留下来就真的死定了。说完大家叩头，哭声一片，知府也嚎啕大哭起来，官民就这样相对痛哭，可是哭也没用，老百姓依然逃散一空。

恐惧在华北各地蔓延，逃荒大潮已经势不可挡，有的官员因为无力阻止百姓逃难，绝望之下悬梁自尽。对于当时华北地区的人民来说，末日的帷幕才刚刚拉开。严重旱情依然在继续，有的土地已经旱得冒起了黄烟。随着灾情的发展，能吃上树皮都已经算是非常奢侈的事情了，没有树皮吃什么呢？有的灾民竟然找来一些石头，磨成石头渣滓吃，可是这种东西肠胃是消化不了的，吃进肚子里以后不仅会刮破肠胃，而且石头无法排泄出体外，最后人是被活活憋死的。

灾情依然在继续，丝毫没有缓解的样子。人性是非常禁不住考验的东西，人在绝望之后就是疯狂。当时在灾区的一些地方，谣言四起，说老百姓要饿死了，可是当地的一些大户人家家里有粮，一些灾民就开始砸大户人家院门要粮，可是灾情都到这地步了，地主家也没余粮，而且就算是有粮也不能给别人，当时谁有粮谁活，谁没粮谁死，就这么简单。那些大户人家闭门不答，外边的灾民先是叫骂，发现没效果之后，他们想了一招，当时满大街都是死人，那些灾民就拖来很多尸体，先把尸体吊在大户人家的院门前边，然后再把死人脑袋给剁下来扔进大户人家院里，就用这种方式勒索粮食。随着灾情的进一步加重，就连这种勒索粮食的无赖行为都消失了，弥漫在灾区的恐怖又深入了一层。

有一本清朝人回忆这场灾荒的书，叫《晋灾泪尽图》，书里记载了这么一件事：有一位来自南方的客人，路过山西的时候正好赶上这场灾荒，老婆被活活饿死了，他忍不住嚎啕大哭，但是他身边的人立即把院门关上然后让他闭嘴，因为当时在街上已经有了抢尸而食的事发生，只要有人一哭，就有人知道这院子里死人了，马上就会有人来抢尸体吃。那个死了老婆的人就问那怎么办，身边的人说等到了夜里，咱们再把你老婆埋院子里，让她入土为安。当天夜里，他们小心翼翼地把尸体埋在院子里，生怕惊动抢尸人。第二天天亮了，他们再到院子里一看，院子里埋得浅的尸体已经被人挖出来，吃得只剩骨头了。而且这种事还不是个例，在山西各地接连出现，说有一村子里有一户人家，夜里睡觉的时候听见院子里有动静，主人就从窗户缝望出去，发现月光之下有两个人背起他母亲的尸体往外跑，那主人赶紧追出去，一直追到了那两个人的住所，但是那屋主人发现那两个人手里拎着斧头和砍刀，就不敢进去，只好跑回村子找人帮忙，等一大群主持公道的村民回到现场时，发现屋主母亲的尸体已经被扒光了放在大锅里煮熟了。村民们一哄而上，把那两个凶手五花大绑抓起来，整个过程中，那两个凶手一直大声叫骂：「宁为村中死鬼，不为县中活人！」村民捆那两人的时候，发现那两个人的屋子里全是死人骨头，这两个人已经饿疯了，变成了食人魔，不知道他们吃了村子里多少人。最后村民协商，把这两人用铡刀活活劈成了两半。

一旦到了人吃人的地步，就标志着社会秩序的彻底崩溃，对文史感兴趣的读者应该听说过新几内亚食人族的例子，吃人肉很有可能导致严重的神经系统疾病（库鲁症）。而且大部分尸体因为迅速腐败，已经不能食用了，但是对于食腐的狼来说，这是再好不过的美味，腐烂的尸体吸引了大量野狼进入人类活动的地方，以至于灾区又出现了野狼吃人的狼灾。狼群在灾区各地四处游荡捕食百姓，任何与它们遭遇的人都留不下全尸。

到 1878 年，灾荒已经到了让人毛骨悚然的地步，有外国传教士回忆说，在山西的一些道路上，无数面如僵尸的灾民摇摇晃晃地走着，野狗则跟在这些灾民身后，一阵风就能吹倒几个难民，倒地的人还没咽气就已经被扑上来的野狗分食了。后来有的外国传教士实在饿得受不了了，于是走进一间民宅讨饭，刚一进屋差点滑一个跟头。他低头一看，地上一层蛆，因为这家人全家都饿死在了屋里，没人给他们收尸，全家烂在屋里，尸体上的蛆已经堆不下了，新蛆噼里啪啦地从尸体流淌到地上，这个传教士几乎被吓疯了，夺门而逃，从此再也不敢随便进入灾区任何一家民宅。

最后，这场灾荒到了什么程度？一个曾经去过灾区的人回忆说，他们路过灾区的时候，听见马车在行进的时候「咔嚓咔嚓」直响，他探出头一看，发现路上全是累累白骨，那咔嚓声是车轮碾碎死人骨头的声音，他吓得缩在车里瑟瑟发抖不敢再看。过了一会，刮风了，大风吹进车里很多黑色的毛发，那人仔细一看，发现那些毛发全是死人的头发。当时的灾区饿殍遍野，荒野上的尸体的头皮已经被喜鹊和乌鸦啄烂了，死尸的头发被大风吹遍原野，于是山西大地上吹起黑色的风。就这样，灾民们曾经留在这个世界的最后证据也在风中吹散了。

这场灾荒从 1876 年一直持续到 1879 年，期间又以 1877 和 1878 两年最甚，1877 年为丁丑年，1878 年为戊寅年，所以这场光绪初年的灾荒被后世称为「丁戊奇荒」。在这场灾荒中，至少有一亿人受灾，1000 万人被饿死。此般惨剧，难怪曾国藩的弟弟曾国荃曾经说过「就是地狱也不过如此了。」


