#+SETUPFILE: ../../styles/readtheorg.setup
#+TITLE: Life Scrap

* 常见房型
** 平房（bungalow）

通常平房在地面上只有一层，少数也有局部错层的二楼。主要房间如卧室、家庭厅、厨房等均在一层，地下室部分往往设计成分门出入式。平房曾于五、六十年代在美国、加拿大流行，因为它造价经济、设计简约、施工方便，符合那个时代的需求。但是平房并非廉价房屋的代表，平房的标准实际上更高，因为这种房型占地面积大，土地的容积率是最低的。

平房由于无需上下楼梯，特别适合老人居住，因此成为了喜欢摆弄花草的老人的首选住宅类型。大多数的度假别墅（cottage）采用的就是平房的房型。

** 独立屋（detached house）

独立屋一般是指独门、独户、独院的住宅，与邻居的建筑物没有任何连接。

** 半独立屋（semi-detached house）

半独立屋在中国一般称为双拼别墅。半独立屋的每个单位至少有一面墙与邻居相连共用。

** 后复式屋（backsplit house）

后复式屋一般归在 house 的房型里面。其实是平房往独立屋演化的一种类型，介于平房和独立屋之间。错半层的功能设计，使得一栋建筑物里面呈现四层或是五层的格局，所以空间上一般感觉很大，房间很多。后复式屋还可以细分成后复式五层、侧复式四层等类型。一些度假别墅也会采用这种房型。

** 连屋（link house）

从外部看，除了建筑物之间的间距比较小一些之外，连屋和普通的独立屋没有太大的区别。从内部结构上来看，连屋之间的地基、地下室连成一个整体结构。但是，连屋在使用上和独立屋没有差别，只有在涉及到翻新或重建工程的时候，才会体现出不同。

** 镇屋（townhouse）

镇屋在中国一般称为排屋或者连排别墅。一列镇屋至少有三个以上的单位。传统镇屋大多是两层高，也有三层高的镇屋。一些镇屋的车库和半地下室（walk out basement）设计在地面上，所以看起来可能达到四层。

** 叠式镇屋（stacked townhouse）

叠式镇屋在加拿大相对比较少见，在中国叫叠拼别墅。叠式镇屋是指在一排镇屋里面，一个单位是位于另一个单位之上的，一般三层或四层高，常见于人口密聚区，是因地皮紧张而产生的一种镇屋形式。这类镇屋通常没有自己的院子，在同一层上可能有两个单位并存，设计难度比较高。

** 共管公寓（condo）

加拿大的共管公寓和中国的精装修商品房类型相近。共管公寓一般设计成高层住宅大厦，常集中在市区或交通方便的十字路口。这类住宅一般面积有限，适于小型家庭居住。优点是健康娱乐设施丰富、无需打理屋前门外的卫生、花草等，垃圾只需放置于指定的地点，无需像独立屋那样每周都要汇总收拾、推出门外等待垃圾车运走。共管公寓的停车都是集中管理，业主可以根据自己的情况购买停车位。
