#+SETUPFILE: ../../styles/readtheorg.setup
#+TITLE: Random Stuff Read Online

* 2019
** 2019/07/30
*** [[https://www.zdnet.com/article/isscc-2019-preview-moores-law-may-be-slowing-down-but-innovation-isnt/][Moore's Law may be slowing down, but innovation isn't]]

For the first time in 66 years, the annual semiconductor conference ISSCC (International Solid-State Circuits Conference) will not include any new general-purpose processors.

- General-purpose processor usually refers to CPU, because it's designed for general computing applications. Examples of non-general-purpose processors include: GPU (specialized in geometric calculation), FPU (specialized in floating point calculations), etc.
- CPU has branch prediction to speed up conditionals, and layered caches to speed up memory access. GPU doesn't have these optimizations, in exchange, it has more transistors to speed up mathematical-related operations. [[https://en.bitcoin.it/wiki/Why_a_GPU_mines_faster_than_a_CPU][Why a GPU mines faster than a CPU?]]

The lack of any major microprocessor presentations seems to reflect two trends. First, Moore's Law scaling is slowing down as transistors approach fundamental limits. Second, recent gains have come less from general-purpose CPUs and more from specialized accelerators such as GPUs, FPGAs and custom chips known as ASICs, specialized for automotive, robotics, cryptography, graph processing and optimization problems.

Most of the progress in deep learning since the ImageNet contest in 2012 has been in supervised learning, which requires lots of data labeled by humans, or in reinforcement learning, which requires too many trials to be practical for many applications.

*** [[https://www.urbandictionary.com/define.php?term=Rule%2034][Rule 34]]

Any object, character, or media franchise imaginable has porn associated with it. Only one known exception: rule 34 itself.

*** [[https://www.urbandictionary.com/define.php?term=Rule%2035][Rule 35]]

An addendum to Internet Rule 34, which states "If there is not porn of it, porn will be made of it."
** 2019/07/31
*** [[https://www.youtube.com/watch?v=QXjU9qTsYCc][How do computers read code?]]

Machine code (binary code) is CPU instructions.

Compiling process:

1. [[https://en.wikipedia.org/wiki/Lexical_analysis][Lexical analysis]]: source code is broken into tokens.
2. [[https://en.wikipedia.org/wiki/Parsing][Syntactic analysis]]: tokens are organized into parse tree.
3. [[https://en.wikipedia.org/wiki/Semantic_analysis_(compilers)][Semantic analysis]]: symbol table is built with context (variable, function names etc.).
