#+SETUPFILE: ../../styles/readtheorg.setup
#+TITLE: Random Stuff Read Online

* [[https://www.zdnet.com/article/isscc-2019-preview-moores-law-may-be-slowing-down-but-innovation-isnt/][Moore's Law may be slowing down, but innovation isn't]]

For the first time in 66 years, the annual semiconductor conference ISSCC (International Solid-State Circuits Conference) will not include any new general-purpose processors.

- General-purpose processor usually refers to CPU, because it's designed for general computing applications. Examples of non-general-purpose processors include: GPU (specialized in geometric calculation), FPU (specialized in floating point calculations), etc.
- CPU has branch prediction to speed up conditionals, and layered caches to speed up memory access. GPU doesn't have these optimizations, in exchange, it has more transistors to speed up mathematical-related operations. [[https://en.bitcoin.it/wiki/Why_a_GPU_mines_faster_than_a_CPU][Why a GPU mines faster than a CPU?]]

The lack of any major microprocessor presentations seems to reflect two trends. First, Moore's Law scaling is slowing down as transistors approach fundamental limits. Second, recent gains have come less from general-purpose CPUs and more from specialized accelerators such as GPUs, FPGAs and custom chips known as ASICs, specialized for automotive, robotics, cryptography, graph processing and optimization problems.

Most of the progress in deep learning since the ImageNet contest in 2012 has been in supervised learning, which requires lots of data labeled by humans, or in reinforcement learning, which requires too many trials to be practical for many applications.

* [[https://www.urbandictionary.com/define.php?term=Rule%2034][Rule 34]]

Any object, character, or media franchise imaginable has porn associated with it. Only one known exception: rule 34 itself.

* [[https://www.urbandictionary.com/define.php?term=Rule%2035][Rule 35]]

An addendum to Internet Rule 34, which states "If there is not porn of it, porn will be made of it."

* [[https://www.youtube.com/watch?v=QXjU9qTsYCc][How do computers read code?]]

Machine code (binary code) is CPU instructions.

Compiling process:

1. [[https://en.wikipedia.org/wiki/Lexical_analysis][Lexical analysis]]: source code is broken into tokens.
2. [[https://en.wikipedia.org/wiki/Parsing][Syntactic analysis]]: tokens are organized into parse tree.
3. [[https://en.wikipedia.org/wiki/Semantic_analysis_(compilers)][Semantic analysis]]: symbol table is built with context (variable, function names etc.).
* European Commission

The European Commission has announced an agreement whereby English will be the official language of the EU, rather than German, which was the other contender. Her Majesty's Government conceded that English spelling had room for improvement and has therefore accepted a five-year phasing in of "Euro-English".

In the first year, "s" will replace the soft "c". Sertainly, this will make sivil servants jump for joy. The hard "c" will be dropped in favour of the "k", Which should klear up some konfusion and allow one key less on keyboards.

There will be growing publik enthusiasm in the sekond year, when the troublesome "ph" will be replaced with "f", making words like "fotograf" 20% shorter.

In the third year, publik akseptanse of the new spelling kan be expekted to reach the stage where more komplikated changes are possible. Governments will enkourage the removal of double letters which have always ben a deterent to akurate speling. Also, al wil agre that the horible mes of the silent "e" is disgrasful.

By the fourth yer, peopl wil be reseptiv to steps such as replasing "th" with "z" and "w" with "v".

During ze fifz yer, ze unesesary "o" kan be dropd from vords kontaining "ou" and similar changes vud of kors be aplid to ozer kombinations of leters. After zis fifz yer, ve vil hav a reli sensibl riten styl. Zer vil be no mor trubls or difikultis and everivun vil find it ezi to understand ech ozer. ZE DREM VIL FINALI COM TRU!

** Links

1. [[http://www.davidpbrown.co.uk/jokes/european-commission.html][European Commission]]

* Thinking Ahead

A police officer pulls a guy over for speeding and has the following exchange:

Officer: May I see your driver's license?

Driver I don't have one. I had it suspended when I got my 5th DUI.

Officer: May I see the owner's card for this vehicle?

Driver: It's not my car. I stole it.

Officer The car is stolen?

Driver: That's right. But come to think of it, I think I saw the owner's card in the glove box when I was putting my gun in there.

Officer: There's a gun in the glove box?

Driver: Yes sir. That's where I put it after I shot and killed the woman who owns this car and stuffed her in the trunk.

Officer: There's a BODY in the TRUNK?!?!?

Driver: Yes, sir.

Hearing this the officer immediately called his captain. The car was quickly surrounded by police, and the captain approached the driver to handle the situation:

Captain: Sir, can I see your license?

Driver: Sure, Here it is.

It was valid.

Captain: Who's car is this?

Driver: It's mine officer, here's the owner' card.

The driver owned the car.

Captain: Could you slowly open your glove box so I can see if there's a gun in it?

Driver: Yes, sir, but there's no gun in it.

Sure enough, there was nothing in the glove box.

Captain: Would you mind opening the trunk? I was told you said there's a body in it.

Driver: No problem.

Trunk is opened; no body.

Captain: I don't understand it. The officer who stopped you said you told him you didn't have a license, stole the car, had a gun in the glove box, and that there was a dead body in the trunk.

Driver: Yeah, I'll bet the lying b*****d told you I was speeding too.

** Links

1. [[http://www.davidpbrown.co.uk/jokes/thinking-ahead.html][Think Ahead]]

* Surrogate Father

The Smiths had no children and decided to use a proxy father to start their family. On the day the proxy father was to arrive, Mr. Smith kissed his wife and said, "I'm off. The man should be here soon".

Half an hour later, just by chance, a door-to-door baby photographer rang the doorbell, hoping to make a sale.

"Good morning madam. You don't know me, but I've come to...."

"Oh, no need to explain. I've been expecting you," Mrs Smith cut in.

"Really?" the photographer asked. "Well, good! I've made a specialty of babies."

"That's what my husband and I had hoped. Please come in and have a seat. Just where do we start?" asked Mrs Smith, blushing.

"Leave everything to me. I usually try two in the bathtub, one on the couch and perhaps a couple on the bed. Sometimes the living room floor is fun too; you can really spread out."

"Bathtub, living room floor? No wonder it didn't work for Harry and me.

"Well, madam, none of us can guarantee a good one every time. But if we try several different positions and I shoot from six or seven angles, I'm sure you'll be pleased with the results."

"I hope we can get this over with quickly," gasped Mrs Smith.

"Madam, in my line of work, a man must take his time. I'd love to be in and out in five minutes, but you'd be disappointed with that, I'm sure."

"Don't I know!!" Mrs Smith exclaimed.

The photographer opened his briefcase and pulled out a portfolio of his baby pictures. "This was done on the top of a bus in downtown London."

"Oh my!!" Mrs Smith exclaimed, tugging at her handkerchief.

"And these twins turned out exceptionally well when you consider their mother was so difficult to work with." The photographer handed Mrs Smith the picture.

"She was difficult?" asked Mrs Smith.

"Yes, I'm afraid so I finally had to take her to Hyde Park to get the job done right. People were crowding around four and five deep, pushing to get a good look."

"Four and five deep?" asked Mrs Smith, eyes widened in amazement.

"Yes," the photographer said. "And for more than three hours too. The mother was constantly squealing and yelling. I could hardly concentrate. Then darkness approached and I began to rush my shots. Finally, when the squirrels began nibbling on my equipment I just packed it all in."

Mrs Smith leaned forward. "You mean they actually chewed on your, er..,um.., ah.... equipment?"

"That's right. Well madam, if you're ready, I'll set up my tripod so that we can get to work."

"Tripod??" Mrs Smith looked extremely worried now.

"Oh yes, I have to use a tripod to rest my Canon on. It's much too big for me to hold while I'm getting ready for action. Madam? Madam?

** Links

1. [[http://www.davidpbrown.co.uk/jokes/surrogate-father.html][Surrogate Father]]


