#+SETUPFILE: ../../styles/readtheorg.setup
#+TITLE: Are you smart enough to work at Google?

* Chapter 2

#+BEGIN_QUOTE
With any question in probability, it is important to know which parts of the story happen by chance and which by design.
#+END_QUOTE

#+BEGIN_QUOTE
... loss aversion. It's universal human nature to recoil from a decision that might leave one worse off, even when the odds are favorable. ... Better safe than sorry. ... Anyone who invents new products would do well to keep this in mind. The consumer thinking of switching boxes or brands may be motivated by reasons that have nothing to do with logic.
#+END_QUOTE

#+BEGIN_QUOTE
We associate color with density, and transparency with nothingness. That instinct is completely wrong with balloons. Air is invisible, and we ignore it 99+ percent of the time. (A ballon) is a partial vacuum within the surrounding air.
#+END_QUOTE

#+BEGIN_QUOTE
The Einstein equivalence principle says that there is no (simple) physics experiment that can distinguish between gravity and acceleration. This assumption is the foundation of Einstein's theory of gravity, known as general relativity.
#+END_QUOTE
* Chapter 5

[[https://sites.google.com/site/steveyegge2/google-secret-weapon][Google's Secret Weapon]]
#+BEGIN_QUOTE
Smart people go where smart people are, which enables them to launch cool stuff, which attracts more attention, and suddenly you have a feedback loop.
#+END_QUOTE
