#+SETUPFILE: ../../styles/readtheorg.setup
#+TITLE: Consent of the Networked

* Preface

#+BEGIN_QUOTE
Not only are software and hardware more efficient and omniscient than humans, but conveniently they also lack consciences.
#+END_QUOTE

#+BEGIN_QUOTE
The technologies and policies that make surveillance and censorship possible in China and many other countries are closely connected to policy, business, and technical decisions being made by governments and companies in the democratic West.
#+END_QUOTE
* Introduction

#+BEGIN_QUOTE
If the events of 2011 taught the world anything, it is that although the Internet empowers dissent and activism, it is not an instant freedom tonic that, when applied in sufficient quantities, automatically results in freedom.
#+END_QUOTE

#+BEGIN_QUOTE
It is a reality of human nature that those with power, however benign or even noble their intentions, will do what they can to keep it.
#+END_QUOTE

#+BEGIN_QUOTE
The essence of Government is power; and power, lodged as it must be in human hands, will ever be liable to abuse. - James Madison
#+END_QUOTE

#+BEGIN_QUOTE
In the physical world, mechanisms of democratic politics and constitutional law have worked ... to protect citizens' rights. But these mechanisms are no longer adequate for people whose physical lives now depend on what they can or cannot do (and what others can do to them) in the new digital spaces where sovereignty and power are ill-defined and highly contested. The reality is that the corporations and governments that build, operate, and govern cyberspace are not being held sufficiently accountable for their exercise of power over the lives and identities of people who use digital networks. They are sovereigns operating without the consent of the networked.
#+END_QUOTE

#+BEGIN_QUOTE
"Governance" functions, once carried out almost entirely by nation-states, are now shared increasingly by private networks and platforms. The lives of people around the world ... are increasingly shaped by programmers, engineers, and corporate executives for whom nobody ever voted and who are not accountable to the public interest in any way.
#+END_QUOTE

#+BEGIN_QUOTE
In the first half of the twentieth century, corporations were forced to consider employees' safety and health. In the past fifty years the environmental movement has forced industry to share responsibility for pollution and more recently climate change ... So far, most Internet and telecommunications companies have failed to accept responsibility ― beyond cyber-utopian platitudes ― for the rights of their customers and users, even as companies in other, much older industries have long since begun to do so with their workers, shareholders, and broader stakeholders.
#+END_QUOTE

#+BEGIN_QUOTE
In the twenty-first century, many of the most acute political and geopolitical struggles will involve access to and control of information. Human freedom increasingly depends on ... what information we are able to create and disseminate: what we can share; how we can share it; and with whom we can share it.
#+END_QUOTE

#+BEGIN_QUOTE
Contrary to what some people may have hoped and believed, the Internet does not change human nature. We have begun to see how absolute power in cyberspace corrupts absolutely as it does in physical space.
#+END_QUOTE

#+BEGIN_QUOTE
The Internet is a human creation. Power struggles are an inevitable feature of human society.
#+END_QUOTE
* Chapter 1: Consent and Sovereignty

#+BEGIN_QUOTE
Innovative technology in the hands of brave people can free us all from tyranny.
#+END_QUOTE

#+BEGIN_QUOTE
The struggle for freedom in the Internet age is shaping up to be very different from the ideological struggles of the twentieth century. Today's struggle is not a clear-cut contest of democracy versus dictatorship, communism versus capitalism, or one ideology over another. Human society has acquired a digital dimension with new, cross-cutting power relationships. ... Today's battles over freedom and control are raging simultaneously across democracies and dictatorships; across economic, ideological, and cultural lines.
#+END_QUOTE

#+BEGIN_QUOTE
On the one hand are the customers and users ― also citizens of polities ― whose trust is required for long-term business success, and who themselves hold a range of often-conflicting beliefs and values. On the other hand are governments, whose approval and regulatory support is critical if the corporations are to run profitable businesses or gain access to lucrative markets, and who are often important customers themselves.
#+END_QUOTE

#+BEGIN_QUOTE
The problem is that our ability to organize and speak out is shaped ― often quite subtly ― by the Internet service providers, e-mail services, mobile devices, and social networking services. If our communications and access to information are manipulated in ways we are not aware of, and if these companies' relationships with government are opaque, our ability to understand how power is being exercised over us, and our ability to hold that power to account, will be eroded in a more subtle and insidious manner than Orwell ever imagined.
#+END_QUOTE

** Corporate superpowers

#+BEGIN_QUOTE
Successful businesses need regulatory and legal environments that allow private citizens to form companies, borrow money or obtain investment, and protect their rights to property and inventions ― both physical and virtual. It was no accident that Microsoft, Apple, Google, and Amazon were spawned by entrepreneurs in the United States and not in other countries with more constrained regulatory, entrepreneurial, and political environments.
#+END_QUOTE

#+BEGIN_QUOTE
... the conventional power politics of nation-states is disrupted by the emerging power of the private sector. Approximately half of the world's one hundred largest economic entities are now corporations. If Wal-mart were a country, it would be the world's twenty-fifth-largest economy in terms of GDP, ahead of countries such as Norway, Venezuela, and the United Arab Emirates.
#+END_QUOTE

** Legitimacy

#+BEGIN_QUOTE
Modern concepts of sovereignty and legitimacy first germinated eight hundred years ago when a critical mass of English nobility decided that the unconstrained "divine right of kings" no longer served their interests ... forced King John to sign a document called the Magna Carta. This "great charter" recognized that even kings must be bound by law and unleashed a powerful set of ideas about legal rights and political sovereignty.

The Magna Carta was the first attempt in the Western world since the ancient Greeks to enshrine the idea that a sovereign's legitimacy does not derive solely from divine right and brute force; even the king is subject to the law. Though the barons were hardly populists, let alone revolutionaries ― their goal was to protect the interests of an elite ruling class ― the Magna Carta nonetheless laid the groundwork for the concept of the modern nation-state, based on the rule of law over men.
#+END_QUOTE

#+BEGIN_QUOTE
In 1647 during the English civil war, a scrappy group of commoners calling themselves the Levellers issued a declaration of rights, including assertions that all citizens have the right to liberty of conscience and religion; that all laws must respect all persons equally, regardless of wealth, nobility, or lack thereof ... Even though they failed, their ideas eventually inspired the American Declaration of Independence and the Bill of Rights, and became the building blocks of the United Kingdom's modern parliamentary system.
#+END_QUOTE

#+BEGIN_QUOTE
... we have a problem: we understand how power works in the physical world, but we do not yet have a clear understanding of how power works in the digital realm.
#+END_QUOTE

#+BEGIN_QUOTE
The point of democracy is that power, when unchecked, will be abused by any person or group of people with the opportunity to wield it. More than three hundred years since the Treaty of Westphalia and over two hundred since the world's first democracy was established, we have a reasonable understanding of how nation-states wield power and how state power can be constrained by constitutions, elections, laws, and international treaties.
#+END_QUOTE

#+BEGIN_QUOTE
Amid all of our excitement over new technologies, our default assumption as citizens must be that governments, powerful corporations seeking market dominance, and various other interest groups will use digital networks to obtain and maintain power whenever the opportunity presents itself. If existing institutions and mechanisms are inadequate to constrain the abuse of power across globally interconnected digital networks, political innovation must catch up to technological innovation.
#+END_QUOTE

#+BEGIN_QUOTE
Democracy was never advanced by people asking politely.
#+END_QUOTE

#+BEGIN_QUOTE
Conceiving and implementing a governance structure for a globally interconnected digital world that constrains the abuse of both government and corporate power and protects individual rights ― based on the notion of consent of the networked ― is not going to be any easier. A first step in that direction is to acknowledge, protect, and nurture a powerful counterweight to government and corporate power: the digital commons.
#+END_QUOTE

* Chapter 2: Rise of the Digital Commons

#+BEGIN_QUOTE
In the early 1800s, when the United States was still a novel political experiment, Alexis de Tocqueville observed in his classic book Democracy in America that the key to functional democracy was a vibrant "civil society." He described the importance of active involvement by citizens in community life: people from all social strata and professions taking personal responsibility for the safety and well-being of their communities, pushing back against perceived infringements of their rights, and sharing ideas and forming associations to solve problems and improve life for everybody.
#+END_QUOTE

** The Technical Commons

#+BEGIN_QUOTE
The technical standards upon which the Internet and the World Wide Web depend are at the core of the digital commons: they are not copyrighted or trademarked.They are free and open to all. The Internet's inherent value and power come from the fact that it is globally interoperable and decentralized, so that everybody can add to the network and create products, services, and platforms on top of it without having to obtain permission or license, or some kind of access code, from anybody in particular.
#+END_QUOTE

#+BEGIN_QUOTE
The technical protocols that enable different kinds of computers and software to communicate with one another across networks are called TCP/IP. These protocols were developed by engineers working across a variety of research labs and companies. ... The Internet would not be what it is today if those engineers had been unable or unwilling to share TCP/IP freely with the world as part of the digital commons.
#+END_QUOTE

#+BEGIN_QUOTE
The World Wide Web, invented two decades after the Internet, ... Sir Tim Berners-Lee ... in 1990 ... wrote a simple computer program called the WorldWideWeb to make it easier for researchers in his lab to locate and share each other's data. Sir Berners-Lee did not try to patent or charge for the use of his HTML language and the web-addressing system he created; instead he released them into the public domain.
#+END_QUOTE

#+BEGIN_QUOTE
... open standards organizations (such as the Internet Engineering Task Force, or IETF, and the World Wide Web Consortium, or W3C) and the coordinating bodies that maintain the global addressing and domain name system (like the Internet Corporation for Assigned Names and Numbers, or ICANN, and regional Internet registries). These organizations maintain, update, and add to the technical standards necessary to keep the Internet running on increasingly sophisticated devices used by almost two billion people around the planet. Governments do not run any of these organizations. Some countries ― China, Iran, and Brazil, to name a few ― have lobbied for the United Nations to take over these organizations and coordinating bodies. Other countries, including the United States, are opposed. So are human rights groups and most major Western Internet companies.
#+END_QUOTE
