#+SETUPFILE: ../../styles/readtheorg.setup
#+TITLE: 飞行中的科学

* 第一章
** 飞行安全

#+BEGIN_QUOTE
一年中，平均 125,000,000 名乘客中只有一人丧生于空难。这比火车旅行要安全三倍。汽车事故，同等风险比率是 1 比 10,000,000，约是飞行危险度的 12 倍。比起在飞机上度过的 6 小时，你在上班场所的 6 小时所可能遭遇事故的风险要更大。

The risk of being killed in a plane crash in any particular year is 1 in 125 million passenger journeys. This makes it three times safer on any particular journey than travelling by train. The equivalent risk for a car is 1 in 10 million – twelve times as dangerous. You're more likely to have a fatal accident during six hours spent in the workplace than you are during six hours on a plane.
#+END_QUOTE

file:../images/inflight_science/01.png

file:../images/inflight_science/02.jpg

file:../images/inflight_science/03.jpg

[[https://en.wikipedia.org/wiki/List_of_aircraft_accidents_and_incidents_resulting_in_at_least_50_fatalities][List of aircraft accidents and incidents resulting in at least 50 fatalities]]\\
[[http://data.worldbank.org/indicator/IS.AIR.PSGR][Air transport, passengers carried]]\\
[[https://en.wikipedia.org/wiki/Aviation_accidents_and_incidents][Aviation accidents and incidents]]\\
[[https://en.wikipedia.org/wiki/Aviation_safety][Aviation safety]]

#+BEGIN_QUOTE
一架飞机从德国某个机场起飞，脱离跑道的时候有些困难，最终才可谓是「爬」上了天空。后来大家才意识到，之前这个城市举办了一场钱币展销会。这趟航班的很多乘客都是钱币商人，袋子里都塞满了新入手的硬币。这些未曾预料的些许增重累计在一起使得乘客重量明显高过预期。

The plane, taking off from a German airport, struggled to get away from the runway and only just managed to claw its way into the air. It later turned out that there was a coin fair on in the city, and many of the passengers were coin dealers with their pockets crammed with new acquisitions. All this unexpected spare change pushed the passengers' weight well above the expected average.
#+END_QUOTE

** X 射线

#+BEGIN_QUOTE
当普通光照射在行李箱这样的物体上时，光束中的光子被吸收，使它不能完全穿透物体。这是因为光子中的能量被那些构成行李箱的粒子吸收了。电子一旦吸收光子中的能量，就从低能级跳到高能级。不久之后，富余的能量又重新以新光子的形式被释放出来，电子失去能量后又回到低能级。我们不清楚光子会朝哪个方向被电子射出来，不过总有一些光子能被我们的眼睛捕捉到。正是因为有了这些被电子释放出来的光子，我们才能看见周围的物体。

When ordinary light hits an object like a suitcase that isn't transparent, the photons of light are absorbed. This happens because the energy in the photon is sucked up by one of the particles that make up the suitcase. Once the electron has absorbed the energy of the photon, it's as if it were teetering on top of a high wall. Before long, that extra energy shoots back out in the form of a new photon, and the electron drops back to having less energy. We don't know in which direction a particular photon will shoot off, but over time some will head towards your eyes. It's these photons, pumped out by the electrons in an object, that allow you to see it.
#+END_QUOTE

file:../images/inflight_science/04.jpg

#+BEGIN_QUOTE
_X 射线中光子的能量远远大于普通光线中的光子，这使它能够迅速突破物体原子中的电子层，减少与电子的相互作用。这意味着 X 射线可以穿透许多能阻挡普通光线的物体。_ X 射线穿透物体时会破坏其中的分子，如果细胞中的 DNA 分子或是其他重要的化学物质被 X 射线损坏，会大大提高患癌症的风险。医用 X 射线通常都被控制在最小剂量，用于扫描行李的 X 射线的强度比大多数医用 X 射线要大得多。

Each photon in X-rays has a lot more energy than a photon of ordinary light, enabling it to smash past the electrons in an object's atoms with much less interaction. This means that X-rays can penetrate many substances that stop ordinary light dead. In the process of battering through matter, the X-rays can cause damage to the molecules. If DNA molecules, or other important chemicals in the cell, are damaged by the impact of X-rays, the changes can increase the chances of cancer forming. Medical X-rays have to be used with care, keeping doses to a minimum. Baggage X-ray machines are considerably more powerful than most medical X-rays.
#+END_QUOTE

#+BEGIN_QUOTE
在机场看到的巨大的扫描设备使用的都是宽幅 X 射线，其中某些 X 射线的穿透能力要比另一些强。由于使用两种强度不同的 X 射线，操作屏幕上会显示出两幅色彩不同的影像。因此，操作者能够分辨出植物、塑料或爆炸物之类的「软」物品，它们在屏幕上呈现出橘色，而那些较难穿透的物品则显示为绿色。

Those big scanners you now find in airports use a wide band of X-rays, some more powerful than others. This distinction between the two strengths of X-ray is used to produce different-coloured images on the operator's screen. This way the picture will distinguish between "soft" matter like plants, plastic or explosives – which are usually coloured orange by the scanner – and less penetrable matter, which will let only the more powerful X-rays through – typically coloured green.
#+END_QUOTE

file:../images/inflight_science/05.jpg

** 嗅探器

#+BEGIN_QUOTE
嗅探器通过分辨气味来排查爆炸物。和许多物质一样，爆炸物容易挥发。爆炸物中的化学分子会在室温下挥发，飘浮在空气中。

A sniffer hunts down explosives by their smell. Like many substances, explosives are to some extent volatile. This means that some of the molecules making up the chemicals within the explosive evaporate at room temperature and waft into the air.
#+END_QUOTE

#+BEGIN_QUOTE
狗是所有先进技术中最古老的一项。在人类有意识地培育下，狗成为了一个具有特定功能的独特品种，它们是最早的能行使自动化功能的「工具」。 _自然界中本没有狗，它们是人类开发出来的「工具」。狗是我们祖先创造的最了不起的东西之一。_ 与狗相比，巨石阵简直不值一提。狗是一项石器时代的「技术」，比巨石阵早 35000 年，而且直到今天，它们还活跃在世界各地的机场中。

The dog is the oldest piece of highly developed technology still in active use. Dogs have been consciously moulded into distinct breeds with specific functions in mind. They were the first autonomous technology. The dog is not a natural animal. It's a human-made piece of technology. The dog is one of the most impressive things our early ancestors made. Forget Stonehenge – it's a toy by comparison. The dog is a piece of Stone Age technology, developed 35,000 years before Stonehenge, that is still going strong in airports around the world.
#+END_QUOTE

#+BEGIN_QUOTE
不难想象，最初是经历了怎样试探性的接触，我们的祖先才开始不再与狼为敌。也许是在某个寒冷的冬天，一只狼悄悄地靠近火堆取暖，突然，其他猎食者闯入人类的营地，它一跃而起，和人类并肩作战，作为奖励，它得到了一块肉。也许，从那一刻起，在自然选择的作用下，改变就开始了。

It's easy to imagine those first, tentative steps away from the wolf's role as enemy. Perhaps it was a cold winter, and a wolf crept close to a fire to keep warm. Maybe while it was there some other predator attacked the camp – the wolf, ever the pack animal, jumped to the defence of the humans, fighting alongside them. It was rewarded with a gift of meat.
#+END_QUOTE

** 金属探测器

#+BEGIN_QUOTE
金属探测拱门中有好几个线圈。线圈中的电流能使附近金属物体的周围产生磁场，而这个磁场反过来又会使检测线圈中产生感应电流。

In the arch of a metal detector, there will be several coils of wire. The flow of electricity in these generates a magnetic field, which produces electric currents in any metal objects nearby. These currents generate magnetism in their turn, which finally produces electricity in a detection coil.
#+END_QUOTE

** 人体扫描仪

#+BEGIN_QUOTE
人体扫描仪可分为两大类，它们使用的都是不可见光。有些使用高能量（波长短）波，有些则为 X 射线。高能量波扫描仪的波长频率与微波类似，没有证据显示该波会造成健康隐患。人体扫描仪采用的是一种称为反向散射 X 射线的流程。在扫描时，X 射线不会穿透你的身体，它穿透你的衣服却被你的身体反弹回来，到达环绕在你四周的探测器。这些 X 射线的辐射量极其小，相当于人们日常生活中每小时所遭受的辐射的五十分之一。

There are two types of body scanners, both using non-visible forms of light. Some employ high-energy (short-wavelength) radio, while others use a form of X-ray. The radio version uses a frequency that is quite close to microwaves. There's no known evidence of a health risk from these radio signals. Full body scanners use a process called backscatter X-ray. Here, instead of passing through you, the X-rays pass through your clothes but are bounced back from your body to detectors all around you. These are very low-dose X-rays. You will be exposed to around 50 times as much damaging radiation for each hour you are in the air as you will receive from a backscatter scan.
#+END_QUOTE

file:../images/inflight_science/06.jpg

** 生物识别

#+BEGIN_QUOTE
尽管从理论上来看，你身体的任何一个部位都可以用作生物数据辨识（如耳朵的大小），但在实际操作中，多数系统都会涉及面部、指纹和虹膜识别技术中的一项或几项。面部识别是最理想的，因为它可以进行远距离识别，并不需要受检者在监测点停下来按指纹或接受虹膜成像。对于安检来说，它是最实用不过了，每当乘客们停下来与工作人员交谈时，它便开始工作，而乘客们却毫无察觉。

Although in principle any aspect of your body could be used for biometrics (ear size, for instance), in practice most systems use one or more of face recognition, fingerprint recognition and iris recognition. Face recognition is the ideal technology, because it can be undertaken remotely without the individual having to stop at a booth to give a fingerprint or an iris photograph. More practically for security, it can be performed unobtrusively in the background at any point an individual stops to speak to an official.
#+END_QUOTE

** 随机事件

#+BEGIN_QUOTE
_迷信的根源在于人类对于事物偶发性的认知，而我们的大脑结构不擅长处理概率。_ 每天在各处发生的随机事件不计其数，大到传染病的爆发，小到有人跌倒。 _这些随机事件的分布如何？我们本能上以为它们是均匀分布的。_ 试想你将一小罐钢珠打翻在光滑平整的地面上。当钢珠静止时，若发现它们均匀地分布在地面上，彼此之间距离相等时，你会作何感想呢？ 自然状态下钢珠的分布是：某些区域小钢珠分布会密集些，而某些区域则会稀疏些。这样的分布便称之为群聚。 _群聚现象适用于现实世界任何事件的无序分布。_

The science of superstition is very much tied in with our perception of chance. Our brains just aren't wired well to cope with probability. Imagine something that happens randomly across the country, anything from outbreaks of disease to people falling over. How would you expect those random things to be distributed? Our natural response is to expect them to be spread out evenly. Imagine tipping a tin of ball bearings onto a flat, empty floor. What would you think if, when the balls stopped moving, they were evenly distributed in a grid, each the same space from the other? The natural thing is for there to be places where there are clumps of ball bearings and others where there are gaps. These clumps are known as clusters. Exactly the same thing happens with any randomly distributed event.
#+END_QUOTE

file:../images/inflight_science/07.jpg

#+BEGIN_QUOTE
非传染性疾病的群发往往归咎于手机信号发射塔或是核电站（附近很有可能也有酒吧和教堂，但是他们却很少会成为替罪羊）。人们总是倾向于在身边找原因，尤其是当周围有某些引起人们焦虑的因素时，那么，它们则最容易成为替罪羊。得通过有效的统计手段来验证两者的因果关系，才能下定论。

Clusters of non-transmitted illnesses are often blamed on phone masts or nuclear power stations. It's very natural to look for a local cause, and, where there's a source of concern nearby, to assume that it's responsible. There are very effective statistical techniques to check on causality that need to be applied before jumping to conclusions.
#+END_QUOTE

* 第二章

file:../images/inflight_science/08.jpg

** 航空燃料

#+BEGIN_QUOTE
航空燃料是煤油的一种，较之汽车使用的汽油或柴油，航空燃料的分子更大，也更不易挥发。假设我们正在使用高技术含量的电脑电池，将近 1 吨这样的电池才能释放出和 10 千克航空燃料等值的热量。这也是为什么我们在短时间内不会看到有充电飞机。航空燃料极好地压缩了能量，它每千克产生的能量是等量三硝基甲苯（TNT）爆炸时的 15 倍。

Aviation fuel is a form of kerosene (paraffin). Aircraft fuel typically has larger molecules than the petrol or diesel used for cars, and because of this is less volatile. Assuming we're using hi-tech computer batteries, to carry the same amount of energy as 10 kilograms of aviation fuel you need around a tonne of batteries. This is why you aren't going to see electric airliners any time soon. Aviation fuel crams the energy in so well that it has fifteen times the energy per kilogram of the explosive TNT.
#+END_QUOTE

#+BEGIN_QUOTE
氢气本身并不能成为一种能源，因为在你使用它之前，必须得先把它制造出来。不过，氢能提供一种优于石油的能源转换途径，因为当它燃烧时，唯一的排放物只有水蒸气。

Hydrogen isn't an energy source in its own right, because you have to make it before you can use it. But it's an alternative way of transporting energy, which has the advantage over fuel oil that when it burns, the only emission is water vapour.
#+END_QUOTE

#+BEGIN_QUOTE
费—托法能把煤转化成石油，这门技术是第二次世界大战时在德国发展起来的，当时的德军被切断了石油供给

There's a technique called the Fischer-Tropsch process that can convert coal into fuel oil. It was developed by the Germans during the Second World War, when they were cut off from their usual sources of oil.
#+END_QUOTE

#+BEGIN_QUOTE
碳非常容易与其他元素结合，组成长链条的分子。没有碳的这一性质，就没有蛋白质、DNA 和其他复杂的分子，而正是它们让生命的诞生有了可能。

Carbon is very good at combining with other elements to make long chains of molecules. Without that it would be impossible to build the proteins, DNA and other complex molecules that make life possible.
#+END_QUOTE

** 温室效应

#+BEGIN_QUOTE
大部分太阳的辐射都能到达地面，地表在接受了太阳能以后，以红外线的形式再向外辐射，红外线的能量低于来自太阳的可见光，向外辐射的能量一部分会被大气层中的二氧化碳分子吸收。几乎是在同时，二氧化碳分子重新释放出能量。这其中的一部分能量会回到宇宙中去，而剩下的则全部返回地面，使地表温度升高。如果离开了温室效应，地球上的平均气温很可能会跌至零下 18 摄氏度，比当前的实际气温低了 30 多度。

Most incoming sunlight shoots straight through greenhouse gases, but when the energy is re-emitted by the Earth as infra-red, which is lower-energy than the visible light that comes in from the Sun, some of it is absorbed by the CO2 molecules in the atmosphere. Almost immediately the molecules release the energy again. A portion continues into space, but the rest returns to Earth, warming the surface. Without greenhouse effect, the average temperature on the Earth would be -18 degree, over 30 degrees lower than it actually is.
#+END_QUOTE

file:../images/inflight_science/09.jpg

#+BEGIN_QUOTE
地球上的主要热量都来自于太阳，越接近山顶的地方离太阳越近，所以，你也许会想山顶上应该更热才对。的确，山顶上的太阳射线最强，为什么山顶那么冷呢？这一切都是温室效应造成的。

The vast majority of the Earth's heat comes from the Sun, and the higher up a mountain you are, the closer you are to the Sun, so you might expect it to get warmer. There's certainly no doubt that the Sun's rays are strong on top of a mountain. So why is it so chilly up there? It's down to the greenhouse effect.
#+END_QUOTE

#+BEGIN_QUOTE
山脉能增加当地降雨，这些季节性的降雨会与空气中的二氧化碳发生反应。水和二氧化碳形成的酸性物质渗透地底，溶解岩石表面，置换出二氧化碳中的某些物质，形成稳定的碳化合物，但是它们不再回到大气中去。这个过程与全球变暖刚好相反，在它的作用下气温下降了。喜马拉雅山脉的形成引发了一系列使地球改头换面的冰川期。

The intrusion of the mountains increased rainfall in the area, and these monsoon rains reacted with the carbon dioxide in the atmosphere. The acid formed by carbon dioxide and water dissolved the surface of the rock below, forming stable carbonate compounds that locked in the carbon dioxide, preventing it from returning to the atmosphere. In a reverse of our current problem of global warming, the temperatures began to drop. The formation of the Himalayas triggered a series of ice ages that transformed the world.
#+END_QUOTE

#+BEGIN_QUOTE
金星就是一个温室效应泛滥的星球，大气层中二氧化碳的含量高达 97%。在这里，平均气温为 480 摄氏度，最高气温可以升至 600 摄氏度，这使金星成为太阳系中最热的星球。

An example of an out-of-control greenhouse effect is the planet Venus, with a 97 percent carbon dioxide atmosphere. Here average temperatures are 480 degree Celsius, with peaks of 600 degree, making it the hottest planet in the solar system.
#+END_QUOTE

** 碳排放

#+BEGIN_QUOTE
在所有出行工具中，飞机的碳排放量最大。拿一趟从欧洲至美国的长途飞行来说，每位乘客将排放 2.5 吨左右的二氧化碳，这相当于一辆普通汽车行驶 15000 千米所产生的碳排放量。当飞机还没上天之前，靠发动机来推动飞机似乎有些浪费而且效率也不高，尤其是在掉头时。所以，在飞机驶离航站楼时，需要飞机拖车（有时也叫牵引拖车）来帮忙。

Flying is the worst means of transport for carbon dioxide emissions. A typical long-haul flight from Europe to the US will produce around 2.5 tonnes of CO2 per passenger. That's the equivalent of driving around 15,000 kilometres in an average car. Manoeuvring driven by the aircraft engines is not a very efficient way to travel when the plane isn't in the air, particularly in reverse, so to get away from the terminal an aircraft tug (sometimes called a pushback tractor) is usually brought in.
#+END_QUOTE

file:../images/inflight_science/10.jpg

file:../images/inflight_science/11.jpg

** 雷达

#+BEGIN_QUOTE
飞机上也有一个雷达系统，安装在机头内，以预警前方的暴风雨。

Plane itself will have a radar system, built into the nose, that it uses to warn of storms ahead.
#+END_QUOTE

#+BEGIN_QUOTE
第一项能于肉眼之外发现飞机的可操作的技术是由英国人在第二次世界大战前夕研发出来的。雷达最初在英国投入使用时，民间流传起这样的说法，多吃胡萝卜能提高视力，尤其是夜间的视力。其实，这是英国空军策划的一次成功的宣传，到处放出消息说空军飞行员正在接受含有大量胡萝卜的饮食以提高其视力，因而能准确地发现入侵的德军轰炸机。

The first practical technology for spotting planes beyond the limits of visibility was developed in Britain just before the Second World War. The early British work with radar seems to have been the source of the old story that eating carrots improves your eyesight, especially in the dark. This was a piece of surprisingly successful propaganda put out by the Air Ministry during the war, who claimed that fighter pilots were on a diet that was rich in carrots to improve their night-time eyesight so that they could spot incoming German bombers.
#+END_QUOTE

#+BEGIN_QUOTE
雷达既是光源，同时也是接收器，它释放出成束的光子，然后感应由物体反射回来的光子。 _由于能量低于可见光，光子很难描绘出物体的具体特征，通常都只能模糊地显示轮廓，_ 远没有人眼看到的景象那样复杂而详尽。

Radar is both the source and the detector. It emits a stream of photons, then looks out for the re-emitted photons coming back from an object. Because the photons have lower energy than visible light they are less able to detect specific features, so typically just show a blob, rather than the detailed view we get with eyesight.
#+END_QUOTE

** 无线电

#+BEGIN_QUOTE
有些无线电是不需要人工操作的。导航灯塔就是这样的全自动的无线电波发射器，它不断地发射出信号，告知飞机何时转向。VOR，即甚高频全向信标，一架飞机一般会用到两台这样的装置来确认自己的位置。

Some of the radio use is automated. Navigation beacons are unmanned radio transmitters that send out a continuous stream of information to enable planes to know where to turn on flight paths. VOR (VHF Omnidirectional Radio Range), a plane typically uses two of these beacons to get a fix on location.
#+END_QUOTE

#+BEGIN_QUOTE
机场内有些自动无线电发射装置更加精密，能提供 ILS（仪表着陆系统）装置，可以精确定位跑道，提供飞机接近地面时的准确角度。有了 ILS 提供的信息，外加一些特殊雷达装置，一架装备精良的飞机能在可见度为零的情况下自动降落，无需飞行员手动操作，这样的系统被称为自动着陆系统。

A more sophisticated collection of automated radio transmitters at airports provide ILS (Instrument Landing System) facilities, which pinpoint the line of the runway and the angle at which the plane is approaching the ground. By combining ILS information with special radar facilities, a suitably equipped plane can land in zero visibility without the pilot handling the controls, a system known as autoland.
#+END_QUOTE

** TCAS

#+BEGIN_QUOTE
大部分飞机上都装有飞行警报和防撞机系统（TCAS）。TCAS 会向其他也装配了相同系统的飞机发出信号来获得它们的位置。每架飞机都配备了一种叫做发射机应答器的装置，这是一种能发出无线电信号的全自动的信号发射器。因此，当发射器接收到其他飞机的请求时，应答器就自动开始工作，向对方播报自己的位置。这样一来，对方飞机就能知道附近有哪些飞机以及它们的位置了。

Airliners are usually equipped with a traffic alert and collision avoidance system (TCAS). The TCAS equipment sends out requests for information to other aircraft fitted with the same technology. Each aircraft has built into it a device called a transponder. This is a radio-activated automatic radio transmitter. So when it gets a request from another aircraft, the transponder springs into life, broadcasting its location. That way the other aircraft can build up a picture of the positions of any other aircraft around.
#+END_QUOTE

** GPS

#+BEGIN_QUOTE
GPS 利用附近的 24～30 颗卫星来判断地球上任何一个 GPS 接收器所处的位置，这些卫星运行在高度 2 万公里的轨道上。越来越多的卫星被送上天，让系统更加精确，所以卫星的数量一直在增加。 _每颗卫星都携带着一只走时精准的计时器，并且不断地播报时间和卫星轨道的位置。每只接收器通常需要 4～6 颗卫星的信号，以光速为单位，计算信号从卫星到达接收器所需的时间，来确认自己的方位。_

GPS uses the nearest handful from a collection of between 24 and 30 satellites scattered around the globe at an altitude of 20,000 kilometres (12,500 miles) to pinpoint the location of a GPS receiver anywhere on the Earth. More satellites are being added to make the system more accurate, so the number is increasing. Each satellite carries a very accurate clock and constantly broadcasts the time and the satellite's orbital position. The GPS receiver typically latches onto between four and six of these transmissions and uses them to fix its location based on knowledge of how long the signals from the satellite should take to arrive at the speed of light.
#+END_QUOTE

file:../images/inflight_science/12.png

file:../images/inflight_science/13.jpg

file:../images/inflight_science/14.jpg

#+BEGIN_QUOTE
狭义相对论提出，快速走动的钟表会比我们期望的走得慢些，并预测到，和地球上的时钟相比，GPS 卫星上的计时器每天差不多晚点 700 万分之一秒，广义相对论告诉我们，重力也会导致时钟变慢。卫星所承受的重力牵引要比我们在地球表面上的小得多，因此，卫星上的计时器每天将多走 4500 万分之一秒。卫星导航系统正是依靠着极其精准的测量来获得准确定位的。 _如果没有相对论指导纠正偏差，仅仅一天之内，GPS 所提供的方位将可能偏差好几公里。_

Special relativity says that fast-moving clocks will run slower than you would expect them to, and predicts that the clocks on GPS satellites will lose around 7 millionths of a second every day compared with clocks on Earth. General relativity tells us that gravity also has the effect of slowing clocks down. As the satellites experience a weaker gravitational pull than we do on the Earth's surface, their clocks should gain around 45 millionths of a second a day. Satellite navigation is dependent on very accurate measurements to get the position right. In just a day, without correcting for relativity, the position provided by GPS would be wrong by several kilometres.
#+END_QUOTE

** INS

#+BEGIN_QUOTE
决定物体惯性的是它的质量，而不是它的重量。物体的质量是其与生俱来的一种属性，无论处于地球表面，还是月球表面，或是飘浮于宇宙中，它的质量不变。 _物体的质量决定它受力时的加速度。重量代表了引力对物体的影响。_ 在地球上物体的重量等于它的质量。这个现象反映了质量的单位的本质，在地球引力下，重量和质量是等值的，但是度量单位不同。

Inertia depends on an object's mass, rather than its weight. An object's mass is an inherent property of that object, something that will be the same whether you're standing on the surface of the Earth, standing on the surface of the Moon, or floating in space. Mass describes how much force it takes to give that object a certain amount of acceleration. Weight reflects the effect of gravity. An object's mass on Earth is the same as its weight. This reflects the way the units of mass were defined, so they come out the same on Earth, as that's where we tend to weigh things.
#+END_QUOTE

#+BEGIN_QUOTE
惯性制导系统（INS）会通过 GPS 确认飞机当前的位置和速度。然后测出飞机加速和减速，以及角加速度（旋转加速度），这些数据能帮助人们追踪飞机从初始点开始的方位。INS 的优点在于即便在无线电通讯中断，飞机无法和 GPS 或导航信标取得联络的情况下，它也能测量出飞机的运动参数。在通讯中断时，INS 能够不间断地标示出飞机准确的位置。

An INS (Inertial Navigation System) starts by establishing a current position and speed, typically from GPS. It then measures the rate at which the plane is accelerating and decelerating, plus any angular acceleration (turning acceleration), to be able to keep tracking the location of the plane from its initial point. The advantage of doing this is that these measurements can be made even if radio communication is unavailable, leaving the plane isolated from GPS and navigation beacons. The INS will continue to plot the location with considerable accuracy despite any communication problems.
#+END_QUOTE

** 陀螺仪

#+BEGIN_QUOTE
陀螺仪测量角运动参数。陀螺仪转子的转速极其之快，获得巨大的角动量。陀螺仪一旦开始旋转，基于角动量守恒的理论，它能反抗任何改变转子轴向的力量。飞机上的陀螺装置的底座固连在飞机上，转子轴提供惯性空间的给定方向。则当飞机转弯时，仪表就相对转子轴转动，从而能给出转弯的角度和航向的指示。

A gyroscope is used to measuring the amount of acceleration in twists and turns. The disc of gyroscope has a large amount of angular momentum because of spinning extremely quickly, it resists any attempt to change its orientation, because that would change the angular momentum. So when the disc is mounted in gimbals that allow it to swing freely in three dimensions, as you twist and turn the object the gimbals are attached to - an aircraft in our case - the disc will keep in its original orientation as the plane moves around it. By measuring how the orientation of the disc changes, you can monitor the twisting acceleration and keep track of the plane's flight path.
#+END_QUOTE

** 电波干扰

#+BEGIN_QUOTE
比起 40 年前的飞机来说，现在的飞机对敏感的电子设备依赖程度更高。从理论上来说，手机发出的信号，或是笔记本电脑这类设备造成的电波干扰的确会影响到飞机上那些电子设备的正常工作。不过就像加油站禁止使用手机这样的规定一样，并没有充分的案例显示这么做一定会发生危险。

The problem is that modern planes are highly dependent on sensitive electronics, much more so than aircraft of 40 years ago. In principle, the radio signal from a phone, or the radio interference caused by other electronic devices like laptops, could interfere with these electronics, though like the ban on mobile phones in filling stations, there's very little evidence of danger.
#+END_QUOTE

** 空管

#+BEGIN_QUOTE
所有商业性空中交通的交流语言都是英语。即便双方一个是中国的地面操控员，一个是中国的班机。小型飞机是通过其注册编号认定身份的，与之不同的是商业飞机，其用于无线电联络的呼号是由航空公司代号加上飞机编号的数字部分组成的。

All commercial air traffic communication is undertaken in English – even if it involves, for example, a Chinese controller handling a Chinese flight. Unlike light aircraft, which are indentified by the registration number of the plane, a commercial airliner will be referred to on the radio by a combination of a designator for the airline plus the numerical part of the flight number.
#+END_QUOTE

** 跑道

#+BEGIN_QUOTE
一个大型的国际机场跑道的长度有 3～5 千米。大型机场一般会有多条平行的跑道和一些面朝不同方向的二级跑道，以提高机场的吞吐量。这是因为，飞机的起飞和降落都需要逆风进行。在现实情况下，机场跑道不可能顾及各个方位，所以它们的方向通常与当地盛行风的方向一致。

At a major international airport, the runways can be 3 to 5 kilometres long. Big airports often have parallel runways to increase throughput, with additional secondary runways positioned at different angles. This is because aircraft take-offs and landings are best made facing into the wind. Realistically, you can't have runways facing in all directions, so airports typically go for the prevailing wind direction.
#+END_QUOTE

#+BEGIN_QUOTE
每条跑道都以它们的磁方位角的缩写编号（在跑道的尽头你能看见巨大的数字）。如果某条跑道与磁北顺时针方向的夹角为 10 度以内，那它就被编为 01 号。夹角若为 20 度以内则为 02 号跑道，以此类推。由于飞机有可能从跑道任何一端着陆，所以跑道的两端都被编了号，两个数字相减为 18。

The runways are labelled (you'll see a large number painted on the end of the runway) with a contraction of their compass direction. If the direction of the runway is within the first ten degrees to the east of north, it's designated 01. The next ten degrees is 02 and so on. As planes may have to approach the runway from either direction, the two ends of the runway will be labelled with numbers that differ by 18.
#+END_QUOTE

file:../images/inflight_science/15.jpg

** 涡流

#+BEGIN_QUOTE
大部分时候，你都不得不在跑道的起点等上几分钟，让前面的飞机先冲上跑道，这样后面的飞机就能远离它们喷射出的气流，尤其是当前面的飞机比你那架飞机要大的时候。 _飞机翼尖产生的涡流需要 2～3 分钟才能平复。_ 若是有飞机驶入混乱的气流，它将变得难以操控，因此，飞机起飞需要间隔，留出足够的时间让气流恢复稳定。

There's a fair chance that you will have to wait in place for a number of minutes, until the plane ahead has started down the runway, so you don't get hit by its jet blast, particularly if the aircraft in front is bigger than yours. The vortices produced by the wingtips of a plane can take 2 to 3 minutes to subside. If another plane flies into the disrupted air it can become difficult to handle, so the gap between take-offs allows enough time for the air to settle down.
#+END_QUOTE

file:../images/inflight_science/16.jpg

#+BEGIN_QUOTE
水槽或浴缸的面积还太小，不足以影响到水涡的方向。反而其他一些客观因素如排水孔的形状和塞子被拔出时的方法将影响其旋转的方向。这些因素的影响超过了科氏效应。

The size of a sink or bath is so tiny that it has no influence on the direction of the vortex. Instead, this is determined by the way you pull out the plug and other physical factors like the shape of the edge of the plughole. These far outweigh the Coriolis effect.
#+END_QUOTE

** 动力

#+BEGIN_QUOTE
发动机熄火时，你能看见其前部的巨大的风叶，它们吸入并压缩空气。空气将与雾状燃料混合在一起，这些混合物会在燃烧室里被点燃。这将产生巨大的能量，部分能量将输送给涡轮机以保持压缩机叶片持续运转，但绝大多数能量将从引擎后部喷射出去，汇入压缩机叶片吸入的强劲的空气中。由于引擎对空气产生了一个巨大的向后推力，反过来，空气也会以相同的力量将发动机（飞机）推向前。飞机之所以能持续飞行，靠的就是牛顿第三定律。

The big fan you can see at the front of a stopped engine sucks in air and compresses it. The air then gets mixed up with a mist of fuel and the combination is ignited in a combustion chamber. This produces a blast of energy, part of which powers a turbine to keep the compressor blades going, but most of which shoots out of the rear of the engine, joining the powerful flow of air sucked through by the compressor blades. Because the engine gives the air a huge push backwards, in its turn that air gives the engine (and hence the plane) the same amount of thrust forwards. The only thing that keeps the plane moving is Newton's third law.
#+END_QUOTE

#+BEGIN_QUOTE
_牛顿第二定律有一定的局限性，它只适用于那些运动速度比光速慢的物体。运动速度越快，它得出的数据就越不精确。_ 如果要获得绝对的精确，或在物体运动速度极快的情况下，我们需要用相对论来替代牛顿第二定律。

Technically the second law is an approximation that works only when something is moving relatively slowly compared to the speed of light. The faster you go, the less accurate it is. For absolute accuracy, or for really fast things, we need to replace Newton's second law with the predictions of relativity.
#+END_QUOTE

** 起飞

#+BEGIN_QUOTE
飞行员会依次接到指令让飞机加速到 V1，VR 和 V2，这是至关重要的三个空速。对于每一个型号的飞机来说，这三个速度都相对固定。飞机一旦接到 V1 的指令，就意味着它必须起飞，V1 被称为决断速度。VR 中的 R 代表 rotation，当飞机达到这个速度时，飞行员会接到 Rotate（抬轮）的指令。飞行员向后轻拉操纵杆，变换水平尾翼舵面的角度，让机头抬头离地。这样的倾斜能使空气与机翼之间形成更小的角度，使飞机获得更多升力。此时，飞机虽然还没有完全离开地面，却一直处于加速中，当加速到 V2（起飞速度）时，它就成功起飞了。

As the plane accelerates, the pilot will be told as the plane passes 3 critical air speeds, known as V1, VR and V2. Each of these speeds is fixed for a particular aircraft. V1 is, in effect, the speed of no return. When the first officer calls out "V1" the plane is committed to take-off. The "R" in VR stands for "rotation", and at this point the first officer calls out "Rotate". The pilot pulls back gently on the control stick, changing the angle of the tailplane control surface so that the aircraft rotates on its main undercarriage, lifting the nose wheel off the ground. This tilt means that the air is hitting the wings at a sharper angle, giving more lift. The plane is still accelerating on the ground until V2 is reached, the take-off speed.
#+END_QUOTE

file:../images/inflight_science/17.png

** 气压

#+BEGIN_QUOTE
机舱中的压力低于标准大气压，由此产生耳朵不适的症状。一架民用飞机的巡航高度为 35000～40000 英尺（约为 5 英里或 11 千米）。之所以选择在这个高度上飞行，一方面是为了省油，因为这个高度上的空气阻力较小；另一方面是为了避开影响飞行安全的气流。在这个高度上，气压极低，使人无法呼吸，这里的氧气量只有地面上的 1/4，所以，此时机舱内需要加压。

This ear popping is caused by the air pressure in the cabin of the aircraft reducing to a level below standard atmospheric pressure. A commercial airliner cruises at between 35,000 and 40,000 feet (around 7 miles or 11 kilometres). This is partly to save on fuel because of the reduced air resistance, and partly to be well above most of the weather systems that can make a flight uncomfortable. At that level, the air pressure outside is too low to be breathable, with around a quarter as much oxygen as you'd get on the ground, so the cabin is pressurized.
#+END_QUOTE

file:../images/inflight_science/18.png

#+BEGIN_QUOTE
从理论上来讲，人们可以将机舱中的压力调整至与海平面气压一致，但是 _随着压力增大，飞机的重量也会随之增加，以确保机舱处于密封状态，因此需要在两者间找到一种平衡。人们认为海平面上 6000～8000 英尺的气压是机舱内最合适的气压，这个高度类似于墨西哥城的海拔，它是地球上海拔最高的城市。6000 英尺处的气压相当于海平面气压的 80%，这意味着你只能获得平时 4/5 的氧气量。而 8000 英尺高空的气压只有平时的 3/4。_

In principle the cabin could have the same pressure as you would have at sea level, but the greater the pressure, the heavier the plane has to be to stay airtight. There's a trade-off. It was arbitrarily decided that a reasonable cabin pressure was the equivalent of being at between 6,000 and 8,000 feet above sea level, reflecting the altitude of the highest cities on Earth like Mexico City. The pressure at 6,000 feet is around 80 percent that at sea level, meaning you get around four fifths as much oxygen as usual. At 8,000 feet you're down to around 75 percent normal pressure.
#+END_QUOTE

file:../images/inflight_science/19.png

#+BEGIN_QUOTE
飞机上的门并不需要锁住。飞机一旦起飞，机舱内外就会产生不同的气压，机舱内的气压将会升高，而机舱外的气压则急剧下降。强行打开舱门则意味着要与大气压对抗，而这绝不是人力能够胜任的。

In practice the doors on a plane don't need to be locked. Once the plane has taken off, a significant pressure difference soon builds up between the inside of the plane and the outside, as the cabin pressure becomes higher than the rapidly falling outside pressure. To open it you would have to pull against the air pressure, well beyond the capabilities of human muscles.
#+END_QUOTE

#+BEGIN_QUOTE
伴随着周围气压的减小，你体内无论什么气体都会膨胀。耳朵不适症源自咽鼓管内空气膨胀。咽鼓管连接着你的鼻子和嘴，压力改变导致咽鼓管内空气膨胀，耳膜充血，造成耳朵不适。一些物理效应也会影响食物的口感。机舱中的低气压、干燥的空气和食物反复加热都能削减食物的美味，机舱内的噪音也是原因之一。

There are physical effects that can reduce the tastiness of the food. There could be some impact from low cabin pressure, the very dry air on board and the way meals are reheated, and the level of background noise.
#+END_QUOTE

#+BEGIN_QUOTE
机舱中的气压相当于海拔 8000 英尺之上的气压。在这样的气压下，水的沸点在 90 摄氏度左右，你在飞机上喝到最热的茶水差不多也就是这个温度。

At the pressure of an aircraft cabin, the equivalent of being up to 8,000 feet above sea level, water boils at around 90°C, and that's as hot as your tea is going to get.
#+END_QUOTE

** 落体

#+BEGIN_QUOTE
试想你站在地面上，一只手拿着一颗子弹，另一只手拿着枪，枪里也装着一颗一模一样的子弹。松手让子弹下坠，与此同时，扳动手枪，枪里的子弹水平射出去。哪颗子弹会先落地呢？我们本能的反应是手中的子弹先掉在地上，但事实上，两颗子弹会同时坠地，而且它们落地的速度也是一样的。

Imagine for a moment that you're on the ground with a gun in your hand, while holding in the other hand an identical bullet to the one that's in the gun. You simultaneously drop the bullet from your hand and fire the gun horizontally. Which of the two bullets hits the ground first? The natural inclination is to say that it will be the bullet in your hand, but in fact both bullets will hit the ground at the same time. The bullet shot from the gun falls at exactly the same speed as the stationary bullet.
#+END_QUOTE

** 升力

#+BEGIN_QUOTE
你也许听过这样的说法，机翼的形状很特别，空气从机翼上方通过的距离要大于从下方通过的距离。按照这个假设，为了追赶上下方的空气分子，上方的空气分子会加快运动速度，这样两者才能同时在机翼前端汇合，这样一来，机翼上方的空气就变稀薄了。由于空气变少，它在机翼上方产生的压力就会减少。这意味着，机翼获得了向上的升力。没有理由说，机翼上方的空气分子就一定要追赶上下方的空气分子。而事实是，通过机翼上方空气的速度远远超出了那个需要追赶的速度，导致该现象的原因也和机翼上下两面的长度没有任何关系。真正的原因是流体（空气）复杂的运动方式。

You may have heard that wings have a special shape whereby the length of the journey that the air travels over the top of the wing is greater than the distance along the bottom. As the air has further to go along the top, the argument goes, these air molecules will travel faster to keep up with the air going around the bottom, which thins out the air across the top of the wing. And with less air at any particular point, the pressure on the top surface drops. That means the wing should feel a force upwards. There's no particular reason why air going over the top would try to catch up with air going around the bottom. As it happens, the speed that air goes over the top of a typical wing shape is much faster than the speed necessary to catch up with air going around the bottom. This effect is completely unrelated to the different distances along the top and bottom of the aerofoil. Instead it's down to the complex way a fluid like air moves. 
#+END_QUOTE

#+BEGIN_QUOTE
_加速度指的是速度而非速率的改变。两者的区别在于速度涵盖了速率和方向，速度是一个矢量。_ 所有发生了改变的速度都可以被当做加速度，哪怕它只改变了方向，而速率不变。当某物体以相同的速率转圈时，它就处于加速状态中，而加速度的产生必须以力的存在为前提。

Acceleration is actually a change in velocity, not a change in speed. The difference between speed and velocity is that velocity has both speed and direction. It's what's known as a vector. Any change in velocity is an acceleration, even if the speed stays the same and only the direction has altered. When something is going around in a circle at a constant speed, it is accelerating, and that acceleration needs a force to make it happen.
#+END_QUOTE

#+BEGIN_QUOTE
机翼的形状被称为翼面，它们能劈开空气，改变气流的方向。由于机翼施力于空气，它们也受到了空气的反作用力。 _弯曲的机翼表面使空气方向发生改变。这意味着空气被加速了，而当它沿着弯曲向下运动时，加速度的方向向下。机翼给空气施了一个向下的力，而机翼则受到空气向上的相等的反作用力。_

The shape of the wing, called an aerofoil or airfoil, cuts through the atmosphere and turns the flow of air in a different direction. As the aerofoil applies a force to the air, the wing is pushed in the opposite direction. The air flowing around the wing. It changes direction because it's passing over the curved upper surface. This means the air is accelerating, and as it curves down over the wing, that acceleration is downwards. A force is being applied downwards on the air by the wing, and the air exerts an equal and opposite force up on the wing.
#+END_QUOTE

#+BEGIN_QUOTE
当飞机在空中飞行时，它会受到五个力的影响：
重力：给飞机一个向下的力。
升力：向上托住机翼。
推力：在发动机的作用下推动飞机向前运动。
阻力：由于空气阻挡，向后拖住飞机的力，它的方向与推力和上升力相反。
湍流：当飞机遭遇不同气流时，受到各个方向来自气流的力。

When a plane is in the air, it's subject to five main forces:
Gravity: pulling the whole plane downwards
Lift: pushing up on the wings
Thrust: pushing the plane forwards in response to the engines
Drag: due to air resistance, pulling the plane back against the thrust and the lift
Turbulence: pushing in all sorts of directions as the plane is exposed to various air currents
#+END_QUOTE

file:../images/inflight_science/21.png

#+BEGIN_QUOTE
将第一张纸片直接扔出去。把第二张纸捏成纸球后再扔出。用第三张纸折一架纸飞机，然后再扔。它们受到的重力和推力几乎都是一样的。造成三者飞行距离远近的只有上升力和阻力了。第一张展开的纸片受到的阻力最大，因为它与空气接触的面积最大。相比较而言，第二张被揉成纸团的纸受到的阻力就会小些，展开的纸片和纸团受到的上升力都较小，但是一架制作得当的纸飞机却能获得更多的上升力，因此，它能比前面两张纸飞得更远。

Throw the first sheet unfolded. Throw the second scrumpled up into a ball. And throw the third after you have folded it into a paper airplane. The gravitational force on the paper and the thrust should be roughly the same in each case. What changes between the three sheets is lift and drag. The first, open sheet has maximum drag because it exposes a lot of surface area to the air. The second, scrumpled up sheet has less drag. Both open sheet and scrumpled ball will have a little lift, but a properly constructed paper plane should have a lot more lift, enabling it to fly further than either of the other sheets.
#+END_QUOTE

** 机翼

#+BEGIN_QUOTE
副翼，它是安装在机翼翼梢后缘外侧的一小块可动翼面；方向舵是垂直尾翼中可操纵的翼面部分；最后是升降舵，它是水平尾翼中可操纵的翼面部分。飞机副翼是负责飞机在空中方向的装置，它们控制飞机的左右偏转。升降舵摆动的方向则与飞机方向一致，它们控制飞机在空中的俯仰运动。

The ailerons, which are long strips along the outer trailing edge of the wings, the rudder on the vertical tailfin, and the elevators on the horizontal tailplane. Ailerons are used to bank the plane to left and right, providing the main turning mechanism in the air. The elevators both go the same way, tilting the aircraft up or down in the air.
#+END_QUOTE

file:../images/inflight_science/20.png

#+BEGIN_QUOTE
机翼后缘有一些可以伸缩的平面，飞机起飞后它们就会收起，而在降落前，它们又会向外延展。它们被称为襟翼。襟翼有双重作用：它们能够增加机翼面积，从而获得更多向上的推力。这样做能保证飞机在低速时也能平稳飞行，襟翼将增加飞机的阻力。这是一种向后的力，它会影响飞机的飞行速度。飞机一旦起飞，襟翼就会收起以减小阻力。

Extensions on the inner trailing edge of the wing retract soon after take-off – and you will certainly see them extend before landing. These are flaps. Flaps have a dual effect on the wing. By increasing the area of the wing, they push up the amount of upward thrust. This means that the plane can fly stably at a lower speed. The flaps also increase drag. This is a backwards force that slows the plane down. If the flaps were used in take-off they will soon be withdrawn to minimize drag.
#+END_QUOTE

#+BEGIN_QUOTE
在飞行中，大型飞机翼尖的摆动幅度能达到 2～3 米，虽然这看起来很吓人，但是和机翼的韧度比起来，这算不了什么。 _在波音 787 飞行前的测试中，它的机翼被弯曲了 8 米仍完好无损。如果机翼是僵直的，机翼和机身的连接处将承受无法负担的重荷。_

The tips of a large airliner's wing can move 2 to 3 metres in flight, which looks extreme, but is relatively minor compared with their tolerance for bending. When the Boeing 787 was undergoing tests before flight, the wings were flexed by a remarkable 8 metres without failure. If a wing were totally rigid, it would put intolerable stresses on the junction between the wing and the fuselage.
#+END_QUOTE

#+BEGIN_QUOTE
翼尖产生的涡流容易在空气中形成破坏性的漩涡，翼梢处的小翼能够截断漩涡，减小涡流的危害，降低阻力。

The tips of the wings tend to produce turbulence in the form of disruptive vortices of air. Putting winglets on the wingtips slices through these vortices and reduces the effect, cutting down on drag.
#+END_QUOTE

* 第三章
** 怀疑论

#+BEGIN_QUOTE
还有许多人坚持认为这些麦圈就是外星人的杰作。原则上这也不是不可能，正如原则上，街道尽头的超市也有可能是外星人造的一样，因为你从未看见是谁建造。

A number of believers cling on to the possibility that some crop circles have extraterrestrial origins. In principle this could be true, just as, in principle, the supermarket at the end of the street could have been built by aliens if you never saw it being built by people.
#+END_QUOTE

** 宏伟建筑

#+BEGIN_QUOTE
当某物被赋予了精神意义时，人们趋向于把它们修建得宏大雄伟。很难想象，居住在简陋房子里的中世纪欧洲人，会有能力建造出这样雄伟的建筑。然而，大教堂就是刻意被建设成超越人类尺度的建筑，它的建设者们认为这样才能与上帝的伟大相称。

It is a natural tendency to use a large scale when undertaking something of a spiritual significance. It would be easy to think that the primitive medieval Europeans with their tiny shacks would have been incapable of putting together such a massive structure. But the cathedral was built with the specific intention of constructing something outside of human scale, something its builders thought would be fit for God.
#+END_QUOTE

** 年龄测定

#+BEGIN_QUOTE
光释光测年法，它通过研究矿物因自然辐射而发生改变的结构来进行年龄测定。这些结构的改变有序而稳步，因此，当物质被埋藏起来时，它们的结构改变像计时器一样记录着埋藏时间。不过，一旦这些矿石暴露在光线之下，「计时器」就不再精准了。

Optical stimulated luminescence dating, which relies on the way mineral structures are modified by the impact of natural radiation. These modifications tend to occur in a steady fashion, providing a kind of clock when something is buried. But the "clock" is reset when the minerals are exposed to light.
#+END_QUOTE

** 估测距离

#+BEGIN_QUOTE
握住某物伸至一臂之远，如果你知道臂长和物体的高度，我们可以使之与远处的物体进行对比。如果你知道这个物体的大致高度，那我们就可以估测出它与我们的距离。

If I know how far away something held at arm's length is, and how big that object is, I can compare it with a distant object. If I know roughly how big that distant object is, I can estimate the distance to it.
#+END_QUOTE

file:../images/inflight_science/22.jpg

** 遗迹

#+BEGIN_QUOTE
某片区域被一个文明所抛弃，或许是由于附近矿产资源枯竭，或是土地荒废，而相应的工作机会也随之消失。

A culture abandons an area could be that a source of work dries up when a nearby mine is exhausted, or the land is no longer workable. 
#+END_QUOTE

#+BEGIN_QUOTE
通过一些合适的工具就能侦测出这些隐匿的历史考古遗址。通常，地基中建筑材料与周围土壤的密度不同，它们的含水量也不同。还有一种更简便的方法来发现遗址，那就是使用低空飞行的飞行器。若土层之下埋有一段残墙，其上植被的生长将受到抑制而显得稀疏，不如周围的植被那样繁茂。若土层掩盖的是一段沟渠，其上的植被则更高壮而丰茂。这样的差别在地面上是不容易被注意到的。不过，当光线以较小角度射入时，长得高的植物将在地面投射下更为浓重的阴影。从空中看，这些阴影连同繁茂和稀疏植被之间微妙的色差将遗址大致的轮廓勾勒了出来。在一片开阔的田野中，这座隐藏的建筑地基会以阴影的形式展露出来。许多考古遗址就是这样被完整地发现的。

It's possible to detect such hidden historical and archaeological sites using appropriate instruments. The building materials in the foundations will usually have a different density to the surrounding soil, contain different levels of water. There's a much simpler way to spot old sites that you may be able to use while flying relatively low in an aircraft. Where there's a solid wall just under the soil, the roots of the plants will be limited and growth will be a little stunted compared with the nearby ground. Where there are ditches, the plants will be a little taller and fuller than usual. This variation isn't noticeable from the ground. But when the light is coming in at a shallow angle, the taller plants will cast a visible shadow. From the air, this and slight differences in coloration between the stunted plants and the normal ones can make an outline of the building stand out. In an open field, the floorplan of a hidden building can be revealed in shadow form. Whole archaeological sites have been discovered this way.
#+END_QUOTE

** 分形

#+BEGIN_QUOTE
年轻溪流的形成过程给我们展示了两种十分有趣的科学现象：自主成形体系和分形。蜡和热水构成的这种自主成形体系十分有趣，因为最开始并没有固定的模式。液体毫无次序地流经表层，随着表层细微的起伏而波动。当液体流动起来时，它开始侵蚀表层。一旦形成了一道浅浅的沟渠，更多的水就会涌向这道浅沟，使之不断被拓宽。

There are two fascinating bits of science visible in the formation of these young streams: self-patterning systems and fractals. Self-patterning systems, like those formed by hot water on wax, are fascinating because initially there was no particular pattern. The fluid runs chaotically across the surface, influenced by tiny fluctuations in levels. As the fluid flows it starts to eat away at the surface. As soon as a shallow channel has formed, more of the water will tend to flow down that path, reinforcing the initial pattern.
#+END_QUOTE

#+BEGIN_QUOTE
数学意义上的混沌说的是事物开始时的状态对其今后发展的影响。初始时十分微小的变化对其未来状态会造成极其巨大的差别。

"Chaos" here is used in the mathematical sense. Mathematically chaotic systems are highly dependent on how you start things off. A small initial change can make a big difference in the way the system develops.
#+END_QUOTE

#+BEGIN_QUOTE
分形是混沌几何形态的一种，它强调的是「自我相似」。如果你将某个形状看成是一个整体，取出整体中任意的一个片段，然后将其放大至与整体大小相同，会发现该片段有着与整体十分类似的结构。树是一种分形，而在孕育过程中树状结构的年轻溪流也是一种分形。

Fractals are chaotic geometrical patterns that are "self-similar". If you look at the pattern as a whole, then take a fraction of the pattern and blow it up to the same size, that fraction has a very similar structure to the whole. Trees are like this, and so are those tree-like first structures of streams.
#+END_QUOTE

file:../images/inflight_science/23.jpg

** 河流

#+BEGIN_QUOTE
假设是一个固体物质绕过弯道，该物体所有部分都组合在一起不能分离，你大概会认识到，比起该物体的外侧来，其内侧通过的速度会慢些，因为在同样的时间内，内侧需要运动的距离比外侧要来得短。这也是汽车轮胎需要安装差速器的原因，因为汽车在转向过程中车体内侧的轮胎比外侧要转得慢。

If you imagine a solid object sweeping around a bend, where everything is fixed together, you would expect the inner parts to be slower, because they have less far to go in the same amount of time. This is why car wheels have to have a differential so the inner wheel on a bend can go slower than the outer wheel.
#+END_QUOTE

#+BEGIN_QUOTE
_和固态物体运动时齐头并进的状态不同，水流的各部分在运动时并不是同步的。河岸内侧的水流加速是为了保持角动量守恒。_ 角动量是由与物体到原点的位移和其速度决定的。在不受外力作用下，角动量是守恒的。当溜冰者将手臂收回时，半径减小了，因此，旋转的速度就会增加以保持角动量不变。

Different parts of the stream don't have to move together, as they do in a solid object. The faster movement on the inner bank is down to the conservation of angular momentum. Angular momentum depends on the distance a mass is from the centre of spin and the velocity with which it's moving. Such angular momentum is conserved, it stays the same unless you apply a force. When the skater's arms come in, the radius is reduced, so the velocity needs to increase to keep the angular momentum the same.
#+END_QUOTE

#+BEGIN_QUOTE
由于地表凹凸不平，当溪流形成时，它们不会笔直地朝一个方向流去。当水流流经半径较小的左边的内侧河道时，其流动的速度会加快以保持角动量守恒。这样一来， _外侧河岸所受的压力将略高于内侧河岸。不同的压力造成了河水从河岸外侧至内侧的二次流动，并从外侧河岸带来沉积物。因此，泥沙从弯道的外侧被冲刷到了内侧，这使得河道愈来愈弯曲。_ 最后河水流成了一条潦草的正弦曲线。

Because of variances in the lie of the land, when a stream forms it's unlikely to be dead straight. When the water is going around the smaller radius of the inner bank, it will speed up to preserve angular momentum. One of the results of this is a slightly higher water pressure on the outer bank than on the inner. This difference in pressure causes a secondary flow to occur, from the outer bank towards the inner, pulling with it material from the outer bank. So soil moves from the outer bank of the curve to the inner bank. This makes the curvature of the bend greater. The result is a meandering route.
#+END_QUOTE

file:../images/inflight_science/24.gif

#+BEGIN_QUOTE
最终，其中的一个河曲越来越弯，形成了一个环形，河流遂截弯取直，由较笔直的新河道流走，留下一个与主河道平行的独立的半月形湖，湖形似于牛轭，称为牛轭湖。

Eventually one of these bends can get so sharp that it forms a loop, pinching off a section of the stream that is left isolated as a separate little bend, paralleling the main stream. These are known as oxbow lakes, separate curved stretches of water that run alongside a meander in a stream or river.
#+END_QUOTE

file:../images/inflight_science/25.jpg

** 城镇

#+BEGIN_QUOTE
地球上已经少有不受人类影响、百分之百天然的景致了，一旦有人类在附近定居下来，它们就会被开发利用，欧洲的发展过程就是一个最好的例子。即便是看起来充满自然气息的乡村，也是因放牧和其他一些农业活动的影响才变成了现在的样子。

Little landscape is totally natural, without any human influence. anywhere near human habitation – and that means pretty well all of Europe, for example – will have a human hand in its development. Even apparently natural countryside, for instance, is kept the way it is by grazing or other agricultural intervention.
#+END_QUOTE

#+BEGIN_QUOTE
历史悠久的城镇是由一些交错的小巷演变而来的，它们的排列遵循了自然界中物质生发的形态，呈现出发枝树木或树状溪流的样子。通常，人类依山傍水而居，江河提供了水源和沟通的媒介，而山脉则保障了安全，因此溪流江河或山脉的形态决定了一处人类定居点的雏形。

Like a branching tree or a dendritic stream, early towns emerged from a collection of lanes that followed natural formations. Often a stream or river, giving communication and water supplies, or the strategic safety of a hill, would be fundamental to the shaping of the settlement.
#+END_QUOTE

** 海岸线

#+BEGIN_QUOTE
所采用的量度越精密，海岸线显露出的细节就越多，而海岸线长度也将趋于无穷。理论上来说，至少是在数学上，海岸线可以是无限长的。科赫曲线包围着有限的面积，它永远都在圆圈里面，但是，随着三角形的层层增加，科赫曲线的周长却不断变大直至无穷。

As you measure to more and more detail, so the length can be increased indefinitely. In principle, mathematically at least, the coastline could end up being infinitely long. Koch curve covers a finite area, it will never come out of the circle, but the distance around the edge of the Koch curve can carry on growing as you continue to add triangles until it's infinite in length.
#+END_QUOTE

file:../images/inflight_science/26.png

#+BEGIN_QUOTE
与科赫曲线相比，英国的海岸线还是有些不同的。尽管在测量岛屿周长时，随着测量单位变得无穷小，你能计入的迂回弯曲也越来越多，但是这毕竟是一个由原子组成的有形的物体。当最终达到以原子量级的尺度为单位时，测量就无法再进行下去了。由原子组成的有形的物体。当最终达到以原子量级的尺度为单位时，测量就无法再进行下去了。

Koch curve is a bit different with the coastline of Britain. Although in principle you can keep adding more and more crinkles into your measurement of the perimeter, this is a physical object made up of atoms. Eventually, your crinkles would get down to the scale of atoms and you wouldn't be able to take it any further.
#+END_QUOTE

#+BEGIN_QUOTE
通常，我们总是习惯地认为科学能给我们一个明确的答案，不过就海岸线问题而言，在某一范围内一系列的答案都是正确的，完全取决于你是怎么测量的。

We're used to science coming up with very specific answers, but this is a situation where a whole range of answers is equally correct, depending on what you want to do with them.
#+END_QUOTE

** 海水

#+BEGIN_QUOTE
海水本身并不含盐，它的成分包括钠离子和氯离子，海水中的钠离子来自于如硅酸钠之类的岩石和碳酸钠。河流入海的旅途中，沿途的碳酸钠溶解于河水中，被带入海洋。海水拍打岸边那些含钠的礁石，也会将钠带入海洋。海水中的氯离子大多来自海底火山和排气孔洞，它们向海水中喷射大量的化学物质。

Sea water doesn't contain salt. What it actually contains are sodium ions and chlorine ions. The sodium ions in the sea have got there as a result of rock material like sodium silicate and sodium carbonate dissolving on a river's journey to the sea, or as sea water passes over and smashes into appropriate rocks. The chlorine ions in the sea have mostly come from underwater volcanoes and vents, which churn out vast quantities of chemicals into the sea.
#+END_QUOTE

#+BEGIN_QUOTE
_在普通的海水中，氯离子和钠离子漂散在水中，它们既不和海水中的其他离子发生反应，相互之间也不结合。但是，海水蒸发时，离子的密度变大，带正电的钠离子吸引带负电的氯离子，两者结合在一起，形成晶状的氯化钠，_ 通常我们称之为盐。

In ordinary sea water, the two sets of ions, sodium and chlorine, are floating around, no more associated with each other than any of the many other ions the sea contains. But if you evaporate sea water, the concentration of the ions increases, the positive sodium is attracted to the negative chlorine and the two join together, forming crystals of sodium chloride or common salt.
#+END_QUOTE

#+BEGIN_QUOTE
_当光线射入水面时，其中的红光更容易被水分子吸收，这样一来，反射回我们眼中的光线就带上了一种蓝色调。_ 大海也会反射天空的颜色。另外，水中的漂浮物也会影响海水的颜色。和水一样，冰能吸收更多红光，于是，任何光线穿过冰后都带上了蓝蓝的色调。

Water molecules are better at absorbing red light energy than the other colours of the spectrum, leaving a blue tint to the remaining light that passes through any water. The sea can also pick up coloration from the sky. And then there's the material floating in the water. Just like water, ice absorbs rather more red light than the other colours, leaving any light that gets through it with a blue tinge.
#+END_QUOTE

** 水资源

#+BEGIN_QUOTE
地球上的水有 1,400,000,000 立方千米之多。将地球上的水按人头来算，我们每人分到的水量是 0.2 立方千米。虽然地球上水资源丰富，但是大部分的水很难为人类所用。有些水被冻结在冰川中或是蕴藏在地底，但是，到目前为止，大部分（占地球总储水量 97% ）的水都在海洋里。

In round figures there are 1.4 billion cubic kilometres of water on the Earth. Divide the amount of water in the world by the number of people and we end up with 0.2 cubic kilometres of water each.
#+END_QUOTE

#+BEGIN_QUOTE
一个普通的西方国家的居民每天会用 5000 至 10000 公升的水。不过现有最耗水的还是加工人类日常消费的商品和食物，它远远超过个人用水量。

The typical Western consumer uses between 5,000 and 10,000 litres (a day). ... but by far the biggest part of our consumption, vastly outweighing personal use, is the water taken up by manufacturing the goods and food that we consume.
#+END_QUOTE

file:../images/inflight_science/27.jpg

file:../images/inflight_science/28.png

file:../images/inflight_science/29.jpg

file:../images/inflight_science/30.png

#+BEGIN_QUOTE
像英国这样的岛国宁愿花巨资修建水库收集淡水，却不用唾手可得、取之不尽的海水，这说明将海水转化为可饮用的淡水的海水淡化过程是多么昂贵。水资源短缺实际上就是能源短缺。如果有足够的廉价能源，我们就能将大量的水运送到适当的地方，用最少的成本将海水淡化。

An island nation like Britain is prepared to spend huge amounts of money on reservoirs to collect a relatively tiny amount of fresh water, rather than use the vast quantities of sea that surround it, emphasizes how expensive is the desalination process required to turn sea water into drinkable fresh water. Water shortages are actually power shortages. If we had enough really cheap power we could transport as much water as we liked to the right place, and remove impurities like salt with little effort.
#+END_QUOTE

** 潮汐

#+BEGIN_QUOTE
地球上面向月球的海水暴涨，朝天空中月亮的方向掀起高涌的潮头。而地球的另一侧，由于离月亮较远，海水受到月球的引力相对微弱，产生离心的趋势，因此在背向月球的海面也形成隆起的潮头。这些潮汐追随着天空中月亮的位置，横扫整个地球表面。

The sea water on the Moon-facing side of the Earth bulges up skyward. As the gravitational pull of the Moon on the far side of the Earth is weaker, the water is less attracted in the Moon's direction, and bulges out away from it. The result is that two high tides are in progress at any one time, one on the side of our planet facing the Moon, the other on the side furthest away from it. These tides sweep around the Earth, following the position of the Moon in the sky.
#+END_QUOTE

file:../images/inflight_science/31.jpg

file:../images/inflight_science/32.gif

#+BEGIN_QUOTE
观察一下海浪，你会觉得它们一直在向前涌去，其实这是一种错觉。大部分海水都还待在原来的位置。

If you watch waves, it looks like water is travelling along, but this is misleading. The shape moves constantly onward, but the bulk of the water doesn't.
#+END_QUOTE

** 海底山脉

#+BEGIN_QUOTE
世界上最长的山脉是大洋中脊，这条在水下绵延超过 55000 千米的山脉，比地球的周长还要长（它不是一条直线，而是由一系列海底山脉组成的）。

The longest mountain range in the world is the Mid-ocean Ridge, a continuous chain of mountains under the water running for over 55,000 kilometres, more than the distance around the Earth (the chain is anything but a straight line).
#+END_QUOTE

file:../images/inflight_science/33.jpg

** 垃圾带

#+BEGIN_QUOTE
太平洋中漂浮着全世界最大的垃圾场。在海水水流的作用下，漂浮的垃圾聚集起来，漂浮在夏威夷群岛不远的两侧海域，它们被称为西太平洋垃圾带和东太平洋垃圾带。漂浮在垃圾场中的物体，预计总重量在 1000 万吨之上，它们聚集在一起，形成了比德克萨斯州还要大的垃圾区。

The biggest rubbish tip in the world is in the Pacific Ocean. Sea currents pull in floating debris to areas either side of Hawaii known as the Western Pacific Garbage Patch and the Eastern Pacific Garbage Patch. Between them, these floating accumulations of debris contain a vast amount of material, estimated at well over 10 million tonnes and covering an area greater than Texas.
#+END_QUOTE

file:../images/inflight_science/34.png

* 第四章
** 水蒸气

#+BEGIN_QUOTE
水蒸气是看不见的气体，是气态的水，我们看见的那些所谓的蒸气是水蒸气凝结后重新变为液态的水，它们在空气中结成细小的水珠。温度变化会产生水珠，不过普遍来说，水珠的萌生离不开空气中那些飘浮的小颗粒，诸如沙粒、烟尘或是花粉，甚至细菌。

Water vapour is an invisible gas, the gaseous form of water. What we see as steam is water vapour that has condensed back to a liquid, forming tiny droplets in the air. These droplets can form due to a temperature change, but are often seeded by floating particles like grains of dust, smoke or pollen. This even happens with bacteria.
#+END_QUOTE

#+BEGIN_QUOTE
水分子一刻不停地向空气中吐射水蒸气。同时，空气中的水分子会重新落回海洋。在任何情况下，水气蒸发和其凝结保持一种相应的平衡。

Water molecules are shooting off as vapour all the time. At the same time, water molecules in the air drop back into the ocean. In any particular set of conditions there will be an equilibrium between water evaporating into vapour and condensing back into liquid.
#+END_QUOTE

** 温度

#+BEGIN_QUOTE
温度是以物质中分子运动的速度来测定的。温度越高，分子运动的速度就越快。不过，温度是一个统计学问题。这并不意味着在某一温度下，任何一个分子都以特定速度运动，而是就平均来说，分子的运动速度会与对应的温度相匹配。

Temperature is a measure of the speed of the molecules in a substance. The faster the molecules move, the higher the temperature. But temperature is a matter of statistics. It doesn't tell us that every molecule is moving at the speed you'd expect for this temperature, but rather that on average their speed will be the one that corresponds to this temperature.
#+END_QUOTE

#+BEGIN_QUOTE
在对流层，大致每升高 1000 米，温度就会下降 5~6 摄氏度。30000 英尺（约 9000 米）通常在这个高度上，气温就停止下降了，在这儿，气温发生逆转，这样的逆转也是高空急流的成因。

Roughly speaking, the temperature drops between 5 and 6°C for each 1,000 metres you climb. At 30,000 feet (around 9,000 metres), the drop in temperature often ceases around this height, where you get the inversion in temperatures that holds the jet stream in place.
#+END_QUOTE

file:../images/inflight_science/19.png

** 云

#+BEGIN_QUOTE
云的确在下沉。云朵没有什么神奇法力，它们如万物一样逃脱不了地球重力的束缚。只不过 _云下落的速度非常缓慢，这是因为组成云朵的水珠的直径大概只有一亿分之一米。物体越小，受到空气的阻力就越大。就云彩中的一粒小水珠来说，空气和它的关系就好比黏稠糖浆和其中的小滚珠。小水珠下降一米得花上一年时间。_

Clouds do sink. There's nothing magic about them, they have to respond to gravity like everything else. But they sink very slowly. It's because the droplets of water are as little as 1/100,000,000th of a metre across. The smaller the object, the more influence air resistance will have. To a droplet of water in a cloud, the air is like very thick treacle is to a small ball bearing. It would take one of our tiny droplets over a year just to drop one metre.
#+END_QUOTE

#+BEGIN_QUOTE
电视上的宇宙画面时，它们看上去都是黑漆漆的。只是，当你关掉电视时，屏幕的颜色是深灰色的，而节目里播放的太空的颜色怎么可能比屏幕的颜色还要深呢？这是你的大脑在捣鬼，它误导你屏幕是黑色的。

Space on your TV looks black, but your screen can't get blacker than it is when the TV is switched off, and that's dark grey. Your brain fools you into thinking the screen is black.
#+END_QUOTE

#+BEGIN_QUOTE
云层中，当许多小水滴开始聚集在一起形成更大的水珠时，云朵就开始变暗了。这意味着更少的光线被云层表面反射，有些甚至被云层吸收，使它看上去愈加灰暗。所以，我们通常将乌云看成暴风雨的前兆。

The darkening of clouds happens as the droplets in the cloud join together to form bigger drops. This means that light is less likely to be reflected from the surface, and some colours get absorbed, giving a darker colour. We tend to associate dark clouds with storms.
#+END_QUOTE

** 云的种类

#+BEGIN_QUOTE
云的种类繁多，差不多有 52 种。最起初的分类系统将云分成三科。它们是卷云、积云和层云。

There are technically a great number of cloud types, around 52. The original classification identified three families of clouds. These were cirrus (from the Latin for "hair" – hence wispy, thin clouds), cumulus (meaning a "heap" or "pile"), and stratus (meaning a "layer" or "sheet").
#+END_QUOTE

file:../images/inflight_science/35.png

#+BEGIN_SRC text
       | Low            | Mid          | Curl          | Rain
-----------------------------------------------------------------------
 Sheet | stratus        | alto-stratus | cirro-stratus | nimbo-stratus 
 Heap  | cumulus        | alto-cumulus | cirro-cumulus | cumulo-nimbus
       | strato-culumus |              | cirrus        |

       | 低             | 高           | 卷            | 雨
-----------------------------------------------------------------------
 层    | 层云           | 高层云       | 卷层云        | 雨层云
 积    | 积云           | 高积云       | 卷积云        | 积雨云
       | 层积云         |              | 卷云          |
#+END_SRC

#+BEGIN_QUOTE
离地面最近最近的云叫做层云，层云飘浮在离地面几百米的低空。

The lowest of the low is the stratus. Stratus can occur just a few hundred metres over ground level.
#+END_QUOTE

#+BEGIN_QUOTE
第二类低云是积云，阳光加热地面空气，导致暖气流上升，在离地面 600 米的空中形成了积云。上升的暖气流夹带着水蒸气、花粉和细菌，这些物质促成了云的形成。

The second low cloud type is the cumulus. With bases around 600 metres and above, cumulus clouds form as a result of thermals, rising columns of warm air that are produced when the Sun heats up the ground. These air columns carry both the water vapour and pollen and bacteria, acting as seeds to trigger cloud formation.
#+END_QUOTE

#+BEGIN_QUOTE
积雨云在空中的高度与积云差不多，但是云顶垂直向上发展得更加旺盛。云顶能向上生长 18 千米，几乎是飞机巡航高度的 2 倍。积雨云的云顶不如云底来得浓厚，通常整朵云呈现出近似于铁砧的形状，这就是酝酿着暴风雨的「云砧」。

Cumulonimbus can start at a similar height (as cumulus), but they go up much further. They can rise as far as 18 kilometres, nearly twice the altitude your plane will cruise at. The top part of a cumulonimbus is more wispy than the bottom, and the whole cloud often forms in an approximate anvil shape, producing the typical "thunderhead".
#+END_QUOTE

file:../images/inflight_science/36.jpg

** 彩虹

#+BEGIN_QUOTE
阳光只有从某一特定角度照射到雨滴上，才会产生清晰可见的彩虹。阳光会以不同角度入射水滴，在水滴内也是以不同的角度反射，当两者角度在 42 度左右时，反射最为强烈，此时，你将会看见一座清晰的七彩虹桥。雨滴能形成圆形的彩虹，不过，地平线会将它们一分为二。

A strong rainbow needs the light to pass through at a fairly precise angle. If the angle between the incoming light from the Sun and the light that heads for your eye is around 42 degrees, you will see a clear spectrum of colours. The raindrops produce a whole ring of rainbow, but this is usually cut off when it hits the ground.
#+END_QUOTE

file:../images/inflight_science/37.jpg

** 速度

#+BEGIN_QUOTE
起初，人类受脚力之限，每小时只能走 3～4 英里，之后我们在马或是船的帮助下，提高了行驶速度。到了 19 世纪，火车的出现让时速最低 50 英里（约相当于 80 千米/小时）成为了出行的常态。接着进入 20 世纪，坐飞机出行使速度大增，我们以每小时 500 英里的速度（约 800 千米/小时）在空中穿梭。20 世纪最快的旅行速度属于协和式飞机，它的时速能达到 1350 英里（约 2170 千米/小时），是声速的 2 倍。有时科技的发展会进入停滞期，至少在某一时间段内是这样的。协和式飞机从一开始接到上百架的订单到最终被停飞，这样的事实说明了对速度真正的限制并不主要来自于科技，而是来自于政治意志。

Initially we were limited to three or four miles per hour on foot, then gained the capabilities of a horse or crude boat. With the 19th century, speeds of at least 50mph (80km/h) became commonplace thanks to the train. Then in the 20th century speeds increased again as air travel eventually took us up to around 500mph (800km/h). The maximum possible speed in the 20th century was when travelling on Concorde, reaching a remarkable 1,350mph (2,170km/h), twice the speed of sound. Sometimes technological achievements reach a plateau, at least for a time. Concorde's rapid trip from having hundreds of orders to being practically given away shows that the real speed limit is not so much technology as political will.
#+END_QUOTE

file:../images/inflight_science/38.png

#+BEGIN_QUOTE
一架普通的飞机能在乘客毫无知觉的情况下突破音障。波音 747 的巡航时速将达到每小时 550～570 英里。飞机的空速是其相对于周围空气的速度，而不是相对于地面的速度。如果空气本身也以 200 英里/小时的速度与你做相同方向的运动，那么，地面测速雷达上观测到飞机的时速将达到 750 英里。这将比 740 英里/小时的声速还要快。

You can break the sound barrier in a conventional plane without even noticing it. The cruising speed of 747 is between 550 and 570 miles per hour. The airspeed of an aircraft is its speed relative to the surrounding air, not relative to the ground. Say that air itself is moving in the same direction you are, at 200mph. Then your speed, as seen by the radar gun on the ground, would be 750mph. You would be travelling above sound's 740mph velocity.
#+END_QUOTE

** 太阳

#+BEGIN_QUOTE
虽然阳光涵盖了光谱中所有的色彩，但是其中黄色光的比重最大。太阳表面 5500 摄氏度左右的高温导致了它现有的颜色。阳光中不同的光子释放出不同的能量，当它们混合在一起穿过空气时，一些光子被空气分子中的电子吸收。很快，它们又被重新释放，朝各个方向发射出去。这样的「散射」意味着通过空气的光线会有一部分偏离原来的运动方向而离开了原来的光束，它们的光子在空中四处扩散。能量较高的光子（光谱中位于蓝色末端）更容易发生散射。这意味着，除了太阳本身之外，经过空气分子散射后的光线都呈现出蓝色，所以天空就变成蓝的了。光谱中位于红色末端的光线散射能力较弱，夕阳西下时，由于斜照，光得经过很厚的大气层才能到达地球，这些红色的光线因为不像蓝光一样易于散射而损失最小，因此天空便被染成了红色。

The yellow component of the light the Sun gives out is the strongest, but it does provide the whole spectrum of light. The natural colour of the Sun reflects its surface temperature of around 5,500°C. When this light containing a mix of photons with different energies passes through the air, some of the photons that make up the light get absorbed by the electrons in the gas molecules of the air. Soon after they are re-emitted and shoot off, but in all directions. This "scattering" means that photons are flung across the sky, no longer all on the same path. Higher-energy photons (towards the blue end of the colour spectrum) are more likely to be scattered. This means that away from the Sun itself, the light being scattered from the air molecules has a blue tinge, making the sky blue. Because the red end of the spectrum is scattered less, when sunlight is passing through a lot of air, which happens when the Sun is low in the sky, the light that isn't scattered, coming direct from the Sun, takes on a red tinge.
#+END_QUOTE

file:../images/inflight_science/39.jpg

#+BEGIN_QUOTE
到达地球的能量仅为 890 亿兆瓦，还不到太阳释放总能量的十亿分之一。尽管如此，它仍然是现有地球消耗总能量的 500 倍。

Just 89 billion megawatts reaches the Earth, less than a billionth of the Sun's output. Yet that's still 5,000 times the current total energy consumption for our whole planet.
#+END_QUOTE

#+BEGIN_QUOTE
粒子穿越某一障碍，而出现在另一侧的过程被称为量子力学隧道效应。太阳中的大部分氢原子核都待在它们该待的地方，但是偶尔也会有那么一两个氢原子核穿越了那道使它们不能和其他氢原子聚合在一起的排斥力，来到与它们相邻近的氢原子附近，于是聚变就产生了。虽然这种情况发生的概率不大，但是太阳中的原子不计其数，还是有大量氢原子能够「翻墙」成功，保证了氢原子源源不断地摇身变成氦原子。

This process of getting through a barrier like a wall and appearing on the other side is called quantum mechanical tunnelling. Mostly the hydrogen nuclei in the Sun stay roughly where you would expect them to be, but occasionally one will tunnel through the barrier caused by the repulsion that keeps them away from other nuclei, and will appear so near a neighbour that fusion takes place. Although this is very unlikely for any particular hydrogen nucleus, there are so many of them in the Sun that statistically a vast number will succeed, resulting in a steady transformation of hydrogen into helium.
#+END_QUOTE

#+BEGIN_QUOTE
目前我们认为重力的能量是由引力子作为载体将能量传递到无限远处，就像光以光子的形式传播一样。假设某一天太阳突然消失了，8 分钟过后，地球上才会失重并陷入无边的黑暗。

Gravity, which we now believe to be carried by a stream of particles called gravitons, just as light travels in the form of photons. If, somehow, the Sun disappeared, only after the eight minutes had elapsed would we lose its light and gravitational pull.
#+END_QUOTE

** 尾迹

#+BEGIN_QUOTE
凝结尾迹：在燃烧室里的高温下，水蒸发为气态，接着，它们从飞机的尾部被排了出去，与冷空气接触，水蒸气遇冷凝结成小水滴或是冰晶。尾迹很少出现在 10,000 英尺以下，因为越往高处，气温就越低，而只有在足够的低温环境中，水蒸气才能在消散前迅速地凝结。

Condensation trail: Because of the high temperature of combustion, that water emerges in the form of a gas, but as it's expelled from the back of the jet and meets the cold air, the vapour will condense to form tiny droplets or ice crystals. They rarely appear below 10,000 feet, as the air gets colder the higher you are, and the temperature needs to be low enough to rapidly cool the vapour, before it's dispersed.
#+END_QUOTE

** 高空生物

#+BEGIN_QUOTE
细菌不仅仅能作为凝结核，聚集起水汽，形成云雨，而且它们非常非常轻，能随气流飘散到几英里之外。人们发现在 20,000 米的高空中也有细菌存在，这是普通飞机巡航高度的 2 倍。

As well as acting as seeds for the formation of water droplets in clouds, bacteria are light enough to be carried many miles on the air currents. ... bacteria have been detected above 20,000 metres up, twice the typical cruising height of a plane.
#+END_QUOTE

#+BEGIN_QUOTE
在昆虫界，大黄蜂就是爬高纪录的保持者。这种生物能生存在海拔 18,000 英尺的喜马拉雅山脉上，现已证实在实验室条件下，它们的飞行高度将近 30,000 英尺。

A bumblebee holds the altitude record for insects. These creatures live at least 18,000 feet up on Everest, and have been proved capable of flying around in lab conditions up to around 30,000 feet.
#+END_QUOTE

#+BEGIN_QUOTE
迁徙鸟类中斑头雁飞得最高，靠着气流的推动，有些斑头雁一天就能飞行 1000 英里。不过，它们只有升到 30,000 英尺的高空才能获得这样的速度。

The bar-headed goose, generally considered the highest-flying of the migrant birds, makes use of the jet stream, some travelling as much as 1,000 miles in a single day. To do this they have to get up to as high as 30,000 feet.
#+END_QUOTE

#+BEGIN_QUOTE
人们曾在非洲象牙海岸 38,000 英尺的上空发现了一只鲁氏粗毛秃鹫。不过不幸的是，这只鸟儿被飞机引擎吸了进去，被发现的时候已经死了。

A Ruppell's griffon was detected the hard way at nearly 38,000 feet over the Ivory Coast. The bird, unfortunately, perished when it was sucked into a jet engine.
#+END_QUOTE

** 风切变

#+BEGIN_QUOTE
空气温度的变化或是风的切变（风切变指的是水平和垂直方向的风的运动方向发生突然变化）都会引起飞机颠簸。在现代航空史上，从来没有飞机是因为遇上气流而从天上掉下来的，气流不会导致坠机。

A sudden plunge can be precipitated by a change in temperature in the air, or wind shear where two sections of the air are moving in different directions. No modern airliners have ever been brought down by turbulence. It isn't going to cause a crash.
#+END_QUOTE

** 电

#+BEGIN_QUOTE
通常两个物体发生摩擦时就能产生静电。这样产生的电被称为摩擦电。著名的静电发电机——范德格拉夫起电机——就是通过这个原理工作的。一条橡胶带和驱动轮之间通过摩擦起电，产生的电荷被输送到顶部圆球的表面，不断堆积。这个装置能产生出数百万伏特的电，不过，人们更常用特斯拉线圈来获得高频电压，制造出炫目的「人工闪电」。这种线圈可以使普通电压上升，获得上百万伏的高频电压。

Static electricity is often made by rubbing one thing against another. The production of electricity this way is called triboelectric. The best known static electricity generators, called Van der Graaf generators, work this way. A belt rubs against rollers, producing a static charge that is then built up on a metal dome. These devices can produce millions of volts, though high-voltage "artificial lightning" displays are more often produced using a Tesla coil, which is a form of transformer that can push voltages up to very high levels.
#+END_QUOTE

file:../images/inflight_science/40.jpg

#+BEGIN_QUOTE
类似于「流」和「流量」这类有关电的术语通常是用来描述水的。法拉第和那些与他同时期的科学家们甚至都不知道原子的存在，就更不用说电子了。他们只知道，某些东西（实际上就是电流）是可以像水一样流动的，他们把电从正电极端子输送到负电极端子，然后大致地判断出电流的去向。事实上，当电子被发现后，人们才意识到自由电子移动的方向与电流标注的方向相反，不过这个发现来得太晚，很多事情已经来不及改变了。

Words like "current" and "flow" were taken straight from water systems. Michael Faraday and the other scientists of the time didn't even know that atoms existed, let alone electrons. They knew that something "electric current" was flowing, and arbitrarily decided which way it went, sending it from what they called the positive terminal to the negative. In fact, when electrons were discovered it was found that they, the real thing that flows, moved in the opposite direction to the way electric current is labelled, but it was too late to do anything about it.
#+END_QUOTE

** 闪电

#+BEGIN_QUOTE
虽然空气是很好的绝缘体，但如果空气中的电压不断累积增高，电火花将最终打破这种阻力，击穿空气。大致上来说，在常规的湿度下，30,000 伏特的电压产生的电火花能击穿 1 厘米厚度的空气（湿润的空气比干燥的空气更容易发生放电）。常规情况下 1 米的放电需要空气中的电压达到 300 万伏特。

Air is quite a good insulator, but if you crank up the voltage of the electricity, you will eventually get a spark to break down the resistance and jump through the air. A rough guide is that at normal humidity (wet air conducts better than dry) it takes around 30,000 volts to get a spark to jump across 1 centimetre. To make a metre-long electrical discharge under normal circumstances would take around 3 million volts.
#+END_QUOTE

#+BEGIN_QUOTE
我们大致上知道是空气中水滴和冰晶摩擦产生了电荷，这些静电荷十分微小，不过却充斥在无数的水滴周围，聚集起巨大的能量，这些摩擦生成的电荷也许就是促成闪电的原因。

(lightning) appears to be due to the movement of water drops and ice crystals in the air causing an electrical charge, possibly due to friction – tiny triboelectric charges, but spread across so many drops that it adds up to a massive amount.
#+END_QUOTE

#+BEGIN_QUOTE
在带负电荷的雷雨云团和由其产生的正电荷的相互作用下，例如，云团和地面之间，另一种能量相对较小的放电发生了。空气在这种放电作用下发生电离。电离过程中原子中的外层电子摆脱原子核的束缚而脱离，原子成为带正电荷传导性更强的离子。 _第一次击闪开辟出了闪电通道，因此被称为先导。接下来，云中出现一根闪亮无比、携带巨大电流的光柱，这被称为回击。回击与第一次击闪的方向相反——第一次击闪中闪电由云层击向地面，而在回击发生时，电流则从地面驰向云底，和人们预想的方向相反。_

A relatively weak electrical discharge runs between the negatively-charged storm cloud and the positive charge it has induced, say from the cloud down to Earth. This discharge ionizes the air. Ionization means it strips electrons off atoms, leaving the very atoms of the air charged and making it more conductive. This first stroke, called a leader, has set up a pathway. Now the main discharge, the one we see, called the return stroke, takes place. This goes in the opposite direction, if the lightning is striking the Earth, the return stroke runs from the ground up to the cloud, the opposite direction to the one we would expect.
#+END_QUOTE

file:../images/inflight_science/41.png

#+BEGIN_QUOTE
闪电电击有着超高的电压，而它产生的电流能达到 30,000 安培，释放出高达 5 亿焦耳的能量，这相当于一座大规模发电站 1 秒钟发电量的总和。当如此巨大的能量击穿空气时，空气分子就开始急速运动起来。空气中的温度将瞬间飙升至 20,000 摄氏度，这甚至远远超过了太阳表面的温度。这种急剧的温度变化生成压力波，现实中，这种冲击波强大的威力与爆炸无异。

In a lightning strike, there's a high voltage and the flow can be more like 30,000 amps, producing as much as half a billion joules of energy, the total output of a good-sized power station for a second. When this amount of power rips through the air, the result is that the air molecules start to move extremely quickly, the temperature shoots up to as much as 20,000°C, significantly hotter than the surface of the Sun. This sudden change in temperature produces a pressure wave, a shock wave that is, in effect, an explosion.
#+END_QUOTE

** 避雷

#+BEGIN_QUOTE
在人类探索电能的早期，法拉第发现电荷无法穿过金属盒外层到达其内部。这种金属笼子被称为法拉第屏罩，即便大量的电流经过笼子的外侧，金属导电性也能中和笼子内侧的电流。结果是，笼子内是绝缘的。

Early on in the exploration of electricity, Michael Faraday discovered that you can't get an electric charge through to the inside of a metal box. As the electric charge builds up outside such a box, called a Faraday cage, the electrons in the metal that makes up the cage move around to cancel out any charge on the inside. The result is nothing gets through the cage.
#+END_QUOTE

file:../images/inflight_science/42.gif

#+BEGIN_QUOTE
尽管电流本身并不会穿透飞机的外壳，但是，雷电会因为电磁效应而产生感应电流，那么有可能导致飞机电路电流过大，这和工作中变压器的道理是一样的。因此，所有的飞机都装配了内置避雷电系统，遭遇雷电时亦可利用它来放电。

Although the electric discharge itself can't get into the plane's shell, it can produce electromagnetic effects that can induce currents, like a transformer in action. Because of this, all airliners have built-in lightning protection systems that discharge any electrical build-up.
#+END_QUOTE

** 火山

#+BEGIN_QUOTE
任一时刻，都有大致 1500 座的火山具有某种潜在的灾难。

At any one time there are around 1,500 volcanoes that present some sort of threat.
#+END_QUOTE

file:../images/inflight_science/43.jpg

#+BEGIN_QUOTE
如果喷力足够大，灰也足够多的话，火山灰可以弥散到世界各地。1883 年喀拉喀托火山喷发，将近 20 立方千米的火山灰和火山岩块随着爆炸喷涌而出，喷发产生的冲击波使这些火山灰进入到 80 千米高的大气中，并将它送往世界各地，据估测，这些冲击波能整整绕地球 7 圈。这些灰黑色的尘埃悬浮在大气中，当它们遮挡住阳光时，地球的温度将会降低 1 摄氏度甚至更多，全球的气候系统在数年内都将受此影响。

If there's enough of this ash, thrown out with enough force, it can spread around the world. When Krakatoa erupted in 1883 around 20 cubic kilometres of ash and rock was spewed out by the explosion. This ash was thrown up 80 kilometres into the atmosphere and travelled around the Earth, following the shock wave from the eruption which was measured passing around the globe a total of seven times. When the dark ash suspended in the atmosphere got in the way of sunlight, it reduced global temperatures by over a degree Celsius and disrupted weather patterns for several years.
#+END_QUOTE

file:../images/inflight_science/44.png

#+BEGIN_QUOTE
今天，这样规模的火山喷发将会使全球的航空系统陷入瘫痪，至少需要一年时间才能恢复。冰冷的海水，尤其是那些火山之上的冰川融水的不断拍打，使蒸腾的熔岩瞬间降温，产生出大量的熔岩碎片，那些玻璃状的碎片十分细小，它们很快就被喷发的爆破力冲入空中。如果大量的火山灰被吸入到飞机引擎内，它们就会熔化，附着在引擎上并重新凝结起来，这会带来一系列麻烦，最糟糕时会使引擎停止运转。

Today such an eruption would shut down aviation worldwide, potentially for at least a year. Cold water, particularly from the glacial ice above the volcano, rapidly cooled the blazing hot lava, producing masses of tiny glass-like splinters, which were then thrown up into the air by the explosive force of the eruption. If a lot of this kind of ash gets into a jet engine it can melt again, stick to parts of the engine and solidify, causing problems and, at the extreme, engine shutdown.
#+END_QUOTE

** 辐射

#+BEGIN_QUOTE
从技术上来说， _发射塔和无线网络产生的辐射是一种电磁辐射，它与核能和原子弹完全扯不上任何关系。_ 与电离辐射相比，电磁辐射的辐射形式有很大不同。电离辐射来源于放射性物质，它包括 X 射线以及更具杀伤力的伽马射线，一些电子和不稳定的原子核放射出的粒子也能产生电离辐射。电离辐射对人体有害，因为它能穿透皮肤，破坏体内细胞组织的运行。人在接受中等剂量的辐射后，其患癌症的几率将会增加，而暴露在大量辐射中的人则会患上一系列的辐射病，过大的辐射量则会导致死亡。

Technically what phone masts and wireless networks produce is radiation, but this has nothing to do with nuclear power and atomic bombs. What they broadcast is electromagnetic radiation. Electromagnetic radiation in the form of radio is quite different from ionizing radiation, which is the stuff that comes from radioactive materials. It includes X-rays and even more powerful gamma rays, but also particles like electrons and the nuclei of small atoms. Ionizing radiation is a problem for us because it can penetrate the skin and damage the inner workings of the cells in our bodies. Medium-size doses can increase the risk of cancer, while large doses will produce radiation sickness, and, at extreme levels, death.
#+END_QUOTE

file:../images/inflight_science/45.jpg

file:../images/inflight_science/46.jpg

file:../images/inflight_science/47.png

#+BEGIN_QUOTE
人体本身就具有放射性。这些射线来自于构成你身体的物质，它偶尔会对一些零星的细胞产生破坏，不过它带来的危害可以忽略不计。

You are naturally radioactive. Some radioactivity is produced by the material in your body, and this will occasionally damage the odd cell, but the risk is vanishingly small.
#+END_QUOTE

#+BEGIN_QUOTE
在我们周围也存在着许多天然放射物质。有些地域的辐射会高于其他地方。比方说，分布有花岗岩的地区辐射较高，对人体的危害也相对会大些。花岗岩会释放出一种叫做氡的气体，当室内氡气的浓度增高到一定程度时，人们的健康将面临风险。

There's plenty of natural radioactivity in the world around us. Some places are significantly more radioactive than others. Where, for instance, there's a lot of granite rock there's usually increased radioactivity and a slightly higher risk. This can be particularly significant if a radioactive gas from the rocks called radon builds up in a house.
#+END_QUOTE

#+BEGIN_QUOTE
在毫无征兆的情况下，你的电脑突然就瘫痪了。虽然这极有可能是因为病毒，但自然辐射也能造成相同的后果。出现这种状况是因为电脑芯片上的一些电子被放射性颗粒或是伽马射线击中了，使计算机的内存和中央处理器无法正常运行而导致瘫痪。遗憾的是，我们无法预测这样的情况会在什么时候出现。

For no obvious reason the computer crashes. While it's most likely to be a bug, this can be caused by natural radiation. What has happened is that a radioactive particle or gamma ray has bashed a few electrons out of one of the chips in the computer. This throws the memory or the processor off kilter and typically results in a crash. Unfortunately there's no way to predict when this is going to happen.
#+END_QUOTE

#+BEGIN_QUOTE
机舱是另一个辐射指数高于正常标准的地方。地面上，岩石释放的辐射会导致指数升高，而在空中，辐射指数升高则源自于宇宙射线。有些射线来自太阳，而更多的则来自遥远的外太空，它们或许发源于某些遥远的星球或恒星爆炸，在太空中漫游了数百万年，行进了几十亿英里。这些粒子猛烈穿入地表大气层与空气分子发生剧烈碰撞，产生巨大的能量并生成新的粒子和高能量的射线。这些射线将投向地面。

Another place where radiation levels are higher than usual is on an aircraft. Where increased levels on the ground are due to radioactive rocks, in the air, extra radiation comes from cosmic rays. Some cosmic rays come from the Sun, many more from the depths of outer space where they may have travelled millions of years, across billions upon billions of miles from distant stars and stellar explosions. When these particles smash into the upper atmosphere, the energy from the collisions with air molecules produces other particles and high-energy light, which smash down towards Earth.
#+END_QUOTE

#+BEGIN_QUOTE
太阳辐射的强弱处于变化之中，平均每 11 年为一个周期。太阳会在你每小时飞行所受的辐射量上增加 0～1μSv，这取决于它位于周期的哪个时段。在一趟飞越大西洋的航程中，你所承受的射线的量相当于做一次胸透的 X 线，是地面所遭受的辐射量的 100 倍左右。

The amount of radiation the Sun pumps out varies on an eleven-year cycle. Depending on where it is in its cycle, the Sun can add between almost nothing and 1mSv an hour during a flight. In the average trip across the Atlantic, your exposure to this radiation is the equivalent of having a chest X-ray, amounting to around 100 times your typical dosage on the ground.
#+END_QUOTE

#+BEGIN_QUOTE
食用贝类会使你每年的辐射暴露量增加 0.5mSv，因为贝类会过滤并吸收水中的放射性物质。

Eating shellfish can add around 0.5mSv a year to your exposure, because shellfish tend to filter natural radioactive materials out of the water.
#+END_QUOTE

* 第五章
** 静脉血栓

#+BEGIN_QUOTE
深静脉血栓是由小血块引起的，在坐飞机时，由于长时间坐在位置上，椅子会对你产生持续的压迫，导致腿部形成血栓，而气压降低则会加剧血栓的形成。每小时至少活动一次，大量喝水也对你有益，同时远离酒精和咖啡等那些会使你脱水的物质。对成人来说，半片阿司匹林就能有效地降低血液的黏稠度。

DVT, deep vein thrombosis, is caused by a small blood clot, typically forming in your legs on a plane, due to the constant pressure from the seat on a long-haul flight, made worse by the reduced air pressure. Move around the cabin at least once an hour. It also helps to drink plenty of water and stay away from dehydrating substances like alcohol and coffee. For an adult, half a tablet of aspirin can help by thinning the blood a little.
#+END_QUOTE

** 时区

#+BEGIN_QUOTE
火车的出现让人们意识到统一时间标准的必要性，以这个标准为基础，通过加减，确定火车在铁路沿线不同站点的到站时间。我们目前使用的时间区大致是在 19 世纪晚期形成的。

the coming of the railways made it essential to be able to exchange times between different stations along a line. Time zones as we now know them were mostly introduced in the late 19th century.
#+END_QUOTE

#+BEGIN_QUOTE
每跨过一个时间区，你就需要一天的时间来恢复，假如你朝西面飞行，这种不适反应则会减轻些。

It takes around a day to recover from each hour of time zone crossed, with the effect being less strong when travelling in a westerly direction.
#+END_QUOTE

** 参考系

#+BEGIN_QUOTE
你没法在机舱里捣鼓那些能证明你是在运动中的物理实验。这种平稳会让我们错以为自己在陆地上。伽利略认识到任何运动都是以其他参照物为前提的。这个认识非常重要，因为它有力地支持了哥白尼提出的太阳中心说。人们否认地球是处于运动状态的，普遍的观点认为如果地球在动，那些没有被固定在地面上的物体肯定会被甩出地球。

You couldn't do any basic physical experiments inside the plane that would tell you that you were moving. Things behave entirely normally. Galileo realized that all movement has to be relative to something else. One of the reasons this was so important to Galileo was in his support for Copernicus' idea that the Earth moves around the Sun. A common objection in Galileo's day to the idea that the Earth was moving was that anything not fixed down would fly off the Earth to be left in its wake.
#+END_QUOTE

** 急流

#+BEGIN_QUOTE
急流是一种持续不断的气流，它自西向东运动，是地球自转的产物。急流是大气气温逆转造成的，急流通常产生于 30,000～40,000 英尺的巡航高度。这个高度是大气下层（也叫对流层）与大气上层（也叫平流层）的分界线，一股狭长的气流带，以每小时 250 英里的速度前行。若遇急流，向东飞行航班的速度将远远快于向西飞行的飞机。

Jet stream, a constant current of air that moves from west to east as a result of the rotation of the Earth. Jet streams form at a temperature inversion in the atmosphere, typically happens around the 30 to 40,000-foot cruising height of an airliner. This is the border between the lower atmosphere, the troposphere, and the upper atmosphere, the stratosphere, form in long corridors and can flow as fast as 250mph. This can make eastbound flights at the right location significantly faster than their westbound counterparts.
#+END_QUOTE

file:../images/inflight_science/48.gif

* 第六章
** 球面

#+BEGIN_QUOTE
地球上两点间最短的距离反映在地图上不一定是直线，在球面上两点间最短的距离是一条弧线，弧线两端延伸就形成一个大圆。

The shortest distance between two points on the Earth usually won't appear as a straight line on a map. The shortest distance between two points on a sphere is part of a great circle.
#+END_QUOTE

#+BEGIN_QUOTE
用平面的地图来表现现实中的弧形的线路。这个转换的过程被称为投影法，但这难免会有些失真。在所有投影法中，麦卡托投影法最为经典，麦卡托将地球仪投影在假想的绕赤道一圈的圆柱筒上，再摊开成平面地图。
 
The process of getting great circle off a sphere onto a flat map is called projection. It inevitably distorts shapes. The traditional way to do this is called the Mercator projection. This approach involves unwrapping the surface of the Earth onto an imaginary cylinder that's fitted around the equator.
#+END_QUOTE

file:../images/inflight_science/49.jpg

file:../images/inflight_science/50.jpg

** CRT

#+BEGIN_QUOTE
阴极射线管是维多利亚时期的发明。显像管电视的局限性在于必须使电子枪与屏幕保持一定的距离，让线圈能够控制电子的偏转角度。

CRT (cathode ray tubes) was a Victorian technology. The trouble with CRTs is that the gun has to be well back from the screen to give those magnets a chance to move the electron beam around.
#+END_QUOTE

** 偏振光

#+BEGIN_QUOTE
像太阳光这类的一般光是由不定向震动的光子组成的，而经过反射后，其中大部分光子的震动方向就一致了。兰德（宝丽来太阳镜的发明者）意识到如果能在太阳镜中加上一层过滤层来阻挡这种方向一致的有序光，就能消除路面或汽车挡风玻璃反射而产生的眩光。

Ordinary light, coming from the Sun, say, consists of photons polarized in any old direction, an overall mess of all possibilities. But when light reflects off a surface, much of it is polarized in one specific direction. Land (Edwin Land who invented Polaroid sunglasses) realized that if he made sunglasses with a filter in them that cut out light in that particular direction, they would reduce the amount of glare from reflections off the road and windscreens.
#+END_QUOTE

** 液晶

#+BEGIN_QUOTE
液晶是一种奇特的物质，正如它的名字那样，它介于液体和固体之间。有些液晶的特性很有趣，当给它们施予一定电压时，液晶分子能旋转一定角度，这能改变光线原来的方向，横向的光线射入后，会旋转 90 度出来。LCD 显示屏背部有一块发光的背板，能源源不断地输送光子。光线从发光背板射入，先进入第一道偏光板，然后经过液晶层，偏转 90 度后，正好能进入第二道偏光板。在没通电的情况下，屏幕是黑的，通电后，屏幕就亮了。

Liquid crystal is a weird substance that, as the name suggests, behaves partly like a liquid and partly like a solid crystal. Some liquid crystals have the interesting property that when you put an electrical current across them, they rotate the polarization of light that passes through them by 90 degrees. There's a flat, glowing panel at the back of LCD screen to provide plenty of photons. The light from it passes through a first polarizing filter, then a liquid crystal, then a second filter at 90 degrees. Result: no electricity = a dark screen; electricity on = a bright screen.
#+END_QUOTE

file:../images/inflight_science/51.jpg

** 塑料保护层

#+BEGIN_QUOTE
驾驶室的窗户没有安装防止乘客破坏的塑料保护内层。知道为什么你从座位上看出去的景色既模糊不清又毫无视觉冲击力吗？都是这层塑料造成的。从驾驶室看出去，外面的景色清晰得令人难以置信，而且通常十分壮观。

Rather than an elongated porthole, the flight deck windows don't have the inner plastic layer that protects the window glass from damage by passengers. It's this plastic that renders the view fuzzy and unimpressive from your seat. The view from the cockpit is startlingly clear and often stunning.
#+END_QUOTE

** 加速度计

#+BEGIN_QUOTE
加速度计是用于测量平移运动加速度的。在拉伸或弯曲时，加速度计上的某个装置会使其电性质发生改变。加速度计和弹簧有类似之处，但是它不会像弹簧那样来回震动，而是通过变化的电流来测量加速度。

Discovering the value of the acceleration in a straight line uses an accelerometer. It employs a device that changes its electrical properties if it's stretched or twisted. This will act like the spring, but won't flop around as the device moves, and will produce a changing electrical current that can be used to measure the acceleration.
#+END_QUOTE

** 轨道飞行

#+BEGIN_QUOTE
任何绕地球轨道飞行的物体都在下落，国际空间站在离地球 300~400 千米之外的轨道中运行，在那儿，地球的引力很小，不过也绝不是零重力。像国际空间站这样的轨道卫星保持了一种微妙的平衡。它一边以自由落体的方式朝地球下坠，一边又以足够快的速度向侧面运动（与地球相切的方向），因此，它总是与地球擦肩而过。如果侧面运动的速度太快，空间站就会脱离轨道，飞入太空。如果速度太慢，则将坠回地球。

Something in orbit around the Earth is always falling. The gravitational pull of the Earth is less at 300 to 400 kilometres up where the space station orbits, but it's certainly not zero. A orbiting satellite like the space station does a clever balancing act. It's both falling towards the Earth in free-fall, and moving sideways (at a tangent to the Earth) fast enough that it always misses the Earth. If it travelled sideways any faster it would escape and fly away. If it went slower it would plunge to the ground.
#+END_QUOTE

** 重力

#+BEGIN_QUOTE
事实上，重力十分微弱。仅仅靠着腿部的肌肉，你就能克服重力跳起来。更有说服力的例子是用一只塑料笔或梳子上的静电荷通过电磁力将小纸片吸起来。一方面是巨大无比的地球想拖住小纸片，而另一方面是微小的电磁力想把纸片吸起来。但重力还是败下阵来。

In fact gravity is very weak. With nothing more than the muscles in your legs you can jump up and overcome the pull of gravity. Even more impressive was when you lifted a piece of paper with the electromagnetic force of the static charge on a plastic pen or comb. You had the whole, massive Earth pulling the paper down and just that tiny amount of electromagnetism pulling up, but still gravity lost.
#+END_QUOTE

* 第七章
** 马桶

#+BEGIN_QUOTE
传统家用抽水马桶的后部有一个 S 形的管道，它的工作原理和弯曲吸管是一样的。在排污时，当马桶内的水面超过 S 弯的高点时，由于大气压形成的虹吸现象，能够把水和污物一同抽走。

In a traditional domestic toilet there's an S-bend at the back, acting like the bendy bit of the straw. When you flush the toilet, a large rush of water enters the bowl and the air pressure on the bowl causes it to siphon, sucking material over the bend and away down the drains.
#+END_QUOTE

file:../images/inflight_science/52.jpg

#+BEGIN_QUOTE
现代飞机上使用的都是真空厕所。当你按下冲刷按钮时，坐便器后边的真空泵就开始工作。几秒钟后，你会听到一阵特殊的声音，连接坐便器和真空系统的控制阀就打开了，依靠与大气压之间的压差，将坐便器中的东西带走，这和吸尘器的原理差不多。

Modern aircraft have vacuum toilets. Here, when the flush button is pressed, a vacuum is built up in a chamber behind the bowl. After a few seconds, with a distinctive sound, the vacuum is opened to the bowl, the pressure in the toilet drops, and the material in it is sucked out of the bowl, just as a vacuum cleaner sucks up rubbish.
#+END_QUOTE

#+BEGIN_QUOTE
被厕所吸住这样的事情从未发生过。事实上，也不可能发生，因为冲水按钮通常位于马桶盖的后方，乘客起身以后才能按得到那个键。即便发生了，乘客也不会被困在马桶上这么久，因为几秒钟后，真空系统就停止工作了。不过，这很有可能会导致人体内伤。

"Stuck in the toilet" incident never happened. It's virtually impossible to do anyway, as the flush button is usually sited behind the toilet lid, so that to be able to flush it you have to be well away from the seat. If it were possible, it's unlikely that the seal would be good enough to trap someone for any length of time, especially as the vacuum system cuts off after a few seconds, but there's a significant risk of causing internal injury.
#+END_QUOTE

** 视星等

#+BEGIN_QUOTE
金星是所有行星中最亮的，次亮的是木星和火星。半人马座阿尔法星是人马座中距离地球最近最亮的恒星，它距离我们不过 4 光年。人马座中第二亮的是半人马座贝塔星（也叫 Agena），它距地球 190 光年，半人马座阿尔法星距离太阳更近，距贝塔星更远，但是，从来没有人想过将太阳和阿尔法星连在一起，组成某个图案。

Venus is the brightest of the planets, followed by Jupiter and then Mars. The Centaurus constellation in the southern sky - its brightest star, Alpha Centauri, is one of the nearest to ours, not much more than four light years distant. The next brightest in the constellation, Beta Centauri (or Agena) lies 190 light years away. Our own star is much closer to Alpha Centauri than Agena is, yet we would hardly think of the Sun and Alpha Centauri as forming a pattern.
#+END_QUOTE

file:../images/inflight_science/53.jpg

** 月球

#+BEGIN_QUOTE
月球的实际大小只有太阳的 1/400，但是它与地球的距离也是太阳与地球间距离的 1/400。在月亮引力的作用下，地球旋转速度会变慢。由于角动量守恒随着月亮的角动量变大，地球的角动量就变小了。月亮以每年 4 厘米的速度离我们远去。

The Moon is around 400 times smaller than the Sun, it's also around 400 times closer to us. The Moon's gravitational effect is slowing the Earth down. Because angular momentum of a system is conserved, the Moon gains momentum as the Earth loses it. The Moon gets around 4cm further away from us each year.
#+END_QUOTE

file:../images/inflight_science/54.gif

#+BEGIN_QUOTE
如果将硬币举到离你一臂之远的地方，你会发现你看到的月亮比任何规格的硬币都小。月亮的直径是 3500 千米，它距离我们 380000 千米。眼睛距离手臂末端的距离是 0.75 米，在距离眼睛一臂之远外的月亮的直径为 0.75 × 3500 × 1000 × 1000 / (380000 × 1000) = 6.9 毫米。纸上戳出的洞的直径差不多是 5 毫米。

Guess what size coin, held at arm's length, would be the same size as the full Moon. You will find that no coin is as small as the visible size of the Moon. The Moon is around 3,500 kilometres in diameter and around 380,000 kilometres away. So to find its apparent size in millimetres at 0.75 metres' distance from the eye. So the Moon's apparent diameter at arm's length is 0.75 × 3,500 × 1,000 × 1,000 / (380,000 × 1,000) = 6.9mm. As punch holes are around 5mm across, this is not a bad approximation.
#+END_QUOTE

#+BEGIN_QUOTE
人们看到月食的次数比日食多。因为，相对于月球的地影比相对于地球的月影更大。月食发生时，地球的阴影投射到月球上。地球上一半的区域内，处于夜晚的人们都可以看到月食。而日食则不同，地球上能够看到日食的区域很有限。

Lunar eclipses happen much more often than solar eclipses. Because the shadow of the Earth is much bigger with respect to the Moon than the shadow of the Moon is with respect to the Earth. An eclipse of the Moon is visible from half the planet – everywhere it's night – unlike a solar eclipse, which can be seen only in a narrow corridor on the Earth's surface.
#+END_QUOTE

#+BEGIN_QUOTE
月食发生时，月亮不是全黑的，而是散发出明显的红光，这是因为阳光穿过地表大气层时发生折射，就像它穿过棱镜时产生的折射一样。红光波长比较长，受到散射的影响不大，红光通过大气层穿透出去，折射到月球表面。

During a lunar eclipse, the Moon doesn't go entirely dark, but instead takes on a strong red coloration, as light from the Sun passes through the Earth's atmosphere and is bent, just as light is bent passing through a prism. Less of the red light is scattered by the atmosphere, so the Moon appears red.
#+END_QUOTE

** 街灯

#+BEGIN_QUOTE
按照粗略的统计，在发达国家的城镇中，平均每 10～20 人就拥有一盏街灯。打个比方，如果横向来看，整个城市的长相当于 15 个这样小正方形区域连在一起，而纵向来看，它的宽相当于 10 个这样的正方形，那么这个城市的总面积就相当于 150 个小正方形面积的总和。我们假定小正方形区域中有 50 盏街灯，那么整个城市就是 7500 盏。因此，这个城市的人口数量大致在 75000～150000 人。

As a very rough rule of thumb, in towns and cities in industrialized countries there's one street light for every ten to twenty people. For instance, if your square would fit about ten times in one direction over the town and fifteen times in the other, that's 150 squares to cover the town. Let's say you counted 50 street lights in the square. That makes 7,500 lights in total. So the population is likely to be between 75,000 and 150,000.
#+END_QUOTE

** 眼睛

#+BEGIN_QUOTE
若已经进入夜晚，机舱中的灯光则会变暗。这么做为的是在突发情况下，如需乘客紧急撤离飞机，你的眼睛能适应低光的环境。人眼调节能力很强。在晴朗的夜晚，人眼能看见 16 千米（约 10 英里）外的烛火。只要有 5～6 个光子进入瞳孔，眼睛就能察觉。

If it's night, the lights in the cabin will be dimmed. This is a precaution in case you have to get out of the aircraft quickly, to ensure that your eyes have acclimatized to the low light conditions. The human eye is a remarkably flexible instrument. On a really clear night, it can see a candle flame 16 kilometres (10 miles) away. It takes only five or six photons of light to trigger a response.
#+END_QUOTE

#+BEGIN_QUOTE
如果你从一个点着电灯的房间里走到明媚的阳光下，你并不会觉得外面有多么亮，也许只比房间里亮 2～3 倍而已。事实上，阳光的强度能比普通灯光强上 100 倍。这就是为什么当你手持摄像机从屋内到屋外时，在机器还没来得及调节好光线之前，你所看到的画面通常将会是白花花的一片曝光过度。在调节光线的能力上，照相机和摄影机远远比不上大脑和眼睛的组合。

If you go from an electrically lit room inside to the outside on a bright sunny day, it doesn't seem hugely brighter, perhaps only a factor of two or three. In reality, outdoor sunlight can be 100 times brighter than typical indoor lighting. This is why, when using a video camera, the view will flare to practical invisibility when you move outside, before the electronics can compensate. The camera isn't as clever as the brain/eye combo at dealing with changes in light levels.
#+END_QUOTE

#+BEGIN_QUOTE
人眼中有将近 700 万个 3 种不同种类的视锥细胞，1.2 亿个比锥细胞更敏感的视杆细胞。视杆细胞负责分辨黑白，视锥细胞负责分辨颜色。在弱光环境中，视锥细胞会停止工作，我们看到的一切都变成灰色的了。在弱光下，用余光看东西比直接盯着它们看来得更清楚。这是因为远离视网膜中央区域的视杆细胞虽然不能分辨颜色，但能感受弱光。人们认为视杆细胞的存在是为了帮助人们在夜间发现向他们逼近的捕食者。

There are about 120 million of these rods, which are significantly more sensitive than the three types of cones, 7 million in all, that deal with colour. When the light levels are low, the cones switch off, leaving our vision as shades of grey. If light is weak, you can see things better if you don't look directly at them. That way the extra rods towards the edges of your vision can come into play. These are thought to be there to help us spot predators, creeping up on us in the dark.
#+END_QUOTE

file:../images/inflight_science/55.jpg

#+BEGIN_QUOTE
我们看到的一切都是大脑加工后的产物，并非主观事实。这也是为什么人会有幻觉。当眼球开始短暂快速地运动，对物体进行扫视时，你看到的却是稳定连续的图像，这也是种幻象，因为大脑已经对图像进行了编辑。在很长一段时间内，人们用「视觉暂留」来解释为什么人眼能将静止的画面转化为连续的视像。真实的原因是，我们被眼睛蒙蔽了，它们通过一系列模式制造出假象，让你认为这些静止的画面是在做连续运动。

The brain builds an artificial picture of the outside world. What we see really is artificial. This is why optical illusions work. Your eyes are constantly jerking around in tiny, very quick movements called saccades. These are ironed out by the brain, leaving a steady view. For a long time, the reason we saw these pictures as moving was thought to be due to "persistence of vision". Instead, it's the way the eye constructs a fake view using these different modules that allows it to be misled by a series of still images and think it's seeing movement.
#+END_QUOTE

#+BEGIN_QUOTE
由于视神经起始于视网膜后部，这导致人眼产生了一个盲点，物体的影像落在这个地方也不能引起视觉。而大脑训练有素的联想能力则填补了盲点的空白。

Where the optic nerve joins the back of the eye, there's a blind spot, leaving an area of sight where you simply can't see. The brain fills in what's happening in that area by educated guesswork.
#+END_QUOTE

** 摩擦力

#+BEGIN_QUOTE
大部分摩擦力都是电磁相互作用引起的。我们知道，物体由原子组成，而原子又是由带正电的原子核和带负电的电子组成，电子在核外空间内做高速运动，在原子核外围形成了一个电荷层。一旦两个物体发生接触，这些电荷就开始相互作用。当你坐下去时，椅子上方带负电的电子与你身体表层的电子之间相互排斥。事实上，你的身体没有和椅子发生接触，你漂浮在那一层电荷斥力互相作用的云状物上。某些原子外层的「电子云」更厚，威力更大，它会把对方原子周围的电子挤开，从而吸引更多正电荷。大多数摩擦力都是由于这样的电磁吸引产生的。

Most friction is electromagnetic. As we've seen, the atoms that make up objects consist of a positively-charged nucleus and negative electrons, forming a cloud of charge around the nucleus. These charges interact whenever two objects are brought together. The negative electrons on the outside of the seat repel the negative electrons on the outside of your body. You don't actually come into contact with the seat, you float just above it on a cloud of repulsion. There's a large electron cloud on one atom it can push the electrons on another atom out of the way, leaving more of a positive charge for it to cling on to. It's this electromagnetic attraction that's responsible for much of friction.
#+END_QUOTE
