#+setupfile: ../../styles/readtheorg.setup
#+title: 叫魂

* 第一章 中国窃贼传奇

我们不能预见未来。然而，构成未来的种种条件就存在于我们周围。

** 官僚机制对妖术的处理

1768 年蔓延于中国东部与中部的大恐慌是以各地有关妖术的种种信念为丰富的养料滋生而成的。各地的信念中都包含有以下一些要素：在某种条件下，人的魂能够同拥有魂的躯体相分离；一个人若掌握了另一个人的魂，便可以利用它的力量来为自己谋利；若要偷取别人的魂（亦即「叫魂」），可以通过施展妖术来实现，或者可以对着已从受害者身上分离出来的某种实物（例如男人的辫梢或女人的衣襟）念咒，或者可以把受害者的名字放在一根将要打入地下的桩子的上面或底下，并在打桩时念诵受害者的名字；通过向受害者撒出粉状的迷药，可以使他在被剪去发辫时无法抵抗；受害者极可能是男性孩童；受害者会得病或死去。

-----

在一个通过父系继承，婴儿死亡率又极高的社会里，对孩子（尤其是男童）的保护，是生活中唯此为大的事情。在清代，人们对大多数疾病的原因还不甚清楚或存有误解，因此，当孩子患病的时候，便不能排除这是否因妖术引起的可能。那些本来便与超自然事物打交道的人（如和尚与道士），在人们按情理的推想中掌握着操纵超世俗事务的种种手段，也就最有可能是妖党术士一流了。

-----

也许妖术真的是存在的，但是，起决定作用的因素肯定还是因此而引发大恐慌的可能性。如果坏人试图施行妖术，他们实际上便已经在民众中触发了危险的恐惧感，官府在面对因妖术而引发的歇斯底里时，其反应总是要把案子从街上转移到官府大堂上来。若在某人的管辖范围内发生了公众动乱，那便是此人无能或无知的铁证。这比之未能完粮纳税更确定地会摧毁一个人的仕途生涯。

要阻止公众为对付妖术而大动干戈，也许需要付出极大的代价。根据其他文化所提供的例证，如果政府因为认为妖术不可知或不可信而禁止老百姓以暴力来对付它，则其声誉就会受到严重的损害。纳瓦霍人曾抱怨说，白人当局禁止他们杀害巫师。

从维护政府公共形象的角度来看，最聪明的也许是乌干达的那种解决方案。在英国的管辖下，那里有一个法律，对为了威胁对手或为了制造一种使别人畏惧自己的名声而「假冒」为巫师的人，要予以惩罚。在这个事例中，政府并不承认自己相信巫术实有其事，但却表明自己是在同假冒从事巫术的行为作斗争。《大清律例》中有关反妖术的条款同乌干达的不可知论颇有异曲同工之妙。

* 第二章 盛世
** 弘历治下的镀金时代

描述十八世纪的中国社会，比之探讨进入十九世纪后中国的衰落、破败、孱弱以及无所作为，是一种令人更为振奋的经历。

十八世纪中国的经济成就是以国内和平为基础的。此前，中国本土发生大的战争还要回溯到 1681 年，亦即弘历的祖父玄烨平定三藩之乱的时候。1683 年，当清军征服台湾之际，中国的沿海地区也安定了下来，征战年代人口锐减的现象已经扭转。而自十七世纪初，由美洲引进的各种新作物（玉米、甜薯、花生、烟草等适于在干燥高地上生长的作物）开始被种植到中国内陆难以灌浇的山坡地上。因此到了十七世纪下半叶，导致现代人口激增的环境已经形成。有人认为，在整个十八世纪的过程中，中国的人口数翻了一番。

来自西属美洲的白银源源不断地从国外流入中国，以换取中国的丝绸、茶叶、瓷器以及外部世界所需的其他产品，推动了土地与劳动力的自由买卖。此时，西方的工业革命尚处于起始阶段，在他们看来，中国的商业活力与人口增长正在创造出一个既生机勃勃又相当稳定的社会。
