#+SETUPFILE: ../../styles/readtheorg.setup
#+TITLE: 浪潮之巅

* 目录

| 第一章 | 帝国的余晖：AT&T                     |
|--------+--------------------------------------|
| 第二章 | 蓝色巨人：IBM                        |
|--------+--------------------------------------|
| 第三章 | 「水果」公司的复兴：乔布斯和苹果公司 |
|--------+--------------------------------------|
| 第四章 | 计算机工业的生态链                   |
|--------+--------------------------------------|
| 第五章 | 奔腾的芯：英特尔公司                 |
|--------+--------------------------------------|
|        |                                      |

* 帝国的余晖：AT&T

| 1875 | 贝尔和沃森发明电话                                                             |
|------+--------------------------------------------------------------------------------|
| 1877 | 美国贝尔电话公司成立                                                           |
|------+--------------------------------------------------------------------------------|
| 1880 | 贝尔长途电话业务开通                                                           |
|------+--------------------------------------------------------------------------------|
| 1892 | 长途电话业务进入美国中部芝加哥地区                                             |
|------+--------------------------------------------------------------------------------|
| 1913 | 和美国政府达成第一次反垄断协议                                                 |
|------+--------------------------------------------------------------------------------|
| 1915 | 电话业务进入美国西部旧金山地区                                                 |
|------+--------------------------------------------------------------------------------|
| 1925 | 贝尔实验室成立                                                                 |
|------+--------------------------------------------------------------------------------|
| 1972 | Unix 操作系统和 C 语言从贝尔实验室诞生                                         |
|------+--------------------------------------------------------------------------------|
| 1982 | 美国司法部打赢了长达 8 年的针对贝尔电话公司的反垄断官司                        |
|------+--------------------------------------------------------------------------------|
| 1984 | 美国贝尔电话公司被拆成 AT&T 和 7 家地区性贝尔公司                              |
|------+--------------------------------------------------------------------------------|
| 1996 | AT&T 主动地一分为三，包括新 AT&T、朗讯和 NCR                                   |
|------+--------------------------------------------------------------------------------|
| 2000 | 朗讯的移动部门 Avaya 单独上市                                                  |
|------+--------------------------------------------------------------------------------|
| 2001 | AT&T 再次主动地一分为四，变为独立的长途电话、无线电话、宽带和媒体 4 家公司     |
|------+--------------------------------------------------------------------------------|
| 2004 | AT&T 被道琼斯指数除名，从地区性贝尔公司发展起来的 SBC 替代了它在该指数中的位置 |
|------+--------------------------------------------------------------------------------|
| 2005 | AT&T 被 SBC 并购，成为新 AT&T                                                  |
|      | 此前，从AT&T分出的几家独立公司均被竞争射手或业界同行收购                       |
|------+--------------------------------------------------------------------------------|
| 2006 | 朗讯被法国的阿尔卡特并购，原来的美国贝尔电话公司（AT&T）从此消亡               |

#+BEGIN_QUOTE
贝尔实验室著名的发明除电话外，还包括射电天文望远镜、晶体管、数字交换机、计算机的 Unix 操作系统和 C 语言等。此外，贝尔实验室还发现了电子的波动性，发明了信息论，组织发射了第一颗通信卫星，铺设了第一条商用光纤。
#+END_QUOTE

#+BEGIN_QUOTE
道琼斯工业指数在 20 世纪初包括 20 家上市公司，后来扩大到 30 家。这 30 家公司是美国支柱产业的大公司。因此道琼斯又称为蓝筹股—blue chips，因为蓝色的筹码是赌局中面值最大的筹码。
#+END_QUOTE

#+BEGIN_QUOTE
为什么美国小公司能很快成为跨国公司，我认为其中一个原因是反垄断法逼着公司进行科技进步。当一个公司开始垄断一个行业时，它会更多地倾向于利用自己的垄断资源，而不是科技进步获得更多的利润，毕竟前者比后者容易得多。
#+END_QUOTE

#+BEGIN_QUOTE
美国几乎所有的老公司，创始人及其家族早剩不了多少股权了，大部分股权都散落在民间（包括基金），当然 AT&T 也不例外。因此，为了管理这些公司，董事会会请职业经理人担任各种管理人员，包括首席执行官。而董事会里除了大投资基金和银行的代表，剩下的是独立董事，他们的任务是监督执行官们的工作，保证投资人的利益，而不是考虑公司的长远发展。AT&T 几个执行官们手上的股票远不如华尔街投资银行控制的多。

上个世纪 90 年代，AT&T 已经不属于一个人、一个机构，没有人为它十年百年后的发展着想（我们以后还会多次看到，当一家公司没有人对它有控制权时，它的长期发展就会有问题）。
#+END_QUOTE

#+BEGIN_QUOTE
从 1995 年至今，贝尔实验室没有再搞出轰动世界的发明。到 2001 年，朗讯公司不得不关闭贝尔实验室的几乎全部研究部门。只是象征性地留下一两个实验室，以保住贝尔实验室这块招牌。今天，贝尔实验室的牌子还在，只是联系地址已经到了法国。
#+END_QUOTE

#+BEGIN_QUOTE
在 2000 年前后，短线投资者发现最快的挣钱方法不是把一个企业搞好，而是炒作和包装上市。将公司的一部分拆了卖无疑挣钱最快。

以前，美国政府多次要求拆散 AT&T 而做不到，但是在美国经济最好、科技发展最快的 10 年中，它自行把自己拆了卖。
#+END_QUOTE

#+BEGIN_QUOTE
如果说终结 AT&T 帝国的内因是华尔街和 AT&T 自己的贪婪和短视，那么互联网的兴起则从外部彻底击垮了这个帝国。
#+END_QUOTE
* 蓝色巨人：IBM

| 1924 | 老沃森控股原打表机公司，改名 IBM                                |
|------+-----------------------------------------------------------------|
| 1925 | 进入日本市场，此前制表机公司已经开始逐渐进入欧洲市场            |
|------+-----------------------------------------------------------------|
| 1933 | IBM 工程实验室成立                                              |
|------+-----------------------------------------------------------------|
| 1936 | 在罗斯福新政时，获得美国政府大订单                              |
|------+-----------------------------------------------------------------|
| 1940 | 20 世纪 40 年代进入亚洲市场                                     |
|------+-----------------------------------------------------------------|
| 1943 | IBM 研制出真空管放大器                                          |
|------+-----------------------------------------------------------------|
| 1945 | 沃森实验室成立                                                  |
|------+-----------------------------------------------------------------|
| 1952 | 小沃森成为 IBM 总裁，开始了快速发展的 20 年计算机时代           |
|------+-----------------------------------------------------------------|
| 1953 | 研制出使用磁鼓的计算器                                          |
|------+-----------------------------------------------------------------|
| 1964 | IBM360 大型计算机问世                                           |
|------+-----------------------------------------------------------------|
| 1969 | 开始语言识别的研究，司法部开始对 IBM 进行反垄断调查             |
|------+-----------------------------------------------------------------|
| 1971 | 小沃森退休                                                      |
|------+-----------------------------------------------------------------|
| 1973 | 江崎玲于奈博士因在电子隧道效应上的研究为 IBM 获得第一个诺贝尔奖 |
|------+-----------------------------------------------------------------|
| 1981 | IBM-PC 诞生                                                     |
|------+-----------------------------------------------------------------|
| 1993 | 郭士纳接管 IBM，开创 IBM 10 年黄金时代                          |
|------+-----------------------------------------------------------------|
| 1997 | 计算机深蓝战胜国际象棋世界冠军卡斯帕罗夫                        |
|------+-----------------------------------------------------------------|
| 2005 | IBM 将 PC 部门卖给联想，从此退出 PC 市场                        |

#+BEGIN_QUOTE
IBM 公司可能是世界上为数不多的成功逃过历次经济危机，并且在历次技术革命中成功转型的公司。
#+END_QUOTE

#+BEGIN_QUOTE
IBM 至今仍然是世界上最大的服务公司、第二大软件公司、第二大数据库公司。IBM 有当今工业界最大的实验室 IBM Research（虽然其规模只有贝尔实验室全盛时期的 1/10），是世界第一专利申请大户，它还是世界上最大的开源的 Linux 服务器生产厂商。
#+END_QUOTE

#+BEGIN_QUOTE
机械革命从 300 年前开始到第二次世界大战结束，一般认为其高峰是 19 世纪末期。当时很多人认为机械可以代替一切，就如同今天不少人认为计算机可以代替一切一样。IBM 就是在那个背景下成立的。

早期的 IBM，产品主要是一些用于管理的机械，诸如打孔机、制表机等，服务对象是政府部门和公司。IBM 从那时起，就锁定了政府部门和企事业单位为它的主要客户，直到今天。
#+END_QUOTE

#+BEGIN_QUOTE
……二次世界大战，以制造精密机械见长的 IBM 马上把它的生产线民用转军用，参加制造著名的勃朗宁自动步枪和 M1 冲锋枪。
#+END_QUOTE

#+BEGIN_QUOTE
我们可以将第二次世界大战作为机械时代和电子时代的分水岭。英国在二战后很长时间里试图恢复它的机械工业，虽然它做到了，但是也已经落伍了。而一片焦土的日本，已经没有剩下什么工业基础了，因此另起炉灶，发展电子工业，结果成为了西方世界中的老二。
#+END_QUOTE

#+BEGIN_QUOTE
美国研制计算机的直接目的是在第二次世界大战时为军方计算弹道的轨迹。在流体力学中，计算量常常大到手工的计算尺无法计算的地步，因此，对通用计算机的需求就产生了。
#+END_QUOTE

#+BEGIN_QUOTE
小沃森对世界最大的贡献不足将 IBM 变成一个非常成功的公司，而是将计算机从政府部门和军方推广到民间，将它的功能由科学计算变成商用。

今天我们知道计算机可以单纯用于存储信息、处理表格和文字、编辑和打印文章。但是在 50 年前就能够看到这一点是非常了不起的。
#+END_QUOTE

#+BEGIN_QUOTE
银行里有大量的简单计算，主要是账目上的加加减减，不需要复杂的甬数功能，比如三角函数、指数对数函数等。因此，就需要有一种专门处理大量数据而运算简单的程序语言。上个世纪六七年代的主流高级程序语言 COBOL 就在这个背景下诞生了。COBOL 的全名为「面向商业的通用语言」（Common Business Oriented Language）。
#+END_QUOTE

#+BEGIN_QUOTE
如果要把计算机工业的历史划分阶段，那么，1976 年可以作为一个分水岭。这一年，没有读完大学的天才史蒂夫・乔布斯在车库里整出了世界上第一台可以商业化的个人电脑 Apple-I。
#+END_QUOTE

#+BEGIN_QUOTE
仅一年时间，IBM-PC 就问世了，那是 1981 年的事。虽然第一批 IBM-PC 的性能只有现在个人电脑的万分之一，但是，它比苹果公司的 Apple 系列已经好很多了，而且对当时的字处理、编程等应用已经足够了。

虽然 IBM-PC 在外部的反应很好，在公司内部反应却很冷淡。IBM-PC 第一年的营业额大约是两亿美元，只相当于 IBM 当时营业额的 1% 左右，而利润还不如谈下一个大合同。要知道，卖掉十万台 PC 可比谈一个大型机合同费劲儿多了。因此，IBM 不可能把 PC 事业上升到公司的战略高度来考虑。

个人电脑时代的最终领导者是微软和英特尔，而不是 IBM。随着 2005 年 IBM 将个人电脑部门卖给了中国的联想公司，IBM 彻底退出了个人电脑的舞台。
#+END_QUOTE

#+BEGIN_QUOTE
从上世纪 70 年代初到 80 年代初，美国司法部和 IBM 打了 10 年的反垄断官司，两家最终于 1982 年和解。IBM 为此付出了很大的代价：第一，IBM 分出了一部分服务部门，让它们成为独立的公司；第二，IBM 必须公开一些技术，从而导致了后来无数 IBM-PC 兼容机公司的出现。

IBM-PC 的主要部件，如处理器芯片、磁盘驱动器、显示器和键盘等，或者本身是第三家公司提供的，或者很容易制造，而它的操作系统 DOS 又是微软的。因此，IBM-PC 很容易仿制。IBM-PC 唯一一个操作系统的内核 BIOS 是自己的，但是很容易就被破解了。在短短的几年间，IBM-PC 的兼容机如雨后春笋般地冒了出来。
#+END_QUOTE

#+BEGIN_QUOTE
当时 IBM 为了以最快速度推出 PC，连操作系统都懒得自己开发，而是向其他公司招标。

盖茨看到了机会，他用 7.5 万美元买来磁盘操作系统（DOS），转手卖给了 IBM。盖茨的聪明之处在于，他没有让 IBM 买断 DOS，而是从每台 IBM-PC 中收一笔不太起眼的版权费。而且，IBM 和微软签的协议有个很小的漏洞，没有说清楚微软是否可以将 DOS 再卖给别人。

IBM 原来认为 PC 机赚钱的部分是几千块钱的硬件，而不是几十块钱的软件。但由于兼容机的出现，IBM 沦为了众多 PC 制造商之一，利润受到竞争的限制。而所有微机的操作系统只有一种，虽然每份操作系统现在还挣不了多少钱，但将来的前途不可限量。

盖茨明修栈道，暗渡陈仓，一方面和 IBM 合作开发 OS/2，另一方面下大力气开发视窗操作系统（Windows）。当视窗 3.1 研制出来的时候，微软帝国也就形成了。硅谷一位最成功的 CEO 讲，凡是和微软合作的公司，最后都没有好结果。IBM 也许是其中第一个吃亏者。
#+END_QUOTE

#+BEGIN_QUOTE
在美国，以大欺小的官司常常很难赢，而且即使赢了，也不可能得到太多的赔偿，因为小公司没有什么油水可榨。
#+END_QUOTE

#+BEGIN_QUOTE
1993 年，郭士纳出任 IBM 的首席执行官。他成功地帮 IBM 完成了从一个计算机硬件制造公司到一个以服务和软件为核心的服务性公司的转变，并开创了 IBM 的十年持续发展。

无论世界如何发展，对 IT 服务业的需求总是存在的，而且是上升的。因此，虽然有金融危机，使得各个公司和企业会迅速减少，甚至终止对 IT 产品的采购，但是，只要这些企业还存在一天，就需要 IT 服务一天。有了这个稳定的收人来源，IBM 在金融危机最严重的季度，营收也没有受到多少影响。
#+END_QUOTE

#+BEGIN_QUOTE
IBM 在经营上相当的保守，它一直固守自己的核心领域，很谨慎地开拓新的领域。从机械的制表机到大型计算机，到今天的 Linux 开源服务器，IBM 始终牢牢地控制着美国政府部门、军队、大公司和银行的业务，即使它生产的笔记本电脑，也是针对公司用户而不是个人用户的。

保守的好处是不容易轻易出错，因为像 IBM 这样服务于美国乃至世界各国核心部门的公司，产品上出一点错就会造成不可弥补的损失，要知道美国主要银行对计算机系统的要求是一年宕机时问不能超过 5 分钟。
#+END_QUOTE

#+BEGIN_QUOTE
几十年来，如果说在工业界哪个实验室有资格和贝尔实验室相提并论，恐怕只有 IBM 实验室了。

上世纪 50 年代，IBM 发明了计算机的硬盘和 FORTRAN 编程语言；上个世纪 60 年代，IBM 发明了现在通用的计算机内存（DRAM），提出了现在广泛使用的关系型数据库（Relational Database）。上个世纪 70 年代以来 IBM 的重大发明和发现包括今天通信中使用最广泛的 BCJR 算法、精简指令集计算机（RISC）的]工作站、硬币大小的微型硬盘（用于照相机等设备），以及后来获得诺贝尔奖的可以看见原子的显微镜。
#+END_QUOTE

#+BEGIN_QUOTE
IBM 一直是美国专利大户，每年都有几千个专利。

在美国，申请专利的目的一般有两种，第一种是保证自己不被别人告侵权，即防御性的。一个公司发明一种东西后，为了防止其他公司和个人将来提出什么不合理的要求，通过申请专利来保护自己。第二种是进攻性的，一个公司申请一些可能以后有用的但是自己未必使用的专利，专门来告别人侵权。IBM 的专利很多是后一种。

IBM每年花上亿美元，养了一支庞大的知识产权方面的律师队伍，专门去告那些可能侵犯它们专利的公司，每年 IBM 从专利赞上挣来的钱是 10 亿美元左右。
#+END_QUOTE

#+BEGIN_QUOTE
IBM 不断地淘汰不挣钱或挣钱少的部门，扩充利润高的部门。2002年，IBM 将效益不好的硬盘部门以 30 亿美元的价格卖给了日本的日立公司。2004 年底，IBM 将它的笔记本电脑部门以 17.5 亿的价格卖给了中国的联想公司。
#+END_QUOTE

#+BEGIN_QUOTE
IBM 的高层很清楚，即使裁员 20%，他们的业务也不会有什么根本的影响。从郭士纳掌权以后，每到经济危机时期，IBM 就开始变相裁员。

……更进了一步，把很多工作永久性地移到了印度，因为那里的成本能比美国少一半。作为一个业务遍布全球的跨国公司，IBM 的服务也是全球化的，从美国给全球服务和从印度给全球服务投有太本质的区别。
#+END_QUOTE

#+BEGIN_QUOTE
不仅仅是 IBM，美国在这次金融危机中实体经济并没有受到太大的打击，原因就是美国各个行业主要的龙头公司都是跨国公司，它们的收入有一半，甚至更多来源于海外。
#+END_QUOTE
* 「水果」公司的复兴：乔布斯和苹果公司

| 1976 | 苹果计算机公司成立                                                  |
|------+---------------------------------------------------------------------|
| 1977 | 发明个人电脑                                                        |
|------+---------------------------------------------------------------------|
| 1984 | 推出采用图像视窗界面操作系统的麦金托什电脑                          |
|------+---------------------------------------------------------------------|
| 1985 | 乔布斯和新 CEO 斯卡利开始权力斗争，前者失败离开苹果公司             |
|------+---------------------------------------------------------------------|
| 1994 | 苹果告微软的视窗撮作系统抄袭它的麦金托什操作系统，官司最终和解      |
|------+---------------------------------------------------------------------|
| 1997 | 乔布斯回到苹果公司，经过权力斗争，接管了多年亏损的公司              |
|      | 和微软的官司以微软注资苹果而得到和解                                |
|------+---------------------------------------------------------------------|
| 1998 | iMac 诞生，苹果重新盈利                                             |
|------+---------------------------------------------------------------------|
| 2001 | iPod 诞生，颠覆了音乐产业                                           |
|------+---------------------------------------------------------------------|
| 2007 | iPhone 诞生，颠覆了整个手机行业                                     |
|------+---------------------------------------------------------------------|
| 2010 | iPad 诞生，同年苹果公司的市值再次超过微软，成为全球最值钱的 IT 公司 |

#+BEGIN_QUOTE
在每一次技术革命中，新技术必须比老的有数量级的进步才能站住脚。
#+END_QUOTE

#+BEGIN_QUOTE
今天，当我们已经习惯了使用交互式图形界面的 Windows 时，如果要我们退回到 DOS，我们会觉得很别扭。麦金托什和 IBM-PC 当年的差别就有 Windows 和 DOS 那么大。

麦金托什的交互式图形窗口界面最早是从施乐（Xerox）公司帕洛阿图（Palo Alto，斯坦福大学所在地）实验室（Parc）研制出来的。帕洛阿图实验室可能是世界上最有创新同时也是最不会将发明创造变成商品的地方。它另一个改变了世界但是没有为施乐带来任何好处的发明是今天每个人都用的以太网。
#+END_QUOTE

#+BEGIN_QUOTE
苹果走了一条封闭的道路，它不允许别人造兼容机，以便独吞 PC 市场。如果苹果开放了麦金托什的硬件技术，允许其他硬件厂商进入市场，我们今天可能使用的就不是 IBM-PC 系列，而是苹果系列了。

两种系列的个人电脑胜负的关键就要看苹果和微软在操作系统上的决斗了。在没有兼容机帮忙的情况下，苹果无法挑战微软，虽然它努力试过，但最终败了下来。

苹果被微软打得一塌糊涂，差点被卖给 IBM 和太阳公司（Sun Microsystems），但这两公司谁也看不上苹果这个市场不断萎缩的 PC 制造商。
#+END_QUOTE

#+BEGIN_QUOTE
既然苹果在微机领域已经不可能替代兼容机和微软的地位了，他干脆往高端发展，讲究性能、品味和时尚。慢慢地，苹果的产品成了时尚的东西。
#+END_QUOTE

#+BEGIN_QUOTE
苹果封闭式的软硬件，从成本上讲，无法和微软加兼容机竞争，也无法为用户提供丰富的应用软件。乔布斯做了两件事，他在苹果的微机中逐渐采用了英特尔的通用处理器，同时采用 FreeBSD 作新的苹果操作系统的内核。这样相对开放的体系使得全社会大量有兴趣的开源工程师很容易地为苹果开发软件。
#+END_QUOTE

#+BEGIN_QUOTE
广大用户已经习惯戴着耳机从播放器中听歌而不是随身带着便携的 CD 唱机和几十张光盘。因此，它不需要花钱和时间培养出一个市场，乔布斯决定开发被称为 iPod 的音乐和录像播放器。
#+END_QUOTE

#+BEGIN_QUOTE
唱片公司和苹果如何分成，当然谁都想多得一些。乔布斯是个非常优秀的谈判高手，他把在价格上最强硬的 Sony 放在最后，他和其它四家公司共同达成了协议，Sony 只好就范，否则就永远被隔离在广大的 iPod 用户群以外。
#+END_QUOTE

#+BEGIN_QUOTE
制造手机本来适合计算机公司无关的，但是随着手机中信号处理的重要性逐渐下降，或者说这些技术难点已经不存在了，打电话的用途在逐渐次要；功能的要求，上网的需求在上升，使得智能手机制造商开始崛起。
#+END_QUOTE
* 计算机工业的生态链

#+BEGIN_QUOTE
摩尔定理（Moore’s Law）：每十八个月，计算机等 IT 产品的性能会翻一番；或者说相同性能的计算机等 IT 产品，每十八个月价钱会降一半。几十年来 IT 行业的发展始终遵循着摩尔定理预测的速度。

2007 年，世界上最快的计算机 IBM 的蓝色基因（BlueGene/L），速度高达每秒钟 367 万亿次浮点运算，是 ENIAC 的 734 亿倍，正好是每 20 个月翻一番，和摩尔定理
的预测大致相同。
#+END_QUOTE

#+BEGIN_QUOTE
存储容量的增长更快，大约每 15 个月就翻一番。十几年来，网络的传播速度也几乎是按摩尔定理预测的速度在增长。
#+END_QUOTE

#+BEGIN_QUOTE
二战后至今，IT 领域的技术进步一直是每一到两年翻一番，至今看不到停下来的迹象。在人类的文明史上，没有任何一个其它行业做到了这一点。因此，IT 行业必然有它的特殊性。
#+END_QUOTE

#+BEGIN_QUOTE
摩尔定理主导着 IT 行业的发展。为了能使摩尔定理成立，IT 公司必须在比较短的时间内完成下一代产品的开发。这就要求，IT 公司在研发上必须投入大量的资金，这使得每个产品的市场不会有太多的竞争者。另外摩尔定律使得各个公司的研发必须针对多年后的市场。
#+END_QUOTE

-----

#+BEGIN_QUOTE
安迪-比尔定理 （Andy and Bill’s Law）：What Andy gives, Bill takes away.

在过去的 20 年里，英特尔处理器的速度每 18 个月翻一番，计算机内存和硬盘的容量以更快的速度在增长。但是，微软的操作系统等应用软件越来越慢，也越做越大。所以，现在的计算机虽然比十年前快了一百倍，运行软件感觉上还是和以前差不多。
#+END_QUOTE

#+BEGIN_QUOTE
现在软件开发人员不再像 20 年前那样精打细算了。当年的 BASIC 解释器是用汇编语言写成的，精炼得不能再精炼了，否则在早期的 IBM-PC 上根本运行不了。

由于有了足够的硬件资源，软件工程师做事情更讲究自己的工作效率，程序的规范化和可读性等等。另外，由于人工成本的提高，为了节省软件工程师写程序和调程序的时间，编程的语言越来越好用，同时效率却越来越低。
#+END_QUOTE

#+BEGIN_QUOTE
各个硬件厂商恰恰是靠软件开发商用光自己提供的硬件资源得以生存。

个人电脑工业整个的生态链是这样的：以微软为首的软件开发商吃掉硬件提升带来的全部好处，迫使用户更新机器让惠普和戴尔等公司收益，而这些整机生产厂再向英特尔这样的半导体厂订货购买新的芯片、同时向 Seagate 等外设厂购买新的外设。

如果微软的开发速度比预期的慢，软件的业绩不好，那么就一定不能买英特尔等公司的股票了。
#+END_QUOTE

#+BEGIN_QUOTE
2008 年后，全世界的手机和移动通信的格局……当年的 WinTel 格局。Android 渐渐起到了当年 Windows 的作用，而高通、博通和 Marvell 基于 ARM 的手机芯片公司起到了当年英特尔和 AMD 的作用。
#+END_QUOTE

-----

#+BEGIN_QUOTE
反摩尔定理 （Reverse Moore’s Law）：一个 IT 公司如果今天和 18 个月前卖掉同样多的、同样的产品，它的营业额就要降一半。
#+END_QUOTE

#+BEGIN_QUOTE
为了赶上摩尔定理预测的发展速度，光靠量变是不够的。每一种技术，过不了多少年，量变的潜力就会被挖掘光，这时就必须要有革命性的创造发明诞生。
#+END_QUOTE

#+BEGIN_QUOTE
在科技进步量变的过程中，新的小公司是无法和老的大公司竞争的，因为后者在老的技术方面有无以伦比的优势。

但是，在抓住质变机遇上，有些小公司会做得比大公司更好而后来居上，因为它们没有包袱，也比大公司灵活。
#+END_QUOTE

#+BEGIN_QUOTE
任何一个技术发展赶不上摩尔定理要求的公司，用不了几年就会被淘汰。大公司们，除了要保持很高的研发投入，还要时刻注意周围和自己相关的新技术的发展，经常收购有革命性新技术的小公司。
#+END_QUOTE
* 奔腾的芯：英特尔公司

| 1968 | 英特尔成立                                                                 |
|------+----------------------------------------------------------------------------|
| 1971 | 开发出英特尔第一个商用处理器 Intel 4004                                    |
|------+----------------------------------------------------------------------------|
| 1978 | 公司开发出 8086 微处理器，成为 IBM-PC 的 CPU                               |
|------+----------------------------------------------------------------------------|
| 1982 | 80286 处理器问世                                                           |
|------+----------------------------------------------------------------------------|
| 1985 | 32 位的 80386 处理器问世                                                   |
|------+----------------------------------------------------------------------------|
| 1986 | 英特尔公司上市                                                             |
|------+----------------------------------------------------------------------------|
| 1987 | 安迪・格罗夫担任英特尔 CEO                                                 |
|      | 英特尔开始了快速发展的 10 年，并且成为全球最大的半导体公司                 |
|------+----------------------------------------------------------------------------|
| 1989 | 定点和浮点处理合一的 80486 处理器问世                                      |
|------+----------------------------------------------------------------------------|
| 1993 | 奔腾系列处理器问世                                                         |
|------+----------------------------------------------------------------------------|
| 2000 | 手机处理器 X-Scale 问世                                                    |
|------+----------------------------------------------------------------------------|
| 2001 | 64 位服务器处理器 Itanium 问世                                             |
|      | 英特尔在服务器市场彻底超越 RISC 的代表太阳公司                             |
|------+----------------------------------------------------------------------------|
| 2005 | 基于 ARM 的处理器占到了智能手机处理器市场的 98%                            |
|      | 英特尔在这个市场明显落后于高通公司和德州仪器公司                           |
|------+----------------------------------------------------------------------------|
| 2006 | 双核处理器问世                                                             |
|      | 英特尔的手机处理器部门 X-Scale 卖给了 Marvell 公司，从此退出手机处理器市场 |
|------+----------------------------------------------------------------------------|
| 2009 | 四核处理器问世                                                             |
|      | 英特尔继续在服务器处理器市场上占优势                                       |

#+BEGIN_QUOTE
英特尔起步的八十年代恰恰是日本的十年，当时日本股市的总市值占了全世界的一半，日本东京附近的房地产总值相当于半个美国的房市总值。世界上最大的三个半导体公司都在日本，PC 里面日本芯片一度占到数量的 60%。

日本的半导体工业集中在技术含量低的芯片上，如存储器等芯片（即内存），而全世界高端的芯片工业，如计算机处理器和通信的数字信号处理器全部在美国。
#+END_QUOTE

#+BEGIN_QUOTE
八十年代，英特尔果断地停掉了它的内存业务，将这个市场完全让给了日本人，从此专心做处理器。1985 年，英特尔公司继摩托罗拉后，第二个研制出 32 位的微处理器 80386，这个芯片的研制费用超过三亿美元，在当时确实是一场豪赌，这笔研制费超过中国当时在一个五年计划中对半导体科研全部投入的好几倍。英特尔靠 80386 完成了对 IBM PC 兼容机机市场一统江湖的伟业。
#+END_QUOTE

#+BEGIN_QUOTE
1993 年，英特尔公司推出奔腾处理器。从奔腾起，英特尔公司不再以数字命名它的产品了，但是在工业界和学术界，大家仍然习惯性地把英特尔的处理器称为 x86 系列。
#+END_QUOTE

-----

#+BEGIN_QUOTE
资金密集型的日本半导体公司终究不可能是技术密集型的英特尔公司的对手。英特尔公司迄今唯一遇到的重量级对手只有八十年代的摩托罗拉。英特尔的崛起是靠击败老牌半导体公司摩托罗拉而实现的。

摩托罗拉之败，首先是外界微软的因素，即英特尔有了微软这个没有签约的同盟军。但是，摩托罗拉自己在商业、管理和市场诸方面也有很多失误。如果摩托罗拉自己经营得当，它今天应该能通过精简指令集的处理器守住工作站和苹果的市场。
#+END_QUOTE

#+BEGIN_QUOTE
英特尔公司则是一的典型的硅谷公司。每个员工的工作强度比摩托罗拉要大很多，但是每个人平均的股票期权也多很多。

美国的历史学家评论中日甲午战争，认为这是两个不同时代军队之间的战争，虽然双方武器相差不多，战争的结果不会有任何悬念，因为一个在专制的农业时代后期的军队很难打赢一个兴起的工业化国家的军队。英特尔和摩托罗拉之间的竞争也是如此。
#+END_QUOTE

#+BEGIN_QUOTE
半导体只是摩托罗拉的一个部门，而微机处理器又只是其半导体部门的一项业务，可是它对于英特尔来讲却是全部。因此，摩托罗拉即使完全退出微机处理器市场也不过是损失一些地盘，而英特尔一旦失败，则会面临灭顶之灾。

一般来讲，华尔街总是希望一个上市公司有尽可能多的而不是单一的收入来源。雅虎有没有可能在搜索领域赶上谷歌，我明确地回答：没有，因为雅虎不可能专注在这个领域。有时，一个好的公司不能完全按华尔街的意愿办事。
#+END_QUOTE

-----

#+BEGIN_QUOTE
当今的计算机系统结构可以根据指令集合分成复杂指令（CISC）和简单指令（RISC）两种。每个处理器的指令集不相同。
#+END_QUOTE

#+BEGIN_QUOTE
采用复杂指令系统的处理器芯片存在主要问题有两个，第一，设计复杂，实现同样的性能需要的集成度高；第二，由于每个指令执行时间不一样长，处理器内部各个部分很难流水作业，处理器会出现不必要的等待。除此之外，还有复杂指令芯片高集成度带来的高功耗。

使用复杂指令集的，包括早期 IBM 和 DEC 的全部计算机，今天的英特尔和 AMD 的处理器等。
#+END_QUOTE

#+BEGIN_QUOTE
八十年代，计算机科学家们提出了基于精简指令集的处理器设计思想。精简指令系统只保留很少的常用指令并将一条复杂的指令用几条简单的指令代替。

基于精简指令集的设计思想是计算机发展史上的一次革命，它使得计算机处理器的设计得到很大简化，同时由于精简指令集的处理器可以保证每条指令执行时间相同，处理器内各部分可以很好地流水作业，处理器速度可以比同时期的基于复杂指令的处理器要来得快。

精简指令集的处理器包括很多工作站的处理器和现在最快的 Sony PS/3 游戏机的微处理器 PS/3-Cell。
#+END_QUOTE

#+BEGIN_QUOTE
英特尔设计 8086 时还没有精简指令的芯片。一旦走上了复杂指令这条不归路，英特尔为了和 8086 完全兼容，在以后的 80286 和 80386 中必须继续使用复杂指令系统。在整个九十年代，工业界只有英特尔一家坚持开发复杂指令集的处理器，对抗着整个处理器工业。

但英特尔可以在每个处理器的开发上投入比任何一种精简指令处理器多的多的研发经费和人力，这样保证了它处理器性能提升得比精简指令还要快。

而在精简指令阵营，九十年代五大工作站厂家太阳、SGI、IBM、DEC 和 HP 各自为战，每家都生产自己的精简指令处理器，加上摩托罗拉为苹果生产的 PowerPC，六家瓜分一个市场，最后谁也做不大、做不好。到了 2000 年前后，各家的处理器都做不下去了，或者全部或者部分地开始采用英特尔的产品了。
#+END_QUOTE

-----

#+BEGIN_QUOTE
由于 IBM 采购的原则是必须有两个以上的公司参加竞标，所以在很长的时间里，Intel 主动让 AMD 将它生产的芯片卖给 IBM 等公司。

在整个九十年代，英特尔和 AMD 虽然打打闹闹但是，它们在开拓 x86 市场，对抗精简指令集的工作站芯片方面利益是一致的。因此它们在市场上的依存要多于竞争。
#+END_QUOTE

#+BEGIN_QUOTE
留着 AMD 对英特尔利大于弊。首先，它避免了反垄断的很多麻烦。其次，留着 AMD 这个对手对英特尔自身的技术进步有好处。柳宗元在他的《敌戒》一文中指出，「秦有六国，兢兢以强；六国既除，訑訑乃亡」。
#+END_QUOTE

-----

#+BEGIN_QUOTE
英特尔公司的商业模式历来是靠大投入大批量来挣钱，同一代的芯片，英特尔的销量可是太阳公司的十倍甚至更多，因此，它可以花几倍于其他公司的经费来开发一个芯片。但是，当一种芯片市场较小时，英特尔公司很难做到盈利。这是它面临的最大问题，这个问题不解决，它很难培养起新的成长点。
#+END_QUOTE

#+BEGIN_QUOTE
虽然在个人微机的市场上，英特尔 x86 系列的处理器在很长的时间内是不可替代的，因为有微软在操作系统中为它保驾。但是在服务器市场却不一定，因为，现在服务器主要的操作系统是开源的 Linux，而 Linux 在什么处理器上都可以运行，因此只要有一种处理器各方面性能明显优于英特尔的，购买服务器的客户就会考虑采用非英特尔的处理器。

在能源紧缺的今天，服务器厂家对处理器最关心的已经不单单是速度，而是单位能耗下的速度。现在，一个酷睿处理器如果昼夜不停使用，一年的耗电量已经等同于它的价格。
#+END_QUOTE

#+BEGIN_QUOTE
平板电脑使用的是基于 RISC 的芯片，更具体地说是 ARM（Advanced RISC Machines）控股公司的产品。ARM 的商业模式是把它的 CPU 设计提供给半导体公司，由后者集成到它们的芯片中。这些芯片都称为基于 ARM（ARM based）的。
#+END_QUOTE

#+BEGIN_QUOTE
IBM 已经垄断了任天堂、索尼和微软三大游戏机的处理器市场，这些采用精简指令处理器的游戏机无论是计算速度，还是图形功能，都已经超过了基于英特尔处理器的个人电脑。
#+END_QUOTE

-----

#+BEGIN_QUOTE
英特尔对世界最大的贡献在于，它证明了处理器公司可以独立于计算机整机公司而存在。英特尔不断地为全世界的各种用户提供廉价的、越来越好的处理器，直接地使个人微机得以普及。
#+END_QUOTE

* IT 业的罗马帝国：微软

#+BEGIN_QUOTE
在整个 IT 领域，微软永远是所有公司最可怕的敌人。微软靠它在操作系统上的垄断地位和无比雄厚的财力在计算机领域几乎是无往不胜。二十几年来，微软作为计算机领域生态链最上层的一个环节一方面刺激着整个计算机领域的发展，另一方面微软扼杀了无数具有创新的大大小小的公司。
#+END_QUOTE

** 双雄会

#+BEGIN_QUOTE
1981 年，在硅谷的苹果公司总部，事业正蒸蒸日上的苹果公司的创始人史蒂夫·乔布斯邀请了刚刚拿下 IBM-PC 操作系统合同的微软公司创始人比尔·盖茨洽谈合作事宜。乔布斯给盖茨看了新设计的麦金托什个人电脑以及漂亮的基于图形界面的操作系统。这种基于图形界面的操作系统比 DOS 不知道强多少倍，使得计算机的操作比以前方便了许多。乔布斯没有意识到操作系统在今后整个微机工业中的重要性，否则他不会过早地给别人看他还没上市的设计。
#+END_QUOTE

#+BEGIN_QUOTE
即使是在高速发展了几年后的 1984 年，微软已经为世界上 80% 微机提供操作系统时，它的营业额不过区区一亿美元。直到 1990 年微软发布 Windows 3.0 并成为软件霸主时，它的营业额才达到苹果同时期的五分之一。乔布斯很难料到比自己小得多的微软以后会威胁到自己。
#+END_QUOTE

#+BEGIN_QUOTE
IBM 有世界上最好的科学家和工程师，他们可以用比你还快的速度将你没有发表的想法实现、申请专利并发表。
#+END_QUOTE

#+BEGIN_QUOTE
计算机工业比任何行业都容易出现垄断公司。乔布斯和盖茨都想做垄断者，但是他们的方式不同。前者是想做原来 IBM 那样的垄断者，从硬件到软件全部垄断，这后来证明是行不通的。而盖茨天才之处在于，他在微机工业刚刚开始的时候，就意识到 _只要垄断了操作系统，就间接垄断了整个行业，因为操作系统和别的软件不同，是在买计算机时预装好的，一般用户没有选择权。_ 所有的应用软件又必须在操作系统下开发。因此，操作系统必然会在自由竞争后，率先出现赢者通吃的垄断局面。二十年前，IBM、微软和苹果三个公司都有垄断微机操作系统的可能性。另外三个公司 Novell、太阳和 Oracle 也有可能从中分到一杯羹。二十年后的结果是微软一家独大。
#+END_QUOTE

** 亡羊补牢

#+BEGIN_QUOTE
免费的 BASIC 和五美元预装的 DOS 其实是微软的一个钓饵，为了吸引软件公司和计算机爱好者在上面开发各种软件，使用户产生对微软的依赖。在众多应用软件公司中，莲花公司（Lotus）的制表软件 1-2-3 最为成功，几乎每台 IBM-PC 微机上都装了一份，这使得在很长的时间里，开发应用软件的莲花公司居然比开发操作系统的微软还大。
#+END_QUOTE

#+BEGIN_QUOTE
DOS 甚至算不上严格意义上的操作系统，它没有操作系统的一些基本功能，比如进程管理。最早的 IBM-PC 因为硬件速度较慢，内存较少，使用 DOS 未尝不可。但是，随着硬件速度的提高，DOS 的问题马上就显示出来了。首先，它不能直接访问 640KB 以上的内存，因为它当时就只是为内存特别小的微处理器设计的。第二，它在任务管理上完全是串行的，像现在一边听歌一边上网这种事在 DOS 上永远做不到。尤其是等到 32 位的处理器 80386 出来，DOS 就大大地限制了硬件性能的发挥。作为技术出身的盖茨很明白这一点，但是他别无选择。在很长一段时间内，微软必须全力推广技术上已经非常落后的 DOS，这样可以争取时间。
#+END_QUOTE

** 人民战争

#+BEGIN_QUOTE
微软最终花了 9 年时间才做好图形界面加鼠标的操作系统视窗，即 Windows 3.0，这期间苹果本来还很有机会，苹果在操作系统上领先微软整整一代，但是，领先下的苹果犯了一个致命的错误——走封闭式道路和纯技术路线。
#+END_QUOTE

#+BEGIN_QUOTE
在微软以前，软件是不能直接挣钱的，因为都是在卖硬件时送给用户的。软件的价值必须通过硬件销售才能体现出来，也许是出于这种考虑，苹果始终坚持软件硬件一起卖。 _苹果拒绝开放麦金托什计算机技术的结果，客观上把所有的想从微机市场分一杯羹的兼容机厂商推给了 IBM 和微软。_ 从 80 年代中期起，世界硬件市场的格局从苹果对 IBM 一下子变成了苹果对 IBM 加上所有的兼容机。开始，苹果这种劣势还不明显，因为它的系列市场占有率还很高。但是由于 IBM-PC 的开放性特点和信息工业全球化的效应，使得 IBM 兼容机越做越便宜，市场占有率越来越高，DOS 在操作系统占有率上便领先于苹果。
#+END_QUOTE

#+BEGIN_QUOTE
苹果另外一个不容忽视的失误就是兼容性。苹果的产品和其它微机不兼容就不用说了，就是它自己内部也不兼容。这样不仅使软件开发商无所适从，更使得用户一遍遍花钱买新的软件。而微软在很长时间里能打的牌就是 DOS 兼容性这一张，有了兼容机厂商和应用软件开发商，更重要是用户的支持，虽然它在长达 9 年的时间里只有 DOS 这个大刀长矛，却靠广大的用户基础占住了脚。
#+END_QUOTE

#+BEGIN_QUOTE
整个计算机工业的规模上万亿美元，绝不是一家公司能吃得下的。诚然在这个领域生态链的不同环节需要垄断，但是各个环节之间需要互相扶持。尤其是在 90 年代以后，整个计算机工业形成这样一种默契，由软件更新带动硬件更新。
#+END_QUOTE

#+BEGIN_QUOTE
1990 年，微软终于迎来了成功的 Windows3.0 和接下来持续使用了很长时间的 Windows 3.1，在短短几个月里，它的销量就超过了 IBM OS/2 多年来的全部销量。Windows 3.1 对苹果的打击是致命的。而苹果当时正处在历史上最混乱的时期，微软终于靠 10 年的人民战争夺得了微机操作系统的统治地位。
#+END_QUOTE

** 帝国的诞生

#+BEGIN_QUOTE
Windows 3.0 使得整个计算机工业的生态链从此定型，而这个生态链的上端是微软。到 1997 年，微软的市值首度超过 IBM，虽然当时微软一年的营业额还不到 IBM 一个季度的，但是华尔街很看好微软，认为它代表着未来。
#+END_QUOTE

#+BEGIN_QUOTE
微软在一统操作系统的天下后，便接连打出三记重拳，干净利落地消灭了莲花、WordPerfect 和网络界新星网景（Netscape），夺得了利润最大的几个应用软件市场。
#+END_QUOTE

#+BEGIN_QUOTE
微软之所以得以控制整个微机行业，在于它控制了人们使用计算机时无法绕过的接口——操作系统。现在，网景控制了人们通向互联网的接口，这意味着如果微软不能将它夺回来，将来在互联网上就会受制于人。网景选择了和微软一拼，因为它觉得至少目前还有技术和市场上的优势。后来证明这种技术上的优势根本不可靠，这也是我将技术排在形成垄断的三个条件之外的原因。
#+END_QUOTE

#+BEGIN_QUOTE
1995 年，仅成立了一年的网景公司就挂牌上市了，在华尔街的追捧下，网景的股票当天从 28 美元涨到 75 美元。同年 11 月，高盛公司将微软的股票从买入下调到持有，微软的股票应声而下。12 月 7 日，日本偷袭珍珠港的日子，盖茨在微软宣布向互联网进军。盖茨把微软当时的处境比成被日本打败的美国舰队。 _盖茨让很多工程师立即停掉手里的工作，全力投入微软浏览器 IE 的开发。_ 盖茨的这种魄力我以后只在佩奇和布林身上又看到过一次，而在世界上找不到第三次。很快，微软的 IE 浏览器就问世了，但是功能上远不如网景的。盖茨动用了他的杀招——和 Windows 捆绑，免费提供给用户。

根据 1994 年微软和美国司法部达成的和解协议，微软同意不在 Windows 上捆绑销售其他的微软软件。但是，盖茨狡辩说 IE 不是一个单独的软件，而是 Windows 的一项功能。网景公司虽然得到了大家普遍的同情，但是，它没有等到法院对微软的裁决结果就支撑不下去了。不久之后，微软又用同样捆绑播放器的办法打败了做媒体浏览器 RealPlayer 的 Real Network 公司。
#+END_QUOTE

** 当世拿破仑

#+BEGIN_QUOTE
盖茨在起家时，包括微软成立后的十几年里，一直惯用冒险的空手套白狼的手法抢的先机。1980 年，盖茨到 IBM 去推广自己开发的 BASIC 解释器，在那里了解到 IBM 需要一种微机操作系统。盖茨从西雅图计算机产品公司 SCP 买下了 DOS，再卖给 IBM 时，只收版权费，不卖源代码。这样盖茨就控制了微机的操作系统。盖茨以后干脆多次打擦边球，仿制甚至抄袭别人的东西，使用这种做法使得微软避免了很多漫无目的的研究和不必要的失败，因为别的公司已经把成功的经验和失败的教训告诉了他。
#+END_QUOTE

#+BEGIN_QUOTE
据不完全统计，微软这些年来为侵权和垄断赔偿了 100 亿美元左右。这个对别人来讲是天文数字的金额对微软来说不过是九牛一毛，它一年的纯利就远比这个数目多得多。
#+END_QUOTE

#+BEGIN_QUOTE
盖茨和他的忘年交投资大师巴菲特做法相同，他们都是要从每一个人身上挣或多或少的一笔钱，而不是从富人身上狠宰一刀了事。世界上最挣钱的汽车公司是生产大众型汽车的丰田公司而不是生产跑车的法拉利和豪华车的劳斯莱斯，事实上后者因为亏损已经被卖给了宝马。巴菲特投资的公司，都是像保洁（P&G）和强生（Johnson & Johnson）这样生产每个人日常要用的东西。
#+END_QUOTE

#+BEGIN_QUOTE
如果想少缴税，而将财产尽可能多地留给孩子，唯一的办法是将财产捐给自己的慈善基金会。这样做可以免除三种税：第一次买股票的资产增值税，遗产税和每年的投资增值税。 _美国法律规定所有的慈善基金会每年必须捐出 5% 的财产，_ 这就是每年盖茨基金会和其他所有慈善基金会都捐出一些钱的原因之一：根据法律他们必须捐。
#+END_QUOTE

#+BEGIN_QUOTE
在美国税收问题上，通常有两种观点，一种认为很多公益的事业，比如公立学校，必须由政府出面才能办成办，因此应该把税收上来交给政府，民主党人大多持这种观点，比如现任总统奥巴马。另一种观点认为，政府办事效率低下，浪费纳税人的钱，甚至回用于不必要的战争，因此应该少缴税，而每个公民各尽所能靠捐助来完成公益事业，共和党人很多持这种观点。
#+END_QUOTE

#+BEGIN_QUOTE
几十年后，当乔布斯和盖茨都去世后，乔布斯个人和家族的影响力可能荡然无存，而盖茨的影响力通过他的基金会，将会薪火相传。
#+END_QUOTE
