#+SETUPFILE: ../../styles/readtheorg.setup
#+TITLE: Methuselah's Children

* 前言

#+BEGIN_QUOTE
一个好故事讲述的主体必须是人，在理性之外还有着非理性一面的人。
#+END_QUOTE

* 如果这样下去（If This Goes On）

#+BEGIN_QUOTE
买羊肉的人和杀羊的人都是同伙。这是洁癖，不是道德：一个支持砍头，却「善良」得不能挥斧子砍头的人；或者一个认为战争无可避免，却因为不想杀人而逃避兵役的人。这是感情上的婴儿，伦理上的懦夫，左手肯定知道右手做的事，而你的心对双手都要负责。

The man who buys the meat is brother to the butcher. It was squeamishness, not morals - like the man who favors capital punishment but is himself too 'good' to fit the noose or swing the axe. Like the person who regards war as inevitable and in some circumstances moral, but who avoids military service because he doesn't like the thought of killing. Emotional infants, ethical morons - the left hand must know what the right hand doeth, and the heart is responsible for both.
#+END_QUOTE

#+BEGIN_QUOTE
「我们的外科医生可以在你身上设下机关，你被绑得再紧也可以想死就死。我要是把胳膊尽力往后弯，这动作只有通过有意识的努力才能做出来，我的肩胛骨之间有个小胶囊就会破掉，但是你在我背上捶打一整天也敲不破它。」

"Our surgeons can booby-trap you so that you can die at will in the tightest bonds anyone can put on you. For example, if I were to cramp my arms backward in a position a man never assumes without very considerable conscious effort, a little capsule between my shoulder blades would rupture and I would make my last report. Yet you could pound me on the back all day and never break it."
#+END_QUOTE

#+BEGIN_QUOTE
成功的革命是桩大买卖。在复杂而高度商业化的现代国家，革命不是一群人在废墟里围着淌泪的烛光密谋出来的。革命需要无数的人员、装备、现代化的机械和武器。要成功地操作这些要素，就必须保证忠诚、机密和绝佳的人员组织。

Successful revolution is Big Business - make no mistake about that. In a modern, complex, and highly industrialized state, revolution is not accomplished by a handful of conspirators whispering around a guttering candle in a deserted ruin. It requires countless personnel, supplies, modern machinery and modern weapons. And to handle these factors successfully there must be loyalty, secrecy, and superlative staff organization.
#+END_QUOTE

#+BEGIN_QUOTE
保密是一切暴政的要旨。不是暴力，而是保密，是审查。不论起初的动机如何神圣，如果任何政府、教会，开始对它的人民说，「这个你不能读，这个你不能看，这个禁止你了解」，其结果就是专制和压迫。控制一个思想被蒙蔽的人几乎不需要暴力；反之，任何暴力都不可能控制一个自由人。你无法征服一个自由人，你顶多只能杀死他。

I began to sense faintly that secrecy is the keystone of all tyranny. Not force, but secrecy ... censorship. When any government, or any church for that matter, undertakes to say to its subjects, 'This you may not read, this you must not see, this you are forbidden to know', the end result is tyranny and oppression, no matter how holy the motives. Mighty little force is needed to control a man whose mind has been hoodwinked; contrariwise, no amount of force can control a free man, a man whose mind is free. No, not the rack, not fission bombs, not anything-you can't conquer a free man; the most you can do is kill him.
#+END_QUOTE

#+BEGIN_QUOTE
「一个组合出来的人，根据伪造的记录和虚假背景细心打造出来的……比如说要转移一个流亡者，匆忙中又找不到与他匹配的真人，所以我们尽量保持多种类的合成人备用。」

"It's a composite personality, very carefully built from faked records and faked backgrounds ... When we have to move a refugee in a hurry, for example, and there is no real person we can match him with. So we try to keep a fairly broad assortment of synthetics built up."
#+END_QUOTE

#+BEGIN_QUOTE
「信息由两个信号词控制，如果没有听到这两个信号词，你不可能想起来的。一个检查员同时猜到这两个词及其排列顺序的几率可以忽略不计。不论清醒还是睡着，你都不可能泄露这个信息。」

"It's keyed to a pair of signal words; you can't possibly remember until they are spoken to you. The chance that an examiner would hit on both words and in the right order is negligible. You can't give the message away, awake or asleep."
#+END_QUOTE

#+BEGIN_QUOTE
「利用人自身的偏见――哪怕是在无关紧要的事情上的偏见――来左右一千个人，都比用逻辑说服一个人容易。一个词的内涵指数是个复杂变量函数，受到语境、听者年龄、性别、职业、所处地点和一大堆其他因素的影响。内涵指数让你知道针对某个特定听众或某一类听众，用某种特定方式说出某个词，会对他产生什么影响。如果能够准确测量受众，其数学精确性可以达到其他工程学分支的高度。」

"You can sway a thousand men by appealing to their prejudices quicker than you can convince one man by logic. It doesn't have to be a prejudice about an important matter either. The index of a word is a complex variable function depending on context, age and sex and occupation of the listener, the locale and a dozen other things. An index is a particular solution of the variable that tells you whether a particular word is used in a particular fashion to a particular reader or type of reader will affect that person favorably, unfavorably, or simply leave him cold. Given proper measurements of the group addressed it can be as mathematically exact as any branch of engineering."
#+END_QUOTE

#+BEGIN_QUOTE
「不让人有性行为，使性变得禁忌和邪恶，仅限于仪式性的繁殖，把性欲压制成为虐待欲，然后给人们一个替罪羊去仇恨，让他们偶尔杀一个替罪羊发泄和放松。这种手段太古老了，远在「心理学」这个词出现之前多少个世纪暴君们就在使用了。」

"Take sex away from people. Make it forbidden, evil, limit it to ritualistic breeding. Force it to back up into suppressed sadism. Then hand the people a scapegoat to hate. Let them kill a scapegoat occasionally for cathartic, release. The mechanism is ages old. Tyrants used it centuries before the word "psychology" was ever invented."
#+END_QUOTE

#+BEGIN_QUOTE
人的思想极度复杂，其中有些部分连自己也不知晓。

The human mind is a tremendously complex thing; it has compartments in it that its owner himself does not suspect.
#+END_QUOTE

#+BEGIN_QUOTE
「我的宗教信仰是我和我的上帝之间的私事，我拒绝解释和证明它们的正确性。我认为人在必要的时候应改为了兄弟牺牲。但是我不要证明这其中任何一点：它们不需要证明。我也不要求你相信和我一样的东西。」

"My religious faith is a private matter between me and my God. I decline to explain them nor to justify them to you. I think that a man is obliged to lay down his life for his brothers, should it be required of him. But I don't propose to prove any of those things; they are beyond proof. And I don't demand that you believe as I do."
#+END_QUOTE

#+BEGIN_QUOTE
「读你写的那堆玩意儿的心理数学家对于你个人一点儿兴趣也没有，他们甚至都不想知道你是谁。一个姑娘会先看完你的报告，删除所有的名字，包括你本人的，用数字代替，这些都在分析师看报告之前完成。你不过是数据而已。」

"The psychomathematicians who will read that mess of bilge you will write, won't have the slightest interest in you as an individual. They don't even want to know who you are. A girl goes through your report and deletes all personal names, including your own, and substitutes numbers ... all this before an analyst sees it. You're just data, that's all. "
#+END_QUOTE

#+BEGIN_QUOTE
和革命相比，战争真是件简单的事。战争是一种应用科学，其原理清晰而历经考验。武器从投石器进化到了氢弹，战略却并无太大变化。革命却都是非正常状态，是一种畸形的突变，其条件绝不重复，行动执行者又都是业余人士和个人主义者。

War is a simple matter compared with revolution. War is an applied science, with well-defined principles tested in history; analogous solutions may be found from ballista to H-bomb. But every revolution is a freak, a mutant, a monstrosity, its conditions never to be repeated and its operations carried out by amateurs and individualists.
#+END_QUOTE

#+BEGIN_QUOTE
决定独裁者实力的并不是枪炮，而是民众对他的信仰，凯撒、拿破仑和希特勒全都如此。

In essence, a dictator's strength depends not upon guns but on the faith his people place in him. This had been true of Caesar, of Napoleon, of Hitler, of Stalin.
#+END_QUOTE

#+BEGIN_QUOTE
人们只相信自己愿意相信的东西，与逻辑无关。他们愿意相信从小在妈妈膝下学到的古老信仰，这会让他们的心灵重获安全感。

People believe what they want to believe and logic has no bearing on it. They wanted to believe in their old time religion as they learned it at their mothers' knees; it restored security to their hearts.
#+END_QUOTE

#+BEGIN_QUOTE
「自由的人不是靠「调节」出来的！自由的人之所以自由，是因为他们脾气坏，固执己见，自己坚持自己那一套，而不是让自命不凡的操纵者来喂给他们！」

"Free men aren't "conditioned"! Free men are free because they are ornery and cussed and prefer to arrive at their own prejudices in their own way - not have them spoon-fed by a self-appointed mind tinkerer!"
#+END_QUOTE
* 考文垂（Coventry）

#+BEGIN_QUOTE
「就算一个人故意伤害了他人，政府也无意于做到的审判，或者予以惩罚。我们没有足够的智慧，而且这样的道德强制总会引发一系列不公正的后果，对所有人的自由造成威胁。对我们的生活方式你可以有自己的审美判断，也可以表达你的看法，但你不能期望我们为了符合你的口味而改变生活方式。你可以如你所愿地寻求危险和冒险，但是你不能随便让我们面对你的暴力倾向。」

"Even if one should willfully and knowingly damage another, the state does not attempt to sit in moral judgment, nor to punish. We have not the wisdom to do that, and the chain of injustices that have always followed such moralistic coercion endanger the liberty of all. You are free to hold and express your esthetic opinion of our way of living, but you must not expect us to live to suit your tastes. You are free to seek danger and adventure if you wish, but you are not free to expose us to the violence of your nature."
#+END_QUOTE

#+BEGIN_QUOTE
「我同意你对于这个人的感觉和判断，而且从个人角度来说，对你打了他一拳感到很高兴。但你的心理测量显示，你认为自己可以对与你同样的公民进行道德判断，并且有理由对他们的过失进行纠正与惩罚。你是个危险人物，因为我们无法预计你将会造成什么样的损害。」

"I agree with your esthetic judgment of that individual, and am personally rather gratified that you took a punch at him. But your psychometrical tests show that you believe yourself capable of judging morally your fellow citizens and feel justified in personally correcting and punishing their lapses. You are a dangerous individual, for we can not predict whet damage you may do next."
#+END_QUOTE

#+BEGIN_QUOTE
这辆钢制龟甲车让麦金纳感觉自己和鲁滨逊一样自由。他并没意识到自己的运载工具是成百上千人智力合作和不断努力的结果。过去他的天赋都表现在文学批评而非工程技术上，但他还是相信只靠他的天生智慧，加上基本参考书的帮助，他就能够在必要时再造出一辆龟甲车。他知道他需要金属矿石，但他并不觉得这是什么障碍，因为他不知道自己对于勘探、采矿和冶炼跟对驴子一样无知。

The steel tortoise gave MacKinnon a feeling of Crusoe-like independence. It did not occur to him his chattel was the end product of the cumulative effort and intelligent co-operation of hundreds of thousands of men, living and dead. His talents had been devoted in the past to literary criticism rather than engineering, but that did not prevent him from believing that his native intelligence and the aid of a few reference books would be all that he would really need to duplicate the tortoise, if necessary. Metal ores were necessary, he knew, but saw no obstacle in that, his knowledge of the difficulties of prospecting, mining, and metallurgy being as sketchy as his knowledge of burros.
#+END_QUOTE

#+BEGIN_QUOTE
他对法律程序的依赖貌似和他最近刚抛弃了对政府的信任之一行为不太相称，他可以咒骂那个羞辱他的法庭，但他却认为法庭应该公正。

His dependence on judicial procedure may appear inconsistent in view of how recently he had renounced all reliance on organized government. He could curse the court that had humiliated him, but he expected courts to dispense justice.
#+END_QUOTE

#+BEGIN_QUOTE
「你打断了他的鼻子，可是他却根本没有伤害你。他嘴里发出了点噪声，给你贴了个标签。如果这个标签不符合你的实际情况，这噪声就没有意义。如果对你来说这标签正确，你就不会因为有人念出这个标签而多出一点，或者少一点。简单地说，他没有伤害你。」

"You broke his nose, yet he had done you no harm of any sort. He made a noise with his mouth - a verbal label. If the label does not fit you, the noise is meaningless. If the label is true in your case, you are neither more, nor less, that thing by reason of some one uttering the verbal label. In short, he did not damage you."
#+END_QUOTE

#+BEGIN_QUOTE
「从你对那句辱骂的语义学反应来看，你和烧死女巫的狂热者们一样疯狂。」

"From the viewpoint of your semantic reactions you are as socially unsane as any fanatic witch burner."
#+END_QUOTE

#+BEGIN_QUOTE
革命者们希望最大限度地保证个人自由。首先，他们抛弃了「公平」这个概念。从语义学上检视，「公平」没有任何指标，在连续的时间-空间-物质组合中没有任何能被观察到的现象，可以被指出来说：「这就是公平。」科学只能处理可以观察和测量的事物，「公平」不是这样的事物，它对于每个人的含义都不一样，关于它的任何「杂音」都会增加混乱。但是伤害，无论是身体上的还是经济上的，都可以指出并测量。

The revolutionists wished to establish maximum personal liberty. First they junked the concept of "justice". Examined semantically "justice" has no referent - there is no observable phenomenon in the space-time-matter continuum to which one can point, and say, "This is justice." Science can deal only with that which can be observed and measured. Justice is not such a matter; therefore it can never have the same meaning to one as to another; any "noises" said about it will only add to confusion. But damage, physical or economic, can be pointed to and measured.
#+END_QUOTE
* 不合群的人（Misfit）

#+BEGIN_QUOTE
「咱们就来点真空吸尘。」气密门外门开了大概五分钟，再打开的时候衣服都干透了，宇宙真空带走了所有的水汽，那些讨厌的呕吐物只剩下一堆无菌粉末。

"We'll just give them a dose of vacuum." This time the lock was left closed for about five minutes. When the lock was opened the garments were bone dry - all the moisture boiled out by the vacuum of space. All that remained of the unpleasant rejecta was a sterile powdery residue.
#+END_QUOTE

* 关于那些从未写出的故事

#+BEGIN_QUOTE
曾经发展成熟的太空旅行会被废弃。想想一千年前维京人的远航和他们在北美建立过的殖民地。他们的努力毫无结果，哥伦布及其后来人只能从头开始。太空旅行在近期恐怕只是个因军事目的而得到资助的无足轻重的计划，这个计划可能会渐渐被取消，然后通过新的技术，在新的经济和政治压力下复苏。
#+END_QUOTE

#+BEGIN_QUOTE
如果拥有了足够的政治力量，几乎每一种教派、秘密团体都会将自己的教义变成法律，然后压制反对意见，操纵教育以尽早控制年轻人的思想，将所有异端杀害、关押或者逼入地下。这就是信徒必尽的责任，「正确信仰」的守护者不可能把容忍异端看成美德。
#+END_QUOTE

#+BEGIN_QUOTE
人类思想接受谬论并且用暴力压制的手段将其推进的能力到底有多大，至今尚无人知晓。
#+END_QUOTE

* 玛士撒拉之子（Methuselah's Children）

#+BEGIN_QUOTE
「个人都是和善而正派的――在作为个体，对待其他个体时。伊芙的邻居和朋友对她没有威胁，我的邻居和朋友对我也没有。但我的邻居和朋友对她而言就是威胁，她的对我也一样。群体心理并不是简单的个人心理总和，这是社会群体行为规则，也就是暴民狂热定律。在表达它的数学公式产生前很久，军事、政治和宗教领袖，广告人、先知、煽动者、演员和黑帮领袖都利用过它。」

"Individuals are kind and decent - as individuals and to other individuals. Eve is in no danger from her neighbors and friends, and I am in no danger from mine. But she is in danger from my neighbors and friends, and I from hers. Mass psychology is not simply a summation of individual psychologies; that is a prime theorem of social psychodynamics. It is the social mass-action rule, the mob-hysteria law, known and used by military, political, and religious leaders, by advertising men and prophets and propagandists, by rabble rousers and actors and gang leaders, for generations before it was formulated in mathematical symbols."
#+END_QUOTE

#+BEGIN_QUOTE
「生活经历是线性叠加的，但记忆之间的关联却是无限扩张的。人要是能活上一千年，就必须得发明一种全新的记忆关联方法，才能够进行有效记录；否则，人只能无助地面对自己丰富的知识却无法利用，要么发疯，要么变成弱智。」

"Life experience is linearly additive, but the correlation of memory impressions is an unlimited expansion. If mankind lived as long as a thousand years, it would be necessary to invent some totally different method of memory association in order to be eclectively time-binding. A man would otherwise flounder helplessly in the wealth of his own knowledge, unable to evaluate. Insanity, or feeble-mindedness."
#+END_QUOTE

#+BEGIN_QUOTE
当人民专注于一件事而忘记其他，这就是无赖、煽动人心的政客和野心家最好的时机。

Whenever the citizens fix their attention on one issue to the exclusion of others, the situation is ripe for scalawags, demagogues, ambitious men on horseback.
#+END_QUOTE

#+BEGIN_QUOTE
「对我来说，死亡之所以可以忍受，只因为死亡是最大的民主，对所有人都同等对待。」

"Death has been tolerable to me only because Death has been the Great Democrat, treating all alike."
#+END_QUOTE

#+BEGIN_QUOTE
文化与文化之间不可能永远隔离，而当它们接触的时候，强者就会取代弱者，这是自然规律。

Cultures could not be kept apart forever, and when they did come in contact, the hardier displaced the weaker; that was a natural law.
#+END_QUOTE

#+BEGIN_QUOTE
「新疆域号」没有反应容器，它的转换器可以采用任何物质，将之转换为纯辐射能。任何东西都可以：宇宙尘、物质回收场收集到的零散原子，或者船上产生的任何东西，比如垃圾、尸体、舱板上的尘土，什么都可以。物质即能量。每克质量的消亡都发出九亿亿尔格的推进力。

The New Frontiers had no tanks; her converter accepted any mass at all, turned it into pure radiant energy. Anything would serve - meteors, cosmic dust, stray atoms gathered in by her sweep field, or anything from the ship herself, such as garbage, dead bodies, deck sweepings, anything at all. Mass was energy. In dying, each tortured gram gave up nine hundred million trillion ergs of thrust.
#+END_QUOTE

#+BEGIN_QUOTE
只有但丁才能描述十万人同时晕船呕吐的情形。

Free-fall nausea, likes seasickness, is a joke only to those not affected; it would take a Dante to describe a hundred thousand cases of it.
#+END_QUOTE

#+BEGIN_QUOTE
「在朝向太阳的那面，我们看到的是被拉长到可见光区的短谱辐射；在反面，我们看到的是蓝移到可见光区的无线电波。」

"Over on that side, toward the Sun, we're seeing by short radiations stretched to visibility. On the opposite side we're picking up something around radio wavelengths dopplered down to light."
#+END_QUOTE

#+BEGIN_QUOTE
「因果律和真实世界毫无关系。事实即存在。因果律只不过是科学出现之前的一种过时的哲学假设。」

"Causality has nothing to do with the real plenum. A fact simply is. Causality is merely an old-fashioned-postulate of a pre-scientific philosophy."
#+END_QUOTE

#+BEGIN_QUOTE
「一个主张的真实性与其在心理动力学上的影响力几乎或完全不相关。「真理必胜」的说法只不过是个良好愿望，历史上的现实并非如此。」

"The truth of a proposition has little or nothing to do with its psychodynamics. The notion that 'truth will prevail' is merely a pious wish; history doesn't show it."
#+END_QUOTE

#+BEGIN_QUOTE
他们现在「看」东西是通过电子显示。对于人眼来说，他们身后的半球一片黑暗，连最短波的辐射都已经红移到肉眼不可见的长波范围。前方的星星还能看见，但其实是波长最长的电磁波，被飞船本身的高速压缩成为可见「光」；本来暗淡的「射电星」现在是一等亮星；那些发出的电波波长较短的星星都已经看不清楚。熟悉的星座都变成了难以辨认的形状。

They were "seeing" now only by electronic vision. To the human eye itself the hemisphere behind them along their track was a vasty black; the shortest radiations had dopplered to wavelengths too long for the eye. In the forward direction stars could still be seen but their visible "light" was made up of longest Hertzian waves crowded in by the ship's incomprehensible speed. Dark "radio stars" shined at first magnitude; stars poor in radio wavelengths had faded to obscurity. The familiar constellations were changed beyond easy recognition.
#+END_QUOTE

#+BEGIN_QUOTE
她正在照顾被称为「霍金斯太太」的永生鸡心组织。「霍金斯太太」比所有的家族成员都老；在二十世纪，诸家族从洛克菲勒学院获得了一些原始组织，这些组织培育于二十世纪早期，到现在已经有两个多世纪了，「霍金斯太太」依然鲜活如新。

... found her servicing the deathless tissue of chicken heart known to the laboratory crew as "Mrs. 'Avidus." Mrs. 'Avidus was older than any member of the Families; she was a growing piece of the original tissue obtained by the Families from the Rockefeller Institute in the twentieth century, and the tissues had been alive since early in the twentieth century even then ... alive for more than two centuries now ... and still Mrs. 'Avidus flourished.
#+END_QUOTE

#+BEGIN_QUOTE
「鲤鱼似乎不会死。它们要么是被杀死，要么被吃掉，要么被饿死，要么死于感染，但就我们所知，它们自己死不了。我觉得长生不死和它们永不停止生长肯定有关。」

"Carp don't seem to die. They get killed, or eaten, or starve to death, or succumb to infection, but so far as we know they don't die. I think it has to do with the fact that they never stop growing."
#+END_QUOTE

#+BEGIN_QUOTE
「阿米巴虫也不会死。现在活着的每只阿米巴虫都已经活了大概五千万年了。它们不会死，只会不断分裂，一直活下去。」

"Amoebas don't die. Every amoeba now alive has been alive for fifty million years or so. They don't die. They just twin and keep on living."
#+END_QUOTE

#+BEGIN_QUOTE
一座城市，不管什么样的城市，都具有一定的实际功能：居住、饮食、卫生、通讯。这些主要需求由不同的生物在不同的环境下实现，会有无数种结果，但假使由任何一种呼吸氧气的类人恒温动物在特定环境下实现，结果就算再古怪，地球人也仍然可以使用。

A city, any city, is a machine to accomplish certain practical ends: shelter, food supply, sanitation, communication; the internal logic of these prime requirements, as applied by diiferent creatures to different environments, will produce an unlimited number of answers. But, as applied by any race of warm-blooded, oxygen-breathing androidal creatures to a particular environment, the results, although strange, are necessarily such that Terran humans can use them.
#+END_QUOTE

#+BEGIN_QUOTE
没有空间参照哪有时间？时间和空间本是一体，密不可分……肯定有飞船时间，飞船上的时钟有的滴答作响，有的嗡嗡作响，有的只是无声转动；人们会饿，会吃饭，会累，会睡觉。同位素会衰变，物理化学过程会朝向熵增的方向前进，他的意识也能感受到时间。可在人类历史上用来测量所有时间函数的星空背景却消失了。

What is time without a space reference? Time and space, inseparable and one ... there necessarily was ship's time. Clocks in the ship ticked or hummed or simply marched; people grew hungry, fed themselves, got tired, rested. Radioactives deteriorated, physio-chemical processes moved toward states of greater entropy, his own consciousness perceived duration. But the background of the stars, against which every timed function in the history of man had been measured, was gone.
#+END_QUOTE

#+BEGIN_QUOTE
他没有机会获取大量测量数据；任何严格遵从认识论的诚实的科学家都只能记录下这个事实，并注明理论无法解释。

There had been no opportunity to obtain significant data, measured data; the best that any honest scientist could do, with epistemological rigor, was to include a note that recorded the fact and stated that it was unexplained.
#+END_QUOTE

#+BEGIN_QUOTE
「地球上现在是哪年？」
「我不知道怎么回答这个问题。就好像问「多高才算是上面？」」
「我知道时间是相对的，同时性只对同一个结构中足够近的两点适用。但我还是想知道，我们比以前任何人都走得更快更远？我们的时间不会慢下来或者怎样吗？」
利比的表情万分困惑，数学物理学家每次听到普通人试图用非数学的语言讨论物理时都是这种表情。「你说的是洛伦兹-菲茨杰拉德收缩。不过，请原谅，任何人用语言来表达这件事都毫无意义。这个所谓的收缩作用，其表达式假设观察者自身也处于现象之中，然而，口语中隐含的假设是我们可以置身事外进行观察，但数学语言否定了这种外界观察点存在的可能性。每个观察者都有自己的世界线，他无法置身世界线之外观察。」
「当两个事件在一个连续统一体中分别发生时，是无法用任何绝对的方式来测量时间的。你只能测量时间区间。」
「我可以把表达式写出来，但是没法用语言说清楚。你能够把一整部交响乐的所有乐谱用语言写下来吗？就算这样音乐家还是无法演奏，除非再转换回音乐符号。我说语言不合适的时候，就是这个意思。」
「这没法用语言表达，惯性不是一个词；它是一个数学概念，在一个充满物质的空间的某些方面有数学适用性。我说不出来。」

"What year is it back on Earth?"
"I don't know how to answer that question. It's like saying, 'How high is up?'"
"I did gather the idea that time is relative and simultaneity is an idea which applies only to two points close together in the same framework. But just the same, I want to know something. We've traveled a lot faster and farther than anyone ever did before. Don't our clocks slow down, or something?"
Libby got that completely baffled look which mathematical-physicists wear whenever laymen try to talk about physics in nonmathematical language. "You're referring to the Lorentz-FitzGerald contraction. But, if you'll pardon me, anything one says about it in words is necessarily nonsense. The formulae used to describe the effect loosely called a contraction presuppose that the observer is part of the phenomenon. But verbal language contains the implicit assumption that we can stand outside the whole business and watch what goes on. The mathematical language denies the very possibility of any such outside viewpoint. Every observer has his own world line; he can't get outside it for a detached viewpoint."
"There is no way to measure time in any absolute sense when two events are separated in a continuum. All you can measure is interval."
"I can write down formulae about it and show you how we use it, but it can't be defined in words. Can you write the score for a full orchestration of a symphony in words? And musicians still could not play it until you put it back into musical notation. That's what I meant when I said that the language was inappropriate."
"Inertia isn't a word; it is a mathematical concept used in mathematically certain aspects of a plenum. I was stuck."
#+END_QUOTE

#+BEGIN_QUOTE
……指定将自己的钱用来延长人类寿命。信托管理者们没有别的办法实现他的遗愿，只能去寻找那些家族里表现出了天生的长寿倾向的人，然后诱使他们和同样的人生育后代。

... commanded that his money be used to lengthen human life. The administrators of the trust found no way to carry out his wishes other than by seeking out persons whose family trees showed congenital predispositions toward long life and then inducing them to reproduce in kind.
#+END_QUOTE

#+BEGIN_QUOTE
这些问题从猿人产生自我意识开始，就不断地困扰着他的种族，他们吃饱了饭，还造出了精致的机器，还是没能解决这个问题。祖先们对灵魂的追求始终无果，这漫长的宁静岁月也并没有给他最终的答案。

... problems that had made sad the soul of his breed since the first apeman had risen to self-awareness, questions never solved by full belly nor fine machinery. And the endless quiet days did no more to give him final answers than did all the soul searchings of his ancestors.
#+END_QUOTE

#+BEGIN_QUOTE
她面对永恒的生死问题，既没有选择生，也没有选择死…却选择了失去自我。

Faced with the eternal problem of life and death, she had escaped the problem by choosing neither ... selflessness.
#+END_QUOTE

#+BEGIN_QUOTE
「这是个超人。它的躯体结构经过重新设计，效能更高，我们那些无用的猿类遗传特征被清除掉了，它的器官也都重新排列，位置更加得当。你也不能说它不是人，它是…改进版。」

"It's sort of a superman. Its body architecture has been redesigned for greater efficiency, our useless simian hangovers have been left out, and its organs have been rearranged in a more sensible fashion. You can't say it's not human, for it is ... an improved model."
#+END_QUOTE

#+BEGIN_QUOTE
那些行星组成了一只有九根指针的钟。所有行星的周期都不完全相等，每一天，这些「指针」都有一个独特的构型。海王星的周期和冥王星极端不同，两者的相对位置七百五十八年才大致重复一次。这只大钟可以给出任何时期任何精度的读数，只是不容易辨认。

The planets themselves make a clock with nine hands. For any date there is a unique configuration of those "hands" since no planetary period is exactly commensurate with another. Neptune's period is so cantankerously different from that of Pluto that the two fall into approximately repeated configuration only once in seven hundred and fifty-eight years. The great clock can be read with any desired degree of accuracy over any period - but it is not easy to read.
#+END_QUOTE

#+BEGIN_QUOTE
知识本身并不能赢得战争。欧洲中世纪那些无知的宗教狂人打败了成就远高于他们的伊斯兰文化；阿基米德被一个普通士兵打死；野蛮人洗劫了罗马。

Knowledge alone did not win wars. The ignorant fanatics of Europe's Middle Ages had defeated the incomparably higher Islamic culture; Archimedes had been struck down by a common soldier; barbarians had sacked Rome.
#+END_QUOTE

#+BEGIN_QUOTE
「衰老主要是代谢过程中有毒废物的积累，血液会把它们运走，但后来血液里毒素太多，清理过程就无法正常进行。」
「问题在于扩散压逆差。细胞在血液一面的扩散压力差必须能够维持一个很高的浓度梯度，否则细胞就会产生越来越严重的自体中毒。保证废物的正常清理从而抵挡死亡的基本观念早就有了，我手头有点鸡心组织，靠同样的技术已经活了两个半世纪。」

"Old age is primarily a matter of the progressive accumulation of the waste poisons of metabolism. The blood is supposed to carry them away, but presently the blood gets so clogged with the poisons that the scavenging process doesn't take place properly."
"It's a matter of diffusion pressure deficit - the d.p.d. on the blood side of a cell wall must be such as to maintain a fairly sharp gradient or there will occur progressive autointoxication of the individual cells. The basic idea of holding off death by insuring proper scavenging of waste products is not new - I have a bit of chicken heart which has been alive for two and one half centuries through equivalent techniques."
#+END_QUOTE

#+BEGIN_QUOTE
「人类，我们这样的人类，地球人，从来没有足够的时间去研究那些重要的问题。我们有很多能力，却没有足够的时间去正确使用。在那些重要的问题上，我们可能还只是猴子。不过我可以告诉你，不管答案是什么，只要树还没有倒下去，这只猴子就会一直往上爬，一直四处张望，去看所有它能看到的东西。」

"Men - our kind of men - Earth men - never have had enough time to tackle the important questions. Lots of capacity and not time enough to use it properly. When it came to the important questions we might as well have still been monkeys. But I can tell you this, whatever the answers are, here's one monkey that's going to keep on climbing, and looking around him to see what he can see, as long as the tree holds out."
#+END_QUOTE
