#+setupfile: ../../styles/readtheorg.setup
#+title: Seven Brief Lessons on Physics

* 目录

| 第一课 | 最美的理论           | The Most Beautiful of Theories                |
|--------+----------------------+-----------------------------------------------|
| 第二课 | 量子                 | Quanta                                        |
|--------+----------------------+-----------------------------------------------|
| 第三课 | 宇宙的构造           | The Architecture of the Cosmos                |
|--------+----------------------+-----------------------------------------------|
| 第四课 | 粒子                 | Particles                                     |
|--------+----------------------+-----------------------------------------------|
| 第五课 | 空间的颗粒           | Grains of Space                               |
|--------+----------------------+-----------------------------------------------|
| 第六课 | 概率、时间和黑洞的热 | Probability, Time and the Heat of Black Holes |
|--------+----------------------+-----------------------------------------------|
| 尾声   | 我们                 | In closing: Ourselves                         |

* 第一课

#+begin_quote
牛顿想象物体是在空间中运动的，他认为空间是一个巨大的空容器，所有物体都在其中做直线运动，直到有一个力使它们的轨道发生弯曲。至于「空间」，或者说这个容纳世界的容器是由什么做成的，牛顿也没有给出答案。法拉第和麦克斯韦为牛顿冰冷的世界添加了新鲜的内容：电磁场。

Newton imagined that bodies moved through space, and that space was a great empty container, through which all objects ran true until a force obliged their trajectory to curve. What this "space" was made of, this container of the world he invented, Newton could not say. Michael Faraday and James Maxwell, had added a key ingredient to Newton's cold world: the electromagnetic field.
#+end_quote

#+begin_quote
爱因斯坦想到，就像电力一样，引力一定也是由一种场来传播的，一定存在一种类似于「电场」的「引力场」，他产生了一个非同凡响的想法： _引力场不「弥漫」于空间中，它就是空间本身。_ 这就是广义相对论的思想。这是一个惊世骇俗的理论，对宇宙做了惊人的简化： _空间不再是一种有别于物质的东西，而是构成世界的「物质」成分之一，一种可以波动、弯曲、变形的实体。_

Einstein came to understand that gravity, like electricity, must be conveyed by a field as well: a "gravitational field" +analogous to+ the "electrical field" must exist. An extraordinary idea occurred to him: the gravitational field is not diffused through space; the gravitational field is that space itself. This is the idea of the theory of general relativity. It's a momentous simplification of the world: space is no longer something distinct from matter, it is one of the "material" components of the world. An entity that undulates, flexes, curves, twists.
#+end_quote

#+begin_quote
如何描述这种空间的弯曲呢？19 世纪最伟大的数学家、「数学王子」卡尔·弗里德里希·高斯已经写出了描述二维曲面（比如小山丘的表面）的公式。他还让自己的得意门生将这一理论推广到三维乃至更高维的曲面。这位学生就是波恩哈德·黎曼，他就此问题写了一篇重量级的博士论文，但当时看起来全然无用。黎曼论文的结论是，任何一个弯曲空间的特征都可以用一个数学量来描述，如今我们称之为「黎曼曲率」，用大写的「R」来表示。后来爱因斯坦也写了一个方程，将这个 R 与物质的能量等价起来，也就是说：空间在有物质的地方会发生弯曲。

How can we describe this curvature of space? The most outstanding mathematician of the nineteenth century, Carl Friedrich Gauss, the so-called "prince of mathematicians", had written mathematical formulae to describe two-dimensional undulating surfaces, such as the surfaces of hills. Then he had asked a gifted student of his to generalize the theory to encompass spaces in three or more dimensions. The student in question, Bernhard Riemann, had produced an impressive doctoral thesis of the kind that seems completely useless. The conclusion of Riemann's thesis was that the properties of a curved space are captured by a particular mathematical object which we know today as Riemann's curvature, and indicate with the letter "R". Einstein wrote an equation which says that R is equivalent to the energy of matter. That is to say: space curves where there is matter.
#+end_quote

* 第二课

#+begin_quote
量子力学正好诞生于 1900 年，它几乎引领了整整一个世纪的密集思考。德国物理学家马克斯·普朗克计算了一个「热匣子」内处于平衡态的电磁场。为此他用了一个巧妙的方法：假设电磁场的能量都分布在一个个的「量子」上，这个方法计算出的结果与测量得到的数据完全吻合，但却与当时人们的认知背道而驰，因为当时人们认为能量是连续变动的。对于普朗克来说，把能量视为一个个能量包块的集合只是计算上使用的一个特殊策略，就连他自己也不明白为什么这种方法会奏效。然而五年以后，又是爱因斯坦，终于认识到这些「能量包」是真实存在的。

It's said that quantum mechanics was born precisely in the year 1900, virtually ushering in a century of intense thought. The German physicist Max Planck calculated the electric field in equilibrium in a hot box. To do this he used a trick: he imagined that the energy of the field is distributed in "quanta", that is, in packets or lumps of energy. The procedure lead to a result which perfectly reproduced what was measured but clashed with everything that was known at the time. Energy was considered to be something which varied continuously. To treat energy as if it were made up of finite packages had been, for Planck, a peculiar trick of calculation, and he did not himself fully understand the reason for its effectiveness. It was to be Einstein once again who, five years later, came to understand that the "packets of energy" were real.
#+end_quote

#+begin_quote
1925 年，量子理论的方程终于出现了，取代了整个牛顿力学。很难想象什么比这更伟大的成就了。霎时间，一切现象都找到了归宿，一切都可以被计算出来。为什么元素周期表的结构是这样的？为什么这些元素和周期会有这样的特征？答案就是， _每一种元素都是量子力学最主要方程的一个解。整个化学学科都基于这一个方程。_

In 1925 the equations of the theory finally appeared, replacing the entire mechanics of Newton. It's difficult to imagine a greater achievement. At one stroke, everything makes sense, and you can calculate everything. Why does the periodic table have this particular structure, with these periods, and with the elements having these specific properties? The answer is that each element corresponds to one solution of the main equation of quantum mechanics. The whole of chemistry emerges from a single equation.
#+end_quote

#+begin_quote
量子力学的方程以及用它们得出的结果每天都被应用于物理、工程、化学、生物乃至更广阔的领域中。量子力学对于当代科技的整体发展有着至关重要的意义。没有量子力学就不会出现晶体管。然而一个世纪过去了，我们还停在原点。这些方程仍然十分神秘，因为它们并不描述在一个物理系统内发生了什么，而只说明一个物理系统是如何影响另外一个物理系统的。

The equations of quantum mechanics and their consequences are used daily in widely varying fields: by physicists, engineers, chemists and biologists. They are extremely useful in all contemporary technology. Without quantum mechanics there would be no transistors. Yet a century later we are at the same point. They remain mysterious for they do not describe what happens to a physical system, but only how a physical system affects another physical system.
#+end_quote
* 第四课

#+begin_quote
我们身边的所有物体都是由电子、夸克、光子和胶子组成的，它们就是粒子物理学中所讲的「基本粒子」。除此之外还有几种粒子，例如中微子——它布满了整个宇宙，但并不跟我们发生交互作用，和希格斯玻色子——不久前日内瓦欧洲核子研究中心的大型强子对撞机发现的粒子。

Electrons, quarks, photons and gluons are the components of everything that sways in the space around us. They are the "elementary particles" studied in particle physics. To these particles a few others are added, such as the neutrinos which swarm throughout the universe but have little interaction with us, and the "Higgs bosons" recently detected in Geneva in CERN's Large Hadron Collider.
#+end_quote

#+begin_quote
量子力学描述了这些粒子的性质和运动方式。这些粒子并不像小石子那般真实可感，而是相应的场的「量子」，比方说光子是电磁场的「量子」。就跟在法拉第和麦克斯韦的电磁场中一样，它们是这些变化的基底场中的元激发，是极小的移动的波包。它们的消失和重现遵循量子力学的奇特定律： _一切存在的东西都是不稳定的，永远都出在从一种相互作用跃迁到另一种相互作用的过程中。_ 彻底的虚空是不存在的，就像最平静的海面，我们凑近看还是会发现细微的波动和振荡。 _构成世界的各种场也会轻微地波动起伏，我们可以想象，组成世界的基本粒子在这样的波动中不断地产生、消失。_

The nature of these particles, and the way they move, is described by quantum mechanics. These particles do not have a pebble-like reality but are rather the "quanta" of corresponding fields, just as photons are the "quanta" of the electromagnetic field. They are elementary excitations of a moving substratum similar to the field of Faraday and Maxwell. Minuscule moving wavelets. They disappear and reappear according to the strange laws of quantum mechanics, where everything that exists is never stable, and is nothing but a jump from one interaction to another. There is no such thing as a real void, one that is completely empty. Just as the calmest sea looked at closely sways and trembles, however slightly, so the fields that form the world are subject to minute fluctuations, and it is possible to imagine its basic particles having brief and ephemeral existences, continually created and destroyed by these movements.
#+end_quote

#+begin_quote
粒子理论的细节在 20 世纪 50—70 年代逐渐得到完善。20 世纪 70 年代，在其所有预测被一系列实验证实之后，这个「标准模型」终于得以确立。2013 年希格斯玻色子的发现，完成了「标准模型」确认工作的最后一环。迄今为止，标准模型仍然是解释物质世界最好的理论，它的预测全都得到了证实。除了暗物质和广义相对论中被描述为时空曲率的引力之外，它很好地解释了已知世界的方方面面。

The details of particle theory were built gradually in the 1950s, 1960s and 1970s. The "Standard Model" was finalized in the 1970s, after a long series of experiments which confirmed all predictions. Its final confirmation occurred in 2013 with the discovery of the Higgs boson. The Standard Model remains the best that we have when speaking today about the world of things, its predictions have all been confirmed; and apart from dark matter - and gravity as described in the theory of general relativity as the curvature of space-time - describes well every aspect of the perceived world.
#+end_quote

#+begin_quote
天文学家们发现，在每一个星系的周围都存在着一团巨大的云状物。我们是通过它对星体的引力和它使光发生偏折的现象才间接发现它的。我们无法直接看到这团巨大的云，也不知道它由什么组成。科学家们提出了很多假设，却没有一个说得通。今天我们把它称为「暗物质」，一种无法用标准模型描述的东西。

Around every galaxy astronomers observe a large cloud of material which reveals its existence via the gravitational pull that it exerts upon stars, and by the way it deflects light. But this great cloud, of which we observe the gravitational effects, cannot be seen directly and we do not know what it is made of. Numerous hypotheses have been proposed, none of which seem to work. Nowadays it is called "dark matter". Evidence indicates that it is something not described by the Standard Model.
#+end_quote

#+begin_quote
物理学家们却从未真正认真看待「标准模型」。这个理论至少第一眼看上去零零碎碎，东拼西凑。它由不同的理论和方程集合而成，看不出有什么清晰的秩序。我们距离广义相对论和量子力学的简洁方程还很遥远。

The Standard Model has never been taken entirely seriously by physicists. It's a theory which looks, at least at first sight, piecemeal and patched together. It's made up of various pieces and equations assembled without any clear order. We're far from the simplicity of the equations of general relativity, and of quantum mechanics.
#+end_quote
* 第五课

#+begin_quote
20 世纪物理学的两颗明珠是广义相对论和量子力学。前者是宇宙学、天体物理学、引力波、黑洞以及其他许多研究的起源；后者则是原子物理、核物理、基本粒子物理、凝聚态物理等学科的基础。这两个理论带来了丰富的成果，奠定了当代科技的基石，彻底改变了我们的生活方式。但这两个理论不可能同时正确，至少以它们目前的形式，它们是相互矛盾的。

The twentieth century has given us the two gems: general relativity and quantum mechanics. From the first cosmology developed, as well as astrophysics, the study of gravitational waves, of black holes, and much else besides. The second provided the foundation for atomic physics, nuclear physics, the physics of elementary particles, the physics of condensed matter, and much, much more. Two theories, profligate in their gifts, which are fundamental to today's technology and have transformed the way we live. And yet the two theories cannot both be right, at least in their current form, because they contradict each other.
#+end_quote

#+begin_quote
大自然就像一位年长的拉比，有两个人跑去找他解决争端。听了第一个人的话，拉比说：「你说得对。」第二个人坚持为自己辩解。拉比听完对他说：「你说得也对。」拉比夫人在另一个房间听到了他们的谈话，大声说道：「但是他们两个不会都有道理吧？」长老认真思考了一下，点点头说：「你说得也对。」

Nature is behaving with us like that elderly rabbi to whom two men went in order to settle a dispute. Having listened to the first, the rabbi says: "You are in the right." The second insists on being heard, the rabbi listens to him and says: "You're also right." Having overheard from the next room the rabbi's wife then calls out, "But they can't both be in the right!" The rabbi reflects and nods before concluding: "And you're right too."
#+end_quote
* 第六课

#+begin_quote
_在所有不发生热交换，或热交换可以忽略不计的情况下，我们看到的未来和过去是一模一样的。_ 如果没有摩擦，钟摆可以永远摆动下去。如果我们把这个摆动过程录下来，倒着播放，也不会觉得有任何问题。但是，如果存在摩擦，钟摆微微加热了底座，损失了能量，运动速度就会减慢，这时我们立刻就能分辨未来（钟摆变慢的方向）和过去。

In every case in which heat exchange does not occur, or when the heat exchanged is negligible, we see that the future behaves exactly like the past. While there is no friction, a pendulum can swing forever. If we filmed it and ran the film in reverse we would see movement that is completely possible. But if there is friction then the pendulum heats its supports slightly, loses energy and slows down. Friction produces heat. And immediately we are able to distinguish the future (towards which the pendulum slows) from the past.
#+end_quote

#+begin_quote
为什么热量会从热的物体跑到冷的物体上，而不是相反呢？其中的原因惊人地简单：这完全是随机的。热量从热的物体跑到冷的物体上并非遵循什么绝对的定律，只是这种情况发生的概率比较大而已。原因在于：从统计学的角度看，一个快速运动的热物体的原子更有可能撞上一个冷物体的原子，传递给它一部分能量；而相反过程发生的概率则很小。

Why, as time goes by, does heat pass from hot things to cold and not the other way round? The reason is surprisingly simple: it is sheer chance. Heat does not move from hot things to cold things due to an absolute law: it only does so with a large degree of probability. The reason for this is that it is statistically more probable that a quickly moving atom of the hot substance collides with a cold one and leaves it a little of its energy, rather than vice versa.
#+end_quote

#+begin_quote
在 20 世纪的进程中，热力学（研究热的科学）和统计力学（研究各种运动的概率的科学）都延伸到了电磁场和量子现象的领域。不过，当把它们延伸到引力场时，却出现了问题。温度升高时，引力场会如何变化，仍是一个未解的难题。引力场就是空间本身，或者说是时空，因此，当热量在引力场扩散开来的时候，空间和时间也应该发生振动……但是我们还不知道如何描述它，我们还没有发现可以描述热时空的热振动的方程。

In the course of the twentieth century thermodynamics (that is, the science of heat) and statistical mechanics (that is, the science of the probability of different motions) have been extended to electromagnetic and quantum phenomena. Extension to include the gravitational field, however, has proved problematic. How the gravitational field behaves when it heats up is still an unsolved problem. The gravitational field is space itself, in effect space-time. Therefore when heat is diffused to the gravitational field, time and space themselves must vibrate ... But we still don't know how to describe this well. We don't have the equations to describe the thermal vibrations of a hot space-time.
#+end_quote

#+begin_quote
这些问题把我们引向时间问题的核心：时间的流动究竟是什么？物理学通过公式来描述世界，告诉我们物体是如何随「时间」而变化的。但是，我们也可以用另一些公式解释物体如何随「位置」的改变而变化。时间看起来是在「流动」，但是空间中的位置不会「流动」。那么区别在哪里？

Such issues lead us to the heart of the problem of time: what exactly is the flow of time? Physics describes the world by means of formulae that tell how things vary as a function of "time". But we can write formulae that tell us how things vary in relation to their "position". Time seems to "flow", whereas the location in space does not "flow". Where does the difference come from?
#+end_quote

#+begin_quote
在物理学中，没有东西对应「现在」这个概念。对比一下「此刻」和「此处」。「此处」是指说话人所在的位置：如果有两个不同的人，「此处」就是指两个不一样的地方。因此，「此处」的意思取决于说话的地点，用术语表达就叫作指示性。「此刻」指说话的这一瞬间，也具有指示性。没有人会说「此处」的东西是存在的，不在「此处」的东西就不存在。那么，为什么我们可以说「此刻」的东西是存在的，不在「此刻」的东西就不存在呢？究竟「此刻」是客观的，它的「流动」让物体一个接着一个地「存在」，还是，它和「此处」一样，是主观的？

In physics there is nothing that corresponds to the notion of the "now". Compare "now" with "here". "Here" designates the place where a speaker is: for two different people "here" points to two different places. Consequently "here" is a word the meaning of which depends on where it is spoken. The technical term for this kind of utterance is "indexical". "Now" also points to the instant in which the word is uttered, and is also classed as "indexical". But no one would dream of saying that things "here" exist, whereas things which are not "here" do not exist. So then why do we say that things that are "now" exist and that everything else doesn't? Is the present something which is objective in the world, that "flows" and that makes things "exist" one after the other, or is it only subjective, like "here"?
#+end_quote

#+begin_quote
历史已经多次证明，我们的直觉是不准确的。直觉建立在我们有限的经验之上。如果被困在直觉中，我们还想着地球是平的，太阳绕着地球转呢。狭义相对论告诉我们「现在」的概念也是主观的。物理学家们和哲学家们得出结论：全宇宙共有同一个「现在」的观念是种幻觉，时间在宇宙中同步「流逝」这种概括也是行不通的。

Many times in the past we have realized that it is _our immediate intuitions that are imprecise. Our intuitions have developed on the basis of our limited experience._ If we had kept to these we would still believe that the Earth is flat and that it is orbited by the sun. Special relativity has shown that the notion of the "present" is also subjective. Physicists and philosophers have come to the conclusion that the idea of a present that is common to the whole universe is an illusion, and that the universal "flow" of time is a generalization that doesn't work.
#+end_quote

#+begin_quote
我认为答案就在热量和时间的紧密联系中：只有当热量发生转移时，才有过去和未来的区别。热量与概率相关，而概率又决定了：我们和周围世界的互动无法追究到微小的细节。这样一来，「时间的流逝」便在物理学中出现了。「此刻」并不比「此处」更加客观，但是世界内部微观的相互作用，促使某系统（比如我们自己）内部出现了时间性的现象。

I think that the answer lies in the intimate connection between time and heat. There is a detectable difference between the past and the future only when there is flow of heat. Heat is linked to probability; and probability in turn is linked to the fact that our interactions with the rest of the world do not register the fine details of reality. The flow of time emerges thus from physics. The "present" does not exist in an objective sense any more than "here" exists objectively, but the microscopic interactions within the world prompt the emergence of temporal phenomena within a system (for instance, ourselves).
#+end_quote

#+begin_quote
霍金利用量子力学成功地证明了黑洞总是「热的」。从来没有人观测到这种热，因为在我们观测到的真实的黑洞中，这种热非常微弱。但是霍金的计算令人信服，在各种场合被人们引用，黑洞的热也被普遍认为是真实存在的。这个现象同时涉及问题的三个方面：量子力学、广义相对论和热力学。黑洞的热如同物理学中的罗塞塔石碑，它用量子、引力和热力学三种语言写就，仍在等待解读，以告诉我们时间的本质。

Using quantum mechanics Hawking successfully demonstrated that black holes are always "hot". No one has ever observed this heat because it is faint in the actual black holes which have been observed so far. But Hawking's calculation is convincing, it has been repeated in different ways, and the reality of the heat of black holes is generally accepted. This phenomenon involves all three sides of the problem: quantum mechanics, general relativity and thermal science. The heat of black holes is like the Rosetta Stone of physics, written in a combination of three languages - Quantum, Gravitational and Thermodynamic - still awaiting decipherment in order to reveal the true nature of time.
#+end_quote
* 尾声

#+begin_quote
我们建构的宇宙图像存在于我们心中，在我们的思维之中。在这些图像——我们能够借助有限的手段重构和理解的事物——和我们身为其组成部分的真实世界之间，存在着无数滤镜：我们的无知，感官和智力的局限。

The images which we construct of the universe live within us, in the space of our thoughts. Between these images - between what we can reconstruct and understand with our limited means - and the reality of which we are part, there exist countless filters: our ignorance, the limitations of our senses and of our intelligence.
#+end_quote

#+begin_quote
当我们谈及宇宙大爆炸或空间的肌理时，并不是在延续几十万年来，人们围坐在夜晚篝火旁讲述的天马行空的故事。我们要延续的是另外的传统：先人们注视黎明第一缕曙光的眼力，他们可以借此发现热带大草原尘埃之上一只羚羊留下的足迹，通过观察真实世界中的蛛丝马迹来发现那些我们无法直接看到却有迹可循的东西。认识到我们可能会不断犯错，因此，一旦有新的迹象出现，我们要能随时改变方向，同时我们也清楚，如果我们足够聪明，就会做出正确的判断，找到我们追寻的东西。这就是科学的本质。黎明时猎获的羚羊和前晚故事里讲的羚羊神相距并不遥远。界限是模糊的，神话与科学相互滋养。但知识总是有价值的。捉到羚羊，我们就能填饱肚子。

When we talk about the Big Bang or the fabric of space, what we are doing is not a continuation of the free and fantastic stories which humans have told nightly around campfires for hundreds of thousands of years. It is the continuation of something else: of the gaze of those same men in the first light of day looking at tracks left by antelope in the dust of the savannah - scrutinizing and deducting from the details of reality in order to pursue something which we can't see directly but can follow the traces of. In the awareness that we can always be wrong, and therefore ready at any moment to change direction if a new track appears; but knowing also that if we are good enough we will get it right and will find what we are seeking. This is the nature of science. The separation is a subtle one: the antelope hunted at dawn is not far removed from the antelope deity in that night's storytelling. The border is porous. Myths nourish science, and science nourishes myth. But the value of knowledge remains. If we find the antelope we can eat.
#+end_quote

#+begin_quote
世间万物都在不断相互作用，彼此身上都会留下对方的印记，从这个意义上来说，所有事物都在不断地交换信息。一个物理系统拥有的其他物理系统的信息，不包含任何精神的或主观的东西，只是受物理规律支配的某一事物状态与另一事物状态之间的联系。一滴雨水包含着天空中一片云的信息；一束光包含着发光物质颜色的信息；一阵风携带着一场即将到来的暴风雨的信息；一个流感病毒携带着我们易受感染的鼻腔的信息。

All things are continually interacting with each other, and in doing so each bears the traces of that with which it has interacted: and in this sense all things continuously exchange information about each other. The information which one physical system has about another has nothing mental or subjective about it: it's only the connection that physics determines between the state of something and the state of something else. A raindrop contains information on the presence of a cloud in the sky; a ray of light contains information on the colour of the substance from which it came; the wind carries information about an approaching storm; a cold virus has information of the vulnerability of our noses.
#+end_quote

#+begin_quote
自由并不意味着我们的行为不受自然规律的支配，而是说明自然规律通过大脑的运作来决定我们的行为。我们的自由决定，是我们大脑中数十亿个神经元相互作用的结果。我们的抉择固然自由，但却不可能超出神经元的相互作用。正如 17 世纪荷兰哲学家斯宾诺莎极为清楚地认识到的那样，这二者是一回事。其实并没有「我」和「我大脑的神经元」之分，这两者本是一码事。一个人就是一个程序，复杂而又极其完备。

To be free doesn't mean that our behaviour is not determined by the laws of nature. It means that it is determined by the laws of nature acting in our brains. Our free decisions are freely determined by the results of the rich and fleeting interactions between the billion neurons in our brain: they are free to the extent that the interaction of these neurons allows and determines. The two things, as the Dutch philosopher Baruch Spinoza understood with marvellous lucidity in the seventeenth century, are the same. There is not an "I" and "the neurons in my brain". They are the same thing. An individual is a process: complex, tightly integrated.
#+end_quote

#+begin_quote
我们是一个好奇心很重的物种，在一个由至少十来个好奇心强的物种组成的属（人属）中，我们是唯一存活下来的一支。十万年前，或许正是出于这种好奇心，我们这个物种从非洲出发，学着眺望远方。夜晚，我在飞越非洲大陆时浮想联翩，假如在我们这些遥远的祖先中，有一个站立起来，朝着北方的旷野行进，他仰头看天时，会不会想到在遥远的未来，他的一个子孙正在这片天空中飞行，思考着事物的本质，而起因正是与他一样的好奇心。

We are a species which is naturally moved by curiosity, the only one left of a group of species (the genus Homo) made up of a dozen equally curious species. One hundred thousand years ago our species left Africa, compelled perhaps by precisely this curiosity, learning to look ever further afield. Flying over Africa by night, I wondered if one of these distant ancestors setting out towards the wide open spaces of the North could have looked up into the sky and imagined a distant descendant flying up there, pondering on the nature of things, and still driven by the very same curiosity.
#+end_quote

#+begin_quote
我认为，我们这个物种不会延续很久。我们似乎没有乌龟的那种本事，能够几亿年来一直保持着原来的样子。我们属于一个短命的物种，所有的表亲都已经全部灭绝。而且我们一直在破坏。对地球来说，这只是一个无关紧要的小挫折，但我认为，人类将很难安然无恙地渡过这个难关。就像我们或多或少都知道该如何面对个体的死亡一样，我们也知道如何面对我们文明的覆灭。并没有太大的不同，这当然不会是第一个覆灭的文明。玛雅文明和克里特文明，还有许多其他文明都已经成为过去。我们的生死如同星辰的生灭，个体如此，全人类也是如此。这就是我们的现实。

I believe that our species will not last long. It does not seem to be made of the stuff that has allowed the turtle, for example, to continue to exist more or less unchanged for hundreds of millions of years. We belong to a short-lived genus of species. All of our cousins are already extinct. What's more, we do damage. For the Earth they may turn out to be a small irrelevant blip, but I do not think that we will outlast them unscathed. As we know more or less well how to deal with our individual mortality, so we will deal with the collapse of our civilization. It is not so different. And it's certainly not the first time that this will have happened. The Maya and Cretans, amongst many others, have already experienced this. We are born and die as the stars are born and die, both individually and collectively. This is our reality.
#+end_quote
