#+setupfile: ../../styles/readtheorg.setup
#+title: Stuff Matters

* 目录

| 序章 | Introduction |
|------+--------------|
|      |              |

* 序章

#+begin_quote
从我们对文明发展阶段的划分（石器时代、青铜时代和铁器时代）就可以看出材料对我们而言有多么根本和重要。人类社会每一个新时代都是因为一种新材料出现而促成的。

The fundamental importance of materials to us is apparent from the names we have used to categorize the stages of civilization - the Stone Age, Bronze Age, and Iron Age - with each new era of human existence being brought about by a new material.
#+end_quote

#+begin_quote
钢是维多利亚时代的关键原料，让工程师得以充分实现梦想，做出吊桥、铁路、蒸汽机和邮轮。建筑师运用大规模生产的结构钢和平板玻璃建起摩天大楼，创造出新的都市生活形态。产品和服装设计师用塑料彻底改变了我们的住宅与穿着。聚合物制造而成的赛璐珞催生了影像文化一千年来的最大变革，也就是电影的诞生。铝合金和镍超合金让我们制造出喷气发动机，使得飞行从此变得便宜，进而加速了文化互动。医用和牙科陶瓷让我们有能力重塑自己，并改写了残障与老化的定义。材料往往是新疗法诞生的关键，从器官修补（如髋关节置换手术）到美化外表（如硅胶隆胸）都是如此。

Steel was the defining material of the Victorian era, allowing engineers to give full rein to their dreams of creating suspension bridges, railways, steam engines, and passenger liners. Architects took mass-produced sheet glass and combined it with structural steel to produce skyscrapers that invented a new type of city life. Product and fashion designers adopted plastics and transformed our homes and dress. Polymers were used to produce celluloid and ushered in the biggest change in visual culture for a thousand years: the cinema. The development of aluminum alloys and nickel superalloys enabled us to build jet engines and fly cheaply, thus accelerating the collision of cultures. Medical and dental ceramics allowed us to rebuild ourselves and redefine disability and aging. Materials are often the key to new treatments used to repair our faculties (hip replacements) or enhance our features (silicone implants for breast enlargement).
#+end_quote

#+begin_quote
微观世界的空间尺度虽小，时间尺度却常常大得惊人。我们身上穿的牛仔裤和所有衣服都是微型编织结构，而许多结构的式样比英国的巨石阵还古老。20 世纪发明了强韧的纤维，让我们可以制作太空服保护登陆月球的航天员，还有坚固的纤维可以制造义肢。

While the physical scale of the microscopic world is much smaller, its timescale is often dramatically bigger. Textiles are one of the earliest man-made materials. When we wear a pair of jeans, or any other piece of clothing, we are wearing a miniature woven structure, the design of which is much older than Stonehenge. In the twentieth century we learned how to make space suits from textiles strong enough to protect astronauts on the Moon; we made solid textiles for artificial limbs.
#+end_quote

#+begin_quote
材料科学的基本概念就是：看不见的微观世界若有变化，那么在人的尺度之中，物质行为也会跟着改变。我们的祖先能做出铜和钢之类的新材料，就是因为碰巧蒙到了这个过程。敲打金属不只会改变它外在的形状，还会改变它内在的结构，因此若用某种方式敲击，金属的内在结构就会有所改变，使它变得更硬。

The central idea behind materials science is that changes at these invisibly small scales impact a material’s behavior at the human scale. It is this process that our ancestors stumbled upon to make new materials such as bronze and steel. When you hit a piece of metal you are not just changing its shape, you are changing the inner structure of the metal. If you hit it in a particular way, this inner structure changes in such a way that the metal gets harder.
#+end_quote

#+begin_quote
针对「酥脆感」所做的研究显示，我们觉得某些食物好吃与否不只是跟味道有关，还跟品尝时的声音有关，两者同样重要。这让不少厨师受到启发，开发出具有音效的餐点，而某些薯片商更进一步，不仅让产品更酥脆，还让包装更会发出声音。

Studies of "crispness" have shown that the sound created by certain foods is as important to our enjoyment of them as their taste. This has inspired some chefs to create dishes with added sound effects. Some potato chip manufacturers, meanwhile, have increased not just the crunchiness of their chips but the noisiness of the chip bag itself.
#+end_quote
