#+setupfile: ../../styles/readtheorg.setup
#+title: The Cartoon Introduction to Statistics

* Part 1: Gathering Statistics
** Introduction: They're everywhere

#+begin_quote
Statistics is about using the fish we did catch to say things about the fish we didn't.
#+end_quote

#+begin_quote
Statistics help us make *confident dicisions* when we have *limited information*.

We can use statistics to make *confident guesses*, but you can never use them to achieve *certainty*.
#+end_quote

** Chapter 1: Numbers

#+begin_quote
Treat all numbers with a healthy dose of skepticism.
#+end_quote

#+begin_quote
Always ask these questions of any number you encounter:
- Where did you come from?
- Who made you?
- And why?
#+end_quote

** Chapter 2: Random raw data

#+begin_quote
Sometimes it's impossible to count all the things you want to know about. Which is why, long ago, someone dreamed up the strategy of studying a *sample* to learn something about an entire *population*.
#+end_quote

#+begin_quote
Ideally we'd like to gather a sample that accurately mirrors the population. This can seem like an impossible task when we don't know what the population looks like. To avoid bias, we always collect samples *randomly*.

*Random sampling* is the key to all statistical inquiry.
#+end_quote

** Chapter 3: Sorting

#+begin_quote
We gather *categorical data* when we're studying features that we can *describe only with words* (eg. colors, nations)h or *yes/no answers*.

After we gather categorical data we can easily pile it or slice it to give us a sense of the proportions in our sample.
#+end_quote

#+begin_quote
We gather *numerical data* when we're studying features that we can *compare using numbers* (eg. age, height).
#+end_quote

#+begin_quote
The crucial difference between the two types of data is that we can do math on numerical data.
#+end_quote

-----

#+begin_quote
The most basic picture of numerical data is called a *histogram*.
#+end_quote

#+caption: Histogram
file:../images/the_cartoon_introduction_to_statistics/01.jpg

#+begin_quote
Another useful way to visualize numerical data is with a *boxplot*.

... cram the middle 50% of sample values into one big box.
#+end_quote

#+caption: Boxplot
file:../images/the_cartoon_introduction_to_statistics/02.png

#+begin_quote
Boxplots can be especially useful when we want an overview of our data or want to compare different samples or groups.

Boxplots can give us a quick sense of *how data clumps together* and *whether it trails off* in one direction or the other.
#+end_quote

#+caption: Boxplots
file:../images/the_cartoon_introduction_to_statistics/03.jpg

** Chapter 4: Detective work

#+begin_quote
When we start to investigate any pile of data, we always look at four primary characteristics:
- sample size
- shape
- location
- spread
#+end_quote

-----

#+begin_quote
The size of a sample is directly related to the level of confidence we can have about a population.

In general, a larger sample size is better.
#+end_quote

-----

#+begin_quote
We call a pile of data *flat* when all the possible outcomes are equally likely.
#+end_quote

#+begin_quote
We call a pile of data *normal* when something is causing it to clump around one particular value.
#+end_quote

#+begin_quote
We call a pile of data *skewed* when something is causing it to trail off more in one direction than the other.
#+end_quote

#+caption: Normal and skewed distribution
file:../images/the_cartoon_introduction_to_statistics/04.png

-----

#+begin_quote
*Location* is a measure of where the bulk of the data sits on a number line.
#+end_quote

| mean   | average value       | 平均数 |
|--------+---------------------+--------|
| median | middle value        | 中位数 |
|--------+---------------------+--------|
| mode   | most repeated value | 众数   |

-----

#+begin_quote
*Averages* can be deceptive if a pile of data is skewed.

With skewed data, the *median* is often more revealing as a measure of location.
#+end_quote

#+caption: Average (mean) vs median
file:../images/the_cartoon_introduction_to_statistics/05.gif

#+begin_quote
... never think about the location of any pile of data without also thinking about its shape.
#+end_quote

-----

#+begin_quote
The most common measure of spread is *Standard Deviation (SD)*.
#+end_quote

#+caption: Standard Deviation
file:../images/the_cartoon_introduction_to_statistics/06.gif

** Chapter 5: Monster mistakes

#+begin_quote
Much of the time we're exploring how one variable influences another. But remember, when we use statistics we can never totally prove any of our conclustions.
#+end_quote

#+begin_quote
Whenever we think we see a relationship between two variables, there might be some other variable influencing our conclusions.
#+end_quote

-----

#+begin_quote
... lurking variables can bedevil all kinds of statistical analysis, and part of a statistician's job is dig around for them.
#+end_quote
** Chapter 6: From samples to populations

#+begin_quote
When we pile up sample data, we call the result a *sample histogram*.

If we could pile up an entire population, we'd call the result a *population distribution (群体分布)*.
#+end_quote

#+begin_quote
We refer to qualities in samples as *statistics*, and to qualities in populations as *parameters*.

Statistics are the things we actually calculate and therefore know with certainty.

Parameters are the things we really want to know but can only make guesses about.
#+end_quote
* Part 2: Hunting Parameters
** Chapter 7: The Central Limit Theorem
