#+setupfile: ../../styles/readtheorg.setup
#+title: 万万没想到

* 第一章：「反常识」思维
** 「反常识」思维

#+begin_quote
统计数字的力量远远比不上一个人，一个具体的人。受试者对远在天边的国家的抽象数字没有多大兴趣，而他们对一个具体人物 — 哪怕仅仅听说了她的名字和最简单的背景，都更乐于出手相助。
#+end_quote

#+begin_quote
一直到进入现代社会之前，我们都生活在一个「具体的」世界中。我们熟悉每一个有可能打交道的人，而这些人的总数加起来也不是很多。这种生活模式对大脑的演化有巨大的影响。据估计，我们至今能够维持紧密人际关系的人数上限，也只有 150 个而已。
#+end_quote

#+begin_quote
世代定居的传统中国社区本质上是熟人社会。在熟人社会中人们做事不是靠商业和法治，而是靠道德和礼治。在这个体系中出了案子，首先关乎的是名声和面子，而不是利益。费孝通说乡土中国的最高理想是「无讼」。

生活在这样的社会里，我们的首要技能的不是数学计算，而是分辨善恶美丑。也许这就是文人思维的起源：针对每个特定动作的美学评价。
#+end_quote

#+begin_quote
只有刚接触艺术的人才喜欢令人愉快的东西，审美观成熟到一定程度以后我们就觉得快乐是一种肤浅的感觉，改为欣赏愁苦了。

美学是不可能客观的，每个人都在鄙视别人低端审美观和被别人鄙视，我们在审美观的鄙视链上不断移动。
#+end_quote

#+begin_quote
现代社会与古代最大的不同，是人们的生活变得越来越复杂。面对这种复杂局面，最基本的一个结果是好东西虽然多，你却不能都要。我们不得不在生活中做出各种取舍，而很多烦恼恰恰来自不愿意或者不知道取舍。古人很少有这样的烦恼，他们能有一个选择就已经高兴的不得了了。
#+end_quote

#+begin_quote
世界上并没有多少事情是「在没有使任何人境况变坏的前提下使得至少一个人变得更好」的所谓「帕累托改进」，绝大多数情况下兴一利必生一弊，而利弊都不是无限大的。

做过利弊分析，理工科思维要求妥协，而文人总爱戏剧性的不管不顾，喜欢说不惜一切代价，喜欢看动不动就把全部筹码都押上的剧情。

文人却喜欢用一个动作的「美感」来说服别人。万历皇帝想收商业税，东林党反对，而他们给出的反对理由不是收税这个动作的输出后果，而是「天子不与小民争利」！
#+end_quote

#+begin_quote
诺贝尔奖得主丹尼尔·卡尼曼的《思考，快与慢》一书，把人脑的两套思维系统称为「系统 1」和「系统 2」。前者自动起作用，能迅速对事物给出一个的很难被改变的第一印象；而后者费力而缓慢，需要我们集中注意力进行复杂计算。

系统 2 根本不是计算机的对手，没人能在百万分之一秒内计算 111.61872 的平方根。然而系统 1 却比计算机强大得多，直到 2012 年 Google 用了 1.6 万块处理器，才让计算机学会识别猫的脸。

系统 1 这么快，显然是因为它在漫长的进化史中非常有用的缘故。我们可以想见一个不会算数，甚至不会清晰地逻辑推理的人只要知道谁对他好谁对他坏，靠本能也能在草原上生活的不错。只有到了现代社会，他才会有大麻烦。

文人思维显然是系统 1 的集大成者，而理工科思维则是系统 2 的产物。
#+end_quote

#+begin_quote
Tradeoff 要求量化输入和预计输出，这也是理工科思维的最根本方法。但人脑天生不适应抽象数字。

文人思维天生喜爱耸人听闻的消息，如果再加上不爱算数，就会对世界乱担心和瞎指挥。文人可能从「是不是纯天然的」这个角度认为有机农业很美而核电很可怕，这不是一个好标准。在大多数公共问题上，常识是不好使的。资源调配即使做不到完全依赖市场，也不应该谁声音大就听谁的。
#+end_quote

#+begin_quote
以下这四件事，每个文人都想要：（1）用纯天然方法种植的有机农业；（2）保护环境；（3）取消人口控制；（4）让每一个人都吃饱穿暖。可是这四件事不可能同时做到，你必须放弃一个。
#+end_quote
** 别想说服我！

#+begin_quote
蒙洛迪诺说，人做判断的时候有两种机制：一种是「科学家机制」，先有证据再下结论；一种是「律师机制」，先有了结论再去找证据。

每个人都爱看能印证自己已有观念的东西。我们不但不爱看，而且还会直接忽略，那些不符合我们已有观念的证据。
#+end_quote

#+begin_quote
如果我反对一个结论而你支持，那么当我看一篇支持这个结论的论文就会不自觉地用更高的标准去看，就会认为这个论文不行；而你，因为支持这个观点，则会认为这个论文很好 — 如此一来我不就认为你是弱智了么？于是两个对立阵营都会认为对方是弱智。一切都可以在潜意识发生。
#+end_quote

#+begin_quote
如果人已经被各种观念分成了阵营，那么媒体就不应该追求什么「客观中立」，因为没人爱看客观中立的东西！

给观众想要的东西，比给观众事实更能赚钱。观众想要什么呢？娱乐和确认。观众需要你的新闻能用娱乐的方式确认他们已有的观念。

很多新闻网站使用一个叫做 multivariate testing（也叫 A/B testing）的技术：在一篇文章刚贴出来的时候，读者打开网站首页看到的是随机显示的这篇文章的两个不同标题之一，网站会在五分钟内判断哪个标题获得的点击率更高，然后就统一使用这个标题。事实证明在读者的选择下最后胜出的标题都是耸人听闻型的。

「当你年轻的时候，你看着电视就会想，这里面一定有阴谋。电视台想把我们变傻。可是等你长大一点，你发现不是这么回事儿。电视台的业务就是人们想要什么它们就给什么。这个想法更令人沮丧。阴谋论还算乐观的！至少你还有个坏人可以打，我们还可以革命！而现实是电视台只不过给我们想要的东西。」 — 乔布斯
#+end_quote

#+begin_quote
这个毛病叫做「确认偏误」（confirmation bias）。如果你已经开始相信一个什么东西了，那么你就会主动寻找能够增强这种相信的信息，乃至不顾事实。

对于那些已经支持强烈共和党或民主党的学生来说，如果你给他们关于其支持的党的负面新闻，功能性磁共振成像（FMRI）会显示这些人大脑中负责逻辑推理的区域关闭了，而负责感情的区域却激活了！换句话说他会变得不讲理只讲情。

在确认偏误的作用下，任何新证据都有可能被忽略，甚至被对立的双方都用来加强自己的观念。这就是为什么每一次枪击事件之后禁枪派和拥枪派都变得更加强硬。
#+end_quote

#+begin_quote
根据诺贝尔奖得主 Robert Aumann 1976年的论文「Agreeing to Disagree」，说如果是两个理性而真诚的真理追求者争论问题，争论的结果必然是二人达成一致。

认知科学家 Hugo Mercier 和 Dan Sperber 2011 年的一篇论文，「Why do humans reason?」，甚至认为人的逻辑推理能力本来就不是用来追求真理的，而是用来说服别人的。也就是说我们天生就都是律师思维，我们的大脑本来就是个争论设备。这也许是因为进化总是奖励那些能说服别人的人，而不是那些能发现真理的人吧。
#+end_quote

#+begin_quote
「Consume deliberately. Take in information over affirmation.」 — 要主动刻意地消费，吸收有可能修正我们观念的新信息，而不是吸收对我们现有观念的肯定。
#+end_quote

#+begin_quote
统计表明人们的关注集群也不是按照政治立场划分，而更多的是按照视野大小划分的。
#+end_quote
** 真理追求者

#+begin_quote
两个真诚而理性的人应该对事情有相同的看法。如果争论不欢而散，一定是有人不诚实！这个定理中所假设的理性的人，被学者称为「truth-seekers」，真理追求者。如果我们是诚实的真理追求者，我们终将能够达成一致。

一个真正理性的人，如果他认为其他人也是理性的，那么他不应该买股票。为什么？如果他买股票，就必然有人卖这支股票 — 这就意味着两人对这只股票的升值前景（不一定是确切的预测，可以是一个概率）有不同看法。
#+end_quote

#+begin_quote
所有科学家有一个共同优点：他允许你改变他的想法。实际上，搞科研的一大乐趣就是被别人改变想法！
#+end_quote

** 坏比好重要

#+begin_quote
一个重要的心理学定律，叫做「损失规避」（loss aversion）。人总是喜欢获得而害怕失去。
#+end_quote

#+begin_quote
人们对负面感情的重视程度总是超过正面感情。心理学对这个更一般的现象也有个名词，叫「负面偏见」（negativity bias）。
#+end_quote

#+begin_quote
进化心理学认为恐惧来自人的自我保护本能，而冒险来自人的求偶本能。恐惧使人害怕损失，浪漫使人热爱冒险。

人一出生就有自我保护本能，而求偶本能则是在长大后才有。进化使我们大脑中恐惧的优先级高于浪漫，也许这就是负面偏见存在的原因。
#+end_quote

** 最简单概率论的五个智慧

#+begin_quote
概率论最基础的思想是，有些事情是无缘无故地发生的。

古人认为一切事物都是有原因的，甚至可能都是有目的的。人们曾经认为世界像一个钟表一样精确地运行。但真实世界不是钟表，它充满不可控的偶然。

更严格的说，有些事情的发生，跟它之前发生的任何事情，都可以没有因果关系。不论我们做什么都不能让它一定发生，也不能让它一定不发生。
#+end_quote

#+begin_quote
现代职业化竞技体育中，参赛者之间的实力差距并不是天壤之别，决定比赛结果的偶然性因素非常大。强队也会输给弱队，这是现代体育的重要特征，也是魅力所在。若强队一定胜利，比赛还有什么悬念？
#+end_quote

#+begin_quote
理解随机性，我就知道很多事情发生就发生了，没有太大可供解读的意义。我们不能从这件事获得什么教训，不值得较真，甚至不值得采取行动。

偶然的错误不值得深究，成绩也不值得深究。
#+end_quote

#+begin_quote
偶然因素是永远存在的，即使实验条件再精确也无法完全避免随机干扰的影响，所以做科学实验往往要测量多次，用取平均值之类的统计手段得出结果。多次测量确实是一个排除偶然因素的好办法。
#+end_quote

#+begin_quote
希格斯粒子质量为 125.3±0.4(stat)±0.5(sys) GeV，意思是说，质量是 125.3，但其中有 0.4 的统计误差，还有 0.5 的系统误差。真实的质量其实只有一个，但这个数字是多少，我们不知道，它可以是这个误差范围内的任何一个数字。事实上，甚至可能是误差范围外的一个数字。这是因为误差范围是一个概率计算的结果，这个范围的意思是说物理学家相信真实值落在这个范围以外的可能性非常非常小。
#+end_quote

#+begin_quote
「大数定律」：如果统计样本足够大，那么事物出现的频率就能无限接近它的理论概率——也就是它的「本性」。

但人们常常错误的理解随机性和大数定律，以为随机就意味着均匀。如果过去一段时间内发生的事情不均匀，人们就错误的以为未来的事情会尽量往「抹平」的方向走。

但大数定律的工作机制不是和过去搞平衡，它的真实意思是说如果未来进行非常多次的抽奖，你会得到非常多的 2 和非常多的 6，以至于它们此前的一点点差异会变得微不足道。
#+end_quote

#+begin_quote
「除 2 以外的素数都是奇数」，这是一个「性质」，而不是真正的「规律」，因为你无法用它去预测下一个素数。
#+end_quote

#+begin_quote
发现规律是人的本能。我们的本能工作的如此之好，以至于我们在明明没有规律的地方也能找出规律来。

在没有规律的地方发现规律是很容易的事情，只要你愿意忽略所有不符合这个规律的数据。如果数据够多，我们可以找到任何我们想要的规律。
#+end_quote

#+begin_quote
人脑很擅长理解规律，但是很不擅长理解随机性。
#+end_quote

#+begin_quote
有一门学问任务地震和各种自然灾害会严格按照某种数学规律发生，甚至用研究数学——确切地说是做数字游戏——的办法去预测地震。这个方法叫做「可公度性理论」。
#+end_quote

#+begin_quote
只要数据足够少，我们总能发现一些没有破解的「规律」。如果数据少，随机现象可以看上去「很不随机」，甚至非常整齐，感觉好像真有规律一样。

这个现象被戏称为「小数定律」：如果样本不够大，那么它就会表现为各种极端情况，而这些情况可以跟它的本性一点关系都没有。

如果统计样本不够大，就什么也说明不了。正因为如此，我们才不能只凭自己的经验，哪怕加上家人和朋友的经验去对事物做出判断。我们的经验非常有限。
#+end_quote

#+begin_quote
随机分布不等于均匀分布。实际上均匀分布仅在样本总数非常大的时候才有效。

当初 iPod 推出「随机播放」功能的时候，用户发现有些歌曲会被重复播放，据此认为播放根本不随机。苹果公司只好放弃真正的随机算法，用改进以后的算法使播放「更不随机以至于让人感觉更随机」。
#+end_quote

** 一颗阴谋论的心

#+begin_quote
世界非常大而且非常复杂，每天要发生很多很多事，绝大多数事情之间并没有什么因果关系。可是正如人很善于在本来没有规律的地方寻找规律，我们也非常擅长在本来没有联系的事情中发现联系，并且用一个简单理论对这些事情进行解读。
#+end_quote

#+begin_quote
中国流行国际大棋论，美国则流行专门针对美国政府的阴谋论，而且相信的人很可能并不比中国少。
#+end_quote

#+begin_quote
相信阴谋论很可能是人的一个思维本能。人们总是希望能给复杂而混乱的世界找个简单的解释，这个解释就是有某个强大的力量，怀着一个不可告人的目的，在控制一切。
#+end_quote

#+begin_quote
想要对任何事情的真伪都给以正确判断是不可能的，我们只能在有限的条件下合理评估每件事的可能性。阴谋论之所以不足信，并不是因为我们不应该质疑政府，而是因为其成立的可能性很低。
#+end_quote

#+begin_quote
「Linda 是个银行出纳员」和「Linda 是个热衷于女权运动的银行出纳员」哪个可能性更大？……这个错误的原因在于人们搞不清「合理性（plausibility）」和「可能性（probability）」的区别。「热衷于女权运动」增加了对 Linda 描述的合理性，但是却降低了可能性。增加细节也许可以增加合理性，但是一定减少可能性。
#+end_quote

#+begin_quote
在儿童成长的某个阶段，他的世界观会有两个基本点。一个是「animism」，万物有灵。他认为每个物体都是活的，比如汽车之所以不走是因为它累了需要休息。更重要的是，东西有它自己的意愿，比如「太阳在跟着我们走」。另一个是「artificialism」，人为主义。小孩认为一切东西都是人出于某种目的造出来的。比如为什么会有太阳？太阳是人用火柴造出来照亮用的。

由此，在儿童的世界中根本就不存在随机现象，一切都是有目的的。
#+end_quote

#+begin_quote
中国之所以没有自然科学，一个重要原因在于中国传统上认为天道是有目的的。
#+end_quote

#+begin_quote
To this purpose the philosophers say that Nature does nothing in vain, and more is in vain when less will serve; for Nature is pleased with simplicity, and affects not the pomp of superfluous causes. —— Issac Newton

解释自然界的一切，应该追求使用最少的原理。比如牛顿力学很简单，就足以解释自然届的各种现象 — 所以就没必要认为每个物体的每个运动背后都有它自己的特殊理由。
#+end_quote

#+begin_quote
个人意愿能改变的事情很少，绝大多数人都是在随波逐流。但即使所有人都随波逐流，复杂的系统也会出现非常激烈的「事件」。哪怕没有任何消息输入，仅仅是交易者之间的简单互动，也可能让股价产生很大的波动。
#+end_quote

#+begin_quote
认为凡事都有个目的，是普通人思维区别于科学思维的根本之一。
#+end_quote
** 桥段会毁了你的生活

#+begin_quote
TV Tropes（tvtropes.org），这是一个维基百科式的众人合作贡献内容的网站，它的主题是分析列举各种流行电影，电视剧，动画，小说和游戏中出现的所有剧情。网站的参与者看电影不是欣赏情节的好坏，而是本着理工科的精神把情节分解，识别并统计其中的桥段。

TV Tropes 的真正意义并不是「桥段百科全书」或「桥段数据库」，而是一个「桥段编程语言」！TV Tropes 就是剧本的库函数和编剧们的算法大全。
#+end_quote

#+begin_quote
真正的原创剧情是高雅文学和文艺片的事情，流行文学和商业片只需要「好用的」剧情。评价严肃作品，往往要看它是不是发明了独一无二的人物和剧情。所以严肃文学作家是科学家，通俗文学作家是工程师。
#+end_quote

** 健康的经济学

#+begin_quote
社会经济地位越高的人，越强调工作优先。60% 的白领处于过劳状态？中国企业家的过劳比例是 90.6%。越有钱的人，他们的健康就越值钱 — 所以他们就越有可能用健康换钱？
#+end_quote

#+begin_quote
在一个公平合理的社会里，更高的风险必须给人更高的价格。而我们这个社会没有做到这一点。很多人的议价能力连墨西哥妓女都不如，可是他们别无选择地接受了自己健康的价格。

一个选择了高风险高回报的人在健康出问题以后应该愿赌服输 — 再给他们一次机会很可能还是这样选。
#+end_quote

** 核电站能出什么大事

#+begin_quote
核电站不会像原子弹一样爆炸。你可能会获得一次常规当量的爆炸，但绝不是原子弹。因为原材料纯度远远不够。
#+end_quote

#+begin_quote
核电站泄漏对公众的真正危害是癌症。所有人都知道辐射导致癌症，但很少有人注意到一个更重要的事实：不辐射也可能得癌症。
#+end_quote

#+begin_quote
根据美国国家癌症研究所对美国 17 个地区统计的最新数据，一个人一生之中得癌症的概率是 44.29%，最终因癌症而死的概率则是 21.15%。

有些癌症可以用吸烟和环境之类的原因解释，有些癌症则无法解释。哪怕你的生活方式再健康，你也有差不多 20% 的可能性死于癌症。
#+end_quote

#+begin_quote
核辐射致癌的数学是在 20% 的「基础概率」上的基础上，增加人死于癌症的概率。这个被增加的概率与辐射的剂量成正比，具体地说就是每受到 25 雷姆的辐射，得癌症的概率增加一个百分点。

「雷姆」（rem）是对人体有效的辐射计量单位，换算成媒体报道常用的单位「西弗」（Sv），是 1 雷姆 = 10 毫西弗 = 10000 微西弗。

日本距离福岛最近的三个县中目前辐射剂量最高的是茨城县，为每小时 0.169 微西弗。在这个剂量下要想使一个人死于癌症的概率增加1个百分点，他必须在茨城县生活 250000/0.169/24/365 = 168 年。注意这还不算辐射剂量会随时间下降。
#+end_quote

#+begin_quote
更有意义的数字，是一次核电站事故总共可以增加多少癌症患者。

据估计，在广岛和长崎原子弹的 10 万幸存者中，平均每人被增加的癌症概率是 0.8%。这相当有 800 个本来不应该死于癌症的人最后死于癌症。然而这 10 万人中本来就应该有至少 20000 人死于癌症。

切尔诺贝利事故直接影响的 3 万人平均被增加的癌症概率是 1.8%。这意味着 3 万人中有 500 人得了不该得的癌症。很多科学家认为如果辐射剂量小于 6 雷姆（相当于 6 万微西弗），根本就不会增加癌症概率。

美国三里岛事故，研究表明当地居民的癌症率根本就没有显著增加。三里岛核电站所在地因为土壤里存在天然铀，其辐射本底本来就高。附近居住的 5 万居民，就算没有核电站，也会有 60 人因为死于天然核辐射导致的癌症。
#+end_quote

#+begin_quote
中国和美国的国家标准都是规定一般公众每年受到的辐射剂量不超过 1 毫西弗，也就是 0.1 雷姆。

一个辐射超标但是空气清洁的城市是不是比一个空气污染但是辐射达标的城市更安全？ 1 毫西弗标准不能告诉我们这些。实际上，丹佛附近的天然辐射剂量就超过国家标准。然而丹佛的癌症发病率低于美国大部分地区。
#+end_quote

#+begin_quote
每年死于交通事故的人数以十万计，可是我们该开车开车该坐车坐车。从来没有人提议禁止一切汽车。

我国每年有数以千计的矿工死于煤矿。更不用说因为烧煤产生的污染，导致的各种病症只会更多。而烧煤，正是为了发电，这就是中国目前发电的绝对主力：火力发电。我们用着拿别人生命换来的电，心安理得。

跟火电相比，核电就好像民主制度一样，虽然也不是个好的发电方式，却是「最不坏」的发电方式。
#+end_quote
* 第二章：成功学的解药
** 科学的励志和励志的科学

#+begin_quote
只有你的理论具有普遍意义，你的成功才「可以复制」。

在科学家看来，乔布斯的个性管理也许根本不值得推广，而扎克伯格的所谓天才霸业，远远比不上一群普通学生在几个月内的整体进步有研究价值。
#+end_quote

#+begin_quote
想要知道到底什么品质对成功最重要，科学的办法不是看名人传记，而是进行大规模统计。
#+end_quote

#+begin_quote
研究者普遍认为，排除智力因素，不管你心目中的成功是个人成就、家庭幸福还是人际关系，决定成功的只有自控。

自控需要意志力。一般人可能认为意志力是一种美德，应该通过教育的方式提升思想的境界来培养。然而实验表明意志力其实是一种生理机能。它就好像人的肌肉一样每次使用都消耗能量，而且用多了会疲惫。

研究者推断人的意志力能量来自血液中的葡萄糖。
#+end_quote

#+begin_quote
做选择会消耗意志力。

商家非常理解这个被称之为「决策疲劳」的原理。买新车的时候往往会有很多升级配置的选项，而聪明的销售总是让你刚来的时候先对一些花钱少的配置进行选择。等你连续决策到选累了以后，他再向你介绍价格贵或者根本没用的选项，而这时候你的意志力已经没办法对抗他的推荐了。
#+end_quote

#+begin_quote
善于自控的人可以为长远打算而拒绝短期诱惑。
#+end_quote

#+begin_quote
真正有效的办法是「常立志」。意志力是一种通用资源，这意味着你可以通过做一些日常小事来提高意志力，然后把它用在其它事情上。
#+end_quote

#+begin_quote
中国的教育改革家们一天到晚就想着把强调自控的中式教育改成强调自尊的美式教育，这其实是舍己之长用人之短。

尽管亚裔只占美国人口的 4%，亚裔学生却占到斯坦福之类顶级名校的四分之一。亚裔靠的是意志力。有实验发现中国小孩从两岁开始就比美国小孩有更强的自控能力。可能是基因的问题，因为中国的多动症儿童比美国少得多。也可能是传统的问题，因为中国父母更早要求孩子控制大小便。
#+end_quote

** 匹夫怎样逆袭

#+begin_quote
「屌丝」似乎还有精神上被人嘲笑的意味，而「underdog」仅仅强调这个人在实力对比上处于劣势 — 虽然处于劣势，他们还在继续战斗而没有退出。
#+end_quote

#+begin_quote
想要战胜歌利亚，关键在于两点。

第一，你要知道你的不利条件，在某些情况下可能是你的有利条件；而巨人的所谓有利条件，在某些情况下可能是他的不利条件。

第二，你绝对不能按照对手的打法去跟他玩，你有时候得使用非常规手段。
#+end_quote

#+begin_quote
……实验发现如果把测试试卷印的很难看，比如字非常小，读起来很困难的情况下，受试者反而能进行更多的思考，成绩反而更高！
#+end_quote

#+begin_quote
单亲家庭对普通人来说是个巨大的困难，可是对那些没有被这个困难击倒的人来说，他们不得不更早地自立而且也真的自立了，他们反而因此而变得更强大。
#+end_quote

#+begin_quote
一般有创造性的人物，都要有点特立独行（disagreeableness）的气质：你要敢于做一些社会上通常认为不应该做的事。你不是去适应这个社会，而是让这个社会去适应你。他们追求取胜，他们根本不追求别人的喜欢。
#+end_quote

** 练习一万小时成天才？

#+begin_quote
也许一个人最后的成就，不是练习加天赋，而是练习乘以天赋，一项是零最后结果就是零。
#+end_quote

#+begin_quote
真正的关键根本就不是训练时间的长短，而是训练的方法。

想要成为某一领域的顶尖高手，关键在于「刻意」地在这个领域内练习。
#+end_quote

#+begin_quote
刻意练习（deliberate practice）：

一、只在「学习区」学习；

二、把要训练的内容分成有针对性的小块，对每一个小块进行重复练习；

三、在整个练习过程中，随时能获得有效的反馈；

四、练习时注意力必须高度集中。
#+end_quote

-----

#+begin_quote
练习的精髓是要持续地做自己做不好的事。
#+end_quote

#+begin_quote
心理学家把人的知识和技能分为层层嵌套的三个圆形区域：最内一层是「舒适区」，是我们已经熟练掌握的各种技能；最外一层是「恐慌区」，是我们暂时无法学会的技能，二者中间则是「学习区」。
#+end_quote

#+begin_quote
年龄越大的人群中，人和人的思想差别就越大。
#+end_quote

#+begin_quote
当我们把一件事练熟以后，我们会把这件事「自动化」。真正的职业高手绝对不允许自己「自动化」，他们没有「舒适区」，一旦他们发现自己对这一项技术的掌握已经可以了，他们就会立即进入下一项更难的项目。

一旦你会了，就赶紧进入下一关。把这一关的攻略倒背如流没有任何意义。我国的高考制度其实是鼓励学生自动化，因为考题的难度有上限，一个好学生反复练习的结果就是对解题的「自动化」。他本该把时间用到学习更高级的东西上去。
#+end_quote

-----

#+begin_quote
人所掌握的知识和技能绝非是零散的信息和随意的动作，它们大多具有某种「结构」，这些「结构」就是套路。
#+end_quote

#+begin_quote
「短期工作记忆」是指人脑在同一时间能够处理的事情的个数，「长期工作记忆」存储了我们的知识和技能，人的技能取决于这两种工作记忆。

专家做的事情，就是使用有限的短期工作记忆，去调动自己几乎无限的长期工作记忆。而刻意练习，就是在大脑中建立长期工作记忆的过程。
#+end_quote

#+begin_quote
对于脑力工作者来说，水平的高低关键要看掌握的套路的多少。所以，艺术家要采风，棋手要打谱，律师要学案例，政客要读历史，科学家要看论文。
#+end_quote

#+begin_quote
事实上，掌握像弹琴和竞技体育的比学会解微分方程要困难得多，因为其需要协调调动的肌肉和脑神经元实在太多了。别人用个什么招式就算你全看到了而且看明白了，也不能立即学会。
#+end_quote

#+begin_quote
技能是人脑中的一种硬件结构。技能很不容易获得，获得了也很难抹掉。

练习，是对人体的改造，高手拥有长期训练获得的特殊脑神经结构。
#+end_quote

#+begin_quote
「莫扎特效应」根本不存在，没人能重复这个实验，在其他所有实验中听音乐对提高智商毫无帮助。
#+end_quote

#+begin_quote
如果你想学好微积分，最好的办法是找本微积分习题集做，而不是用大脑训练软件去试图先把大脑磨快一点再学微积分，那等于缘木求鱼。
#+end_quote

#+begin_quote
国内训练学生搞科研……把科学知识当成历史典故之类的考试材料，而不知道这些知识其实是可以拿来用的，更不知道你的任务不是学这些知识而是创造新知识。
#+end_quote

#+begin_quote
不积跬步，无以成千里；小事不做一心就想玩个大的，不是专业的训练方式。
#+end_quote

-----

#+begin_quote
一本书看好多遍，只是让我们对这个东西「熟悉」而已，而熟悉并不等于理解。想要真正了解，唯一的办法是考试和测验，这就是反馈。
#+end_quote

#+begin_quote
再牛的科学家，也需要同行评议，世界排名第一的运动员，也需要教练。反馈者不见得比你的水平高，关键是他们不是你，他们可以从你看不到的角度看你。
#+end_quote

#+begin_quote
一件事给你的信息也许是无比复杂的，但其中真正有用的也许就那么几项。专家要做的就是首先通过大量细致的数据统计来发现这几项有用的指标，以后就只看这些指标就行了。
#+end_quote

#+begin_quote
直觉，只有在「环境友好」的状态下才好使，所谓「环境友好」，就是其中有短期的反馈。只要有快速反馈，再进过长时间的训练，你就能培养出专家的直觉。
#+end_quote

#+begin_quote
培养人才的有效办法只有一个，那就是学徒制。师傅带着徒弟参与一个实际的项目，徒弟在试错中提高。不管是科研、工程还是艺术，都是如此。
#+end_quote

#+begin_quote
现代教育制度与其说是一种培养制度，不如说是一种选拔制度，或者更确切地说是一种淘汰制度。好的工作岗位有限，想干这个工作的人却很多。大学的真正作用是决定谁能进入到那个岗位上去。
#+end_quote

-----

#+begin_quote
学习时间长不等于用功，决定性因素不是学习时间，而是学习环境。必须在一个不受打扰的环境中单独学习，在这种环境下学习的时间才是有效时间。
#+end_quote

#+begin_quote
刻意学习不好玩，它要求练习者调动大量的身体和精神资源，全力投入。如果你觉得你在享受练习的过程，那你就不是刻意练习。
#+end_quote

#+begin_quote
在刻意学习中没有「寓教于乐」这个概念。你看纪录片也是为了娱乐，电影根本不是一个教育工具，哪怕是纪录片。纪录片对科学的作用并不在于让观众学到什么知识，而是激发观众对于科学的兴趣。

练习需要重复，而重复一定不好玩。教育需要全面，而娱乐一定只关注其中好玩的部分。所以娱乐和学习必然是不相容的。

如果你想学点知识，最好的办法是找本书——最好是正规的教科书或者专业著作——然后老老实实地找个没人的地方坐下反复读，而且还要自己整理笔记，甚至做习题获得反馈。
#+end_quote

-----

#+begin_quote
对于某些不相当普通人，一心想要出人头地的人来说，输了起跑线就没有机会参加后面的比赛了。

累死在起跑线当然不对，但牛人是赢在起跑线的。

很多人将会被淘汰，但是也有极少数人能够一路赢下来。世界就是属于这极少数人的，世界并不需要一千个钢琴大师或者一万个足球明星。如果你想享受快乐童年，你的位置在观众席。
#+end_quote

#+begin_quote
如果你想出类拔萃，那么你要参与的这场竞争很大程度上是一个零和博弈——你想赢就意味着有人要输。这种博弈对社会有没有好处对你来说不重要，你关心的是怎么做对自己有好处。这个博弈没有双赢。
#+end_quote

#+begin_quote
黑人身体素质好只是一方面，更重要的是但凡有点能耐的白人家庭都不会让孩子把赌注押在体育上。在阿根廷、巴西、葡萄牙、英国这些传统足球强国，只有不太富有的家庭的孩子才从小就把踢足球当作此生追求。
#+end_quote

#+begin_quote
亚裔家庭的孩子之所以意志力更强，跟家长给的奖励制度很有关系。其他族裔的家长给孩子买东西往往是兴之所至，而亚洲家长往往对孩子有清晰的目标：你必须完成这个目标才能获得奖励。
#+end_quote

#+begin_quote
刻意练习并不区分「要我练」和「我要练」，你只要按要求练就行了。

兴趣最大的作用是让人自己愿意在这个领域内苦练。学习一个技能的初期，智商可能是决定性因素。但是随着学习的深入，兴趣的作用可能就越来越大了，因为兴趣可以在很大程度上决定谁能坚持下来。
#+end_quote

#+begin_quote
环境可以影响基因表达，即便你的 DNA 里有绘画天赋，但是如果你没遇到这个环境，你的天赋也就完全表现不出来。更复杂的是人的任何一个特点都不是由一条基因决定的，这就使得我们几乎不可能单凭查看一个人的 DNA 来判断他有什么天赋。
#+end_quote

#+begin_quote
科学界的共识是，先天因素远远大于后天因素。

任何一种能够测量的心理特征，包括智商、兴趣爱好、性格、体育、幽默感、甚至爱不爱打手机，都是天生的。后天环境对智力和性格的影响非常有限。
#+end_quote

#+begin_quote
越是社会经济地位高的家庭，基因对孩子的影响越大；越是社会经济地位低的家庭，环境对孩子的影响越大。
#+end_quote

#+begin_quote
人并不仅仅被动地等着被环境改变，有一个理论认为，自然选择给了每个人不同的基因，而人可以出去寻找自己的基因所喜欢的环境。

寻找适合自己兴趣的环境，把自己的基因发扬光大——这难道不就是进化论告诉我们的人生意义吗？
#+end_quote

#+begin_quote
也许兴趣就是大师们最大的先天因素。每个人都有天生的不同兴趣，区别仅在于有的人足够幸运能够在比较早的时候就找到适合自己兴趣的环境。

家庭和社会能为人才做的最好的事情，就是提供能施展各种兴趣的环境。
#+end_quote

** 最高级的想象力是不自由的

#+begin_quote
儿童的确比大人更容易想象，这是因为儿童大脑的前额叶皮质并没有发育成熟，不太容易专注，思维表现得更加开放。但儿童的想象力也不是「无章可循」的，只有在理解了事物之间的因果关系之后，「想象」才成为可能。我不知道没有知识的人能想象出什么东西。
#+end_quote

#+begin_quote
初级的想象力就是在日常生活中玩「what if」游戏。一个整天问 what if 的人，可以写出一大堆童话故事来。郑渊洁的想象力就是这个级别的：如果把核儿吞到肚子里会不会长出樱桃树来？这个想象力并没有脱离「有核儿才能长成树」这个因果知识。
#+end_quote

#+begin_quote
写大著作，必须构建一个完全自洽的想象世界。中国导演拍不出来 Avatar，他们缺的不是「自由」，而是这种「不自由」的脑力和物力。
#+end_quote

#+begin_quote
「自由想象力崇拜」的背后，是「顿悟崇拜」。这种思想认为一般人终日被自己的知识所束缚，而一旦跳出这种束缚，就能够取得重大的突破。这种思想其实是对科学发现的庸俗解释。认为专业科学家被他们的知识所束缚，认为专业科学家缺乏想象力，是很多民间科学家安身立命的根本和愤愤不平的原因。但事实是专业科学家比民间科学家更有想象力。
#+end_quote

** 思维密集度与牛人的反击

#+begin_quote
思维密集度 = 准备这个读物需要的总时间 / 阅读这个读物需要的时间
#+end_quote

#+begin_quote
每个人的时间都一样多，因此时间不是金钱。时间是围棋：你走一手，牛人也走一手，牛人获胜并不是因为他走比你多，而是他每一手都走在最有价值的地方。
#+end_quote
** 上网能避免浅薄么？

#+begin_quote
上网是一个居高临下的姿态，我们游离在内容之外，面对众多等着被「临幸」的超链接想点哪篇从心所欲。

可是上网者才是真正的奴隶。相对于读书，网络阅读使我们能记住的信息更少，理解力和创造力下降，形成不了知识体系——互联网把我们的大脑变浅薄了。
#+end_quote

#+begin_quote
实验表明，网上冲浪可以增进做决策和解决问题的能力，这对老年人保持头脑年轻有好处，但坏处则是牺牲了深度理解。
#+end_quote

#+begin_quote
只有有意识的短期记忆，称为工作记忆，才有可能被转化为长期记忆。研究结果显示，人的工作记忆最多只能同时容纳 2 到 4 条信息。这样有限的容量非常容易被无关信息干扰导致过载。上网时分散的注意力，不停地为点还是不点做决定，都在阻碍我们把短期记忆升级为知识。
#+end_quote

#+begin_quote
考察地图、钟表和书籍技术对人类思维方式的影响，会发现技术并不仅仅为思维服务，技术能改变思维。比如地图就加强了人们抽象思维的能力。而互联网这个技术是用各种小信息去干扰人的思考。
#+end_quote

#+begin_quote
Google 的真正业务是搜索，利润的绝对大头是广告。一个盯着屏幕看的用户不会给它带来任何广告收入，你必须不停地搜索和点击。

Google 的核心战略就是让用户快来快走，它做的一切都是为这个战略服务。对 Google 来说，短而新的信息可以带来更多点击，价值远远超过经典长篇大论，它把所有书籍上网，正是把整体的书变成一堆可搜索的短信息的集合。
#+end_quote

#+begin_quote
廉价必然导致低俗流行。

在通讯和交通手段不发达的时代，出门看一场戏剧往往要花费很多时间和金钱，所以要看就看个经典的，而且戏剧往往很长。同样道理在中国发明纸张之前，竹简是昂贵而费力的信息载体，所以那时候的书本本都是经典。
#+end_quote

#+begin_quote
如果获得信息很容易，我们就会倾向于短小轻快的内容。这有一个心理学原因，那就是期待和尝试的乐趣。

另外，很多时候完成一个工作的乐趣集中在开始和结束，而不在漫长的中间过程，我们喜欢不断地开始和不断地结束。相对于一本 600 页的书，我们可能更想读两本 300 页的书。我们在网上追求能够立即满足的小刺激。
#+end_quote

#+begin_quote
新技术的最重要特性是允许我们定制自己接收的信息。网上阅读的要点在于选择和过滤，我们应该学会订阅特选的博客，访问专门的论坛，从而排除无关信息。
#+end_quote

#+begin_quote
自闭症患者往往因为大脑的缺陷而缺少对情感交流的解读能力。对人情的不解反而使他们让思想保持冷静客观。他们把更多的精力投入到对特定信息的收集，整理，分类和记忆中，是最极端的信息爱好者。

高效率的上网应该像自闭症患者一样具有很强的目的性，以我为主，不被无关信息左右。
#+end_quote

** 高效「冲浪」的办法

#+begin_quote
「窄框架」（narrow framing）和「宽框架」（broad framing）。所谓窄框架，就是遇到一个东西做一次决策，一事一议；而宽框架则是把所有东西都摆在桌面上集中选择。

好东西很多，我们不可能都选，最好的方法是使用宽框架思维，把所有需要你注意力的项目都摆在一起，从中选出最值得的一个。
#+end_quote

** 笔记本就是力量

#+begin_quote
高级的知识体系需要一个人不断地摸索总结，甚至直接为其内容做出贡献，才能逐渐掌握。
#+end_quote

#+begin_quote
真正的知识是分层的，你必须完全理解基础的一层，才能谈得上去看懂上面的一层。
#+end_quote

#+begin_quote
知识不能仅仅机械地「存」在你的脑子里，而必须以一种个性化的结构「长」在你的脑子里。

真正的专家，都有自己的一整套知识体系。这套体系就如同他们心中的一棵不断生枝长叶的树，又如同一张随时变大变复杂的网。每当有新的知识进来，他们都知道该把这个知识放到体系的什么位置上去。
#+end_quote

#+begin_quote
建立知识体系的第二要点，是要把新的知识跟自己已有的知识联系起来。一般人善于发现新事物的不同点，而真正的高手则善于发现共同点。
#+end_quote

** 用强力研读书

#+begin_quote
阅读有三个档次：为了娱乐而读，为了信息而读，为了理解而读。

首先，只有为了理解某个我们原来不懂的东西而读书，才值得认真对待。其次，读书应该以我为主，而不是以书为主。
#+end_quote

#+begin_quote
强力研读要求读书笔记必须包含四方面内容：

一、清晰地表现每一章的逻辑脉络；

二、带走书中所有的亮点；

三、有大量自己的看法和心得；

四、发现这本书和以前读过的其他书或文章的联系。
#+end_quote

#+begin_quote
阅读要求的是理性思考。一个好的读者不会因为偶尔发现了什么警句妙语而欣喜若狂或情不自禁地鼓掌——一个忙于分析的读者恐怕无暇顾及这些。
#+end_quote

#+begin_quote
低水平的读书人会在看完的书上画满了重点线，而高水平的人会在看完的书上写满了批注。

你不可能对说得好的一段话无动于衷。你可以写下自己对这件事的理解，你还可以写下对作者的质疑或肯定，更高级的批注则是写下自己因为看到这段文字而产生的灵感。
#+end_quote

#+begin_quote
世界上有很多比读书重要的事，在做事和读书之间，做事优先。但读书是除实践外迅速积累见识的最好办法。
#+end_quote

#+begin_quote
读书快的关键是你之前已经度过很多书，这样当你读一本新书的时候，你可以在相当的程度上预计作者在说什么。
#+end_quote

** 创新是落后者的特权：三个竞争故事

#+begin_quote
……可以改变你们公司的「新思想」。这些思想真的付诸实施，是有风险的。企业不能每年都搞一次这种彻底改革。对于领先的企业，更没有必要冒这种风险。谚语说，If it works, don’t fix it! 只有落后者反而可以冒这个风险，冒险至少还有赢的机会，不冒险就输定了。
#+end_quote

#+begin_quote
不管航线左侧风向是否真的有利，只要我们两个的条件能保持一样，那么最后肯定还是我赢，因为现在我领先。哪怕你的选择是错误的，为了确保胜利我也必须做跟你同样的选择。所以在这种一对一的帆船比赛中不是落后者学习领先者，而是领先者学习落后者。

像 IBM 这样的特大公司并不不以特别能创新而闻名，他们最大的能力恰恰是把那些已经被别人证明是好东西的技术迅速普及产业化。
#+end_quote

** 过度自信是创业者的通行证

#+begin_quote
心理学家对人性有一个基本认识，叫做「损失厌恶（Loss Aversion）」。这个原理说当面对「机遇与风险并存」的局面时，我们对损失的厌恶超过对获得的喜悦。它甚至可以被推广到更一般的情况：我们对失败的恐惧超过对成功的渴望。
#+end_quote

#+begin_quote
人们很乐意花一两元钱买明知道中奖概率很低预期收入为负数的彩票，但是赌注一旦增大，哪怕预期收入是正的，也只有亡命徒或者资本家才愿意玩。
#+end_quote

#+begin_quote
亚裔的本性似乎是非常不喜欢风险的，也许是土地文化与海盗文化的区别吧。
#+end_quote

#+begin_quote
人生面临一个风险悖论。如果你一辈子谨慎小心，干什么事情都谋定而后动，你的生活再差也差不到哪去；而如果你勇于承担风险大胆尝试，你可能特别失败，但也可能特别成功。
#+end_quote

#+begin_quote
过度自信者的竞争策略就是有枣没枣先打一杆子再说。如果恰好没人跟你争，你不就白白赢了一回么？就算有人争，也许他们还不如你。当那些非常有自知之明的人还在苦逼地计算得失概率的时候，过度自信者已经捷足先登了。

这个模型很好地解释了为什么有那么多美女最后落在了各方面条件非常一般的男生手里。
#+end_quote

** 夺魁者本色

#+begin_quote
一件事如果不是竞争，哪怕像高空跳伞一样惊险，做过三次以后你就会慢慢获得平常心；一件事如果是竞争，哪怕是舞蹈比赛，你不管比过多少次还是会同样感到压力。
#+end_quote

#+begin_quote
男人在决定参与竞争之前并不在乎失败的风险，可是竞争中一旦遇到挫折就容易放弃。女人却总能合理评估竞争风险，一般不爱竞争，但是一旦参与了，就算遇到挫折也常常能坚持下来。

在很多情况下，过度自信和敢出手恰恰是男人的优势。
#+end_quote

#+begin_quote
睾酮，可以让人在竞争中更敢于冒险，更乐意投入比赛，在比赛中更无私，更关心队友，更可能抗议对手犯规，甚至能更多地诉诸于理性认知而不是感情冲动。

一个人基础睾酮水平可以反映在无名指和食指的长度比上。胎儿在子宫中的发育同时受到睾酮和雌激素的影响。这两种激素影响胎儿大脑的同时，也影响手指。睾酮水平相对雌激素水平越高，人的无名指相对于食指就越长。
#+end_quote

#+begin_quote
如果你的 COMT 酶是快酶，那么你面对压力的时候就很容易保持一颗平常心。这并不是因为你主观上定力过人，而是因为多出来的多巴胺会被迅速清理掉。有些学者把这样的人成为「战士（Warriors）」，因为他们临危不惧。

而如果你的 COMT 酶是慢酶，那么面对压力多巴胺就容易过多，导致自己惊慌失措，这样的人则被称为「颤士（Worriers）」。

平时没有压力的时候战士的多巴胺也被清理的很快，于是他们就会表现为缺乏干劲，不兴奋。而颤士则因为平时也能维持一个比较高的多巴胺水平而表现很好。战士在战时表现超过颤士，颤士在平时表现超过战士。
#+end_quote

#+begin_quote
竞争其实有两种。一种是有限博弈（finite game），这种竞争就好像体育比赛一样有结束的时候，你比赛中必须全力以赴，比较强调爆发力，更适合男性或者战士参加。一种是无限博弈（infinite game），竞争永远都在进行，讲究持续力，需要你能够在其中偷偷地自我调整和恢复，更适合女性或者颤士参加。
#+end_quote

** 打游戏的三个境界

#+begin_quote
游戏吸引人的几个特点：

一、现实感；

二、随机性；

三、付出总有回报；

四、汇报是即时的。
#+end_quote

** 穷人和富人的人脉结构

#+begin_quote
整天跟你混在一起的这帮人，很可能干的事跟你差不多，想法必然也很接近，如果你不知道有一个这样的工作机会，他们又怎么会知道？只有「弱联系」才有可能告诉你一些你不知道的事情。

人脉的关键不在于你融入了哪个圈子，而在于你能接触多少圈外的人。

虽然人们重视强联系，人们的大部分知识还是来自弱联系。
#+end_quote

#+begin_quote
越是富裕的小区，其住户交往的“多样性”越明显。越是富人越容易跟不同阶层和不同地区的人联络，而且阶层多样性要比地区多样性更重要。正所谓「贫居闹市无人问，富在深山有远亲」。
#+end_quote

#+begin_quote
这种数据分析的问题在于它只能告诉我们社交网络跟经济地位之间有这么个关系，但不能告诉我们到底是谁导致谁。
#+end_quote

#+begin_quote
弱联系理论的本质不是「人脉」，而是信息的传递。亲朋好友很愿意跟我们交流，但是话说多了就没有新意了。最有效率的交流，也许是跟不太熟悉的对象进行的。
#+end_quote

#+begin_quote
Facebook 的一项研究通过随机试验的办法来跟踪特定的一组网页地址，结果发现别人分享地址给我们，我们看到以后再转发的可能性（p_feed），比我们自己看到这个地址直接分享的可能性（pno_feed），大五倍以上。
#+end_quote
* 第三章：霍金的答案
** 亚里士多德为何不数数妻子有几颗牙

#+begin_quote
科学知识是一种高度结构化的知识，其有一个很酷的性质：只要学会了一般原理，就能解决无穷多表面看来千奇百怪的问题。掌握科学知识的人有凭借理论推导就能破解世界的力量。
#+end_quote

#+begin_quote
科学家的工作不是使用科学知识，而是使用科学方法。
#+end_quote

#+begin_quote
现有的科学原理远未完备只是一个原因，更重要的原因是复杂现象涉及的数学计算和各种相关因素多到根本不可能用理论推导的程度。在这种情况下「动手」才是更直接了当的办法。
#+end_quote

** 物理学的逻辑和霍金的答案

#+begin_quote
判断一个物理理论的好坏不在于这个理论是否符合人的直觉，或者是否够漂亮，而在于它能不能做出预言。
#+end_quote

#+begin_quote
物理学家也有一个可以称作「信念」的东西，这个信念就是世界应该是合「理」的。也就是说，物理定律应该适用于所有时间和所有地点，所有事件都必须精确地符合描写物理定律的数学方程。
#+end_quote

#+begin_quote
地球在太阳系的位置实在是太幸运了。方程表明一个行星的轨道在一般情况下应该是椭圆形，圆形是非常特殊的情况。如果地球轨道是椭圆，哪怕「椭」的不是特别厉害，其近日点和远日点的温度也将会非常不同，而不会有像现在这样一年四季温度相差不算太大的环境。而地球的轨道几乎就是圆的！地球四季的温差几乎完全来自自转和公转的倾角，而与距离太阳远近无关。
#+end_quote

#+begin_quote
霍金首先用所谓「无边界条件」来取消了「宇宙创生之前发生了什么」这个问题，这个条件说在早期宇宙的极端条件下，时间维被扭曲得好像一个空间维，也就是说那时候有四维空间而没有时间，也就不存在「之前」的问题了。
#+end_quote

** 怎样用统计实验检验灵魂转世假说

#+begin_quote
一个有灵魂的世界，和一个没有灵魂的世界的表现如果完全一样，也就是灵魂不可测量，那么有没有灵魂这个问题就毫无意义。
#+end_quote

** 一个关于转世的流行病学研究

#+begin_quote
通过纯粹的被动调查来做研究的方法叫做「流行病学（epidemiology）」。最容易的流行病学研究是所谓回顾性（retrospective）的问卷调查：先找到病人，然后询问并比较他们的生活方式。这种调查的难度在于病人对自己以往生活的回忆常常不准确，甚至是有偏见的。

比如吸烟是否有害健康或者受虐待儿童长大以后是否犯罪率更高之类，往往根本不可能做实验，而只能采取搜集案例，通过流行病学进行做统计分析。

流行病学的结果远远不能作为最后的科学结论，但是这个方法是仍然是科学方法，也可以说是在你没有别的办法的时候所能使用的最科学办法。
#+end_quote

#+begin_quote
现有的科学理论对世界的解释已经相当不错了。一个没有转世现象的世界观并没有让任何科学家感到不安。

如果转世存在，那么就应该无处不在，更进一步灵异现象也应该无处不在，我们生活中应该时刻都有一些使用现代科学解释不了的现象。而事实是灵异现象都比较罕见。
#+end_quote

#+begin_quote
哪怕你关心的是「灵魂转世」这样的问题，你唯一正确的判断办法仍然是科学方法。
#+end_quote
** 摆脱童稚状态

#+begin_quote
相关性研究只是科研的初级阶段。但就是这样它也已经超越了我们的思维本能。

「一朝被蛇咬十年怕井绳」，是人这种动物的最自然思维，而使用大规模统计发现实在的相关性这个最简单的科学方法，是我们摆脱童稚状态的第一步。
#+end_quote

#+begin_quote
「中国 80% 的青少年犯罪与网瘾有关，中国 20% 的网瘾少年有违法犯罪行为。」可以构建这么一个国家，这个国家 80% 以上的青少年有网瘾，而这个国家的所有青少年，不管有没有网瘾，都有 20% 的犯罪概率。这个虚拟国家完美符合以上数据，但是它的犯罪与网瘾完全无关。

这个错误就是没有建立对照组。我们缺少的关键数据是没有网瘾的青少年的犯罪率，以及没有犯罪的青少年的网瘾率。
#+end_quote

#+begin_quote
有相关性未必说明有因果关系，这是一个非常重要的思维。
#+end_quote

#+begin_quote
想要明确证明吸烟导致肺癌，唯一的办法是做实验。找完全相同的两组健康的人，让其中一组吸烟另一组不吸，其它各方面生活都完全一致。20 年之后如果吸烟组中的肺癌患者数高于不吸烟组，那么鉴于这两个组的唯一区别就是吸烟，我们就可以断定是吸烟导致了肺癌。

可是现实世界中根本不存在「完全相同」的两组人，这种理想实验无法进行。好在科学家有一个退而求其次的巧妙办法：找一群人，然后完全随机地把他们分为两组去做实验。在样本数足够大的情况下，随机性可以保证任何不同因素都可以大致均匀地分配到两个组里。这就是在关于人的研究中最重要，也是最可靠的办法。
#+end_quote

#+begin_quote
不管调查到什么程度，都只是对真实世界的管中窥豹。科学研究的是有限的真理。当一篇论文说什么东西可能或者不可能导致什么疾病的时候，它说的其实是在这次研究所调查的这帮人里面有这么一个结论。

很多实验心理学家选择的样本全是在校大学生，他们的结果能推广到所有人么？有人对此讥讽说他们研究的心理学应该叫「大学生心理学」。
#+end_quote

#+begin_quote
每一篇论文都是我们从个人感觉到客观事实，从客观事实到因果关系，从因果关系到能推广使用的机制，这个过程中的一小步。这个过程的每一步都不是完美的，但只有这么做，我们才能摆脱童稚状态。
#+end_quote

** 怎样才算主流科学？

#+begin_quote
科学研究就是这么一个把新思想逐渐变成主流的过程。从这个意义上讲也许真正活跃的科学根本就没主流，或者说主流科学都是死的科学，更严格的说是凝固了的科学。
#+end_quote

#+begin_quote
怎样才算主流科学？你必须得能用现有的理论去解释你的新理论。如果主流科学是一棵大树，你的新理论不能独立于这棵树之外。你必须告诉别人这棵树的这几个位置可以长出这么几个树枝来，而这些树枝可以连接到我的新理论上去 — 这样你的理论就成了这树的一部分。
#+end_quote

** 医学研究能当真么？

#+begin_quote
在医学研究中被广泛使用的统计方法，其实是个非常脆弱的体系。如果你的一项研究是考察某种药物对人的健康是否好处，而你希望能证明有好处的话，你将很容易做到这一点。

首先，现在大部分医学科研研究的效应其实都是比较微弱的，因为不微弱的效应别人早就研究完了。其次，什么叫对健康有好处？也许一个病人的病情并没有什么明显好转，但因为你希望这个药物有效，你也许会完全无意识的刻意寻找他好转的证据，你可能会把本来没什么好转的病人当成好转的病人。
#+end_quote

#+begin_quote
看新闻不如看论文，看一篇论文不如把多篇论文综合在一起看（称为 meta-analysis）。
#+end_quote

** 真空农场中的球形鸡

#+begin_quote
任何科学研究中的任何计算都是针对科学家选择的模型，而不是针对「真实世界」本身。
#+end_quote

#+begin_quote
我们必须使用模型的本质原因是，我们对世界的观察是主观的。
#+end_quote

#+begin_quote
所有物理定律，乃至所有科学理论，都只不过是主观模型。托勒密的理论说地球静止，太阳绕着地球转；而哥白尼的理论说太阳静止，地球绕着太阳转 — 这两个模型其实都可以用，只不过其中一个比另一个更好用一点。

物理学革命其实就是用一个模型取代另一个模型。我们可以把力解释成一种波动的场，或者空间的弯曲，或者一堆粒子的来回传递，或者又把各种粒子解释成弦的震动。当物理学家发明这些模型的时候，他们心里想的并不是「真实的力到底是什么东西呢？」他们想的是什么模型有效就用什么模型！

科学这门业务的工作方式，是从来不直接追求那个「最后的，真正的现实」，而只是不停地用不同的模型去模拟现实。
#+end_quote

#+begin_quote
也许有些科学家的确相信绝对真理的存在 — 但科学研究从来不涉及绝对真理。哲学才研究绝对真理。科学研究的是「有效的真理」，是「有限的真理」。
#+end_quote

#+begin_quote
……「大量观测事实」支持的结果……用观测事实调参数凑答案的结果（叫做「parameterisation」），这些模型在很大程度上是基于经验的。

既然你的模型中有很多参数都是用历史数据拟合出来的，这些模型能够再现历史就不奇怪，最关键的测试还是你能不能预测未来。
#+end_quote

#+begin_quote
一共有十个预报员，每天投票预报，如果有 3 个人认为会下雨，我们就说降雨概率是 30%。IPCC 预测未来的办法跟这个有点类似。一个最常用的办法，是把各个不同气候模型综合起来取平均值。比如把 12 个国家的 17 个研究组使用的 24 个模型取平均。
#+end_quote
