#+SETUPFILE: ../../styles/readtheorg.setup
#+TITLE: 我知道你明天干了什么

* 第一章

#+BEGIN_QUOTE
一种科学理论，只是基于归纳法作出的判断，需要实验来验证。很多人渴望并相信有一种完备的、不需要再修正的权威理论系统，而合理的科学观与此相反，现存的任何权威科学理论，都只是过去经受住了实验验证的假设而已。经过多次实验成功的验证后，假设就可以成为理论。但所有的理论都不是绝对正确的，它们只是「经过多次实验验证的假设」而已，也许未来有了更精密的观测方法和更合理的实验手段，它们就会被修正，甚至被推翻。
#+END_QUOTE

#+BEGIN_QUOTE
所有科学理论就是建立在科学家们对「黑箱」内事物的「猜测」之上。因为在建立「黑箱模型」时，有可能出现模型非常复杂的情况（针对疑问提出的假设性修正，使理论本身不可证伪），英国哲学家 William of Occam 提出了一个 Occam's razor 理论：可接受的假设应该是能解释一切已知现象的最简单的假设。
#+END_QUOTE

#+BEGIN_QUOTE
一般来说，科学实验应该先假设要证明的理论是错误的，然后千方百计去驳倒它，当无论如何不能驳倒那个理论的时候，只有承认：到目前为止，该理论解释某一现象是最合理的。伟大的科学家们不会因为被怀疑而生气，因为他们就是通过怀疑别人来使科学进步的。没有哪位科学家是伟大到神圣不可侵犯之地步的，真理比他们更伟大，而所有人都有权追求真理。
#+END_QUOTE

#+BEGIN_QUOTE
一千个实验也不能证明我是对的，但一个实验就能证明我是错的。 ― Albert Einstein
#+END_QUOTE

* 第二章

#+BEGIN_QUOTE
人类最初的梦想有三个：控制自己的生存环境，控制其他人，长生不老。 ― James E. Gunn
#+END_QUOTE

#+BEGIN_QUOTE
张岱《夜航船》里说：「律令，雷边捷鬼，行最疾。」原来，律令是一种小鬼，归雷神管，跑动最快。
#+END_QUOTE

* 第四章

#+BEGIN_QUOTE
如果一位权威断定某事是可能的，他多半是对的；而当他说某事不可能时，他一定错了。 ― Arthur C. Clarke
#+END_QUOTE

* 第五章

#+BEGIN_QUOTE
一个人如不愿意被催眠，那么无论多么强力的催眠师对他都无能为力。
#+END_QUOTE

* 第六章

#+BEGIN_QUOTE
受精卵在第一次分裂成为两个细胞后，是否就有了一个对称的「正中面」，使得其中一个细胞注定要发育成该生物的左半边，而另一个细胞则发育成右半边？原生动物门以上的任何动物的卵，都有一个「极轴」，这条极轴连同精子钻进该卵的那一点，就确定了一个平面。科学家们假设这个平面就是第一次分裂时的「正中面」。有证据表明很多动物符合这种情况。
#+END_QUOTE

* 第七章

#+BEGIN_QUOTE
每一种新产业都会引起一定范围内的失业问题，同时也会创造很多新的就业机会。有很多职业是在此之前想象不到的，有人曾在马车终结的时代想到「车模」这个职业吗？
#+END_QUOTE

* 第八章

#+BEGIN_QUOTE
「破脚骨」的全部人生价值就建立在谁比较能够忍痛上面。他们如果找人单挑，就是一人一把小刀，各自往自己身上刺，我刺哪里一刀，你也必须照样奉陪一刀，哪一个先受不了，他就输了。
#+END_QUOTE

#+BEGIN_QUOTE
「怕痛」作为一项有利于生存的遗传特征被保存下来，这就是自然选择。虽然疼痛是动物用来避免伤害的一种信号，但当死亡无法避免时，疼痛就是不必要且无价值的了。动物会「关闭」对疼痛的感觉，干脆昏迷了。
#+END_QUOTE
