#+setupfile: ../../styles/readtheorg.setup
#+title: 180° South

* #1

10 years ago, l found that old footage of Doug and Yvon's trip to Patagonia back in 1968. lt was like seeing everything l'd ever wanted to do in my life. From that point on, l promised myself that someday l'd find a way to do a trip like theirs. Years went by before I finally got my chance. l heard about a boat docked down in Mexico that was headed for Patagonia. They needed a crew, and I needed a ride south.

My name is Jeff Johnson. Look in any phone book, and you'll find 10 of me. l grew up in Danville, California. You've probably never heard of it, but it's a long way from the ocean and the mountains.

When I was eight years old, two things set me on the path that l'm still on. The first one was when my parents took me on a camping trip to Yosemite Valley. l remember looking through a telescope up at this huge granite wall and guys climbing thousands of feet up. l couldn't believe my eyes. lt was like watching men walk on the moon.

That same year I saw surfing for the first time, on TV, "Wide World of Sports." l saw these guys riding massive walls of water. There were people out there putting themselves in places they weren't supposed to be. And I knew right then that I wanted to be there, too.

* #2

Most of my life, l've figured out ways to pick up and leave as the seasons change. l've been a dishwasher, a lifeguard, a flight attendant - whatever it took to pay for the next trip. ln the last couple years, though, l've found a real job. l've started planting some roots, and l've spent a lot less time on the road. But I never forgot about my dream of seeing Patagonia with my own eyes.

Sure, I could take my two weeks' vacation time and just fly down to Patagonia, but l'll never get a chance like this one again. lf I don't get on that boat, l know exactly what l'm going home to. lf I do, my future is unwritten.

l'm drawn to open country. lt's where everything becomes clear, where the world makes the most sense. When I put myself out there, l always return with something new. A friend once told me, "The best journeys answer questions that in the beginning you didn't even think to ask."

* #3

Taking a trip for six months, you get into the rhythm of it. lt feels like you can just go on forever doing that. Climbing Everest is the ultimate and the opposite of that because you get all these high-powered plastic surgeons and CEOs, and, you know, they pay $80,000 and have sherpas who put all the ladders in place and 8,000 feet of fixed ropes, and you get to a camp and you don't even have to lay out your sleeping bag. lt's already laid out with a little chocolate mint on the top.

And the whole purpose of climbing something like Everest is to affect some sort of spiritual and physical gain, but if you compromise the process, you're an asshole when you start out and you're an asshole when you get back.

* #4

Yvon had told me about Jared Diamond's book Collapse and how Diamond presents Easter lsland as a cautionary tale - a grim example of a society that exceeded its resources and suffered the consequences.

When the first Europeans set foot on Easter lsland in 17-something, all the Moai were all standing upright. But as the population increased, the people started separating out into different little tribes, putting all their time and energy into, you know, outdoing each other, making larger and larger Moais. And that became the central focus of the entire society. lt took priority over survival, almost. And eventually they would cut down their entire forests to transport these giant carved stones. And this became such an obsession that they depleted the island's resources, and it led to tribal warfare, cannibalism, and eventually the population of the island of 30,000 was finally reduced down to 111 people.

l've met Jared Diamond a few times and talked about his book Collapse and how all the different societies of the past that he's studied that have collapsed, and what does that mean for our society, and in the end he really says that we're making all the same mistakes that all of these other societies have made.

As the story of Easter lsland goes, so goes the planet. lt's a haunting thought, and l'm beginning to see these statues a little differently. l remember a quote I read one time from Aldous Huxley. lt never resonated with me much until now. He wrote, "Men do not learn very much from the lessons of history, and that is the most important of all the lessons of history."

* #5

This journey was like going back in time... Like seeing North America before it became dominated by industry. But for these people, it's not some nostalgic trip into the past. lt's their present. Their hard work and ability to live simply with the land is proof that we can learn from tradition. These people have shown me that if you love a place, you have a duty to protect it, and to love a place, you must know it first.

This is one of the rivers the gauchos have been trying to protect, and where one of five dams is supposed to go in. l'm certainly no expert, but those fallen statues in Rapa Nui are seared in my memory. Lying face down in the dirt, it's like they're trying to tell us something.

l left home six months ago to follow in the footsteps of my heroes. A bit of surfing, some climbing, lots of unspoiled terrain. Pretty simple, really. Well, I got all that, but along the way, l've also begun to make connections that I never thought much about. ln these far corners of the world, l am seeing the effects of encroaching progress. And most of this has to do with overconsumption elsewhere. lt's easy for us to blindly consume when we don't see the effect it has on other places.

The hardest thing in the world is to simplify your life. lt's so easy to make it complex. Βut what's important is leading an examined life because most of the damage caused by humans is caused unintentionally, I think.

In response to people who say, "You can't go back," say, "Well, what happens if you get to the cliff, and do you take one step forward or you do a 180-degree turn and take one step forward? Which way are you going? Which is progress?"

The solution may be for a lot of the world's problems is to turn around and take a forward step. You can't just keep trying to make a flawed system work.
