#+SETUPFILE: ../../styles/readtheorg.setup
#+TITLE: Civilisations 2018

* Episode 1: Second Moment of Creation

#+BEGIN_QUOTE
I've always felt at home in the past. For after all, what is the present except an endless chain of memories?
#+END_QUOTE

#+BEGIN_QUOTE
We can spend a lot of time debating what civilisation is or isn't, but when its opposite shows up in all its brutality and cruelty and intolerance and lust for destruction, we know what civilisation is.
#+END_QUOTE

#+BEGIN_QUOTE
The record of human history brims over with the rage to destroy. But it's also imprinted with the opposite instinct - to make things that go beyond the demands of food and shelter,  things that make us see the world and our place in it  in a different light. We are the art-making animal.
#+END_QUOTE

#+BEGIN_QUOTE
All civilisations want what they can't have - the conquest of time. They build higher and grander to escape mortality. It never works. There's always an ending. Cities with their markets, temples, palaces and tombs are simply abandoned and that great leveller, Mother Nature, closes in, strangling the place with vegetation, covering it with desert sand. It might seem, then, that it's all for nothing, but that's entirely wrong. All these ruins, all these remains are monuments to human creativity, human ambitions, human hopes. Monuments to shaping hands and shaping minds. Monuments to humanity itself.
#+END_QUOTE
* Episode 2: How Do We Look

#+BEGIN_QUOTE
When Romans thought about where the impulse to portraiture came from - even the impulse to painting as a whole - they had a very vivid story to tell about a young woman who was the creative genius behind the very first portrait. Her lover was going away on a long journey and before he went, she got a lamp and she threw his shadow against a wall and traced round it to create a silhouette. She was trying not just to memorialise him, but to keep his presence in her world.
#+END_QUOTE
