#+SETUPFILE: ../../styles/readtheorg.setup
#+TITLE: Cosmos

* Episode 1: The Shores of the Cosmic Ocean

#+BEGIN_QUOTE
When Carl Sagan, Steven Soter and I wrote the Cosmos TV series in the late 1970s, a lot of things were different. Back then, the U.S. and the Soviet Union held the whole planet in their perpetual hostage crisis called the Cold War. The wealth and scientific ingenuity of our civilization was being squandered on a runaway arms raise. Then employed more than half the world's scientists and infested the world with 50,000 nuclear weapons.

So much has happened since then. The Cold War is history and science has made great strides. We've completed the spacecraft recognizance of the Solar System, the preliminary mapping of the visible universe that surrounds us, and we've charted the universe within: the human genome. When Cosmos was first broadcast, there was no World Wide Web. It was a different world.

What a tribute to Carl Sagan, a scientist who took many a punch for daring to speculate, that even after 20 of the most eventful years in the history of science, Cosmos requires few revisions and indeed is rich in prophecy. Cosmos is both the history of the scientific enterprise and an attempt to convey the spiritual high of its central revelation: our oneness with the universe.

... Cosmos, the proud saga of how through the searching of 40,000 generations of our ancestors, we have come to discover our coordinates in space and in time. And how, through the awesomely powerful method of science, we have been able to reconstruct the sweep of cosmic evolution and defined our own part in its great story.
#+END_QUOTE
