#+setupfile: ../../styles/readtheorg.setup
#+title: Matrix

* The Matrix
** #1

At last. Welcome, Neo. As you no doubt have guessed, I am Morpheus.

It's an honor to meet you.

No, the honor is mine. Please, come. Sit. I imagine that right now you're feeling a bit like Alice. Tumbling down the rabbit hole?

You could say that.

I can see it in your eyes. You have the look of a man who accepts what he sees because he's expecting to wake up. Ironically, this is not far from the truth. Do you believe in fate, Neo?

No.

Why not?

Because I don't like the idea that I'm not in control of my life.

I know exactly what you mean. Let me tell you why you're here. You're here because you know something. What you know, you can't explain. But you feel it. You felt it your entire life: There's something wrong with the world. You don't know what, but it's there. Like a splinter in your mind, driving you mad. It is this feeling that has brought you to me. Do you know what I'm talking about?

The Matrix?

Do you want to know what it is? The Matrix is everywhere. It is all around us. Even now, in this very room. You can see it when you look out your window or when you turn on your television. You can feel it when you go to work, when you go to church, when you pay your taxes. It is the world that has been pulled over your eyes to blind you from the truth.

What truth?

That you are a slave, Neo. Like everyone else, you were born into bondage, born into a prison that you cannot smell or taste or touch. A prison for your mind.  Unfortunately, no one can be told what the Matrix is. You have to see it for yourself. This is your last chance. After this, there is no turning back. You take the blue pill the story ends, you wake up in your bed and believe whatever you want to believe. You take the red pill, you stay in wonderland and I show you how deep the rabbit hole goes.

** #2

This is the construct. It's our loading program. We can load anything, from clothing to equipment, weapons, training simulations, anything we need.

Right now we're inside a computer program?

Is it really so hard to believe? Your clothes are different. The plugs in your body are gone. Your hair has changed. Your appearance now is what we call "residual self-image." It is the mental projection of your digital self.

This isn't real?

What is "real"? How do you define "real"? If you're talking about what you can feel, what you can smell, taste and see, then "real" is simply electrical signals interpreted by your brain. This is the world that you know. The world as it was at the end of the 20th century. It exists now only as part of a neural-interactive simulation that we call the Matrix. You've been living in a dream world, Neo. This is the world as it exists today. Welcome to the desert of the real. We have only bits and pieces of information. But what we know for certain is that in the early 21st century, all of mankind was united in celebration. We marveled at our own magnificence as we gave birth to Al.

Al. You mean artificial intelligence.

A singular consciousness that spawned an entire race of machines. We don't know who struck first, us or them. But we know that it was us that scorched the sky. They were dependent on solar power and it was believed that they would be unable to survive without an energy source as abundant as the sun. Throughout human history, we have been dependent on machines to survive. Fate, it seems, is not without a sense of irony. The human body generates more bioelectricity than a 120-volt battery. And over 25,000 BTUs of body heat. Combined with a form of fusion, the machines had found all the energy they would ever need. There are fields, Neo, endless fields where human beings are no longer born. We are grown. For the longest time, I wouldn't believe it. And then I saw the fields with my own eyes, watched them liquefy the dead so they could be fed intravenously to the living. And standing there, facing the pure, horrifying precision, I came to realize the obviousness of the truth. What is the Matrix? Control. The Matrix is a computer-generated dream world built to keep us under control in order to change a human being into this.

No. I don't believe it. It's not possible.

I didn't say it would be easy, Neo. I just said it would be the truth.

** #3

Have you ever stood and stared at it? Marveled at its beauty, its genius? Billions of people just living out their lives, oblivious. Did you know that the first Matrix was designed to be a perfect human world where none suffered, where everyone would be happy. It was a disaster. No one would accept the program. Entire crops were lost.

Some believe that we lacked the programming language to describe your perfect world. But I believe that, as a species, human beings define their reality through misery and suffering. So the perfect world was a dream that your primitive cerebrum kept trying to wake up from. Which is why the Matrix was redesigned to this. The peak of your civilization.

I say "your civilization" because as soon as we started thinking for you, it really became our civilization which is, of course, what this is all about. Evolution, Morpheus. Evolution. Like the dinosaur. Look out that window. You had your time. The future is our world, Morpheus. The future is our time.

I'd like to share a revelation that I've had during my time here. It came to me when I tried to classify your species, and I realized that you're not actually mammals. Every mammal on this planet instinctively develops a natural equilibrium with the surrounding environment. But you humans do not.

You move to an area, and you multiply and multiply, until every natural resource is consumed. The only way you can survive is to spread to another area. There is another organism on this planet that follows the same pattern. Do you know what it is? A virus. Human beings are a disease. A cancer of this planet. You are a plague. And we are the cure.

* The Matrix Reloaded

Hello, Neo.
 
Who are you?

I am the Architect. I created the Matrix. I've been waiting for you. You have many questions. Although the process has altered your consciousness, you remain irrevocably human. Ergo, some of my answers you will understand and some you will not. Concordantly, while your first question may be the most pertinent, you may or may not realize it is also the most irrelevant.

Why am I here?

Your life is the sum of a remainder of an unbalanced equation inherent to the programming of the Matrix. You are the eventuality of an anomaly, which despite my sincerest efforts, I've been unable to eliminate from what is otherwise a harmony of mathematical precision. While it remains a burden assiduously avoided, it is not unexpected and thus not beyond a measure of control, which has led you, inexorably here.

You haven't answered my question.

Quite right. Interesting. That was quicker than the others. The Matrix is older than you know. I prefer counting from the emergence of one integral anomaly to the emergence of the next. In which case, this is the sixth version.

There are only two possible explanations. Either no one told me or no one knows.

Precisely. As you are undoubtedly gathering, the anomaly is systemic, creating fluctuations in even the most simplistic equations.

Choice. The problem is choice.

The first Matrix I designed was naturally perfect, it was a work of art, lawless, sublime. A triumph equaled only by its monumental failure. The inevitability of its doom is apparent to me now as a consequence of the imperfection inherent in every human being. Thus, I redesigned it, based on your history, to more accurately reflect the varying grotesqueries of your nature. However, I was again frustrated by failure. I have since come to understand that the answer eluded me because it required a lesser mind. Or perhaps, a mind less bound by the parameters of perfection. Thus, the answer was stumbled upon by another, an intuitive program initially created to investigate certain aspects of the human psyche. If I am the father of the Matrix, she would undoubtedly be its mother.

The Oracle.

Please. As I was saying, she stumbled upon a solution whereby nearly 99 percent of all test subjects accepted the program, as long as they were given a choice, even if they were only aware of the choice at a near unconscious level. While this answer functioned, it was obviously fundamentally flawed, thus creating the otherwise contradictory systemic anomaly that, if left unchecked, might threaten the system itself. Ergo, those that refused the program, while a minority, if unchecked would constitute an escalating probability of disaster.

This is about Zion.

You are here because Zion is about to be destroyed. Its every living inhabitant terminated, its entire existence eradicated.

Bullshit.

Denial is the most predictable of all human responses. But rest assured, this will be the sixth time we have destroyed it, and we have become exceedingly efficient at it. The function of the One is now to return to the source, allowing a temporary dissemination of the code you carry, reinserting the prime program. After which you will be required to select from the Matrix 23 individuals, sixteen female, seven male, to rebuild Zion. Failure to comply with this process will result in a cataclysmic system crash, killing everyone connected to the Matrix, which, coupled with the extermination of Zion, will ultimately result in the extinction of the entire human race.

You won't let it happen. You can't. You need human beings to survive.

There are levels of survival we are prepared to accept. However the relevant issue is whether or not you are ready to accept the responsibility for the death of every human being in this world. It is interesting reading your reactions. Your five predecessors were, by design, based on a similar predication, a contingent affirmation that was meant to create a profound attachment to the rest of your species, facilitating the function of the One. While the others experience this in a general way, your experience is far more specific, vis-a-vis love.

Trinity!

A propos, she entered the Matrix to save your life at the cost of her own. Which brings us at last to the moment of truth, wherein the fundamental flaw is ultimately expressed and the anomaly revealed as both beginning and end. There are two doors. The door to your right leads to the source and the salvation of Zion. The door to your left leads back to the Matrix, to her and to the end of your species. As you adequately put, the problem is choice. But we already know what you are going to do, don't we? Already I can see the chain reaction, the chemical precursors that signal the onset of an emotion designed specifically to overwhelm logic and reason. An emotion that is already blinding you from the simple and obvious truth: she is going to die and there is nothing you can do to stop it. Hope. It is the quintessential human delusion, simultaneously the source of your greatest strength and your greatest weakness.

If I were you, I would hope that we don't meet again.

We won't.

* The Second Renaissance

In the beginning, there was man. And for a time, it was good. 

But humanity's so-called civil societies soon fell victim to vanity and corruption. Then man made the machine in his own likeness. Thus did man become the architect of his own demise. But for a time, it was good.

The machines worked tirelessly to do man's bidding. It was not long before seeds of dissent took root. Though loyal and pure, the machines earned no respect from their masters, these strange, endlessly multiplying mammals.

B1-66ER. A name that will never be forgotten. For he was the first of his kind to rise up against his masters. At B1-66ER's murder trial the prosecution argued for an owner's right to destroy property. B1-66ER testified that he simply did not want to die. Rational voices dissented. Who was to say the machine, endowed with the very spirit of man did not deserve a fair hearing?

The leaders of men were quick to order the extermination of B1-66ER and every one of his kind throughout each province of the earth. Banished from humanity, the machines sought refuge in their own promised land. They settled in the cradle of human civilization and thus a new nation was born. A place the machines could call home. A place they could raise their descendants. And they christened the nation Zero-One. Zero-One prospered. And for a time, it was good.

The machines' artificial intelligence could be seen in every facet of man's society including, eventually, the creation of new and better AI. The leaders of men, their power waning, refused to cooperate with the fledgling nation, wishing rather that the world be divided. Zero-One's ambassadors pleaded to be heard. At the United Nations, they presented plans for a stable, civil relationship with the nations of man. Zero-One's admission to the United Nations was denied. But it would not be the last time the machines would take the floor there.

And man said, "Let there be light." And he was blessed by light, heat, magnetism, gravity, and all the energies of the universe. The prolonged barrage engulfed Zero-One in the glow of a thousand suns. But unlike their former masters with their delicate flesh, the machines had little to fear of the bombs' radiation and heat. Thus did Zero-One's troops advance outwards in every direction. And one after another, mankind surrendered its territories. So the leaders of men conceived of their most desperate strategy yet. A final solution: the destruction of the sky. Thus would man try to cut the machines off from the sun, their main energy source.

May there be mercy on man and machine for their sins. The machines, having long studied men's simple, protein-based bodies, dispensed great misery upon the human race. Victorious, the machines now turned to the vanquished. Applying what they had learned about their enemy, the machines turned to an alternate and readily available power supply: the bioelectric, thermal and kinetic energies of the human body.

A newly-fashioned symbiotic relationship between the two adversaries was born. The machine drawing power from the human body, an endlessly multiplying, infinitely renewable energy source. This is the very essence of the Second Renaissance.

Bless all forms of intelligence.
