#+SETUPFILE: ../../styles/readtheorg.setup
#+TITLE: The Vietnam War

* Episode 1

#+BEGIN_QUOTE
One of the things that I learned in the war is that we're not the top species on the planet because we're nice. People talk a lot about how well the military turns kids into killing machines. And I'll always argue that it's just finishing school.
#+END_QUOTE

America's involvement in Vietnam began in secrecy. It ended, 30 years later, in failure, witnessed by the entire world. It was begun in good faith by decent people out of fateful misunderstandings, American overconfidence, and Cold War miscalculation. And it was prolonged because it seemed easier to muddle through than admit that it had been caused by tragic decisions, made by five American presidents, belonging to both political parties.

Before the war was over, more than 58,000 Americans would be dead. At least 250,000 South Vietnamese troops died in the conflict, as well. So did over a million North Vietnamese soldiers and Viet Cong guerrillas. Two million civilians, north and south, are thought to have perished, as well as tens of thousands more in the neighboring states of Laos and Cambodia.

For many Vietnamese, it was a brutal civil war; for others, the bloody climactic chapter in a century-old struggle for independence. For those Americans who fought in it, and for those who fought against it back home, as well as for those who merely glimpsed it on the nightly news, the Vietnam War was a decade of agony, the most divisive period since the Civil War.

-----

The French conquest of Indochina began with an attack on the ancient Vietnamese port of Danang in 1858. It took 50 years to lay claim to the whole region The Vietnamese people did not take easily to French occupation, just as they had fought against earlier invasions by the Chinese. By the early 20th century, nationalism was on the rise.

In the spring of 1919, the victorious Allied Powers met in Paris to rebuild a world shattered by the Great War. A 29-year-old man appeared with a petition for President Woodrow Wilson. Inspired by Wilson's declaration that the interests of colonial peoples should be given equal weight with those of their European rulers, the man was asking that this principle be applied to his homeland. His name was Nguyen Tat Thanh. During his long, shadowy career, he would adopt some 70 different pseudonyms, finally settling on "the most enlightened one" - Ho Chi Minh.

By 1940, much of the world was at war again. Imperial Japan threatened many of the European colonies in Asia, and occupied Vietnam, where they permitted their allies, the collaborationist French, to continue to oversee their colony.

In February of 1941, after three decades away from his homeland, Ho Chi Minh slipped back across the Chinese border into Vietnam and set up headquarters near the remote village of Pac Bo in a limestone cave at the side of a mountain There, he founded a revolutionary movement, which he called the Vietnam Independence League - the Viet Minh.

By the spring of 1945, more than three years after the Japanese attack on Pearl Harbor, the United States government was looking for allies behind the lines in Vietnam, when they were contacted by Ho Chi Minh. The OSS, the secret wartime precursor of the CIA, supplied Ho's ragtag guerrillas with arms.

When an atomic bomb destroyed Hiroshima, and three days later a second one destroyed Nagasaki, Japanese surrender seemed imminent. Ho Chi Minh called upon all Vietnamese to rise up and take over their own country before the Free French could reestablish their old colonial regime.

-----

Ho Chi Minh had great hopes that the U.S. would support the Vietnam desire for independence. His hopes for American support were calculated but understandable. President Franklin Roosevelt had promised a postwar world that would "respect the rights of all peoples to choose the form of government under which they live." But Roosevelt was dead now, and his successor, Harry Truman, had inherited a very different world.

The alliance with the Soviet Union that had won the Second World War had collapsed. The Soviets now occupied the Eastern European countries they had overrun, and hoped to spread their influence farther, into Iran, Turkey, and the Mediterranean. A new cold war had begun. French president Charles De Gaulle warned that if the United States insisted on independence for her colonies, France might have no choice but to "fall into the Russian orbit." The United States was officially neutral, hoping the French and Viet Minh could reach some peaceful solution on their own.

-----

Allied leaders had agreed temporarily to divide Vietnam into two separate zones. Nationalist Chinese troops were to handle things in the north. British colonial troops in the south. In the fall of 1945, fresh French troops began arriving in Saigon, taking over from the British. They quickly established control of the city and set out to reoccupy the entire country. On December 19, 1946, after months of building tension, fighting broke out in Hanoi between the Viet Minh and the French. The Viet Minh proved no match for French firepower. Ho, Giap, and their comrades slipped out of the city and returned to their mountain stronghold far to the north.

France poured thousands of men into Vietnam - French regulars, European mercenaries, and colonial troops from Morocco, Algeria, Tunisia, and Senegal - who fought alongside an army of Cambodians, Laotians, and anti-communist Vietnamese. French forces managed to occupy most of the large towns and province capitals and established hundreds of isolated outposts. The Viet Minh mined roads, blew up bridges and railroads, ambushed French patrols, and then disappeared.

------

Just a few weeks after Russia became a nuclear power, on August 29, 1949, communist forces under Mao Zedong seized control of China. Separate communist insurrections were also underway in the British colonies of Burma and Malaya. In January 1950, Mao formally recognized Ho Chi Minh's insurgency and agreed to provide the arms, equipment, and military training he had been seeking. The Soviets recognized the Viet Minh as well, and also offered help.

President Truman, who was being blamed by his political opponents for having "lost" China, and having failed to "contain" communism, approved a $23 million aid program for the French in Vietnam. The United States was no longer neutral.

In June of 1950, communist North Korea invaded South Korea. President Truman ordered tens of thousands of American ground troops onto the Korean Peninsula. Meanwhile in southern China, Mao's military was beginning to turn the Viet Minh into a modern fighting force, capable of inflicting a heavy toll on the French occupiers. In July, the Truman administration quietly dispatched transport planes and a shipload of jeeps to Vietnam. Thirty-five military advisors went along to oversee their use. The United States was now officially in Vietnam.

As that fighting raged, Truman continued to increase military aid for the French war in Vietnam. In 1952, General Dwight Eisenhower was elected president, in part because he promised to take a tougher stance on communism. That year, American taxpayers were footing more than 30% of the bill for the French war in Vietnam. Within two years, that number would rise to nearly 80%.

-----

By 1953, the French had been fighting for seven years. They had suffered over 100,000 casualties and failed to pacify the countryside. Six commanders had come and gone. In July of 1953, the Korean War ended in a negotiated settlement and a still-divided peninsula. American policymakers saw it as proof that communism in Asia could be contained. That fall, the French indicated their willingness to begin talks to end the fighting in Vietnam. Ho Chi Minh agreed to meet. But before the negotiators were to convene in Geneva, each side sought to improve its position on the battlefield.

The French set up a fortified base in a remote valley in northwestern Vietnam called Dien Bien Phu, where he hoped to lure the Viet Minh into a decisive battle. Navarre was certain that superior French firepower and air support would crush any attack by the Viet Minh. He and his commanders saw no need to worry about the jungle-covered hills that overlooked his 11,000 men.

General Giap saw his chance. He pulled off one of the greatest logistical feats in military history. A quarter of a million civilian porters moved everything he needed for a siege, from sacks of rice to disassembled artillery pieces, on foot through the jungle.

On March 13, 1954, Viet Minh artillery on the hillsides began raining down 50 shells a minute on the French troops huddled below. The besieged troops could only be reinforced and resupplied by airdrop. On the afternoon of May 7, 1954, after 55 days of siege, the exhausted French forces at Dien Bien Phu surrendered. They had lost 8,000 men, killed, wounded, or missing. General Giap had lost three times as many, but he had won a great victory.

-----

The day after the fall of Dien Bien Phu, diplomats from nine nations gathered in Geneva to settle the future of Vietnam. 

Despite their victory, Ho Chi Minh could not keep fighting without more support from China and the Soviet Union. But China had lost a million men in Korea and did not want to become involved in another war along its border. The Soviet Union was hoping to ease tensions with the West. Both of Ho Chi Minh's communist patrons urged him to agree to a negotiated settlement, a partition like the one that had ended the Korean War. Ho had no option but to give in.

Vietnam was temporarily to be divided at the 17th parallel. The two halves would be separated by a demilitarized zone until an election could be held to reunify North and South Vietnam. Under the Geneva Accords, civilians living in either half of Vietnam who wanted to relocate to the other would have 300 days to do so. In the end, some 900,000 refugees, including more than half of all the Catholics living in the North, fled to the South.

-----

The United States hoped to encourage the building of a legitimate government in the South. That government was now headed by Ngo Dinh Diem, who claimed his goal was to turn South Vietnam into a democracy.

The French, who still had thousands of troops stationed in the South, detested Diem. And Saigon was ruled by the Binh Xuyen, a crime syndicate backed by the French. On April 28, 1955, Diem made an all-out assault on the Binh Xuyen syndicate and regained control of Saigon. Diem's forces prevailed. The French then announced their intention to withdraw completely from South Vietnam, ending nearly a century of occupation.

On October 26, 1955, Ngo Dinh Diem named himself the first president of the brand-new Republic of Vietnam. The election to reunify the North and South that had been promised at Geneva would never be held. Eisenhower now saw no option but to stick with Diem. Military advisors were sent with orders to modernize, train, and equip Diem's forces, now called the Army of the Republic of Vietnam - the ARVN.

Most American military advisors were veterans of the war in Korea, determined to prepare South Vietnamese forces to slow a conventional invasion from the North. But no one in North Vietnam was planning a conventional invasion.

-----

Ho Chi Minh was still determined to reunite Vietnam. But he worried that if he took direct military action against the South, the United States would be drawn more deeply into the struggle. He cautioned his comrades in the South to put their faith in political agitation and avoid violence. But new leaders emerged in Hanoi, who grew impatient with Ho Chi Minh's caution. The most important proved to be Le Duan, the First Secretary of the party.

By 1959, Le Duan and his hardline allies were gaining influence within the North Vietnamese Politburo and beginning to change its policy. They now argued that Hanoi should do everything within its power to help Southern revolutionaries remove Diem by force. Bands of 40 to 50 armed Viet Minh began slipping back home into South Vietnam, following jungle paths hacked through the Laotian mountains that the Americans would soon call the Ho Chi Minh Trail.

Violence against the Diem regime steadily accelerated. On the evening of July 8, 1959, at Bien Hoa, 20 miles northeast of Saigon, two American military advisors were killed by Viet Minh guerrillas. They were the first American soldiers to die from enemy fire in the Vietnam War.

-----

On November 8, 1960, John Fitzgerald Kennedy was elected president of the United States, narrowly beaten Vice President Richard Nixon. During the campaign, both Kennedy and Nixon had pledged to hold the line against international communism wherever it seemed to be a threat.

Six weeks after Kennedy's election, at a remote jungle village called Tan Lap near the Cambodian border, representatives of southern revolutionary groups met to form a new organization to replace the Viet Minh, dedicated to overthrowing Ngo Dinh Diem and ousting the foreigners supporting him. Behind the scenes, Le Duan and his communist comrades in Hanoi were orchestrating everything.

The new organization would be called the National Liberation Front - the NLF. The armed wing of the NLF was called the People's Liberation Armed Forces, but its enemies in Saigon and Washington preferred a more disparaging term. In their eyes, the revolutionaries were Communist Traitors to the Vietnamese Nation - the Viet Cong.
* Episode 2

#+BEGIN_QUOTE
We thought we were the exceptions to history, we Americans. History didn't apply to us. We could never fight a bad war. We could never represent the wrong cause. Well, in Vietnam it proved that we were not an exception to history.
#+END_QUOTE

Like the president who picked them, all of Kennedy's men had served during World War II. Each had absorbed what they all believed was its central lesson: ambitious dictatorships needed to be halted in their tracks before they constituted a serious danger to the peace of the world.

The first months of his presidency did not go well. He approved a CIA-sponsored invasion of Cuba at the Bay of Pigs that ended in disaster. He felt he'd been bullied by Soviet premier Nikita Khrushchev at a summit meeting in Vienna. He was unable to keep the Soviets from building the Berlin Wall. And in Southeast Asia, he refused to intervene against a communist insurrection in Laos. Critics accused him of being immature, indecisive, inadequate to the task of combating what seemed to be a mounting communist threat. In South Vietnam, Kennedy felt he had to act.

Kennedy refused to commit American ground troops in Vietnam. He supported a new "flexible" way to confront and contain communism: limited war - war by guerrillas, subversives, insurgents, assassins; war by ambush instead of by combat; by infiltration instead of aggression. Kennedy sent the Green Berets to the Central Highlands of Vietnam to organize mountain tribes to fight the Viet Cong and to undertake covert missions to sabotage their supply bases in Laos and Cambodia. He doubled funding for South Vietnam's army, dispatched helicopters and APCs, armored personnel carriers. Kennedy also authorized the use of napalm and the spraying of defoliants to deny cover to the Viet Cong and destroy the crops that fed them.

Within two years, the number he had inherited would grow to 11,300, empowered not only to teach the Army of the Republic of Vietnam - the ARVN - to fight a conventional war, but to accompany them into battle, a violation of the agreement that had divided Vietnam back in 1954. The administration did its best to hide from the American people the scale of the buildup that was taking place on the other side of the world.

-----

By the summer of 1962, news from South Vietnam seemed so promising that Defense Secretary Robert McNamara made sure the Pentagon was prepared to implement a plan for a gradual withdrawal of American advisors to be completed by 1965. So far as most Americans knew, the United States was achieving its goal: a stable, independent, anticommunist state in South Vietnam.

But that same summer, Ho Chi Minh traveled to Beijing in search of more help from the Chinese. The American buildup in South Vietnam had alarmed him and the other leaders in Hanoi. Ho told the Chinese that American attacks on North Vietnam itself now seemed only a matter of time. The Chinese promised to equip and arm tens of thousands of Vietnamese soldiers. Meanwhile, the Politburo in Hanoi had directed that every able-bodied North Vietnamese man be required to serve in the armed forces.

-----

The government of Ngo Dinh Diem launched an ambitious program meant to gain control of the countryside by concentrating the rural population into thousands of fortified settlements, ringed with barbed wire and moats and bamboo spikes meant to keep out the Viet Cong. They were called strategic hamlets, part of the effort to win the hearts and minds, and loyalty, of the Vietnamese people. Farmers resented being forced to abandon their homes and move to strategic hamlets. Corrupt officials siphoned off funds. And villagers blamed the Diem regime for failing to protect them from guerrilla attacks. As the people's anger grew, so did the ranks of the Viet Cong. The tactics were beginning to make more enemies than friends.

Diem's brother, Ngo Dinh Nhu, ran a personal political party that mirrored the techniques and the ruthlessness of the communists, and supervised a host of internal security units that spied on and seized enemies of the regime. Some reporters who probed too deeply into what Diem and Nhu were doing were ordered out of the country. Meanwhile, out in the countryside,  the corruption within Diem's regime had filtered down to the commanders in the field.

-----

#+BEGIN_QUOTE
This was just continuing that battle against the Russians. Only we were fighting their proxies, the Vietnamese, but it was monolithic communism. It didn't matter to me where it was, I was going to go if my government said we needed to be there. We were probably the last kids of any generation that actually believed our government would never lie to us.
#+END_QUOTE

In October of 1962, the United States and the Soviet Union came closer than they would ever come again to mutually assured destruction. The Soviets had secretly placed nuclear missiles 90 miles from the United States. The Joint Chiefs of Staff urged President Kennedy to bomb Cuba. He resisted and instead ordered a naval blockade to stop Soviet ships from resupplying the island. For 13 excruciating days, the world held its breath.

Finally, in exchange for a private pledge to remove American missiles from Turkey, Khrushchev agreed to remove his missiles from Cuba. Neither the United States nor the Soviet Union wanted so direct a confrontation ever again. From now on, limited wars, like the growing conflict in Vietnam, would assume still greater importance.

-----

Diem began by alienating the rural population, which started the Viet Cong. And now he was alienating the urban population. In the months that followed the Battle of Ap Bac, South Vietnam plunged into civil strife that had little to do with the Viet Cong. A Catholic minority had for years dominated the government of an overwhelmingly Buddhist country, where Seventy percent of the population was Buddhist.

That spring in the city of Hue, when the Buddhists of the city flew their flags to celebrate the birthday of Lord Buddha, police tore them down. Protesters took to the streets. The Catholic deputy province chief sent security forces to suppress the demonstration. The soldiers opened fire. Eight protesters died. Monks throughout the country demanded an apology. American officials urged Diem to make meaningful concessions to the Buddhists, for the sake of maintaining unity in the struggle against communism. They refused.

On June 10, 1963, one reporter of the Associated Press received an anonymous tip: something important was going to happen at a major intersection in Saigon. He took his camera. To protest the Diem regime's repression, a 73-year-old monk named Quang Duc set himself on fire. A large, hushed crowd watched him burn to death.

#+BEGIN_QUOTE
They held the ashes of the monk in one of the main pagodas. And lines of people came to pass by, and I saw these ordinary Vietnamese women, take off the one piece of gold they had on, their wedding ring, and drop it in the bottle to contribute to the struggle. And I thought to myself, "This regime is over."
#+END_QUOTE

Tensions between Washington and Saigon steadily worsened. The more the Kennedy Administration demanded change, the more Diem seemed to resist. The White House announced that a new American ambassador, former senator Henry Cabot Lodge, was being sent to Saigon, a man eminent enough, the president hoped, to make Diem listen more closely to American advice.

A few minutes after midnight on August 21, 1963, with ambassador Frederick Nolting gone and Henry Cabot Lodge's arrival still one day away, Diem cut the phone lines of all the senior American officials in Saigon and sent hundreds of his Special Forces storming into Buddhist pagodas in Saigon, Hue, and several other South Vietnamese cities. Some 1,400 monks and nuns, students and ordinary citizens were rounded up and taken away.

Martial law was imposed, public meetings were forbidden, troops were authorized to shoot anyone found on the streets after 9:00. When college students protested in support of the monks, Diem closed Vietnam's universities and arrested thousands of school children, including the sons and daughters of officials in his own government.

-----

Since the early 1950s, the United States government had encouraged and even orchestrated other Cold War coups in Iran, Guatemala, the Congo, and elsewhere. In the wake of the pagoda raids, a small group of South Vietnamese generals contacted the CIA in Saigon. Diem's brother Nhu was now largely in control of the government, they said. What would Washington's reaction be if they mounted a coup?

Roger Hilsman, Jr., assistant secretary of state for Far Eastern affairs and a critic of the Diem regime, drafted a cable with new instructions for Ambassador Lodge, as President Kennedy and his senior advisors happened to be out of town. The U.S. government could no longer tolerate a situation in which power lay in Nhu's hands, it said. Diem should be given a chance to rid himself of his brother. If he refused, then we must face the possibility that Diem himself cannot be preserved.

Despite the cable, Kennedy and his advisors were sharply divided about a coup. Robert McNamara, Maxwell Taylor, Vice President Lyndon Johnson, and the head of the CIA all cautioned against it, because, while none of them especially admired Diem, they did not believe there was any viable alternative. But several State Department officials believed that without fresh leadership, South Vietnam could not survive.In the end, Kennedy instructed Lodge to tell the renegade generals that while the United States does not wish to stimulate a coup, it would not thwart one either.

-----

On November 1, 1963, troops loyal to the plotters seized key installations in Saigon and demanded Diem and Nhu surrender. Diem and Nhu escaped, and agreed to surrender to the rebels in exchange for the promise of safe passage out of the country. They were picked up in an armored personnel carrier, and murdered soon after they climbed inside.

President Kennedy was appalled that Diem and Nhu had been killed. Three days later, he dictated his own rueful account of the coup and his concerns for the future. "The question now is whether the generals can stay together and build a stable government or whether public opinion in Saigon will turn on this government as repressive and undemocratic in the not-too-distant future."

Kennedy would not live to see the answer to the question he had asked. He was murdered in Dallas 18 days later. There were now 16,000 American advisors in South Vietnam. Their fate and the fate of that embattled country rested with another American president, Lyndon Baines Johnson.
* Episode 3

#+BEGIN_QUOTE
The America's interests in Vietnam were 70% to avoid humiliation, 20% to contain China, and 10% to help the Vietnamese.
#+END_QUOTE

The assassination of Ngo Dinh Diem set in motion a series of coups. Between January 1964 and June of 1965, there would be eight different governments. Meanwhile, the Viet Cong was making coordinated attacks throughout the countryside, An estimated 40% of the South Vietnamese countryside, and more than 50% of the people, were effectively in the hands of the Viet Cong.

There had been change and turmoil in North Vietnam, too, just as there had been in Saigon, though Americans knew almost nothing about it. At the Ninth Party Plenum that began in Hanoi on November 22, 1963, the Politburo had argued over how best to proceed in the war. North Vietnam's two communist patrons, the Soviet Union and China, were giving them conflicting advice. Ho Chi Minh, who favored the Soviet strategy, was outmaneuvered by party First Secretary Le Duan, who sided with the Chinese. Le Duan believed that with Diem gone, and the Saigon government in disarray, it was time to move quickly in 1964.

-----

Tragedy had brought Lyndon Johnson to the presidency in November of 1963. During his years in the White House, he would lead the struggle to win passage of more than 200 important pieces of legislation. In foreign affairs, Johnson was less self-assured. He retained in office all of John Kennedy's top advisors.

Johnson increased the number of American military personnel from 16,000 to more than 23,000 by the end of 1963. The Joint Chiefs of Staff felt strongly that the United States was fighting on the enemy's terms and urged far more drastic and dramatic action. Johnson refused, fearing that such aggressive moves would pull China into the conflict just as it had entered the Korean War in 1950. But he still authorized American pilots to bomb North Vietnamese troops and installations in the neighboring country of Laos. And he directed the military to oversee South Vietnamese shelling of North Vietnamese islands and raids on coastal bases. All of it was to be conducted in secret. It was an election year.

-----

On the afternoon of August 2, the destroyer U.S.S. Maddox was moving through international waters in the gulf on an intelligence-gathering mission in support of further South Vietnamese action against the North. The commander of a North Vietnamese torpedo-boat squadron moved to attack the Maddox. The Americans opened fire and missed. North Vietnamese torpedoes also missed. But carrier-based U.S. planes damaged two of the North Vietnamese boats. No one may ever know who gave the order to attack. To this day, even the Vietnamese cannot agree. But some believe it was Le Duan.

Back in Washington, the Joint Chiefs urged immediate retaliation against North Vietnam. The president refused. On August 4, American radio operators mistranslated North Vietnamese radio traffic and concluded a new military operation was imminent. The attack was probable but not certain, Johnson was told, and since it had probably occurred, the president decided it should not go unanswered. A squadron of Skyhawk A-4 planes aboard the U.S.S. carrier Constellation was ordered to attack torpedo boat installations and oil facilities near the port of Hon Gai. For the first time, American pilots were going to drop bombs on North Vietnam.

-----

On August 7, 1964, by a vote of 88-2, the Senate passed what came to be called the Tonkin Gulf Resolution. Public support for Johnson's handling of the war jumped overnight from 42% to 72%. Lyndon Johnson won the presidency in his own right, and he won it by a landslide. Within a month, the president would approve what was called a "graduated response" - limited air attacks on the Ho Chi Minh Trail in Laos and retaliatory raids on North Vietnamese targets. In private, Johnson doubted that airpower alone would ever work and believed that he would eventually have to send in ground troops, though he was not yet willing publicly to say so.

Le Duan and his comrades did not believe the president's claim that he sought no wider war. For the first time, Hanoi began sending North Vietnamese regulars into the South.

-----

The Viet Cong 9th Division had for weeks been quietly filtering into a province less than 40 miles southeast of Saigon. The was the strategic hamlet of Binh Gia. Their plan was to seize the hamlet and then annihilate the forces Saigon was sure to send to retake it. Tons of heavy weapons were smuggled onto the coast under cover of darkness. Before dawn on December 28, Viet Cong advance units easily overwhelmed the village militia and occupied Binh Gia.

When battle was all over, five Americans had died at Binh Gia. Thirty-two Viet Cong bodies had been left on the battlefield. 200 South Vietnamese were killed; 200 more were wounded. The big question after Binh Gia, is how a thousand or more enemy troops could wander around the countryside so close to Saigon without being discovered.

Twenty-six days after the Binh Gia battle ended and just a week after President Johnson's inauguration, McGeorge Bundy handed the president a memorandum. The administration faced two choices, Bundy said. It could go along as it had been going and try to negotiate some kind of face-saving settlement. Or they could use still more American military power to force the North to abandon its goal of uniting the country.

Anxiety about what seemed to be happening spread around the world. France, which had spent nearly a century in Vietnam, now called for an end to all foreign involvement there. In a private memorandum, Johnson's own vice president, Hubert Humphrey, warned him that widening the war would undercut the Great Society, damage America's image overseas, and end any hope of improving relations with the Soviet Union. Johnson never responded.

Instead, on March 2, 1965, the United States began a systematic bombardment of targets in North Vietnam, code-named Operation Rolling Thunder. The president insisted on strict secrecy - the American people were not to be told that the administration had changed its policy from retaliatory airstrikes to systematic bombing; that he had, in fact, widened the war.

General Westmoreland asked for two battalions of Marines to protect the Danang airbase from which fighter-bombers were hitting the North. The president felt he had no choice but to give Westmoreland what he asked for. He knew he would be blamed if more American advisors died. In March of 1965, Johnson finally took the action he had managed to avoid for so long. He was putting American ground troops in Vietnam. On March 8, 1965, three battalions of Marines landed at Danang on the east coast of South Vietnam, some 100 miles south of the demilitarized zone that divided the North from the South.

Two weeks after the Marines landed at Danang, members of the University of Michigan faculty organized a night-long discussion between professors and some 3,000 students about the escalation of the war. Soon, there were teach-ins on most major university campuses. The bombing of the North and the Marines' arrival also drew protestors to Washington in the spring of 1965. The demonstration was organized by the Students for a Democratic Society - the SDS. 25,000 people attended that rally.

-----

As Johnson had feared, it quickly became clear that the bombing campaign alone was not working. Troops and supplies continued steadily to filter down the Ho Chi Minh Trail. He quietly agreed to send two more Marine battalions and changed their mission from base security to active combat. For the first time, American troops were being asked to fight on their own in Vietnam. Johnson did not want that fact revealed to the American public either.

In May, the Viet Cong, supported now by four regiments of North Vietnamese regulars - approximately 5,000 men - were destroying the equivalent of a South Vietnamese battalion every week. South Vietnam now seemed only weeks from complete collapse. Le Duan was now persuaded the American public, like the French public before them, would eventually weary of a costly, bloody war being waged so far from home. Le Duan's confidence was bolstered by the help American intervention had forced the Soviet Union and China to offer him. Moscow agreed to supply vast amounts of modern weaponry and materiel. And China agreed to send support troops, freeing North Vietnamese soldiers for combat in the South. 320,000 Chinese would eventually serve behind the lines in the North.

Desperate, General Westmoreland requested tens of thousands of more American troops right away. For three weeks, the president and his advisors argued over how to respond to Westmoreland's urgent request. In the end, Johnson sent Westmoreland 50,000 men. But he pledged another 50,000 by the end of 1965, and still more if they were needed.

-----

Most television reports from Vietnam echoed the newsreels Americans had flocked to see during the Second World War - enthusiastic, unquestioning, good guys fighting and defeating bad guys. But at dinnertime on August 5, 1965, Americans saw another side of the war. CBS correspondent Morley Safer and his crew went on patrol with Marines near Danang. Their orders were first to search a cluster of four villages for caches of arms and rice meant for the enemy and then to destroy them all. The next morning, the president called his friend Frank Stanton, the head of CBS. "Hello, Frank, this is your president. Are you trying to fuck me?"

#+BEGIN_QUOTE
The day's operation burned down 150 houses, wounded three women, killed one baby, wounded one Marine, and netted these four prisoners. Today's operation is the frustration of Vietnam in miniature. There is little doubt that American firepower can win a military victory here. But to a Vietnamese peasant whose home means a lifetime of backbreaking labor, it will take more than presidential promises to convince him that we are on his side.
#+END_QUOTE

-----

In September of 1965, the newly created 1st Cavalry Division - 16,000 men, 1,600 vehicles, 435 helicopters - had begun arriving at An Khe, a massive base carved out of the grasslands at the edge of the Central Highlands. Its heliport would come to be called the "Golf Course." Meanwhile, thousands of North Vietnamese regulars were slipping south into the Highlands, joining Viet Cong units already in place. They established their own base on and around a jumble of thickly forested mountains and ravines south of the Ia Drang River.

On the morning of November 14, 1965, 1st Cavalry helicopters belonging to the 1st Battalion of the 7th Regiment flew west along the Ia Drang toward the Chu Pong Massif. Lieutenant Colonel Hal Moore, had been told there was a large enemy base camp somewhere on its slopes. His orders were to take his understrength outfit - 29 officers and 411 men - find the enemy and kill him. Colonel Moore had no way of knowing that there were 3,000 enemy soldiers on the mountain, seven times his strength. Some 18,000 artillery shells would be called in over the course of the battle. Helicopter gunships fired 3,000 rockets into the enemy. The forward air controller called for every available aircraft in South Vietnam to come and help. Warplanes, including B-52 long-range strategic bombers, were stacked above the battlefield, from 7,000 to 35,000 feet, impatiently awaiting targets to strafe or bomb or burn.

After three days and two nights of combat, the surviving North Vietnamese and Viet Cong withdrew into the forest, leaving behind a ghastly ring of their dead surrounding the landing zone - 634 corpses, shot, blasted, blackened by fire. Seventy-nine of Hal Moore's men lost their lives at Landing Zone X-Ray in the Ia Drang Valley and another 121 were wounded.

#+BEGIN_QUOTE
Grab 'em by the belt buckle. That means you've got to get so close, they can't use the artillery and the aerial bombardments on you for fear of killing their own. Get in so close that it's man-on-man. And then everything is even.
#+END_QUOTE

-----

The battles in the Ia Drang Valley may have been declared American victories, but privately, General Westmoreland and the Johnson administration were worried. In spite of the Americans' new airborne mobility, the enemy had been able to choose the place and time of battle. Despite months of bombing, three times as many North Vietnamese regulars were now slipping south of the demilitarized zone as originally believed.

Westmoreland, who had said he could win the war in three years, now sent an urgent cable to Washington asking for 200,000 more troops.
Once again, Robert McNamara offered Johnson two options: try to negotiate a compromise with Hanoi, or accede to Westmoreland's request for more men, though the chances of victory, the secretary of defense said, might be no better than one in three. They voted for option two.

#+BEGIN_QUOTE
I can understand a policy error that is incredibly painful and kills a lot of people out of a mistake if they made that with noble hearts. Making a mistake, people can do that. But covering up mistakes, then you're killing people for your own ego.
#+END_QUOTE
* Episode 4

#+BEGIN_QUOTE
If a man is bloody stupid, his mother will receive a telegram and it will say, "Your son is dead because he's stupid." Let's hope your telegram only reads, "Your son is dead." With the training we're going to give you here, maybe your mother won't receive any telegram at all. So pay attention.
#+END_QUOTE

-----

Johnson had tried to forge an international coalition to defend South Vietnam. But only five other countries would ever send combat troops - Australia and New Zealand, Thailand, the Philippines, and South Korea. America's most important allies, Britain, France and Canada, refused to take part and were calling instead for peace talks.

-----

As 1966 began, 2,344 Americans had died in Vietnam. Nearly 200,000 were stationed there, and more were on their way. General William Westmoreland thought his most urgent task was to destroy the North Vietnamese regular army units Hanoi was sending South. Westmoreland's target for the next two years would be reaching what he called the "crossover point" - the point at which U.S. and ARVN forces were killing more enemy troops than could be replaced. It would be a war of attrition. But that would require still more American soldiers.

#+BEGIN_QUOTE
We tend to fight the next war in the same way we fought the last one. We are prisoners of our own experience. And many of the things that we learned that worked in World War II were not applicable to the war in Vietnam. We simply thought we'd go in with a sledgehammer and knock things down, clean them up, and it would be all over. It was a kind of an oversimplification of the problem combined with our overconfidence that caused us to be arrogant. And it's very difficult to dispel ignorance if you retain arrogance.
#+END_QUOTE

Search-and-destroy and bombing campaigns - 17 large-scale U.S. offensives in 1966 alone - would produce a total of more than three million homeless people all across the country, roughly one-fifth of South Vietnam's population.

-----

Since there was no front in Vietnam, as there had been in the first and second World Wars, since no ground was ever permanently won or lost, the American military command in Vietnam fell back more and more on a single grisly measure of supposed success: counting corpses.

#+BEGIN_QUOTE
The problem with the war, as it often is, are the metrics. It is a situation where if you can't count what's important, you make what you can count important. If body count is the measure of success, then there's the tendency to count every body as an enemy soldier. There's a tendency to want to pile up dead bodies and perhaps to use less discriminate firepower.
#+END_QUOTE

-----

For years, Hanoi had smuggled most of its arms and supplies to the South aboard an improvised fleet of junks, trawlers and freighters. But when the U.S. Navy effectively blockaded the Southern coastline, the North Vietnamese would be forced to move almost all of their supplies overland, through Laos and Cambodia. Americans called it the Ho Chi Minh Trail. The North Vietnamese called it Route 559, after the men and women of the 559th Army Corps, who were turning it from a braided web of footpaths into 12,000 tangled miles of jungle roadways.

MACV reasoned that if the Ho Chi Minh Trail could somehow be sufficiently damaged, the enemy would be unable to sustain itself. Three million tons of explosives would eventually be dropped on the Laos portion of the trail alone - a million more tons than fell on Germany and Japan during all of World War II. To expose enemy traffic, other aircraft dropped chemical defoliants, including Agent Orange, that destroyed thousands of acres of jungle and turned the earth into what one American pilot called "bony, lunar dust." As many as 230,000 teenagers, many of them volunteers, worked to keep the roads open and the traffic moving. More than half of them were women. Thousands died on the trail from starvation and accidents, fevers and snakebite and sheer exhaustion, as well as from the relentless bombing.

-----

The war by 1966 began to impact the middle class because the draft calls had to be enlarged. Reservists and Guardsmen were almost always white, generally better educated, better connected, and better paid than draftees. Interrupting their lives, President Johnson felt, would have increased opposition to the war. The result was an Army heavily skewed toward minorities and the underprivileged.

Since 1942, every male citizen of the United States had been required to register at age 18. Of the nearly 27 million American men who came of age during the Vietnam War, more than half avoided military service through exemptions and deferments. Now, thousands of college students could no longer expect a deferment.

#+BEGIN_QUOTE
If your rank fell below a certain threshold, you were yanked out of college. And the worst that could happen to you is you would be killed in Vietnam. So we protested at the University of Chicago that the university was complicit with this war by agreeing to supply those rankings to the draft board.
#+END_QUOTE

-----

On May 15, 1966, the government of South Vietnam again seemed on the brink of collapse. The ascendancy of Prime Minister Ky had dealt a severe blow to activist Buddhists, who had been demanding representative government and a negotiated end to the war since 1963. When Ky suddenly fired a rival general, a popular Buddhist commander, demonstrators poured into the streets of Hue and Danang. Some South Vietnamese soldiers, loyal to the dismissed general, abandoned the struggle against the communists and headed for the city. From his command post on a hilltop outside the city, an American Marine lieutenant had watched in disbelief as two battles unfolded simultaneously: in the west, his fellow Marines were fighting the Viet Cong; in the east, the South Vietnamese army seemed to be at war with itself. The rebellion was crushed. Washington was relieved. Ky seemed to be back in control.

-----

The president agreed to intensify the bombing campaign called Operation Rolling Thunder. He approved attacks on oil facilities all over North Vietnam. Many bombs hit their intended targets. But many missed and fell on residential neighborhoods instead. Operation Rolling Thunder did destroy most of North Vietnam's oil storage facilities. But the North Vietnamese shifted most of their oil to underground tanks, and more arrived every day from China and the Soviet Union. The bombing was stepped up anyway. Throughout the North, enough crude air shelters were fashioned from concrete pipe buried five feet beneath the ground to accommodate some 18 million people - virtually the entire population. Over a million people were said to be working around the clock to undo what American bombs had done.

By the summer of 1966, Lieutenant Everett Alvarez, the first American pilot to have been shot down over North Vietnam, had been a captive for nearly two years and had been joined in and around Hanoi by more than 100 other downed airmen. They were subjected to isolation, beatings, and hour upon hour of torture, all aimed at forcing them to admit their guilt and record statements denouncing the war. Some of the men who were forced to record statements did their best to make their true feelings known back home. Commander Jeremiah Denton blinked his eyes to spell out "torture" in Morse code.

-----

The antiwar movement was growing in numbers and militancy. Some in the Johnson administration became convinced the antiwar movement was a communist conspiracy directed by Moscow. The FBI and the CIA, which was barred by statute from operating within the United States, began infiltrating the movement, wiretapping its leaders, even inciting violence in order to undercut their appeal.

#+BEGIN_QUOTE
There's a monstrous myth abroad, a myth which Hanoi creates and which it believes, and that is that the United States is so divided that if they just hang on that they will win in Washington, and in the United States the victory that our fighting men are denying them in field.
#+END_QUOTE

Two weeks after the Manhattan protest, General Westmoreland addressed a joint session of Congress, the first general ever to be called home from a battlefield by his president to do so. Behind the scenes, neither Westmoreland nor the administration he served was confident the United States would prevail. He warned that the United States was doing little better than holding its own. If he were given 200,000 additional troops and allowed to go into Laos and Cambodia, he could cut off the Ho Chi Minh Trail and end the war in two years. But "When we add divisions," Johnson asked, "can't the enemy add divisions? Where does it all end?" Westmoreland had no answer.

Meanwhile, Robert McNamara, the chief architect of American strategy in Vietnam, had grown less and less confident in its ultimate success and in the repeated calls for more men and more bombing. He urged the president to limit troop levels, not raise them, and to declare an unconditional end to all bombing north of the 20th parallel. In the end, Johnson tried to find a middle ground. He expanded the list of bombing targets, but he refused to mine the harbors and he agreed to send Westmoreland only 47,000 more troops, which would bring the total of U.S. forces in the country to more than half a million men.
