#+setupfile: ../../styles/readtheorg.setup
#+title: The Ascent of Money

* Episode 1. Dreams of Avarice

500 years ago, the most powerful society in South America, the Inca Empire, had no real concept of money. Labour was the unit of value in the Inca Empire, just as it was later supposed to be in a communist society.

But in 1532, the Incas ran into a man whose hunger for money had led him across an ocean. Francisco Pizarro and his fellow Conquistadores had come from Spain to what they called Upper Peru inspired by the legend of El Dorado, the realm of the gold-covered king. At Potosi, in what is now Bolivia, the Spaniards struck it rich. They discovered the Cerro Rico, literally the Rich Hill. In their 250 years of Spanish rule, more than two billion ounces of silver were extracted from the mines and shipped to Europe as bars and coins.

And yet, all the silver in the mines of Potosi couldn't halt the inexorable economic and political decline of the Spain empire. More silver coins didn't make Spain richer. They simply made prices higher as an increased quantity of money chased the same amount of goods.

What the Spaniards didn't get was that money is only worth what other peopIe will give in exchange for it. Even lumps of clay can work better than silver coins, if people have enough confidence in them. Bank notes have next to no intrinsic worth. They're simply promises to pay, just like the clay tablets of ancient Babylon four millennia ago.

Money is about trust. Trust in the person paying the money, trust in the central bank issuing the money, trust in the commercial bank that honours the cheque. Money is trust inscribed, and it doesn't much matter what it's inscribed on - paper, silver, clay, or a screen - provided the recipient believes in it.

-----

Among the many remnants of the defunct Roman Empire was a numerical system singularly ill-suited to complex mathematical calculation, let alone the needs of commerce. By comparison, economic life in the Eastern world - in the Muslim caliphate or the Sung Chinese Empire - was far more advanced. The Hindu or Arabic numerals made all kinds of calculation easier.

In northern ltaly, around 1200, a young mathematician called Leonardo of Pisa or Fibonacci, introduced to Europe many Eastern mathematical ideas with his path-breaking book the Liber Abaci - The Book of Calculation. In particular, Fibonacci showed how the new methods of calculation could be applied to commercial bookkeeping, to currency conversions and, crucially, to the computation of interest.

-----

The idea that one could rely on people to borrow money and pay it back at some future date revolutionise world history. Without the invention of credit, the entire economic history of world would have been impossible. Venice - more exposed than any of the other Italian city states to Oriental influences - became the great money-lending laboratory.

With any loan, things can go wrong. Ships can sink. And that is precisely why anyone who lends money to a merchant - if only for the duration of an ocean voyage - needs to be compensated. We usually call the compensation "interest" - the amount paid to the lender over and above the sum lent or "principal". Overseas trade of the sort that Venice depended on couldn't operate without such transactions. And they remain the foundation of international trade to this day.

Fibonacci might have figured out the mathematics of lending, but it took Shylock to do the deal. The medieval church's laws against usury - charging interest on loans - were a major obstacle to the development of finance in Europe. However Jews could provide a service that Christian merchants were forbidden to do - they could charge interest on their loans. The price the Jews paid for performing this service was social exclusion.

-----

Why don't debtors always default on their debts, especially when the creditors belong to unpopular ethnic minorities? Individual loaners have to be rapacious and ruthless because the costs to them of even a single defaulter are so high. And that explains why, since the time of Renaissance ltaly, the moneylender is so often a hated figure. If lenders were too generous, they didn't make any money, but if they were too hard-nosed, borrowers would eventually default. The answer to this problem was to get bigger and more powerful, by inventing banks.

In 15th century Italy, the key financial service of providing credit moved out of the ghetto to become the legitimate preserve of banks. This transition was symbolised by the rise of one family - the Medici. With their ascent, moneylending ceased to be disreputable and became glorious. In 150 years, the Medici had transformed themselves from backstreet moneylenders to the most powerful financial force in Europe.

The secret of their success was an ingenious bit of creative accounting that got the Medici off the hook of the anti-usury laws. The Church prohibited the collection of interest on loans, but there was nothing to prevent a trader from making money on foreign exchange transactions, which involved muItiple currencies. There was no interest, and therefore no sin, simply a commission deducted for the conversion of currency.

Decentralisation was also a key to their astonishing profits. Earlier Italian banks had been monolithic and very vulnerable to default by a singIe bad borrower. The Medici banking network extended from Florence, to Venice, to Rome. The scale and diversity of operations reduced the risks of moneylending, and therefore also the costs to borrowers. That's the essential difference between loan sharks and banks - between Shylock and the Medici.

-----

The United States has been built on borrowed money. Whereas the Medici tended to lend only to the relatively well off, American banks seemed willing to give just about anyone a loan.

From 1996 to 2006 there were between one and two million bankruptcy cases a year in the United States. The ability to walk away unscathed from unsustainable debt and start again has been a defining characteristic of American capitalism. The world's most successful capitalist economy is based on a foundation of more or less painless economic failure.

The theory is that American law exists to encourage entrepreneurship - to facilitate the creation of new businesses. Many of America's greatest successes failed in their early endeavours. For their part, the banks simply assume that a proportion of the loans they make will go bad. After all, most people going bankrupt owe relatively trivial sums.
* Episode 2. Human Bondage

Bonds are the magical link between the world of high finance and the world of political power. Governments always spend more than they raise in taxation, and they borrow on an unimaginably vast scale by selling bonds that pay interest. The total worth of bonds is around $85 trillion.

Today the global market for bonds is still bigger than the all the world's stock markets put together. Buying or selling bonds doesn't just affect financial markets and government policy, it affects the value of pension funds and the interest rates we pay on our mortgages.

-----

War is impossible if you don't have the money to pay for it.

The ability to finance war through the bond market was an invention of the Italian Renaissance. For much of the 14th and 15th centuries, the medieval city-states of Tuscany, Florence, Pisa and Siena were at war with each other. Rather than require their own citizens to do the dirty work of fighting, each city hired military contractors. The cost of these incessant wars plunged Italy's city-states into crisis.

Then came revolutionary idea that rather than paying direct tax, citizens were obliged to lend money to their own government. In return for these forced loans, they received interest. The wonderful thing about them was that you could sell your bonds to other citizens. They were liquid assets. This wartime expedient marked the birth of the modern bond market.

If you buy a bond when war is raging, you're taking a risk - the risk that the city won't pay you back or pay your interest. And that is how the bond market works - you get return for the risk you're prepared to take.

-----

The Battle of Waterloo was the culmination of more than two decades of intermittent conflict between Britain and France. To pay for the war, the British government had sold an unprecedented amount of bonds. But neither bonds nor bank notes were any use to Wellington. To provision his troops and pay Britain's allies against France, he needed a currency that was universally acceptable.

Nathan Rothschild was given the job of taking the money raised on the bond market and gathering as much gold and silver as he could find on the European continent, and delivering it to Wellington and his army. The Rothschilds were so effective as war financiers, because they had a ready-made banking network within the family in London, Frankfurt, Paris and Amsterdam.

The battle of Waterloo was a glorious victory for Wellington, but not for the Rothschilds. With the coming of peace, the great armies that had fought Napoleon could be disbanded. That meant no more gold for soldiers' wages and it meant the price of gold, which had soared during the war, would fall.

There was only one possible way out. Nathan's gamble was that the British victory at Waterloo would send the price of British bonds soaring upwards. By purchasing and holding a large quantity of bonds for over a year, and sold it in July 1817 with the prices up by 40%, the Rothschilds had shown that bonds were more than just a way for governments to fund their wars, they could be bought and sold in a way that generated serious money.

-----

Like the Italian city states 500 years before, the Confederate Treasury had initially raised money for the war by selling bonds to its own citizens and later to Europe. The South's idea was to use cotton as collateral to back its bonds. Investors would be comforted to know that if the interest payments dried up they could still demand their cotton instead. Cotton bonds formed the basis of the South's new financial strategy.

In 1860, more than 80% of the cotton in Britain came from the Southern United States. Ihe Confederate leadership decided to impose an embargo on all shipments of cotton to Liverpool, in the hope to bring Britain on their side in the Civil War.

For a while, the South's strategy worked brilliantly. Cotton prices soared. So did the value of the Confederates' cotton-backed bonds. Yet the South's ability to manipulate the bond market depended on one over-riding condition - that investors could be sure of taking physical possession of the cotton which underpinned the bonds if the South failed to make its interest payments.

And that's why the fall of New Orleans, the principal outlet for cotton, on April 28, 1862, was the real turning point in the American Civil War. Without control over the cotton trade the South's cause was doomed. By 1863, the mills in Britain had found new sources of cotton in China, Egypt, and India and investors were rapidly losing faith in the South's cotton-backed bonds.

With its domestic bond market exhausted, the Confederacy really had no alternative but to print paper dollars. With more and more of this cash chasing fewer and fewer goods, inflation in the South simply exploded. By January 1865, the price of some goods was up by a factor of 90. The South had bet everything on manipulating the bond market and had lost.

-----

The lethal danger that inflation poses is that it undermines the value of being paid a fixed rate of interest on a bond. If inflation goes up to 10% and the value of a fixed-rate interest is only 5%, then that means that the bond holder is falling behind inflation by 5%. That's why, at the first whiff of higher inflation, bond prices fall.
* Episode 3. Blowing Bubbles

By the 1690s, Amsterdam was the world capital of financial innovation. And the single greatest Dutch invention was the company.

Dutch traders spread out all over the world, but it was Asia that became the primary
target of Dutch commercial expansion because of spices. The Asian spice trade was very profitable, yet so prolonged was the journey round the Cape of Good Hope to the East and so hazardous that merchants had to pool their resources and their risk. The result was around six fledgling East lndia enterprises. In 1602, at the instigation of the Dutch government, these various companies came together to form the United Dutch East India Chartered Company.

The structure of the new entity was novel. Citizens were invited to participate in the new venture by investing. And shareholders who wanted their cash back could not have it refunded, but would have to sell their shares to another investor. Thus a market for the company's shares was born - the world's first true stock market. It created a mechanism whereby the price of shares was determined by the laws of supply and demand. And the trading of these company stocks made the world's first shareholders very rich.

The key to the company's success wasn't just its cannons. It was able to combine economies of scale with reduced transaction costs, and the ability to pool information between multipIe employees and agents. The big networked company was simply more efficient. By the 1 620s, it had established a virtual monopoly on spice exports from Asia to Europe. Over its entire lifetime, the company paid an average annual dividend of 16.5%.

-----

The Dutch financial system struck John Law as not quite complete. For one thing, it seemed completely nuts to restrict the number of East India Company shares when the markets were so clearly enamoured of them. For another, it had created an internal system which allowed merchants to settle their accounts by direct cashless transfers, but it hadn't issued any real banknotes to the public.

Combining the properties of a monopoly trading company and a public bank, and the sky would be the limit. In 1716, John Law arrived in Paris. He had identified France as the ideal laboratory for the biggest experiment in the history of the stock market.

Law's ambition was to revive economic confidence in France by establishing a bank on the Dutch model, but with the difference that this bank would issue paper money. The second part of Law's idea was that a huge monopoly trading company should be established, The focus for this wildly ambitious scheme would be in America, where the French laid claim to a vast tract of land either side of the Mississippi - Louisiana.

The Mississippi Company was given a monopoly on trade with the new colony. Frenchmen were encouraged to buy shares in the company. In a fever of mass speculation, the Mississippi Company's share price soared, from the original price of 500 livres to 10,000 by December 1719. The higher the share price went, the more they wanted to buy. It was a classic stock market feedback loop.

At root, Law's system was what we nowadays call a Ponzi scheme, The acquisitions of other companies and the generous dividends Law paid were financed not from company profits, but simply by selling new shares. Therefore he had a strong personal interest in printing more money, which his own bank controlled, to drive up the price of his own company's shares. Law had become the ultimate insider trader. Law's problem was that he had no clear idea where to stop. 

By the beginning of 1720, the Mississippi Bubble was about to bust. According to Law's PR campaign, the huge profits he was projecting would come from the French colony of Louisiana, which he painted as a veritable Garden of Eden. Several thousand bold Germans signed up and set sail to the promised land. Within a year, 80% of them had died of starvation or tropical diseases like yellow fever. The Mississippi Company's principal asset, its monopoly on trade with Louisiana, was more or less worthless.

In Paris, the first rumours began to circulate. The share price of the Mississippi Company began to slide. By December, the shares had lost more than 90% of their value. Law, vilified by the French people, fled the country. He never saw his wife and daughter again. He spent the rest of his life in Venice.

The Mississippi Bubble of 1719 was the first stock market bubble in history. Its bust fatally set back France's financiaI development. The French monarchy's fiscal crisis went unresolved for the rest of the reign of Louis XV and Louis XVI. Eventually, France was driven by royal bankruptcy to revolution.

-----

Why does any crash happen? This remains one of the most hotly debated questions in financial history. There are all kinds of technical explanations for stock market crashes. But at root, it's all about herd psychology.

In a bull market, that's when share prices are rising, even the smartest investors can succumb to the "irrational exuberance". But when the herd changes direction, sometimes in reaction to nothing more than a change in the wind. One cow gets scared, and that fear just translates to the whole herd. Fear overwhelms all rational thinking, until it's over.

Markets are mirrors of the human psyche, they are prone to mood swings, from greed to fear. That happens rather more often than some financial theories would lead you to expect, but not so often that we're ever quite ready for the next breakdown.

If movements in financial markets were statistically distributed like human heights, there would hardly be any crashes. Most months would be clustered around the average, with only a tiny number witnessing extreme ups or downs. A drop of 10% would happen only once every 500 years. And stock market crashes of 20% in a year would be unheard of. Whereas in fact, there have been seven such crashes in the past century.

-----

The story of Enron was like a re-run of the Mississippi Bubble 280 years before.

Once a small-time gas company in Nebraska, Enron was now the fifth largest company in the United States, with stated revenues of 111 billion dollars. In the space of just three years after 1997, the Enron stock price rose by a factor of very nearly five, from below 20 dollars a share to above 90. Enron was named by Fortune Magazine as "America's Most Innovative Company" for six consecutive years.

Ken Lay, the chairman of Enron, planned to revolutionise the global energy business. For years, the industry had been dominated by huge utility companies, which both produced the energy, pumped the gas and generated the electricity, and sold it on to consumers. Lay's big idea was to create a kind of energy bank, which would act as the intermediary between suppliers and consumers. His dream was to make Enron the greatest energy company in the world.

Enron's money was stolen in more ways than one. The company's stated assets were vastly inflated. But its key financial innovation was to remove its debts from the balance sheet and hide them in so-called "special purpose entities". Each quarter, the company's executives had to use more smoke and more mirrors to make actual losses look like bumper profits.

When they sensed the game would soon be up, Lay and his cronies started to unload hundreds of millions of dollars worth of shares, while at the same time reassuring the public that the share price would continue to soar. And on November 2001, Enron filed for bankruptcy. Its long-term debt picture was 38 billion dollars.

Enron became the biggest corporate fraud in modern American history. Yet the fraudulent practices that propelled Enron's rise and fall didn't die with it. The habit of hiding debt off-balance-sheet that Enron pioneered subsequently spread throughout the Western financial system. Nothing illustrates more clearly than the history of stock market bubbles how hard human beings find it to learn from history.
* Episode 4. Risky Business

Disasters kept striking Japan in the first half of the 20th century. Private insurance policies turned out to be worth little more than the paper they were printed on. As in most competent countries, the lesson was clear - the world was just too dangerous a place for private insurance markets to cope with. A new idea began to emerge in Japan - that the state should take care of risk. The Japanese set up a welfare state.

So successful was the Japanese welfare superpower that by the 1970s, life expectancy was the longest in the world. In fact, the problem was that Japan's welfare state was so successful that, Japan's Ministry of Welfare is relying on an ever-smaller number of active workers to support an ever-rising population of retirees.

In just 30 years, the cost of social security benefits has risen in relation to Japan's national income by a factor of four. Today, virtually all Japan's health insurance societies are in deficit. Japan's once so-super welfare state is threatening to bankrupt the nation.

-----

The origins of hedging are agricultural. For a farmer, nothing is more important than the future price of his crop after it's been harvested and brought to market. A futures contract allows him to protect himself by committing a merchant to buy the crop when it's brought to market at a price agreed when the seeds are being planted. The farmer gets a floor below which the price can't sink. The merchant gets a ceiling above which it can't rise. By signing a futures contract, both the farmer and the merchant have hedged their bets.

With the development of a standardised futures contract, agreed rules, and an effective clearing house, the first true futures market was born in Chicago. After the city's futures exchange was established in 1874, hedging commodities became standard practice.

Because they're derived from underlying assets, all futures contracts are known as "derivatives". But an even smarter kind of derivative is an "option".

For example, the buyer of a call option has the right to buy a barrel of oil for $120 in a year's time. If the price of oil rises to $150 a barrel, then the option is in the money and the smart guy makes a profit of $30. But if that doesn't happen, if the price of oil stays the same, or actually declines, he's under no obligation to carry through the deal. All he does is to write off the cost of the option itself.

In theory, derivatives offer a new way to hedge against an uncertain future. It's a much smarter, and more profitable way than insurance. In the past decade, derivatives have seemed to take over the world of finance. By the end of 2007, the notional value of all derivatives contracts reached a staggering $596 trillion. That's 43 times the size of the American economy. Warren Buffet described derivatives as "financiaI weapons of mass destruction".
