#+setupfile: ../../styles/readtheorg.setup
#+title: The China Hustle

What is capitalism? At its heart, it rewards those who work hard, but it also rewards those who are willing to take advantage of others.

-----

Before the dust had settled on the economic collapse of 2008, Wall Street had already figured out a new way to package garbage as gold. But this time, the lies at the center of the scam were 100 percent legal.

With the whole Western world on the brink of another depression, prospects seemed bleak. The only market that people actually were confident would go up, was China. There was almost no company that you could invest in in 2009 that was China-based that you would lose money on. There was just one problem, foreigners couldn't invest directly in Chinese markets.

A small California bank Roth Capital found a niche that the big banks had overlooked, taking small Chinese companies and listing them directly on U.S. stock exchanges, so that others could participate in the Chinese economic miracle. Between 2006 and 2011, Roth hosted over a dozen conferences and raised billions for Chinese companies. And in New York, a small operator named Rodman & Renshaw brought over 40 Chinese companies to U.S. markets, with an aggregate value of over $31 billion.

While Rodman and Roth made fees for bringing Chinese companies to the U.S., the real paydays came when the companies listed on major stock exchanges Their analysts would recommend the risky stocks as great investments. Once the stocks rose high enough, the banks and insiders could cash out, leaving others holding the overvalued shares.

Listing a company on the stock exchange normally required audits and public vetting, but the banks found a way around all that. They used a backdoor process called a reverse merger. It's normally a shell company that is a public-traded stock that has no operations underneath it. A Chinese company looking for a way into American exchanges merges with the shell of a defunct U.S. company that no longer operates but still legally exists and has a listing on a U.S. stock exchange. The Chinese company then takes the shell company's place in the market. Between 2006 and 2012, over 400 Chinese companies listed on U.S. markets. 80 percent of them were reverse mergers.

-----

Orient Paper deployed a classic move in the reverse-merger playbook: get a stamp of approval from a trusted source - one of the Big Four global audit firms. The financial statements are prepared by management, not by the auditors. Auditor's job is to simply review management's work. And if management is trying to hide something or has co-opted the auditors, they will hide it. If hiding it doesn't work, they opt for plan B. hire a good lawyer.

And even if you got caught, there was no consequences. Nobody's going to jail. It's a fine. For investment banks, especially the bigger ones, fraud is baked into the income statement. It becomes part of the budget.

-----

All of the people who we think of as gatekeepers, the lawyers, the bankers, the auditors, the people making good money to ensure that the markets are clean, weren't doing anything of the sort. They simply processed the necessary paperwork, took their fees, and moved on. Companies lie. Companies have companies' best interests at heart, not a community's, not a people's. The people need to have their own interests at heart.

-----

Short selling is betting that a stock is gonna go down, as opposed to go up. Here's a simple way to think of it. I think that sugar is overvalued and it's going to cost less in six months than it does today. I see a business opportunity. I go to my neighbor and borrow one pound of sugar. Then I turn right around and sell that sugar for the going rate of $1 a pound. In about six months, when I have to give my neighbor a pound of sugar back, I go buy it on the open market, where the price has come down, and it only costs me 50 cents. I give my neighbor a pound of sugar back, plus a little extra for interest, and pocket the 50-cent difference.

-----

In China, it's not illegal to steal from foreign investors. Even if the SEC gets its entire wish list of documents from the company and they have enough evidence to pursue a case, the Chinese people responsible for this don't really care. You can't compel somebody that has stolen millions of dollars from U.S. investors to come here from China. You can't compel them to testify. You can't even look at the bank statement. Anytime there is a country like China, where information is not easily obtained, that is a much greater risk.

We sold ourselves on a myth of China as a really compelling market. A nation that wanted the leveling effects of free trade. China is fundamentally a broken societal system. The people who get to the top, get to the top by breaking rules. Good people who want to play by the rules, get stepped on and pushed to the bottom of the pile. This, in some ways, has nothing to do with China. If you gave American management teams that incentive structure, we'd have the same amount of fraud here.

In this country, when anyone says, "Just trust us," the first thing you do is hold on to your wallet. You don't trust anybody, and you don't trust anything you can't see and research for yourself. And that goes for Alibaba too.

-----

It's between $20 billion and $50 billion of market capitalization of stock that's listed here in the United States that might be worth zero. That money could never be recovered. The investors were mostly retail investors. These were mostly just people playing the American stock market, who looked at the financials and believed them. And they were also shares that belonged to mutual funds, that manage pension funds.

When we describe a fraud like this one, we use terms like "white-collar crime" to distinguish it. But really, it's just theft. 

Where did the money go? To the bankers and lawyers, who helped set up the deals. And to the Chinese executives who made millions while their companies collapsed. I don't know what's worse, that the executives were beyond the reach of the law, or that the enablers on Wall Street were operating inside the law, just doing their jobs. One way or another, almost all of them got away with it.

We point to $50 billion, and that's an empirical number. What we don't talk about is that there's hundreds of billions of dollars that we can't even begin to touch. You don't have the ability to really research it.

-----

There's an old joke that the biggest lie on Wall Street, is that this time, it's different.
