#+SETUPFILE: ../../styles/readtheorg.setup
#+TITLE: We Steal Secrets

* Timeline

| 1987/00/00 | Julian Assange began hacking with a group called the International Subversives                    |
|------------+---------------------------------------------------------------------------------------------------|
| 1989/10/18 | Spacecraft Atlantis/Galileo was launched, worm WANK was detected on NASA's network                |
|------------+---------------------------------------------------------------------------------------------------|
| 2006/10/04 | Wikileaks's domain name was registered                                                            |
|------------+---------------------------------------------------------------------------------------------------|
| *2009*     |                                                                                                   |
|------------+---------------------------------------------------------------------------------------------------|
| 2009/07/31 | Wikileaks leaked confidential documents from Icelandic bank Kaupthing                             |
|------------+---------------------------------------------------------------------------------------------------|
| 2009/10/00 | Bradley Manning was deployed to Forward Operating Base Hammer near Baghdad                        |
|------------+---------------------------------------------------------------------------------------------------|
| 2009/11/25 | Wikileaks leaked 911 pager messages                                                               |
|------------+---------------------------------------------------------------------------------------------------|
| *2010*     |                                                                                                   |
|------------+---------------------------------------------------------------------------------------------------|
| 2010/04/05 | Wikileaks leaked video of 2007 Baghdad airstrike                                                  |
|------------+---------------------------------------------------------------------------------------------------|
| 2010/05/21 | Bradley Manning contacted Adrian Lamo, and admitted leaking classified material to Julian Assange |
|------------+---------------------------------------------------------------------------------------------------|
| 2010/05/25 | Adrian Lamo gave the chat logs to FBI, leading to Bradley Manning being arrested in Iraq          |
|------------+---------------------------------------------------------------------------------------------------|
| 2010/07/25 | Wikileaks and media partners published 91,000 documents on the Afghanistan War                    |
|------------+---------------------------------------------------------------------------------------------------|
| 2010/08/20 | Swedish police investigated Assange for rape and molestation                                      |
|------------+---------------------------------------------------------------------------------------------------|
| 2010/10/22 | Wikileaks released 400,000 documents relating to the Iraq War                                     |
|------------+---------------------------------------------------------------------------------------------------|
| 2010/11/28 | Wikileaks and 5 newspapers started publishing 251,287 leaked diplomatic cables                    |
|------------+---------------------------------------------------------------------------------------------------|
| 2010/12/02 | Interpol issued demand for Assange's arrest                                                       |
|------------+---------------------------------------------------------------------------------------------------|
| 2010/12/07 | Assange surrendered to police in London                                                           |
|------------+---------------------------------------------------------------------------------------------------|
| 2010/12/08 | Anonymous hackers attacked PayPal, Visa and MasterCard sites to avenge Assange                    |
|------------+---------------------------------------------------------------------------------------------------|
| 2010/12/17 | Tunisian Revolution, Arab Spring began                                                            |
|------------+---------------------------------------------------------------------------------------------------|
| *2012*     |                                                                                                   |
|------------+---------------------------------------------------------------------------------------------------|
| 2012/08/16 | Assange was granted political asylum by Ecuador                                                   |

* Quote

#+BEGIN_QUOTE
The Internet is not a good place for secrets. Cyberspace is like a galaxy of passageways, constantly moving streams of data. With a simple computer, anyone can enter and explore. That's what Julian Assange liked to do, explore. He liked to use trap doors to enter where he wasn't supposed to go, to find secrets and expose them. He built a machine for leaking secrets and called it "WikiLeaks." The website boasted an electronic drop box that could receive secrets sent by people who didn't want to reveal who they were. Once WikiLeaks had the secrets, it would publish them across servers, domain names, and networks hso numerous that the information could never be taken down.
#+END_QUOTE

#+BEGIN_QUOTE
9/11 turned out to be a watershed moment for the world of secrets, both for the leakers and the secret keepers. In the years after 9/11, facing enemies it didn't understand, the U.S. government started sharing more information between different agencies. At the same time, the U.S. also started to keep more secrets from its citizens. In data centers that sprang up all over the country, the U.S. launched a massive expansion of its operations to gather secrets. The amount of classified documents per year increased from 8 million to 76 million. The number of people with access to classified information soared to more than 4 million. And the government began to intercept phone calls and emails at a rate of 60,000 per second. Nobody knows how much money is involved, it's a secret. Not even Congress knows the entire budget.
#+END_QUOTE

-----

#+BEGIN_QUOTE
Julian's a computer hacker. He comes from that ideology that all information is good, and everything should be published. I asked Julian if he would publish information sent to his website that could lead to the deaths of innocents, such as how to release anthrax into a town's water supply. "Yes. Even if there is a possibility it would lead to loss of life." This is a man whose primary way of interacting with the world is a digital one. It is to some degree unsullied by the limitations of human nature. He does sometimes reduce human activity to something formulaic, and he doesn't see the human heart beating in there. He just reduced it to that very, very simple formula.
#+END_QUOTE

-----

#+BEGIN_QUOTE
Items of historical significance for two wars. Iraq and Afghanistan. This is possibly one of the more significant documents of our time. Removing the fog of war and revealing the true nature of 21st century asymmetrical warfare.
#+END_QUOTE

#+BEGIN_QUOTE
"They were stored on a centralized server. I would come in with music on a CD-RW labeled with something like 'Lady Gaga', erase the music, then write a compressed split file. No-one suspected a thing. ... listened to lip-synced Lady Gaga's Telephone while exfiltrating possibly the largest data spillage in American history." Manning turned his computers into efficient exfiltration machines. Over several months, Manning made over 794,000 connections with the State Department's server. He downloaded hundreds of thousands of documents without anyone noticing. When he hit a snag, he reached out to another hacker for advice on how to crack passwords. Later, Manning talked to him about the progress of the uploads.
#+END_QUOTE

-----

#+BEGIN_QUOTE
There is a phenomenon called Noble Cause Corruption. Essentially, you do things which if anyone else did you would recognize aren't okay, aren't right. But because you know you're a good guy, it's different for you. I suppose you can't accuse Julian of not setting out from the beginning what he may do. Mendax by name, Mendax by nature. The same extraordinary personality which conceived of and created WikiLeaks is also the same personality that has effectively destroyed WikiLeaks.

WikiLeaks has become what it detests and what it actually tried to rid the world of. We must get away from this understanding that we see Julian as a savior, that's going to change all of it. The credit is undue. Everybody celebrating Julian as a whistle-blower. He's not. Bradley Manning might have been a whistle-blower, and, if he was, he is the courageous guy. He is the one that took all the risk and in the end now is suffering.
#+END_QUOTE

-----

#+BEGIN_QUOTE
Whistle-blowing is a really isolating act. It's a courageous and phenomenal thing to do, but you are essentially doing something that your colleagues and your friends would not want you to do and not understand. It alienates you further from them. A source who needs to talk to someone and explain what they've done and think through what they've done needs someone safe to do that to. In the logs, Manning says, he couldn't talk to WikiLeaks, that's not how they work. Does that protect whistle-blowers or does it protect WikiLeaks?

In the end, everybody's just human. If you're leaking material to someone, something that really makes a difference, then just from a human perspective, it's really difficult not to get any credit for it. Because no one can tap you on the shoulder and say, "Good job. Courageous thing you did." And this is really the complicated part about it. How do you make sure that your source doesn't compromise themselves?
#+END_QUOTE

* Link

1. [[https://en.wikipedia.org/wiki/WANK_(computer_worm)][WANK]]
1. [[https://collateralmurder.wikileaks.org/][Collateral Murder]]
1. [[https://911.wikileaks.org/][9/11 Tragedy Pager Intercepts]]
1. [[https://wardiary.wikileaks.org/][War Diaries]]
1. [[https://wikileaks.org/plusd/][Public Library of US Diplomacy]]
