#+setupfile: ../../styles/readtheorg.setup
#+title: IT Scrap

* 记忆传承，信息永生
** 开篇

假设你有写日记的习惯。从 5 岁开始，把每天浓缩成 2,000 字，一直写到 105 岁。那么，你一共写了 7,300 万字，相当于 100 部《红楼梦》。

这样，13,000 个你的一生，也只不过刚好能填满薄薄一片存储器，它只有指甲盖大小，只有半克重，一旦丢失，就可能再也找不到。如果有人想要在 100 年内读完这块小小存储器中的文字，他需要不眠不休，并且每秒钟扫过 300 字才行。

我们用一个更轻飘飘的单位来描述它，说它容量 2TB。这个个位数的描述，却意味着 50 万首 MP3 歌曲，或者 77 部高清蓝光电影，亦或者 67 万张 1000 万像素照片。这是 500 年前最博学多识者也无法想象的庞大信息量，现在却能闲闲放在我们的指尖，一不小心就会乘风飞去。

在这片数年之内即会面世的存储装置面前，浩如烟海不过是往事，汗牛充栋早已成笑谈。它足以记录一个人毕生的所学所想，并可以容易地传诸后世。

人们一直试图为后人留下些记忆，而从公元前 15,000 年的岩洞壁画开始，这种设想才逐渐成真。文字的发明是一大革命，它让人们可以将自己的经验与知识简单方便而明确地放在身外，让它有机会一代代传承。岩石、金属、泥陶、骨骼、皮革、布帛、竹木都曾被用于记忆的传递更替，而人们也一直在寻找更轻更快更好的载体，能够将所有在险恶生涯中艰难累积的智慧记录下来，不致遗失。

从纸张、印刷术到磁、光、半导体存储设备，存储密度变得越来越高，存储设备也越来越复杂。今天的人们可以以很少的代价，将自己的记忆完全交给这些不会忘记的金属、半导体和塑料，解放自己的大脑，让它去做更擅长的工作。无论是对机器还是对人来说，这可能都是最好的分工。

2010 年 10 月，西部数据公司的执行副总裁 Jim Welsh 谈到，到 2014 年，每户家庭平均会存储 1TB 的数字内容，而迄今已有近 60 年历史的硬盘，依然将会是最主流的存储设备。人们依然会对云存储心怀疑虑，毕竟它看起来并不如手边的硬盘看起来可靠和安全。而随着带宽的迅速增长，使用者对光盘这类存储介质的需求会下降，下载的便利性让 DVD 和其他光存储设备的价值逐渐趋近于零。

这也许只是一家之言罢了，毕竟这种论调出自世界上最大的硬盘生产商之一。只有一件事可以确定，就是我们永远需要更多的存储空间。Gartner 咨询公司认为， +世界上数据存储量正在以每年 40% 的速度递增，几乎每两年就会翻一倍。+ 这又是一个相互纠缠而发展的范例：当我们拥有更多存储设备的时候，就会发现有更多的内容需要存储；而这又使得我们不得不添置更多存储设备。这像是一条不归路，而也许正是进步所必须付出的代价。

虽然今天的存储设备已经能够达到惊人的效率，但是人们仍不满足。研究者们依然为更高的存储密度、更低的能耗而努力，试图创造出堪称完美的存储设备。它应该容量巨大，应该体积微小，应该成本低廉，应该访问迅速，应该能够长久保存，甚至直到世界末日来临的那一天。当这种介质被发明出来的那天，也就意味着人类的群体记忆，将会与人类这个物种延续最少同样长的时间。

在这系列文章中，我将会和大家一起回溯历史，回顾我们将记忆逐渐从脑中剥离的历程。我们会看到历史上曾经出现过一些存储手段，从古老而原始的刻木、结绳记事，到纸张和计算机的冲突，再到那些以今天的眼光看起来笨重得可笑的早期设备。我们会看到那些存放于身外的记忆，犹如一个动作迟缓的婴儿般蹒跚学步，直到突然以迅雷不及掩耳之势放足狂奔，成为我们生活中不可或缺的成员，并且裹挟着我们轰然前行。

当然，伴随着这一路历程的，是那些改变了我们生活的人们。他们以天才的想法和不屈的努力为起点，以痛苦失落和奋力挣扎为代价，改变了世界的面貌，成就了今天日常生活的基础，让我们受益无穷。我打算写下这些文字，只是因为他们的故事值得被阅读。

那么，让我们开始吧。

-----

#+begin_quote
在西高峰的近旁，有一具已经风干冻僵的豹子的尸体。豹子到这样高寒的地方来寻找什么，没有人做过解释。—— 欧内斯特·海明威，《乞力马扎罗的雪》
#+end_quote

马尔塞利诺·桑托拉，1831 年出生于西班牙的圣米盖尔，毕业于马德里大学法律系，是一位博学的考古爱好者，生活充实而富足。1875 年，一位牧羊人告诉他，在他家族拥有的阿尔塔米拉（Altamira）牧场上，发现了一个岩洞，似乎有人生活过的痕迹。这位考古爱好者自然不会放过这样的机会，他兴冲冲地前往，第一次考察就找到了一些小件文物。但是他也没有把这件事太放在心上。直到在 1878 年的巴黎世界博览会上，他发现法国南部的一些文物与他找到的文物十分相似，才重新产生了考察的兴趣。1879 年，他带着九岁的女儿玛利亚重返故地，再次钻进这个石灰岩洞穴中。

在颤动的蜡烛光下，眼尖的小女孩发现了岩壁天顶上巨大绘画。桑托拉在被震撼之余，很快从马德里大学请来考古学家比拉诺瓦·彼拉，合作对这个洞穴做了深入调查。他们一致认为这应该是旧石器时代的绘画，并且在 1880 年里斯本的一次国际考古学会议上，发表了调查报告《桑坦德省史前文物调查笔记》。

file:../images/ji_yi_chuan_cheng/01.jpg

然而，这项发现并没有获得应有的重视。当时的主流学界并不认同他的发现，欧洲人类学和考古学的领袖人物，法国科学家加布里埃尔·莫尔蒂耶和埃米尔·卡太海克认为，旧石器时期的人类不可能拥有如此高超的绘画技艺，认为这些应该是现代人的手笔，认为是桑托拉伪造了这一现场以骗取名誉。在这样的舆论背景下，当时的学界甚至不肯派出考察人员去实地考察一下。1888 年，桑托拉去世，一直到他去世的时候，还被认定是一个可耻的造假者。

进入二十世纪，更多的有史前壁画的洞穴被发现。直到 1902 年，人们才确认了这处壁画的真实性。卡太海克考察了[[https://en.wikipedia.org/wiki/Cave_of_Altamira][阿尔塔米拉洞穴（Cave of Altamira）]] ，并且向玛丽亚保证，一定恢复她父亲的名誉。他发表了著名的《一个怀疑主义者的忏悔》论文，公开承认他先前犯的错误。桑托拉和他女儿的发现终于获得了肯定。

阿尔塔米拉洞穴中的绘画，是用坚硬的石头刻出了浅浅的轮廓，再用木炭、赭石，以及混合动物血和脂肪的颜料涂抹而成。这里一共有超过 150 幅壁画，被画下的形象包括野牛、野马、野猪、羊和鹿等等，造型真实而优美。这些被叫做克罗马农人的晚期智人在 10,000 多年前像是突然之间达到了一个艺术高峰，至今在考古学上依然没有发现任何先兆，就像是突然插进了历史旋律的一记强音，又突然消失。许多在这些壁画中使用的技法，如透视画法、动态感等等，一直到 10,000 年之后的文艺复兴时代，才又被重新发明出来。

现在，这个洞穴已经成为了世界文化遗产，受到严密的保护。那些身处冰河时期的人们当然不会意识到，他们的后代会把这处他们栖身的洞穴视为人类艺术的起点，也是人类知识传承的开端。

然而，这些壁画到底有什么作用，人们还只能猜测。我们只能从这些绘画中看到，那个时期的人类与野兽们共同生活的记忆，他们彼此围猎、追逐、搏斗和残杀。当夜幕来临，人类回到他们栖息的洞穴，用手边随手可得的原料，默默地记录起那些惊险、勇敢、生存的快乐，以及死亡的伤痛。

他们选在了在当时唯一可以选择的表达方式来记录他们的记忆和感情，这种方式不需要任何解释，就可以跨越种族的隔阂。这些史前人类以他们能想到的最直接的方式记录下他们的生活，这些洞穴里的绘画也许是当时人类的历史，也是他们的生存的记忆与信仰。他们使用木炭和颜料来记录的内容，与今天我们藉由现代存储设备保存的东西，并没有本质上的区别。只是，他们的这些绘画保存了上万年之久，而直到今天，还没有任何人工制造的存储设备能与之比肩。

+纸张，不过能保存百年而已。软盘只不过能保存几年，光盘的有效期也只有十几年。一次摔落就可能对硬盘中的数据造成破坏，即使是全固体的半导体存储器，也只能保证数十年的记忆。+

而更重要的，是 +这些记录设备都需要相应的读取装置+ ；就连纸张上的文字，也需要最合适的解读。而最反讽的是， +获取读取装置的方法，却刚好被存放在这些记录设备当中+ ，就像是将保险箱钥匙锁进保险箱一样无解。

当另一种生物成为这个蓝色星球上的主宰者的的时候，也许阿尔塔米拉洞穴的壁画会依然留存，但是现代人类文明的记录，或许已经丢失殆尽，或许再也不会被解读出来。

也许正像科幻作家刘慈欣在《三体：死神永生》中所写到的那样，要将记忆保留下来，最好的办法是把它们刻在石头上，深深地刻进去。

** 字纸漫漫

#+begin_quote
永远无法根据过去而规划将来。—— 埃德蒙·伯克，《给一位国民大会成员的信》
#+end_quote

1947 年初，16 岁的默罕默德·艾拉迈德正在在死海西北岸放羊。在寻找走失山羊的时候，这个贝都因族的年轻牧羊人发现了一个岩洞。他往岩洞里扔了一块石头，却听见打破了器皿的声音。小伙子钻进去看，发现了一些陶罐，而埋藏了 2,000 年的记忆，就此苏醒。现在，这些古人的记忆正在被扫描成高精度的电子版本，单薄而易碎的古老遗物，将会和现代存储装置共存亡。

file:../images/ji_yi_chuan_cheng/02.jpg

陶罐里存放的，是历史上最为重要的典籍之一：[[https://en.wikipedia.org/wiki/Dead_Sea_Scrolls][死海古卷（Dead Sea Scrolls）]] 。在之后的 10 年间，人们在这片地区附近的 11 个山洞中发掘出了更多的古卷，一共能拼成约 900 种不同的文献。在公元前 100 年到公元后数十年之间，一族迁徙至此的犹太文士收集和抄写了这些文献，并在公元 66 年到 70 年间第一次犹太人起义的时候，把这些珍贵记忆藏进了干燥的洞穴中。

这些古人的文字写在磨光的薄薄羊皮纸和纸莎草纸上，用麻布紧裹，外面还浇上了一层沥青。只有这样，在那种干旱的环境下，它们才能保存 2,000 年。而即便这样，这些文件现在也已经残破不堪，在博物馆展出的时候只能用亮度很低的小灯照射，以尽可能避免光线带来的损害。在时间面前，人造物总是显得脆弱无比。

羊皮纸、纸莎草纸，以及在东方广泛使用的竹木丝帛，是人们最早的便携式存储器。太阳底下并无新事， +这些存储器和磁盘光盘的原理依然相通：利用外界力量改变存储介质的表面特征，为这些改变赋予意义，让它们可以分辨和识读。+

+而这些存储装置，必须依赖一个前提：公认的记录符号——也就是文字——的发明。+ 在文字出现之后，那些轻飘飘的说出口就马上消失的语言，终于找到了载体；人们之间的交流，终于在时间和空间两个维度上，同时获得了极大的扩展。文字，就像希腊神话中普罗米修斯从天上盗来的火种，终于燃起了文明传承的熊熊烈焰。

** 以纸为薪

然而，文字天生的简单性，让它无法细致而全面地记录下所有信息，也让它只能做为一种无奈的代用品而存在。大哲学家苏格拉底认为文字的发明会导致人类记忆退化，甚至把这些书写的符号同麻醉药相比较，认为这两者在提供好处的同时，也会带来消极的负作用。他的学生柏拉图更加激进，认为文字已经成为了某种不利于人类的“异己"，认为书写文字同真实的思想之间存在着距离，认为通过文字，人们获得一些近似智慧、而非真正智慧的东西，却让人们自以为无所不知。

+这两位大哲人都认为，文字是死的，它没有能力辩解和诠释。它只是思想的尸体而已。然而反讽的是，我们之所以能获知他们的观点，却恰恰是文字的功劳。文字的无力和模糊，也许是在那个时代，为了广泛传播而必须付出的代价；而能跨越时间和空间的更好的沟通方式，还远远没有诞生。+

死海古卷上的文字，完全是逐一抄写而成。人工抄写是件相当繁重的工作，特别是当抄写时不能出现任何错误时，更是如此——这些早期圣经的抄写者对产品质量要求很高，哪怕在一页上只写了一个错字，就要重抄整页。当时的抄本就像是上世纪五十、六十年代的计算机，笨重，昂贵，并非每个人都能拥有。

这种情形持续了上千年。 +存储介质的昂贵和书写速度的缓慢，让文字中蕴含的知识注定只能被少数人获得。出身和财富，往往决定了在人类知识阶梯上能够攀到的高度；+ 而绝大多数人，甚至连攀爬这把梯子的权利都没有。只有降低获得知识的成本，文明才可能更迅速地发展。

在西方人依然在羊皮纸上抄抄写写的时候，公元 105 年，宦官蔡伦将改良后的纸献给了汉和帝。这是一项废物再利用实验的成果，那些天然植物纤维经过挫、捣、抄、烘等工序，很快就能变成便宜、便携而性能不错的存储器。 +在之后的数百年里，造纸术愈发成熟，传遍整片国土，而能够与之相配合的记录技术，却渺然无踪。+

直到汉和帝第一次看到改良纸之后 500 年，高速而低成本的书写技术，才姗姗而来。

** 印章的放大版

#+begin_quote
报纸的使命是印出新闻和制造麻烦。—— 威尔伯·斯特瑞，《芝加哥时报》,1861
#+end_quote

file:../images/ji_yi_chuan_cheng/03.jpg

+在大量生产光盘时，普遍使用的是压铸工艺。+ 人们会用金属制造一个光盘母版，它像个印章，一次次在基板上印出独特的凹陷小坑，每个小坑的大小甚至无法直接被肉眼分辨。 压铸光盘和刻录光盘的区别，刚好就像是雕版印刷和手抄的区别一样。

雕版印刷术，大约 1,400 年之前的发明。历史学家对雕版印刷的具体发明年代依然争论不休，但是主流的观点认为，大概是隋朝到唐代之间的事情。隋朝费长房所著《历代三宝记》中，有“废像遗经，悉令雕撰”之说，是人们主要的判断依据；然而正是这句话，让人们产生了不同的解读。文字的模糊，再一次让人们迷惑。

实际上，在有了印章之后，雕版的发明可以说是水到渠成的事情。在殷墟中就已经发现了印章，传国玉玺这种东西，并非秦始皇的首创。到了晋朝末年天下割据的时代，早在春秋战国时期就出现了阳文印章，大面积的雕版印刷，更只是个时间问题。然而， +目前能够找到的最早的雕版印刷制品，是公元 868 年的《金刚经》。+ 更早的资料，即使曾经出现过，也遗失在历史当中。

因为中文字的结构复杂多变，雕版印刷术在中国流行了相当长的时间。甚至有人认为，雕版印刷的出现改变了人们手写文字的方式——用雕刀刻印出的书籍，让手写字也变得更加简洁有力。这种印刷术具有如此强大的生命力，以至于所有尝试改变雕版印刷的努力，在很长时间内都不了了之。

在这些努力中，最耀眼的应当算是活字印刷。活字印刷试图将印刷的最小单位从页变成字，以此来增加印刷的灵活性； +然而它需要的大量初期投资注定了它只是小众产品。为常用的数千个汉字制造字模是个浩大的工程，更何况在少量印刷的时候，活字印刷并没有突出的优越性。+ 从北宋开始，人们不止一次尝试过活字印刷，泥活字、木活字、锡活字、铜活字都曾经被开发出来，技术已经发展成熟，然而却从未如同雕版印刷般盛行。

file:../images/ji_yi_chuan_cheng/04.jpg

随着欧风东渐，1807 年，西方的合金活字才进入中国。这时，距离毕升制造出泥活字已经过了 800 年，而离欧洲人第一次用活字印制出圣经，也已经过了 350 年。

** 让世界听见我的声音

如果你去德国美因兹市，会在中心广场上看到约翰内斯·古登堡（Johannes Gutenberg）的雕像，只不过那并不是按照他的相貌雕刻的。实际上，我们对这个发明了合金活字印刷术的人了解不多，只知道他是一个探险家、一个金匠，开办过不少企业、负过许多债、和许多生意伙伴闹上过法庭。他做为工匠的经验，使他终于用铅锡合金制造出耐用的活字字模，而他的探险家精神，让他最终配置出了适合金属使用的油墨，以及制造出原始的印刷机——和用来为葡萄榨汁的机器十分相似。 +现代印刷的四大要件：活字及其定位法、适宜印刷的墨水、印刷机本身和印刷用的纸张，古登堡解决了其中的三项。+

file:../images/ji_yi_chuan_cheng/05.jpg

古登堡大概活了 60 多岁。在生命的最后 20 年中，终于掌握了必要的技术，从而开发出一套完整的活字印刷术。然而他并不能算是个成功的商人，在一次贸易纠纷中，他甚至不得不将自己开发出来的活字印刷机器赔给生意伙伴。显然，他的生意伙伴更有生意头脑，活字印刷厂很快就开始盈利。而古登堡只来得及印刷出少量作品，其中包括著名的《四十二行圣经》，每套分上下两卷，共有 1,282 页。这套书印了 180 套，目前世界上还留存 49 套，每一套都价值连城。正是这些圣经，让他在生命的最后 3 年中，终于可以在主教的庇护下，不必颠沛流离。

显而易见，古登堡的活字印刷术比手抄方式方便得多。活字印刷几乎马上传遍了欧洲，在大概 50 年间，就印制出了 30,000 多种印刷物，总数超过 1,200 万份。这种势头让教廷相当恐慌，认为魔鬼的诱惑也将可以凭借便宜的书本而占据人们的脑袋，让人们背离上帝的意旨。

而真正的原因在于， +当人们都能独立阅读和独立思考时，建立于无知和欺骗之上的威权将不复存在。+ 1517 年，年轻德国牧师马丁·路德印制了那本著名的《九十五条论纲》，并且借助活字印刷术，迅速燃起了分裂天主教的烈火。如果在 100 年前，马丁路德也许只是一个地方名人，然而在活字印刷术的帮助下，他的声音，可以被全世界听到。技术，就这样改变了世界。

file:../images/ji_yi_chuan_cheng/06.jpg

在十五世纪，古登堡的印刷机每小时可以单面印制 300 张，300 年之后，蒸汽动力的印刷机就将印刷速度提升了 25 倍。

人们开始不再满足。人们想让机器也能够识字。

** 二进制的经纬纵横

#+begin_quote
织布机告诉我们目标，这是命运。—— 《刺客联盟》，2008
#+end_quote

1715 年，曹霑在南京出生。这个孩子自然不会预料到他将会以一部小说而名留后世，也不知道家族世代经营的事业正如夕阳般坠下。当时的江宁织造已由曹氏家族执掌了 50 年，辖下 50,000 余名织工继续用流传了数百年的技术织出云锦，这种灿如云霞的锦缎只供皇家使用；而织工们按照传统挑花结本，把复杂的织物花纹转成一串用线存储的二进制代码，再依照这些代码，织出龙袍妆花。

+在织布机上，预先固定好的竖线是经线，而用织梭从中穿过的则是纬线。纬线从经线上方还是下方穿过，就决定了织物的花纹。繁复的花纹需要多种颜色的丝线，更需要准确无误的操作。+ 而单凭人脑来记忆几十种颜色的纬线应该如何穿过经线，无疑是不可能的任务。

+所以早期的织匠们制出了图纸——结本。做为纸上花样和织出锦缎的中间步骤，这些打了结的线条会告诉织工，每种纬线穿过时经线应当提起还是沉下。+ 配合口诀，织匠们可以尽可能地提高效率。

十五世纪，南京云锦艺人制造出了云锦妆花环形花本大花楼织机。这种庞大的提花机高达 4 米，需要两个人配合操作，楼上的拽花工唱出口诀提升经线，楼下的织手根据提起的经线，投梭打纬妆金敷彩。 +大花楼织机再没有过太大的变化，可以认为已经达到了人工织锦的效率极限——然而，这也不过意味着每天只能产出几厘米的成品而已。+

file:../images/ji_yi_chuan_cheng/07.jpg

寸锦寸金，说的就是这种情形。所以元明清三代，都设置了江宁织造以供应宫闱之内的锦缎需求，形成了容纳数十万人的产业。到了曹雪芹出生的康熙乾隆年间，正是云锦的鼎盛时期，秦淮河畔织户云集，机杼声彻夜不绝。

12 年后的雍正初年，曹家被革职抄家而没落，而提花机依然不紧不慢地唧唧作响。此时，在遥远的法国，已经有人开发出了更方便的提花机，只需再过一个世纪，织花锦缎就不再是奢侈品。提花机学会了认出纹样，靠人工记忆的口诀也失去了用武之地。

** 识字的机器

+欧洲游历和学徒的传统，造就了许多城市独特的支柱产业，例如威尼斯的玻璃业和法国里昂的丝织业。+ 1725 年，里昂的织匠鲁修做出了开拓性的发明：他用打孔纸带控制经线的提起和放下，从而让织出花样成为了一种半自动的工作。

做为一个乐器工人的儿子，鲁修把家学和自己的工作结合得很好。然而，柔软的打孔纸带不能织出太宽的织物，这是它的致命伤之一；而纸带依然需要有人照看，每穿过一次纬线，纸带就需要向下移动一格。 +鲁修提花机的最大贡献，在于实现了花纹的二进制存储——以机器能够识别的方式。历史上第一次，机器能够读出存储介质中的内容，并且照其行事。+

3 年后，鲁修的合作者部分地解决了这种提花机的问题：他用打孔的硬卡片取代纸带，每片卡片上记录几行纹样内容，然后将这些卡片连接起来，构成一个大环。这样就能够织出更大的幅面，也能免除在循环的纹样中更换纸带的工作。又过了将近 20 年，发明家沃康松制造出能随着织物的进程而自动进动的纸卡输送装置，进而革新了纺织工业，全自动提花机就此诞生。

虽然沃康松的提花机还有些缺陷，但是的确能够提高纺织的速度。然而，迎接这位发明家的，却是失业的纺织工人迎面扔来的石头。机器抢夺了人们的工作，人们就把怨气撒在机器的发明者身上——这在那个资本主义发展不久的时期，十分常见。

纺织工人的怒气并没有阻挡提花机发展的进程。 1805 年左右，法国人雅卡尔（Joseph Marie Jacquard）终于发明了堪称完美的提花机，可以用打孔纸卡控制花纹，完全自动，而且效率是之前的 25 倍，就像一台计算机一般。当时的法国皇帝拿破仑专程来参观这台机器，赠与雅卡尔终身奖金，还允许他从每台卖出的提花机中提取五十法郎。仅仅过了几年，欧洲就有了 10,000 余台雅卡尔提花机（Jacquard loom）。

file:../images/ji_yi_chuan_cheng/08.jpg

雅卡尔提花机，可以算是现代计算机的起源之一。几十年后，世界上第一位程序员——一位女性——谦逊地把第一台可编程数字计算机与雅卡尔提花机相比，而这位女程序员，正是诗人拜伦的女儿。

** 那些超越时代的天才

#+begin_quote
精炼我们推理的唯一方式，是让它们和数学一样切实。—— 戈特弗里德·莱布尼茨，《发现的艺术》
#+end_quote

如果要评选十九世纪 Geek 女神的话，奥古斯特·艾达·金（Augusta Ada King）一定能上榜。她是诗人拜伦的女儿，查尔斯·巴贝奇（Charles Babbage）的助手和合作者，拉弗拉斯伯爵夫人，以及世界上第一位程序员——甚至远在“程序员”这个词被赋予现在的意义之前，她就写出了程序，而且打在了硬纸卡片上。

file:../images/ji_yi_chuan_cheng/09.jpg

虽然是拜伦的女儿，但是艾达几乎没有见过自己的父亲。在出生后几个星期，她的母亲就带着她返回娘家，两个月后更是签署了分居协议；而她那热血浪漫的诗人父亲几个月后远赴法国和瑞士，最终客死异乡。艾达的数学天分据说来自母亲，灵动的思维则可能来自父亲——这两者在她后期的研究中缺一不可。良好的家庭环境让艾达能够遵循自己的兴趣，优秀的家庭教师们也为她提供了良好的教育。

在她的家庭教师里，有一些相当出色的人物，例如提出了徳·摩根定律的数学和逻辑学家奥古斯都·徳·摩根，以及女科学家玛丽·索麦维。正是在后者的介绍下，1833 年 6 月，不满 18 岁的艾达遇见了查尔斯·巴贝奇。

两个人的命运，从那一刻开始，紧紧纠缠在了一起。

file:../images/ji_yi_chuan_cheng/10.jpg

查尔斯·巴贝奇，那个时代公认的博学者——或者失败者，这完全取决于观察角度。他毕业于剑桥大学，20 岁的时候就协助建立了英国统计学会，25 岁就成了英国皇家学会会员，37 岁的时候成了母校的卢卡斯数学教授——牛顿曾经担任过的职位。他是发明家、数学家、多产作家以及梦想家。从 20 岁起，他就开始计划制造一台能够自动计算的机器，把人工从繁复的计算中拯救出来。 +而大量的人工计算，正是那个时代欧洲的特色之一。+

1819 年，巴贝奇在一次去法国的访问中，看到普隆尼男爵招募大量计算工人，在几组数学家的带领下趴在桌上写写算算的情形，深受这种智力放大方式的震撼；而这些计算结果的质量之低，更是让他感到无力。当时的科学作家迪昂赛斯·拉德诺写道，从 40 册表里随机抽样，就发现了 3,700 项错误；而根据巴贝奇的计算结果，这些计算错误，每年将会为政府带来超过 300 万英镑的损失。

看来，制造自动运算机器，势在必行。

** 从计算开始

+对数，是当时社会发展的重要基础之一，无论是金融、航海还是天文，都离不开能够简单把乘除化为加减的对数运算。+ 和今天课本上附带的《常用对数表》一样，快速运算也要依赖于对数表；而世界上第一份对数表，却只能靠手工来算出。

巴贝奇就是打算解决这个问题。1822 年，他制造了第一台差分机（Difference Engine），能够进行 3 个 5 位数的加法运算，结果能达到 6 位数。接下来的梦想更加宏伟，他与英国政府签订了合同，计划在两到三年内，制造出可以计算 7 个 20 位数的差分机，并且自带打印功能。

然而，这个计划失败了。也许是因为总是冒出新点子的巴贝奇不停地改动设计，也许是他找到的制造商无法实现他要求的精度，第二部差分机花了 10 年时间和 30,000 英镑的投入，却只完成了七分之一。而此时，巴贝奇几乎将所有精力都放在了一个新项目上——他已经意识到了差分机的不足，并且计划制造出通用的计算机：分析机（Analytical Engine）。

就在这时，他第一次遇见了艾达·拜伦。

巴贝奇设想的分析机采用十进制计算，用齿轮存储 1,000 个 50 位数，能做平方和四则运算。这台用蒸汽机驱动的机器有 30 米长和 10 米宽，每秒钟能够计算一次。几乎所有的人都认为巴贝奇是痴人说梦，而艾达不这么看。她很快理解了巴贝奇的设计，并且预料到了分析机可能的用途，这些用途甚至是巴贝奇没有想到的。艾达写道：“这种机器也许可以作曲，或者解决复杂的问题。”

file:../images/ji_yi_chuan_cheng/11.jpg

1841 年，已经是三个孩子母亲的艾达正式成为巴贝奇的合作者。她把巴贝奇用法文撰写的论文翻译成英文，添加了自己的注释，让这部论文的长度增加到最初的三倍。正是她，从提花机中得到灵感，将分析机的程序用打孔卡片输入，也建立了子循环和条件分支的概念。算法终于不再用硬件实现，而可以通过挂上不同的纸带而实现不同的运算。

而这时，这两位先驱者遭到了巨大的打击。英国政府正式终止了差分机的合同，新任首相公开声称差分机的唯一的用途就是费钱。在制造差分机时自己搭了 13,000 英镑的巴贝奇早已一贫如洗，两人只能靠偶尔销售些小东西来继续支撑。

1852 年，从小体弱多病的艾达因癌症去世，终年 36 岁，留下的只有大量文档和世界上第一个程序的设计：一个计算伯努利数的分析机专用程序。巴贝奇 20 年后去世，就连登在《泰晤士报上》上的讣告也嘲笑他的失败。

他们都没有看到自己梦想成真的那天。

** 凝固的声音

#+begin_quote
怎么说呢，我从来没有听见过有声电影的声音。—— 汤玛斯·爱迪生，生前最后一次接受采访。
#+end_quote

书写在纸上的文字，只对认识这种文字的人来说才有意义。只要有一套已成共识的符号系统，就可以传递任意的想法。这些符号是什么并不重要——福尔摩斯侦破的《跳舞的小人》一案，就已经做了很好的诠释。文字并不是最方便的方式，的确有其他方法可以达到同样的效果。例如速记法。

170 年前，巴黎的一位印刷商和书商就这么想。他还是一名兼职发明家，名字叫爱德华-莱昂·斯科特·德马丁维尔（Édouard-Léon Scott de Martinville）。大概是出于职业敏感，他对快速记录很有兴趣：在 30 岁之前，他一直专注于如何能够让速记技术变得更有效率，写了一些这方面的论文，还出了一本书，谈到速记法的历史。

但是很快，斯科特不再满足于速记。这也许是因为他意识到，如果能够直接将声音转化成文字，会更高效。这是个了不起的突破——之前人们没有想过还有这种可能。这就像是打字和语音识别的区别一样。

于是，他花了 8 年时间，解决了这个问题的第一步。1857 年 1 月，斯科特向法兰西学院提交了一份设计图，两个月后获得了一项专利。世界上最早的留声机（ponautograph），就在这项专利中。

这台留声机所用的存储介质很特别，是用煤烟熏黑了的纸。声音从大喇叭状的接收器传进来，空气的震动推动一支短而轻的针尖，在运动的纸上刮下煤烟，留下浅色的波纹状线条。声音的震动终于转成了图像，就像是今天我们看到的声波图，只是表现方式不大一样。唯一的问题，是这种记录下来的声音不能被还原。它只是能记录，能储存，仅此而已。

file:../images/ji_yi_chuan_cheng/12.jpg

不过这对于斯科特来说也已经够了，毕竟他发明这种设备，是为了研究声音的特征。1860 年 4 月 9 日，他录制了一首已经有悠久历史的法国儿歌《在月光下》。2008 年，人们终于借助计算机技术将这首歌还原了出来，可以在 [[www.firstsounds.org]] 收听或下载。请不要抱太大的希望，因为这段还原自 150 年之前的录音噪声很大，几乎听不出曲调；但是它是迄今为止，跨越时间最长的人声。

斯科特将声音记录视作转为文字的中介，并不认为单纯地保存声音有太大的价值。甚至直到晚年时他也依然认为，另一名发明家所发明的留声机误解了记录声音的根本目的。而被他指责的那名发明家完全不以为意——他叫汤玛斯·爱迪生，听力不大好。也许他根本就没有听到斯科特的言论。

** 从铝箔到虫胶

今年 2 月 11 日，Google 的 logo 又变了。这次是一幅 gif 动画，上面有一盏白炽灯慢慢闪烁。这是为了纪念汤玛斯·爱迪生而设计的；那天，是他诞辰 164 周年。

file:../images/ji_yi_chuan_cheng/13.gif

做为通用电气公司的创始人和作品最多的发明家之一，爱迪生是一个传奇人物。1876 年，他在新泽西州的门罗公园建立起了第一个工业研究实验室，第二年的 12 月，便在改进电话送话器的过程中，顺手发明了留声机。这款留声机的思路和斯科特的留声机有些相似，而区别在于爱迪生使用的存储介质是柔软的铝箔——针尖在铝箔上刻下凹痕，这些凹痕能够在重放时，重新把针尖的颤动还原成声音。

不知出于何种考虑，爱迪生流传下来的第一段录音也是儿歌。现在没有人会听到这段仅有八秒长的爱迪生版《玛丽有只小羊羔》，因为铝箔的柔软性质决定了它只能用很少几次。爱迪生当时并没有试图解决这个问题，毕竟能够把声音录下而且播放，就已经是项惊人的成就。

8 年以后，电话的发明者亚历山大·贝尔和他的堂弟奇切斯特·贝尔推出了更耐用的蜡辊式留声机，爱迪生也很快开始生产同样的设备。又过了两年，出生在德国的美国人埃米尔·柏林纳（Emile Berliner）获得了碟式留声机的专利。用一片碟片录制声音显然更有优势：它意味着可以容易地复制。1892 年，柏林纳以镀金的铜模做为母盘，以硬蜡为原料，成功实现了声音的大规模复制。唱片工业就此诞生。

即使是爱迪生本人，可能也没有预料到留声机会有这样的发展。他改进的微声器被用在各式各样的留声机上，唱片的材质也从硬蜡变成了虫胶——紫胶虫的分泌物。1925 年，贝尔实验室开发的电气化录音方式终于由美国哥伦比亚公司商业化，大众录音时代到来了。

1929 年 11 月，在经济大萧条中，爱迪生退出了留声机界。他所坚持的蜡辊式留声机无法与新式唱片竞争，虽然当时的一张标准唱片最多只能存储 10 分钟声音，但是它体积更小，更容易制造，声音效果也更好。

两年后的 10 月 18 日，爱迪生以 84 岁高龄走完了一生。他亲眼看到自己发明的留声机已经变成了电唱机，走进了千家万户。也许他不会预料到，在一片繁荣的唱片工业的阴影中，一种新的存储技术正在慢慢成形，并且将会彻底埋葬电唱机和唱片。而为唱片的坟墓掘起第一锹土的，正是他创立的通用电气公司。

** 声、电、磁

贝尔发明的电话，实现了声音与电流之间的相互转换；而人们早已知道，电流和磁场也存在着对应关系。这也就意味着，声音可以转化成磁信号存储起来。

最先意识到这一点的，是美国人奥伯林·史密斯（Oberlin Smith）。这位发明家和实业家是英国移民的孩子，一位模具设计和制造的好手，一家金属加工厂的主人。他是个天生的发明家，低调而敏锐，不喜欢申请专利的繁琐手续，而更乐于把自己想法画出草图记录下来。在他留下的文件里，有大量与汤玛斯·爱迪生、亚历山大·贝尔等人的通信，讨论了许多创新和改进的设想；而在他的家乡，人们并不知道他的这些业余爱好。人们认识的只是企业家史密斯而已。

在爱迪生发明留声机后，史密斯就开始设计新的录音方式。1888 年，他在《电气世界》杂志上发表文章，提出了以磁存储方式记录声音的设想。他认为可以 +将连续的钢丝看做无数小磁铁的集合体，将声音转化成强弱不等的电信号之后，以电流产生的磁场在钢丝上留下不同强度的剩磁。将这一过程逆转，就可以利用磁信号播放出声音。+ 他确认这一设想可行，但是并没有制造出能工作的产品原型。直到 1898 年，大洋彼岸的一位工程师才将他的设计变为现实——钢丝录音机（magnetic wire recorder）诞生了。

钢丝录音机的发明者是瓦尔德马·波尔森（Valdemar Poulsen），1869 年出生于哥本哈根，是丹麦高等法院一位法官的儿子。老波尔森把自己的儿子送进了医学院，希望他能成为医生，但是瓦尔德马在医学院里的生活并不开心。他发现自己对医学实在提不起兴趣，让他感到有趣的只是物理学和绘画。24 岁的时候，他从医学院退学，进入哥本哈根电话公司，做起了排查故障的工作。这份工作很清闲，让他有许多时间来钻研自己的兴趣。大概就在这时，他看到了奥伯林·史密斯的文章。

file:../images/ji_yi_chuan_cheng/14.jpg

1898 年 12 月 1 日，波尔森申请了一项名为“录话机”的专利，这是历史上第一部以磁信号存储声音的设备。这项发明描述的设备与现在的录音机在外观上并无本质上的不同：两个缠绕着存储介质的卷轴，用来录制和读取信号的磁头，以及用于输入的麦克风和产生输出的耳机。只是，它离实用还有十几年的距离。

** 通用电气的反击

1900 年的世界博览会上，波尔森的钢丝录音机大出风头，就连奥匈帝国皇帝弗兰茨·约瑟夫一世，也在录音机上留下了一段录音。

但是，钢丝录音机并没有获得商业上的成功。当时电子管和偏磁技术都没有被发明出来，钢丝录音机播放的声音很小而噪音很大。1903 年美国电报公司投入巨资，打算发掘钢丝录音机的速记用途，但最终失败。就像最初的火车比不过马车，早期的汽车会让人一身油腻一样，新发明往往并不完美。

1907 年，波尔森发明了直流偏磁技术，降低了钢丝录音机的噪音；而直到电子管放大器发明之前，声音太小的问题都没有解决。钢丝录音机开始有了些生机，但是大部分的市场依然是留声机的天下。波尔森开始设计更好的录音机，其中有一种设计和现在的磁盘相似：一块直径 4.5 英寸的钢盘，上面有螺旋形的轨迹，针状的磁头如同电唱机的唱针般划过其间，写下或者读出磁信号。不过，这种设备没能量产。

钢丝录音机启发了许多人，钢丝变成了钢带，钢带又变成了磁带。1928 年 1 月 31 号，弗里茨·弗莱莫尔获得了磁带式录音机的专利。这位长居德国的奥地利工程师 +用涂上铁粉的烟纸替代钢丝，发明了磁带录音机。+ 这种录音机使用 16 毫米宽的纸带，但是每次只使用一侧的 8 毫米。纸带以每秒钟半米的速度运动，300 米长的纸带一共可以录制 20 分钟。

4 年后，德国通用电气公司对弗莱莫尔的录音机表示出兴趣。1932 年秋天，以化工产品起家的巴斯夫公司也加入进来，合作推进磁带录音机的商业化。两家公司的君子协定执行得很好：德国通用电气生产所有的机械和电气化部件，而巴斯夫公司则专门生产磁带。

1935 年，这种机器在柏林无线电展览会上展出，随后就做为国家技术机密被严格控制。而与此同时，英国的 BBC 广播电台开始使用钢带录音机录制节目，整台录音机重达 1 吨以上，在剪辑的时候，要用到焊枪才行。

在之后的 20 年间，电唱机渐渐式微，钢丝录音机和磁带录音机竞争激烈。最终，轻便易携的卡式磁带录音机终于一统天下，但这已经是六十年代之后的事情了。

** 自学成才的奥地利人

#+begin_quote
我很清楚，我比父亲聪明得多。—— 汤玛斯·沃森，1892
#+end_quote

二十世纪二十年代，一些企业已经开始使用机械化的工具，例如机械计算机和制表机。这些机器使用打孔卡片来输入数据，效率比人工要高得多，而且不易出错。偶然的机会让一个小办事员发现了自己的天赋，世界也因此变得不同。

古斯塔夫·陶舍克（Gustav Tauschek），十九世纪的最后一年出生于奥地利。他的前半生风平浪静，按部就班地读书、上学，直到成为了一名银行的办事员，并且看起来可以这样安稳地过完下半生；但是一张错误的支票改变了一切。

陶舍克的工作是检查支票是否合法，以及是否缺乏必要的签名。大概是在 1926 年或 1927 年，他发现一张来自帕沃斯会计公司的支票缺了一个签名。在他去帕沃斯公司办公室的时候，第一次看到了机械式制表机。

我无法想象当时他当时受到的冲击，但是一定相当震撼——因为他把之后的近 20 年时间都花在了和制表机相关的领域上，直到生命的尽头。他请帕沃斯公司的工作人员为他讲解制表机的结构和原理，在听说这样一台机器要卖 15,000 到 20,000 美元的时候，他下定了决心。这东西应该可以更便宜。

这个想法点燃了他的热情。他前往美国、英国和德国的专利局，复制了所有和制表机有关的专利，深入研究了一遍，然后开始申请大量的专利：在之后 17 年左右的时间里，他一共拥有了超过 200 项专利，从改进的制表机到能够模仿手写笔迹的机器，从能够自动识别字符的识别系统——没错，就是 OCR，光学字符识别——到世界上第一部可用于计算的磁存储器，磁鼓。

最令人惊叹的，是这些革命性的发明大都是在 1928 到 1932 年之间诞生的。他像是将前半生的精力都在这几年里燃烧了出来，燃出一道灿烂夺目的轨迹。

最先注意到陶舍克的发明的，是德国的莱茵金属公司，德国的老牌国防企业。他们邀请陶舍克去为他们工作，还成立了一家子公司，专门生产改进的制表机。而几乎是在同时，陶舍克也被另一个传奇人物看中。

争夺开始了。当时的人们都不会想到，这次争夺会带来什么样的后果。

** 传奇诞生

让我们把时间向前拨一点。1896 年，根据查尔斯·巴贝奇的理论，统计学家赫尔曼·霍尔瑞斯建立了“制表机公司”，但是经营得并不好。1911 年，连同制表机公司在内的三家企业合并成“计算-制表-记录公司”，简称 CTR 公司；1914 年，40 岁的失业推销员汤玛斯·沃森成了这家小企业的经理，当时这家公司已经陷入破产的边缘。

那一年沃森过的并不大好。他刚刚被全美现金出纳机公司（NCR 公司）开除，也刚刚有了个儿子。他曾经是 NCR 公司最好的销售员，却不得不在 40 岁的时候从头开始。而 CTR 公司只是个生产磅秤和天平的小企业，制表机只是很不起眼的一支业务。但是沃森刚好擅长这个。

经过十年经营，CTR 公司的年销售额已经高达 2,000 万美元以上。1924 年，沃森兴奋地对儿子说：“我给公司改了个很好的名字，叫国际商用机器公司。”当时这个名字并非名副其实，他们的主要业务依然是制表机、自动切肉机和磅秤等等；父子两人也许都不会想到，在 CTR 公司成立一百年的时候，年营收已经超过 1000 亿美元，蓝色巨人 IBM 的名字，早已响遍世界。

二十世纪二十、三十年代，正是 IBM 大力拓展制表机业务的时候。德国分公司也注意到陶舍克的发明，为此沃森专门去见了一次陶舍克。他们在陶舍克的家里谈判了一个星期，一项新合作计划诞生：陶舍克将为 IBM 工作 5 年，IBM 将会买下陶舍克的所有发明和莱茵金属的子公司。

在那 5 年里，陶舍克一共卖给了 IBM 169 项专利；也就是在为 IBM 工作的 1932 年，他发明了[[https://en.wikipedia.org/wiki/Drum_memory][磁鼓（drum memory）]]。

磁鼓的原理和留声机相似，不过使用的介质不同。 +磁鼓的表面有一层铁磁性物质，一个读写头在上面读出数据或者写入数据，方式和磁带很相像。它有多个轨道，每个轨道上都有一个悬浮的读写头；这有点像是把磁带一圈圈粘在一个铁柱子上一样。+

不过不同的是， +磁带是一种线性的存储介质，只能按照固定顺序读取或者写入，而磁鼓不是。磁鼓的旋转速度在每分钟 12,500 转左右，读写头不移动，只是等待着存储区域的到来；这种方式让它比磁带的速度快得多也灵活得多。+ 每只磁鼓存储的数据量都可以不同，完全取决于大小；但是无论如何，今天看来它的容量都相当有限，只有区区几 K 而已。

file:../images/ji_yi_chuan_cheng/15.jpg

但是这项发明有点过于超前。IBM 依然选择使用纸卡，可能是因为大批量换用磁鼓需要太高的代价，而纸卡的效率并不算低下：当时的制表机，已经能够每分钟处理 100 张卡片。磁鼓的图纸，就这样被埋在了档案室里。

金子总会发光。从五十年代起，尘封了 20 年的磁鼓终于成了计算机的标准存储设备，甚至在今天的一些类 UNIX 操作系统中，默认的交换文件还是 /dev/drum。

这时，磁鼓的发明者陶舍克早已去世了。传说在和 IBM 的合同到期后，德国政府征召他设计新型高射速连发武器，但是这个传言并未被证实。我们知道的只是，1945 年，陶舍克病逝于瑞士苏黎世的一家医院里，享年仅 46 岁。

他去世那天，是情人节。

** 听从内心的声音

二十世纪三十年代中期，英国、美国和法国几乎同时发明了雷达。这种技术在几年后席卷世界的战争浪潮中，为早期的同盟国赢得了一些喘息时间，并且最终破灭了第三帝国称霸世界的梦想。

虽然雷达的原理早在二十世纪初就已经被解释了出来，但是三十年代的雷达并不能让人满意。 所有的物体都会反射电磁波，无论它是一架敌机还是一棵果树。要快速地分辨出敌机来并不容易，工程师们需要想办法把那些固定物体的回波消除掉才行。

那个时期人们尝试了多种办法，“延迟线”的概念也就此诞生。 +延迟线能够把电信号转化成声音或者震动，过一段时间再将其恢复成电信号。这样，不同时间的信号就可以进行比较，以此过滤掉固定物体的回波。+ 一个还在读大学的小伙子设计了[[https://en.wikipedia.org/wiki/Delay_line_memory][水银延迟线（delay line memory）]]，利用管子里的水银传递振动，很受军方的欢迎。几年后，这种设备被用在了早期的电子计算机上，成了最早的内存。

虽然朋友们喜欢叫他“普莱斯”，但是这位小伙子的全名有点长：小约翰·亚当·普莱斯伯·埃克特（John Adam Presper "Pres" Eckert, Jr.）。他是一个白手起家的地产商的儿子，1919 年出生于费城，一生中最重要的时光也都在宾夕法尼亚度过。

虽然埃克特从小就喜欢自己动手设计和制作些特别的东西，但是他的父亲约翰·埃克特却和许多第一代富人一样，希望自己的儿子能进商学院。老埃克特夫妇对这个独子十分不放心——可能是因为这孩子 15 岁的时候做了个遥控炸弹的缘故。总之，在小埃克特已经被 500 公里以外的麻省理工学院录取的情况下，老埃克特竟然用假装付不起学费的办法，把他送进了就在家门口的宾夕法尼亚大学沃顿商学院。

小埃克特在沃顿商学院过得不怎么开心，特别是在他发现麻省理工学院的学费并不是那么贵的时候。他想转系，但是物理系人数已满，只好转到莫尔电气工程学院。勉强熬过第一学年之后，小埃克特像是终于觉醒了一般，很快进入了创造力爆发的状态，水银延迟线就是这时候的发明。

1941 年，他大学毕业，打算继续读研究生；在那个无所事事的暑假，他参加了一个为军方服务的电子工程培训班，并且遇到了命中注定的那个人。

** 天才的工程师

约翰·莫奇利（John W. Mauchly）博士比埃克特大 12 岁，是附近的乌尔辛纳斯学院物理系主任，也是这个培训班的学员。两人很快就熟络了起来，然后发现制造一台全自动化高速计算的电子计算机，是两人的共同兴趣。

暑假过完，莫奇利就到摩尔学院申请了一份教职。两人商议的结果，是 1942 年 8 月份的一份建议书，建议军方开始设计和建造一台电子计算机。这份只有 5 页的建议书在删改了几次之后终于得到了批准，在埃克特 24 岁生日那天，这个名为 ENIAC 的项目正式通过。两个月后，合同签署完成，军方投资 40 万美元，由研究生一年级的埃克特担任总工程师。

在参考了爱荷华州立大学的约翰·阿塔纳索夫的一些设计之后，ENIAC 项目于 1946 年成功结束。在制造 ENIAC 的过程中，埃克特和莫奇利已经开始和冯·诺依曼一起讨论如何改进设计，但是在 1945 年，在冯·诺依曼发表的那篇关于计算机结构的著名文章上，却没有埃克特和莫奇利的名字。

这篇文章让埃克特和莫奇利与冯·诺依曼的关系变得很糟。埃克特认为冯·诺依曼剽窃了他关于程序存储的想法却只署上自己的名字；而冯·诺依曼则认为这不过是为了绕开军队保密政策的一个权宜之计而已，完全不值得大惊小怪。到底谁是谁非依然在争论，不过无论如何，今天的计算机还是被叫做“冯·诺依曼机”。

1949 年 8 月，EDVAC 终于制造完成。这台全称为“离散变量自动电子计算机”的机器，使用二进制方式存储和运算，使用水银延迟线做为内存，所使用的电子管数量只有 ENIAC 的三分之一左右，性能却比 ENIAC 好得多。也就是在那一年，埃克特在无线电工程师学会会刊上发表了一篇论文，认为使用水银延迟线做为电子计算机的存储器件，能够让电子计算机的频率达到上兆赫兹。

1950 年，埃克特和莫奇利创建的计算机公司被生产打字机起家，但是因为生产军火而发家的雷明顿·兰德公司收购，并且很快推出了最早的商用计算机 UNIAC I；后来又经过几次公司购并，最终成为了优利系统公司。而埃克特一直在这家公司任职，直到 1989 年退休之后，也依然担任着公司的顾问。

他在家乡平静地走完了人生的最后几年，获得了包括计算机先驱奖在内的无数荣誉，于 1995 年去世。

file:../images/ji_yi_chuan_cheng/16.jpg

2002 年，小约翰·普莱斯伯·埃克特以其一生的 87 项专利为资质，入选美国发明家名人堂，和历史上那些著名的发明家们一起受人瞻仰。这时候，家用计算机已经进入了奔腾时代，内存已经开始以百兆为单位来衡量了。

** 看得见的存储

以 ENIAC 的发明为标志，人类正式进入电子计算机时代。但是 ENIAC 依然不是现代意义上的电子计算机，它并不能存储程序。冯·诺依曼提出的架构的确可行，但是第一台真正应用了可存储程序思路的电子计算机，则是英国在 1948 年开发的“小规模实验机”，它的昵称更广为人知：Baby 计算机。这台机器的开发者是弗雷德里克·克兰·威廉姆斯（Frederic Calland Williams）和他的助手汤玛斯·基尔伯恩（Tom Kilburn），他们也是 +历史上第一种随机访问存储器+ 的发明者；这种存储装置， +用的是人们早已熟悉的显示装置：阴极射线管（CRT）+ 。

1896 年，德国物理学家卡尔·斐迪南·布劳恩（Karl Ferdinand Braun）发明了阴极射线管。它 +用电子撞击涂了荧光粉的显示屏内表面，以电磁场控制电子偏转的幅度，能够显示出图像。+ 人们很快意识到了这种设备的用途，并且很早就应用在雷达中。但是使用阴极射线管做为存储装置，却只是在二战之后才成为现实。

威廉姆斯在 28 岁那年获得了博士学位，并且开始投身于电信研究的工作。随着二战爆发，他的研究方向开始转向军用通讯领域，并且成了这一领域的名人。 1945 年，威廉姆斯受邀访问了麻省理工学院和宾夕法尼亚大学的莫尔学院，就是在美国，他萌生了使用 CRT 来存储数据的设想。和水银延迟线一样，这种存储器最初的设想，也是为了让雷达能够更好地分辨移动和非移动物体。和水银延迟线相比，它的速度要快得多。

回到英国之后，他马上开始投入到 CRT 存储的研究。他尝试用阴极射线管存储模拟数据和数字数据；前者用于雷达，后者则可能会用于电子计算机——实际上，不久之后，这两种方式都被开发出来了。

从原理上看，阴极射线管存储也算不上十分复杂。 +电子撞击在荧光屏上，导致撞击部位的电荷改变；感知这些电荷的数量，就可以读出当前位置存储的是 1 还是 0。+ 但是如何感知这些电荷，是个工程难题。

这时候，一个 26 岁的小伙子解决了这个问题；他叫汤玛斯·基尔伯恩，后来成为了英国最著名的计算机科学家之一，也是一位计算机先驱奖获得者。

** 二维存储

汤玛斯·基尔伯恩比威廉姆斯小 10 岁，在威廉姆斯获得博士学位那一年，汤玛斯刚刚被剑桥大学的西德尼学院录取。他的父亲是一位靠自己的艰苦努力而白手起家的典范，这种勤奋的精神显然也影响了汤玛斯。在剑桥的时候，他参加了一个飞行员培训班，但是因为视力不达标而未能入伍，被转送到另一个学习电磁和电子学的培训班，继而被分配到英国电信研究院，在威廉姆斯的手下工作。

两人配合得很好。战后，威廉姆斯在曼彻斯特大学担任电子技术实验室主任，汤玛斯也依然和他一起工作。他很快设计出了 CRT 存储器，在一个 CRT 上，能够存储 2048 位。在这种存储器工作的时候，屏幕上会出现方方正正的绿色点阵，其中有一些更亮，它们意味着“1”；而另外那些暗淡的，则表示“0”。

file:../images/ji_yi_chuan_cheng/17.jpg

这种装置被命名为“[[https://en.wikipedia.org/wiki/Williams_tube][威廉姆斯-基尔伯恩管（Williams–Kilburn tube）]]”，往往简称成威廉姆斯管。和后来的所有内存一样，威廉姆斯管需要不间断的电源供应，不过它有两个特征让它超越了同时代的其它存储设备：这种存储器的速度是当时最快的；它也是世界上第一种随机访问存储器。

说起来， +之前的种种存储装置，都只能算是顺序访问存储器。人们无法直接跳到磁带上的某个存储点，磁鼓旋转一周的速度也决定了访问数据需要的时间。而威廉姆斯管则不然；当读取或者写入时，所需要的时间与这段信息所在的位置无关。+

以威廉姆斯管为主题，汤玛斯完成了他的博士论文，并且开始尝试将威廉姆斯管应用在计算机上。1951 年，马克一型研制成功，它的原型机就是为了测试威廉姆斯管的可用性。同年，美国普林斯顿大学高等研究院的计算机也完成，同样使用了威廉姆斯管。第二年，在 IBM 首台全电子商用计算机 701 上，也使用威廉姆斯管来作为内存。在二十世纪五十年代那个计算机萌芽时期，威廉姆斯管成为了许多计算机不可或缺的元件。

但是威廉姆斯管的辉煌并没有持续很久。在大洋彼岸的美国，一个留学生设计出一种宛如精细手工的存储装置，并且很快风靡一时，甚至促进了计算机病毒的诞生。磁芯来了。

** 第一代

在我开始写这篇文章的时候，时针已经跳到了 3 月 24 日。1990 年的这一天，王安去世。两年后，他一手建立的王安实验室申请破产保护，并在迈进二十一世纪之前被荷兰的 Getronics NV 收购。王安的品牌不再使用，这个曾列全球排名 150 位的大公司就此消失。

这家巨型公司的名字，始终和它的创始人连在一起。没有王安的王安公司，便已经名不副实。

file:../images/ji_yi_chuan_cheng/19.jpg

1920 年，王安出生于上海，十六岁时以第一名的成绩考入国立交通大学，并且在毕业后留校任教。现在还可以找到他那时的照片，略带羞涩，却眉宇昂扬。二战结束后的 1945 年，王安赴哈佛大学求学，于 1948 年获得应用物理博士学位。也就是在那时，他对电子计算机的兴趣和天分开始凸显了出来。

在获得博士学位后，王安并没有离开。他留在哈佛，和霍华德·艾肯一起设计制造“哈佛马克 4 型”计算机——艾肯的第一台全电子计算机。这台计算机和当时其他类似的机器一样，使用磁鼓作为外存储器，但是主存储器的选择却煞费心思。水银延迟线速度慢，而威廉姆斯管还尚未投入使用。王安打算另辟蹊径，从磁存储入手。

1949 年，王安申请了“脉冲传输控制装置”的专利。在专利文件中，他写道：“这种装置既可以做为开关，也可以做为存储装置。它不会受到机械部件的限制。它没有活动部件，能够达到很快的开关速度，而用于存储的话，性能也会超过其他存储设备。这种装置很适合用于在不同运算速度的机器之间传递数据。”

这项专利催生的 +[[https://en.wikipedia.org/wiki/Magnetic-core_memory][磁芯存储器（magnetic-core memory）]]，在之后的 20 年中，一直是计算机主存储器的首选，直到集成电路技术成熟，+ 才将其赶下历史舞台。而在磁芯诞生之后不久的六十年代初，美国电报电话公司贝尔实验室的 3 位年轻人开发了一个争夺地盘的游戏，被视为现代计算机病毒的始祖。那个游戏，就叫做“磁芯大战”。

** 穿针引线

萨苏写过些我国早期研制计算机时的逸闻趣事，其中有一篇提到与赵静芳先生的对话。赵先生是我国最早从事存储器领域研发的专家之一，而她对当时工作印象最深的就是“[[http://blog.sina.com.cn/s/blog_476745f60100cqzc.html][整天穿磁芯儿]]”。

普遍而言，女性的确是比男性细心一些，所以在当时被归为机密的计算机研制项目中，也只能请这些女研究员们亲自动手制作磁芯。这些精细而又重复性极高的劳动，如果说为当年参与计算机研究项目的巾帼英雄们留下了些许心理阴影，似乎也并不为过；而远在大洋彼岸的磁芯发明者王安博士，自然不会料到会有这样的结果。

磁芯的原理并不复杂： +电流会在导线周围产生磁场，可以用来为磁环赋以不同的磁场方向。用三根导线穿过一个芝麻大小的磁环，以两根导线寻址，第三根导线用来读出和写入数据，就可以实现 1 位的存储。+ 如果要存储 1 字节，需要 8 个磁环，而如果要达到 1K 的存储量，则需要 8192 个磁环才能实现。

file:../images/ji_yi_chuan_cheng/18.jpg

虽然制造过程复杂，但是在当时，磁芯的确是最好的存储设备。1955 年，王安将磁芯的专利卖给了 IBM 公司，把换回的 50 万美元投入到自己的王安实验室，并改名为王安公司。10 年后，这家企业的年销售额超过了 100 万美元。王安公司缓慢起步了。

当时王安公司的主要产品是计算器，但是随着集成电路的问世，王安意识到计算器市场即将面临一场大洗牌。他停止了所有计算器产品线，投入拥有更高附加值的文字处理市场，并且在 1971 年，以远超市场同类产品性能的 1200 型文字处理机震惊了世界。第二年推出的 2200 型文字处理机依然大获成功，以至于人们认为，WPS 不应该是“文字处理系统”的缩写，而是“王安处理系统”的缩写。

王安公司把在文字处理领域的优势保持了许久。整个七十年代后期和八十年代前几年，都是王安公司的黄金时代。1983 年，王安公司的营业额高达 15 亿美元，王安个人资产一度达到 20 亿美元之多，稳居全球华人首富之位。但是，PC 的时代已经到来。

1985 年起，王安公司第一次出现了亏损，之后一亏再亏。虽然几度努力，但是终于颓势难返。这时的计算机，早已不再是王安雄心勃勃开创一番事业时的样子，磁芯早已消失，老对手 IBM 发明的技术却开始发扬光大。

想来，21 年前的这个时候，躺在马萨诸塞州总医院病床上的王安，怕也依然心有不甘吧。

** Links

- [[http://songshuhui.net/archives/tag/%E8%AE%B0%E5%BF%86%E4%BC%A0%E6%89%BF][科学松鼠会 | 记忆传承，信息永生]]

* 计算的极限

[[http://songshuhui.net/archives/tag/%E8%AE%A1%E7%AE%97%E7%9A%84%E6%9E%81%E9%99%90][Source]]

** 所有机器的机器，与无法计算的问题

计算无处不在。

走进一个机房，在服务器排成的一道道墙之间，听着风扇的鼓噪，似乎能嗅出 0 和 1 在 CPU 和内存之间不间断的流动。从算筹、算盘，到今天的计算机，我们用作计算的工具终于开始量到质的飞跃。计算机能做的事情越来越多，甚至超越了它们的制造者。上个世纪末，深蓝凭借前所未有的搜索和判断棋局的能力，成为第一台战胜人类国际象棋世界冠军的计算机，但它的胜利仍然仰仗于人类大师赋予的丰富国际象棋知识；而仅仅十余年后，Watson 却已经能凭借自己的算法，先「理解」问题，然后有的放矢地在海量的数据库中寻找关联的答案。长此以往，工具将必在更多的方面超越它的制造者。而这一切，都来源于越来越精巧的计算。

计算似乎无所不能，宛如新的上帝。但即使是这位「上帝」，也逃不脱逻辑设定的界限。

第一位发现这一点的，便是图灵。

-----

*_一切从逻辑开始_*

1900 年的巴黎，在世纪交替之际，希尔伯特（David Hilbert）提出了他著名的 [[https://en.wikipedia.org/wiki/Hilbert's_problems][23 个问题（Hilbert's problems）]]。其中第二个问题——算术系统的相容性——正是他那雄心勃勃的「希尔伯特计划」的最后一步。这位数学界的巨人，打算让整个数学体系矗立在一个坚实的地基上，一劳永逸地解决所有关于对数学可靠性的种种疑问。一切都为了回答 3 个问题：

*数学是完备的吗？* 也就是说，面对那些正确的数学陈述，我们是否总能找出一个证明？数学真理是否总能被证明？

*数学是一致的吗？* 也就是说，数学是否前后一致，不会得出某个数学陈述又对又不对的结论？数学是否没有内部矛盾？

*数学是可判定的吗？* 也就是说，能够找到一种方法，仅仅通过机械化的计算，就能判定某个数学陈述是对是错？数学证明能否机械化？

希尔伯特明确提出这 3 个问题时，已是 28 年后的 1928 年。在这 28 年间，数学界在算术系统的相容性上没有多少进展。但希尔伯特没有等太久，仅仅三年后，哥德尔（Kurt Friedrich Gödel）就得到了前两个问题的答案，尽管这个答案不是希尔伯特所希望看到的。

#+caption: 哥德尔（Kurt Friedrich Gödel）
file:../images/ji_suan_de_ji_xian/01.jpg

哥德尔的答案分两部分。

第一， +任何包含了算术的数学系统都不可能同时拥有完备性和一致性，也就是说，如果一个数学系统包含了算术的话，要么它是自相矛盾的，要么存在一些命题，它们是真的，但我们却无法证明。这说明，希尔伯特的前两个问题不可能同时为真。+ 在这里，“算术”有着精确的含义，就是皮亚诺公理（Peano axioms），一组描述了自然数的公理。

第二， +任何包含了算术的数学系统，如果它是一致的，那么我们不能在它的内部证明它本身的一致性。这说明，我们没有希望解决第二个问题。+

这就是著名的[[https://zh.wikipedia.org/wiki/%E5%93%A5%E5%BE%B7%E5%B0%94%E4%B8%8D%E5%AE%8C%E5%A4%87%E5%AE%9A%E7%90%86][哥德尔不完备性定理（Gödel's incompleteness theorems）]]，与其说它回答了希尔伯特的前两个问题，不如说它阐述了为什么我们根本不可能解决这两个问题。

哥德尔的证明非常精巧。他先将所有的数学陈述和证明符号化，然后给每个符号串赋予一个数字，这个过程被称为哥德尔配数法。借助数学归纳法，我们可以建立针对所有自然数的陈述，而这样的陈述本身对应着一个数字，这个数字也符合陈述本身的要求。换言之，这个陈述陈述了它本身的性质。哥德尔正是通过这样魔法般的自指，完成了他的证明。这个证明之所以重要，是因为它 +第一次提供了一套完整的数学工具和方法，用于证明有关数学证明的不可能性。这本身就是数学的一次重大胜利，说明数学的力量强大得可以用纯粹逻辑的方法，证明它本身的力量是有界限的。+ 在数学的领地上，有些东西我们不知道，也不可能知道。

希尔伯特的前两个问题已经解决，只剩下最后一个问题。然而，如果一个数学系统不完备的话，它显然不可能是可判定的，因为机械化的计算本身也可以看成一种证明，而在一个不完备的系统中，真理不总能被证明。所以，最后一个问题只对完备的数学系统有意义。

所幸，完备的数学系统是存在的。同样是哥德尔，他证明了所谓“一阶谓词演算”的逻辑系统是完备的，这被称为哥德尔完备性定理。一阶谓词演算是一个比较弱的逻辑系统，在其中我们甚至不能有效唯一地描述算术。比如说，自然数系统符合皮亚诺公理的一阶版本，但它并不是唯一的，还有无数种所谓“非标准模型”同样符合这套一阶系统。在一阶谓词演算中，对于一套公理系统，如果一个命题在所有的模型中都正确，那么必定可以形式地证明这个命题，这就是一阶谓词演算的完备性。在一阶谓词演算中，真理总能被证明。

在这个弱得多的逻辑系统中，我们有了完备性，真的命题必定可以被证明。那么，它是不是可判定的？我们能不能找到一种机械计算的方法，判定其中数学陈述的对错？数学称述的真假，是否可判定的？这个问题，就是希尔伯特的可判定性问题。

注：希望更深入了解哥德尔不完备性定理的读者，可以重温旧文[[http://songshuhui.net/archives/20161][《希尔伯特之梦，以及梦的破灭》]]。

*_复杂的简单机器_*

#+caption: 图灵（Alan Turing）
file:../images/ji_suan_de_ji_xian/02.jpg

在纽曼教授的数理逻辑课上，图灵第一次听到希尔伯特的可判定性问题以及哥德尔不完备性定理。那是 1935 年的春天，他刚刚完成在剑桥国王学院的四年本科学习，以优异的成绩被选为学院研究员，正准备在数学界大显身手，数理逻辑自然而然吸引了他的兴趣。图灵清楚地意识到，解决可判定性问题的关键，在于对“机械计算”的严格定义。考究希尔伯特的原意，这个词大概意味着“依照一定的有限的步骤，无需计算者的灵感就能完成的计算”，这在没有电子计算机的当时，算是相当有想象力又不失准确的定义。

但图灵的想法更为单纯。什么是“机械计算”？机械计算就是一台机器可以完成的计算，这就是图灵的回答。

用机器计算的想法并不新鲜。十七世纪的莱布尼兹就曾设想过用机械计算来代替哲学家的思考，而十九世纪的 Charles Babbage 和 Ada Lovelace 就设计出了功能强大的“分析机（analytical engine）”，只可惜 Babbage 欠缺管理才能，这台超越了时代的机器始终没有完全造好。但图灵需要的机器，跟先驱设想的机器稍有不同。 +它必须足够简单，简单得显然能造出实物，也可以用一目了然的逻辑公式描述它的行为；它又必须足够复杂，有潜力完成任何机械能完成的计算。图灵要找的，是一种能产生极端复杂行为的简单机器。+

这并非易事，但图灵做到了，据说这是他某次长跑过后，在某块草坪上发呆的成果。 +他设计了一类机器，然后定义“机械计算”为“这类机器可以完成的计算”。+ 他设计的这类机器，正是日后以他名字命名的[[https://en.wikipedia.org/wiki/Turing_machine
][图灵机（Turing machine）]]。

+图灵机由两部分组成：一个读写头，还有一条两边无限延长的纸带，纸带被划分为小格，每格中只能有 0 和 1 两种符号。读写头每次只能对着纸带上的一个格子，但它本身可以处于不同的状态，状态的数目是有限的。+ 在所有状态中，有一个特殊的“停机”状态，读写头一旦处于停机状态，就会停止运作；但如果读写头一直没有到达停机状态的话，它就会永远运转下去。

+图灵机的秘密在于读写头的状态转移表，它指示着读写头的状态和当前读写头正对格子的符号如何变化。它只有一种非常简单的规则，就是“如果在状态 A 的读写头对着符号 x，那么对当前格子写入符号 y，将纸带左移一格/右移一格/保持不动，然后转移到状态 B”。状态转移表就是由一系列这样的简单规则组成的。状态转移表就相当于图灵机的源代码。+

实际上，我们平时笔算乘法的思维过程，跟一台图灵机的运转非常相似：在每个时刻，我们只将注意力集中在一个地方，根据已经读到的信息移动笔尖，在纸上写下符号；而指示我们写什么怎么写的，则是早已背好的九九乘法表，以及简单的加法。如果将一个笔算乘法的人看成一台图灵机，纸带就是用于记录的纸张，读写头就是这个人和他手上的笔，读写头的状态就是大脑的精神状态，而状态转移表则是笔算乘法的规则，包括九九表、列式的方法等等。这种模式似乎也适用于更复杂的机械计算任务。如此看来，图灵机虽然看起来简单，但它足以作为机械计算的定义。

既然图灵机如此简单，能不能将它“升级”，赋予更多的硬件和自由度，使它变得更强大呢？比如说，让它拥有多条纸带和对应的读写头，而纸带上也不再限定两种符号，而是三种四种甚至更多种符号？的确，放宽限制之后，在某种程度上，对于相同的任务我们能设计出更快的图灵机，但从本质上来说，“升级”后的图灵机能完成的任务，原来的图灵机也能完成，虽然也许会慢些。也就是说，这种“升级”在可计算性上并没有意义，放宽限制后的机器能计算的，原来的机器也能完成。既然计算能力没有质的变化，无论采取什么样的结构，用多少种符号，都无所谓。

图灵机的一大优点，就是它的简单。只要给出状态转移表，任何一个人都可以模拟一台图灵机的计算。对工程师而言，在现实中用机械建造一台图灵机也并非什么难事。对于程序员来说，写一个模拟图灵机的简单程序更是不在话下。但如此简单的机器，它又能做什么呢？它真的能充当“机械计算”的定义吗？

*_所有机器的机器_*

图灵机非常简单，只要明白了它的运作过程，任何一个受过足够训练的计算机系本科生都可以写出一个模拟图灵机运行的程序。只消输入状态转移表和纸带的输入内容，程序就可以一步一步模拟相应的图灵机在纸带上爬来爬去的过程。对于一些熟悉图形编程的程序员来说，做个模拟动画也问题不大。即使不用计算机，靠人手一步步操作，也是一件小孩子也能完成的事。图灵机就是这么简单的一种机器。

虽然看上去简单，但实际上图灵机能做的事情远远超出一般的想象。只要有足够长的纸带和足够好的耐心，今天的电脑能做的计算，一台精心设计的图灵机也能完成。诀窍在于，电脑中的电路是有限的，电路的状态也是有限的，我们可以用图灵机去模拟电脑中的电路状态。只要有足够长的纸带，那就可以模拟出足够大的寄存器、内存和硬盘；而 CPU 中的电路，虽然所有可能的状态极其多，但终究是有限的，可以用图灵机模拟，虽然这台图灵机的状态转移表将会有着令人头痛的大小，以及令人偏头痛的复杂程度。但是，从原则上来说，用图灵机模拟一台电脑是完全可能的，虽然每次“读写内存”时，读写头都需要花长得令人咋舌的时间在纸带上来回奔波。

也就是说，从原则上来说，只要配备适当的输入和输出设备，以及极其好的耐心，我们完全可以用图灵机上网、玩游戏甚至执行自己写的程序。特别地， +存在一台特定的编写程序专用的图灵机 T，可以在纸带上写程序，将它输入到 T 执行。那么，如果将可以模拟任意图灵机运行的程序 P，写在纸带上输入到 T 中去执行的话，机器 T 就变成了一台可以模拟任何一台图灵机的图灵机。+

#+caption: [[http://www.legoturingmachine.org/][乐高图灵机]]
file:../images/ji_suan_de_ji_xian/03.jpg

更精确地说，因为程序 P 的长度是有限的，我们可以将它直接写进原来机器的状态转移表，得到一台新的机器 UTM。UTM 会在纸带上读取两样东西：一台图灵机 M 的状态转移表的二进制编码，以及作为 M 的初始输入的纸带数据。然后，UTM 会根据 M 的状态转移表和初始输入数据，在纸带上模拟 M 的运作过程。换言之， +UTM 是一台可以模拟任何图灵机的图灵机。它是所有机器的机器，所谓的[[http://rendell-attic.org/gol/utm/utmprog.htm][通用图灵机（Universal Turing Machine）]]。+ 当然，通用图灵机并不是唯一的，只要一台图灵机能完成根据状态转移表模拟任意图灵机的任务，它就是通用图灵机。

通用图灵机的想法，在如今这个计算机泛滥的时代，似乎并不新鲜。但在图灵的 1935 年，电子计算机甚至仍未问世，机械计算机还只能执行内设的一套指令。即使是 Charles Babbage 和 Ada Lovelace 的超越时代的设想，其中执行外部程序的概念也相当含混不清。在这种历史背景下，要归纳出通用图灵机这个概念，本身就需要极为丰富的想象力，而且这种图灵机是否存在，这是个远非显然的问题。而图灵不仅设想到了这个概念，而且正确地判断出它的存在性，这需要何等非凡的直觉！

但单纯的直觉终究不能令人信服，数学家讲究的是逻辑和证明。而要证明通用图灵机的存在，最直接的方法莫过于直接给出一个通用图灵机的实例。这并不简单，如果读者想尝试一下的话，我建议先尝试构造一个能做二进制加法的图灵机。为了降低难度，可以假设纸带上有第三种符号，表示空白，但即使如此，要构造一个能做加法的图灵机，远比想象中的困难。可想而知，通用图灵机的构造肯定更为复杂繁琐。即使是图灵，他在一开始给出的构造也是有问题的，而这些问题甚至在后来的勘误中也没有成功修正。比构造更麻烦的是证明给出的图灵机的确是一台通用图灵机，在图灵解决希尔伯特可判定性问题的论文中，有关通用图灵机的构造和证明占了相当大的篇幅。这部分非常繁复琐碎，而且其中还有错误，如果细细研读的话，绝对有诱发剧烈偏头痛的危险。

幸运的是，无论细节多么复杂，图灵的想法还是被逻辑学家们接受了。一旦领会到图灵机的能力，接受了通用图灵机的构想，再检查几个能完成基本任务的图灵机之后，大部分数学家都会认为通用图灵机的确存在，尽管他们并不一定会细看图灵的详细构造。而现代电子计算机的发展，更是验证了通用图灵机的存在：每一台电脑都相当于一台通用图灵机。

通用图灵机的存在，从侧面说明了图灵机这个计算模型的强大之处：图灵机作为一类机器，其中一个特例就可以模拟整个类别中的任意一台机器，宛如能折射大千世界的一滴水珠。但在这种强大的背后，隐隐也暗藏着不安定的因素。哥德尔不完备性定理告诉我们，有时候越强大的数学理论，因为能表达的概念太多，甚至连理论的命题和证明都能表达，反而会导致不能被证明的真命题的存在。如果一个系统足以描述它自己，那魔法般的自指将是不可避免的。图灵机如此强大，它的其中一台就可以模拟所有图灵机，会不会导致不能用计算来回答的问题存在呢？

很不凑巧，答案是会。

-----

*_无法计算的问题_*

在哥德尔不完备性定理的证明中，哥德尔构造了一个描述了本身不可证明性的自指命题，通过这个命题完成了他的证明。要想照葫芦画瓢的话，那些关于图灵机本身的问题，将会是很好的候补。

关于图灵机，最简单的问题是什么呢？回想一下图灵机的运作过程，一台图灵机从初始状态开始，根据纸带上的内容，一边不断变换状态，一边更改纸带的内容，如此往复永无休止，除非它遇上了表示停机的那个状态，才能从这机械的计算过程中跳出，获得静息的安乐。一个自然的问题是：一台图灵机什么时候会停机呢？

更严格地说，会不会停机并不是图灵机本身的属性，它跟纸带的初始输入也有关系。对于同一台图灵机，不同的纸带输入也可能导致不同的结果和行为。比如说，我可以设计一台图灵机，它的任务只有一个：一步一步向右移动，寻找输入中的第一个 1。如果输入纸带上全是0的话，那么，这台图灵机自然不会停止；但只要纸带上有一个1，那么它就会停止。所以，真正严谨的问题是：给定一台图灵机 M 以及一个输入 I，如果我们将I输入M，然后让M开始运行，这时M是会不停运转下去，还是会在一段时间后停止？我们将这个问题称为停机问题。

初看起来，停机问题并不难。既然我们有通用图灵机这一强大的武器，那么只需要用它一步步模拟M在输入I上的计算过程就可以了。如果模拟过程在一段时间后停止了，我们当然可以得出“M在输入I上会停止”这个结论。问题是，在模拟过程停止之前，我们不可能知道整个计算过程到底是不会停止，它可能会在3分钟后停止，可能要等上十年八载，更有可能永远都不会停止。换句话说，用模拟的方法，我们只能知道某个程序在某个输入上会停止，但永远不能确定那些不停止的状况。所以说，单纯的模拟是不能解决停机问题的。

实际上，停机问题比我们想象中要复杂得多。

举个例子，我们可以编写一个程序GC，它遍历所有大于等于6的偶数，尝试将这样的偶数分成两个素数的和。如果它遇到一个不能被分解为两个素数之和的偶数，它就停机并输出这个偶数；否则，它就一直运行下去。用现代的工具编写GC这样的程序，对于计算机系的学生最多只能算一次大作业；用图灵机实现的话，也不是什么极端困难的事。然而，GC 是否会停止可是牵涉到了哥德巴赫猜想。如果哥德巴赫猜想是正确的，每个大于等于6的偶数都能分解为两个素数之和的话，那么 GC 自然会一直运行下去，不会停机；如果哥德巴赫猜想是错误的话，必定存在一个最小的反例，它不能分解为两个素数之和，而GC在遇到这个反例时就会停机。也就是说，GC 是否永远运行下去，等价于哥德巴赫猜想是否成立。如果我们能判定GC是否会停止，那我们就解决了哥德巴赫猜想。

数学中的很多猜想，比如说 3x+1 猜想、黎曼猜想等，都可以用类似的方法转化为判断一个程序是否会停止的问题。如果存在一个程序，能判断所有可能的图灵机在所有可能的输入上是否会停止的话，那么只要利用这个程序，我们就能证明一大堆重要的数学猜想。我们可以说，停机问题比所有这些猜想更难更复杂，因为这些困难的数学猜想都不过是一般的停机问题的一个特例。如果停机问题可以被完全解决，我们能写出一个程序来判断任意图灵机是否会停机的话，那么相当多的数学家都要丢饭碗了。

停机问题如此复杂，机械的计算看起来没有足够的力量来完全解决它。停机问题似乎是不可计算的。但要想严格证明这个结论，似乎仍要求助于深藏在图灵机之中，那魔法般的自指。
* 数据压缩与信息熵

[[http://www.ruanyifeng.com/blog/2014/09/information-entropy.html][Source]]

1992 年，美国佐治亚州的 WEB Technology 公司，宣布做出了重大的技术突破。该公司的 DataFiles/16 软件，号称可以将任意大于 64KB 的文件，压缩为原始大小的 16 分之一。业界议论纷纷，如果消息属实，无异于压缩技术的革命。

许多专家还没有看到软件，就断言这是不可能的。因为根据压缩原理，你不可能将任意文件压缩到 16 分之一。事实上，有一些文件是无法压缩的，哪怕一个二进制位，都压缩不掉。后来，事实果然如此，这款软件从来没有正式发布。没过几年，就连 WEB Technology 公司都消失了。那么，为何不是所有的文件都可以被压缩？是否存在一个压缩极限呢，也就是说，到了一定大小，就没法再压缩了？

** 压缩的有限性

首先，为什么 WEB Technology 公司的发明不可能是真的？

反证法可以轻易地证明这一点。假定任何文件都可以压缩到 n 个二进制位以内，那么最多有 $2^n$ 种不同的压缩结果。也就是说，如果有 $2^n + 1$ 个文件，必然至少有两个文件会产生同样的压缩结果。这意味着，这两个文件不可能无损地还原（解压缩）。因此，得到证明，并非所有文件都可以压缩到 n 个二进制位以下。

下一个问题就是，这个 n 到底是多少？

** 压缩原理

压缩原理其实很简单，就是找出重复出现的字符串，然后用更短的符号代替，从而达到缩短字符串的目的。比如，「中华人民共和国」这个词语，用「中国」代替，就缩短了 5 个字符，用「华」代替，就缩短了 6 个字符。事实上，只要保证对应关系，可以用任意字符代替那些重复出现的字符串。

本质上，「压缩」就是 _找出文件内容的概率分布，将那些出现概率高的部分代替成更短的形式。_ 所以，内容越是重复的文件，就可以压缩地越小。比如，「ABABABABABABAB」可以压缩成「7AB」。相应地，如果内容毫无重复，就很难压缩。极端情况就是，遇到那些均匀分布的随机字符串，往往连一个字符都压缩不了。比如，任意排列的 10 个数字：5271839406，就是无法压缩的；再比如，无理数也很难压缩。

压缩就是一个消除冗余的过程，相当于用一种更精简的形式，表达相同的内容。可以想象，压缩过一次以后，文件中的重复字符串将大幅减少。好的压缩算法，可以将冗余降到最低，以至于再也没有办法进一步压缩。所以， _压缩已经压缩过的文件（递归压缩），通常是没有意义的。_

** 压缩的极限

压缩可以分解成两个步骤。第一步是得到文件内容的概率分布，哪些部分出现的次数多，哪些部分出现的次数少；第二步是对文件进行编码，用较短的符号替代那些重复出现的部分。第一步的概率分布一般是确定的，现在就来考虑第二步，怎样找到最短的符号作为替代符。

如果文件内容只有 2 种情况（比如扔硬币的结果），那么只要 1 个二进制位就够了，1 表示正面，0 表示表示负面。如果文件内容包含 3 种情况（比如球赛的结果），那么最少需要 2 个二进制位。

在一个文件的所有元素等概率出现的情况下，若每种元素出现的概率是 $p$，那么每个部分的元素有 $\frac{1}{p}$ 种可能，即每个替代符号需要 $\log_2{\frac{1}{p}}$ 个二进制位。

推广到一般情况，若文件由 n 个部分组成，每个部分的元素（在整个文件中）出现的概率分别为 $p_1, p_2, \ldots p_n$，那么，整个文件由替代符号替代之后占据的二进制位最少为：

$$\log_2{\frac{1}{p_1}} + \log_2{\frac{1}{p_2}} + \ldots + \log_2{\frac{1}{p_n}} = \sum\limits_{i=1}^n \log_2{\frac{1}{p_i}}$$

这可以看作一个文件的压缩极限。

-----

（对原文补充：）一个例子，假设有一段文本 =aabbccaa= ，以两个字母为一个部分，总共 4 部分，元素种类有 3 种： =aa= 、 =bb= 、 =cc= ，出现的概率分别为：0.5、0.25、0.25，于是替代符号的二进制长度分别为：1、2、2，比如可以这样进行压缩：aa = 0，bb = 10，cc = 11。每个部分元素出现的概率：$p_1 = 0.5, p_2 = 0.25, p_3 = 0.25, p_4 = 0.5$，所以压缩极限为：

$$\log_2{\frac{1}{0.5}} + \log_2{\frac{1}{0.25}} + \log_2{\frac{1}{0.25}} + \log_2{\frac{1}{0.5}} = 1 + 2 + 2 + 1 = 6$$

** 信息熵

通过上一个结果，可以计算每个替代符号的平均二进制位长度为：

$$\frac{1}{n} \sum\limits_{i=1}^n \log_2{\frac{1}{p_i}}$$

或者从概率的角度进行计算，若共有 m 种元素（替代符号），出现的概率分别为 $p_1, p_2, \ldots p_m$，那么替代符号的平均二进制长度为：

$$p_1\log_2{\frac{1}{p_1}} + p_2\log_2{\frac{1}{p_2}} + \ldots + p_m\log_2{\frac{1}{p_m}} = \sum\limits_{i=1}^m p_i\log_2{\frac{1}{p_i}} = E[\log_2{\frac{1}{p}}]$$

E 表示数学期望。

-----

（对原文补充：）以上面的例子，3 种元素（替代符号）出现的概率分别为：$p_1 = 0.5, p_2 = 0.25, p_3 = 0.25$，所以替代符号的平均二进制长度为：

$$0.5 \times \log_2{\frac{1}{0.5}} + 0.25 \times \log_2{\frac{1}{0.25}} + 0.25 \times \log_2{\frac{1}{0.25}} = 0.5 + 0.5 + 0.5 = 1.5$$

-----

假设有两个文件都包含 1024 个符号，在 ASCII 码的情况下，它们的长度是相等的，都是 1KB。甲文件的内容 50%是 a，30% 是 b，20% 是 c，则平均每个符号要占用二进制位：

$$0.5 \times \log_2{\frac{1}{0.5}} + 0.3 \times \log_2{\frac{1}{0.3}} + 0.2 \times \log_2{\frac{1}{0.2}} \approx 0.5 + 0.52 + 0.47 = 1.49$$

即每个符号约占用 1.49 个二进制位，那么压缩 1024 个符号，理论上最少需要 1526 个二进制位，约 0.186KB，相当于压缩掉了 81% 的体积。

乙文件的内容 10% 是 a，10% 是 b，…… 10% 是 j，则平均每个符号要占用二进制位：

$$0.1 \times \log_2{\frac{1}{0.1}} + 0.1 \times \log_2{\frac{1}{0.1}} + \ldots + 0.1 \times \log_2{\frac{1}{0.1}} \approx 0.332 \times 10 = 3.32$$

即每个符号约占用 3.32 个二进制位，那么压缩 1024 个符号，理论上最少需要 3400 个二进制位，约 0.415KB，相当于压缩掉了 58% 的体积。

对比上面两个算式，可以看到文件 _内容越是分散（随机），所需要的二进制位就越长，这个值可以用来衡量文件内容的随机性（又称不确定性），叫做信息熵（information entropy）。_ 它是 1948 年由美国数学家克劳德·香农（Claude Shannon）在经典论文《通信的数学理论》中，首先提出的。

** 信息熵的含义

- 信息熵只反映内容的随机性，与内容本身无关。不管是什么样内容的文件，只要服从同样的概率分布，就会计算得到同样的信息熵。
- 信息熵越大，表示占用的二进制位越长，因此就可以表达更多的符号。所以，人们有时也说，信息熵越大，表示信息量越大。不过，由于第一点的原因，这种说法很容易产生误导。较大的信息熵，只表示可能出现的符号较多，并不意味着可以从中得到更多的信息。
- 信息熵与热力学的熵，基本无关。这两个熵不是同一件事，信息熵表示无序的信息，热力学的熵表示无序的能量。
