#+SETUPFILE: ../../styles/readtheorg.setup
#+TITLE: Wicked Cool Shell Scripts

* 0 A Shell Script Crash Course

Shell scripts don't need a special file extension.

When running two commands one after another, the 2nd command is provided as an argument to the 1st, bash uses a subshell to run the 2nd command and store the output for use by the 1st command.

* 1 The Missing Code Library

In the early days of Unix, companies innovating and taking the operating system in different directions. The Institute for Electrical and Electronic Engineers (IEEE) stepped in and, with effort from all the major Unix vendors, created a standard definition for Unix called the Portable Operating System Interface, or POSIX.

While the IEEE POSIX standards supposedly provide a common base of functionality, there are still subtle variations among different flavors of Unix and GNU/Linux distributions, for example, the commands are different, they're in different locations, and they often have subtly different command flags.
